### ISSUE TITLE
CreatingClientSecretsFile Step 6

### ISSUE THREAD

**Issue by MikeNdhs** [jay0lee/GAM#100]
Hi,

I'm creating "CreatingClientSecretsFile" for the first time and step 6 says to click on "Consent Screen" which is no longer there. Will it be a problem to skip this step or is there another way to access this part. Thank you please let me know

![image](https://cloud.githubusercontent.com/assets/13904431/9409710/594278d2-47ea-11e5-9cdb-eee710842f2c.png)

**Comment by yubbie** [comment]
Consent is now under credentials - it's a tab on the top of that screen.

**Comment by MikeNdhs** [comment]
Thank you
