### ISSUE TITLE
Error viewing classroom-created groups

### ISSUE THREAD

**Issue by kbarkerpeabody** [jay0lee/GAM#1009]
I've just updated to 4.94, and still having problems. My check serviceaccount gives all PASS.

I've got Google Classroom set up for students, and they have all joined the Classroom.  Some of them, but not all, are unable to see the classroom calendar in their Google calendar page.

I can find the calendar ID using 'gam user xxx show calendars' and find it for the teacher.
I can then get the calendar permissions using 'gam calendar xxx@group.calendar.google.com showacl'

This returns 4 lines - 1 each with the classroom, the teacher, and the group of all teachers of that class listed as owners, and fourth group of the students listed as reader.

When I then try to find information on that group using 'gam info group xxxx', I get ERROR: 403: Not Authorized to access this resource/api - forbidden

I'm able to successfully use the 'gam info group xxx' command with groups that I've created in the admin console - I see the full output of settings and members.

Thank you!

**Comment by jay0lee** [comment]
This is a Google limitation. Google does not expose those hidden groups to the APIs. There's nothing GAM can do to change that.
