### ISSUE TITLE
Batch code for Bulk operation of Suspending users in a OU

### ISSUE THREAD

**Issue by MikeNdhs** [jay0lee/GAM#101]
Hi,

Do you have a Gam batch code written to apply status of users to suspended of everyone in a OU? These are the users who no longer work in this organization but I would like the keep the accounts for a while before deleting these users?

**Comment by MikeNdhs** [comment]
I tried this and it didn't work gam update users 'orgUnitPath="/Staff Alumni"' | gam suspended on

**Comment by mjavick** [comment]
gam org Sales update user suspend on

**Comment by jay0lee** [comment]
This area is for issues / bugs. Please post discussions to the discussion group:

groups.google.com/group/google-apps-manager
