### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by k9mjl** [jay0lee/GAM#1011]
Getting this error every time I try to run a script.

Traceback (most recent call last):
  File "gam.py", line 14898, in <module>
  File "gam.py", line 14296, in ProcessGAMCommand
  File "gam.py", line 2149, in doGetDomainInfo
  File "gam.py", line 2171, in doGetCustomerInfo
  File "gam.py", line 1362, in buildGAPIObject
  File "gam.py", line 1290, in getValidOauth2TxtCredentials
  File "gam.py", line 1279, in getOauth2TxtStorageCredentials
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 21 column 2 (char 1906)
[3064] Failed to execute script gam

**Comment by jay0lee** [comment]
The error indicates your oauth2.txt file is corrupt. Can you try renaming
that file and then running the command again? You'll be prompted to
authenticate GAM again and a new oauth2.txt will be created.

Jay

**Comment by flashadvocate** [comment]
FWIW I ran into this same issue tonight. Rauthing worked but I also had to update from 4.92 to 4.94. Not sure if something changed causing 4.92 to stop working

**Comment by jay0lee** [comment]
Which OS exactly are you seeing these issues on?

**Comment by danny-dillon** [comment]
I have experienced it multiple times on both of these, invariably on overnight reports.

I will add that gam oauth does not work on the corrupt copy - you have to manually delete, or restore a good copy.

# gam_4.87/gam version extended
GAM 4.87 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.7.3 64-bit final
google-api-python-client 1.7.8
Linux-2.6.32-754.23.1.el6.x86_64-x86_64-with-redhat-6.10-Santiago x86_64
Path: /opt/sync/gam_4.87
OpenSSL 1.1.1c  28 May 2019
www.googleapis.com connects using TLSv1.3 TLS_AES_256_GCM_SHA384


# gam_4.94/gam version extended
GAM 4.94 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.7.4 64-bit final
google-api-python-client 1.7.11
Linux-2.6.32-754.23.1.el6.x86_64-x86_64-with-redhat-6.10-Santiago x86_64
Path: /opt/sync/gam_4.94
Your computer is 0 seconds off from Google's time.
OpenSSL 1.1.1c  28 May 2019
www.googleapis.com connects using TLSv1.3 TLS_AES_256_GCM_SHA384

**Comment by picklzfan** [comment]
> Which OS exactly are you seeing these issues on?

I am running Windows 10 Enterprise 1809 and GAM version 4.94.

**Comment by jay0lee** [comment]
OK, I can sort of reproduce this issue with following script:
```
import json
import os
from filelock import FileLock

lock = FileLock('oauth2.txt.lock')
while True:
  with lock:
    s = open("oauth2.txt").read()
  os.remove('oauth2.txt.lock')
  if len(s) > 5:
    try:
      json.loads(s)
    except:
      print(s)
      exit(1)
  else:
    print("empty file")
```
running above script at the same time as something like:
```
gam csv realllylongcsvfile.csv oauth refresh

to force a whole bunch of refreshes in parallel should trigger this corruption on occassion (and a blank oauth2.txt read more frequently) with GAM 4.94.

With the patches I submitted above I can run this script and the GAM csv command at the same time and never get an empty or corrupt oauth2.txt.

We should be good here and I'll see about pushing out a 4.95 fixed version soon.
