### ISSUE TITLE
Inconsistent progress indicator of print commands

### ISSUE THREAD

**Issue by hroudny** [jay0lee/GAM#1013]
Some print commands indicate progress with increasing number of users:

gam print users
Getting all Users in G Suite account (may take some time on a large account)...
Got 500 Users: adam@example.com - barry@example.com
Got 1000 Users: brian@example.com - daniel@example.com
Got 1500 Users: evans@example.com - george@example.com
...

But some print the value 500 all the time:

gam print aliases
Getting all User Aliases in G Suite account (may take some time on a large account)...
Got 500 Users adam@example.com - barry@example.com
Got 500 Users brian@example.com - daniel@example.com
Got 500 Users evans@example.com - george@example.com
...

I believe the first one is much better, so I'd propose to change all progress indicators to that format.

**Comment by taers232c** [comment]
Jay,

In my versions I've standardized on always showing running totals; do you want me to do the same in yours?

Ross

**Comment by jay0lee** [comment]
This is fixed in latest version, thanks Ross.
