### ISSUE TITLE
Error: 1410 - Feature Unavailable For User

### ISSUE THREAD

**Issue by kmkhan** [jay0lee/GAM#102]
I've a script running since the new Google API changes this spring. It makes nicknames (alias) default send-as address immediately after creation of user accounts on Google using GADS. We create many new users every day in education industry.
As soon as I upgraded the GAM version from 3.45 to 3.51, this script has broken. I've given the error code in the subject. I couldn't find any similar cases searching web. If I re-run the script on an existing account it still works. This means nothing is wrong with the script. The new version of GAM as broken something else. Please help
Thanks
Kamran

**Comment by beatleuk** [comment]
This is an issue with newly created accounts, the Gmail routing option is
not ticked in the account profile. A work around is to send it an email and
the Gmail routing becomes enabled, then your script can carry on.

On Friday, August 21, 2015, kmkhan <notifications@github.com> wrote:

> I've a script running since the new Google API changes this spring. It
> makes nicknames (alias) default send-as address immediately after creation
> of user accounts on Google using GADS. We create many new users every day
> in education industry.
> As soon as I upgraded the GAM version from 3.45 to 3.51, this script has
> broken. I've given the error code in the subject. I couldn't find any
> similar cases searching web. If I re-run the script on an existing account
> it still works. This means nothing is wrong with the script. The new
> version of GAM as broken something else. Please help
> Thanks
> Kamran
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/102>.
>


-- 
*Regards*


*Lee Bailey 07770857189 lee@beatle.org.uk <lee@beatle.org.uk>*[image: View
Lee Bailey's profile on LinkedIn]
<http://uk.linkedin.com/in/leembailey>[image:
View Lee Bailey's profile on Google+]
Be green - keep it on the screen

**Comment by kmkhan** [comment]
Thanks for the reply. I’m using older version 3.45 (it works), as I can’t
send emails to dozens of users from within a batch job .

Regards

Kamran



*From:* Lee Bailey [mailto:notifications@github.com]
*Sent:* Friday, August 21, 2015 11:35 AM
*To:* jay0lee/GAM
*Cc:* kmkhan
*Subject:* Re: [GAM] Error: 1410 - Feature Unavailable For User (#102)



This is an issue with newly created accounts, the Gmail routing option is
not ticked in the account profile. A work around is to send it an email and
the Gmail routing becomes enabled, then your script can carry on.

On Friday, August 21, 2015, kmkhan <notifications@github.com> wrote:

> I've a script running since the new Google API changes this spring. It
> makes nicknames (alias) default send-as address immediately after creation
> of user accounts on Google using GADS. We create many new users every day
> in education industry.
> As soon as I upgraded the GAM version from 3.45 to 3.51, this script has
> broken. I've given the error code in the subject. I couldn't find any
> similar cases searching web. If I re-run the script on an existing account
> it still works. This means nothing is wrong with the script. The new
> version of GAM as broken something else. Please help
> Thanks
> Kamran
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/102>.
>


-- 
*Regards*


*Lee Bailey 07770857189 lee@beatle.org.uk <lee@beatle.org.uk>*[image: View
Lee Bailey's profile on LinkedIn]
<http://uk.linkedin.com/in/leembailey>[image:
View Lee Bailey's profile on Google+]
Be green - keep it on the screen

—
Reply to this email directly or view it on GitHub
<https://github.com/jay0lee/GAM/issues/102#issuecomment-133484469>.[image:
Image removed by sender.]
