### ISSUE TITLE
Can't update GAM linux

### ISSUE THREAD

**Issue by StiM-git** [jay0lee/GAM#1025]
**Full steps to reproduce the issue:**
1. Run command "bash <(curl -s -S -L https://git.io/install-gam) -l" to update GAM

**Expected outcome (what are you trying to do?):**
Expected to update to latest release of GAM

**Actual outcome (what errors or bad behavior do you see instead?):**
bash <(curl -s -S -L https://git.io/install-gam) -l
This Linux distribution uses glibc 2.24
Using GAM compiled against glibc2.23

Checking GitHub URL https://api.github.com/repos/jay0lee/GAM/releases for latest GAM release...

Getting file and download URL...

********************************************************************************
Python command will soon point to Python v3.7.3.

Python 2 will be sunsetting on January 1, 2020.
See http://https://www.python.org/doc/sunset-python-2/

Until then, you can continue using Python 2 at /usr/bin/python2, but soon
/usr/bin/python symlink will point to /usr/local/bin/python3.

To suppress this warning, create an empty ~/.cloudshell/no-python-warning file.
The command will automatically proceed in 5 seconds or on any key.
********************************************************************************
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 449 column 4 - line 9091 column 1 (char 23145 - 472213)
********************************************************************************
Python command will soon point to Python v3.7.3.

Python 2 will be sunsetting on January 1, 2020.
See http://https://www.python.org/doc/sunset-python-2/

Until then, you can continue using Python 2 at /usr/bin/python2, but soon
/usr/bin/python symlink will point to /usr/local/bin/python3.

To suppress this warning, create an empty ~/.cloudshell/no-python-warning file.
The command will automatically proceed in 5 seconds or on any key.
********************************************************************************
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 449 column 4 - line 9091 column 1 (char 23145 - 472213)
Downloading file  from  to /tmp/tmp.OnrEIttXAh.
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Extracting archive to /home/.../bin
tar: /tmp/tmp.OnrEIttXAh/: Cannot read: Is a directory
tar: At beginning of tape, quitting now
tar: Error is not recoverable: exiting now
ERROR: extracting the GAM archive with tar failed with error 2. Exiting.

**Comment by jay0lee** [comment]
Your Python is spewing a bunch of noise telling you about the upgrade from 2 to 3. Follow the instructions to silence it and then rerun the command to download and install GAM.

**Comment by jay0lee** [comment]
This is now fixed, the install script will prefer python3 command over python to avoid this.
