### ISSUE TITLE
gpw: command not found

### ISSUE THREAD

**Issue by jellyfish-training** [jay0lee/GAM#1027]
Hi,
Seems that something else has changed as it ran ok yesterday after I made the changes you suggested. I needed to strip out the users and groups to create a brand new setup and am now getting this error:
[INFO] create-hackathon.sh->create_groups_and_users(): started... (20.00 seconds)
[INFO] create-hackathon.sh->create_team(): Creating team #1... (20.00 seconds)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
./setenv.sh: line 90: gpw: command not found
GAM 4.95 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.7.4 64-bit final
google-api-python-client 1.7.11
Linux Debian 9 Stretch x86_64
Path: /home/admin_/bin/gam

Usage: gam [OPTIONS]...

GAM. Retrieve or set G Suite domain,
user, group and alias settings. Exhaustive list of commands
can be found at: https://github.com/jay0lee/GAM/wiki

Any ideas?
Thanks,
Mark

**Comment by jay0lee** [comment]
Please discuss this on the group rather than opening issues.
