### ISSUE TITLE
gam print mobile data issues

### ISSUE THREAD

**Issue by stepuluk** [jay0lee/GAM#1036]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. Yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki Yes

Full steps to reproduce the issue:
1.  gam print mobile query "lastsync:#querytime1#.." querytime1 -30d basic > ./crmobilelist.csv
2.
3.

Expected outcome (what are you trying to do?):

A csv file listing all mobile phones that have synced within the last 30days

Actual outcome (what errors or bad behavior do you see instead?):

No data in csv, I have tested this without the query

gam print mobile basic > ./crmobilelist.csv

I do recieve data back from this command confirming there is data available

Any help would be great thank you

**Comment by taers232c** [comment]
The command you show is not defined in this version of GAM, it is applicable to Advanced GAM (https://github.com/taers232c/GAMADV-XTD3).
The query is not correct, it should be:
gam print mobile query "sync:#querytime1#.." querytime1 -30d basic > ./crmobilelist.csv
