### ISSUE TITLE
MAC OS CATALINA 10.15 update gam broke it

### ISSUE THREAD

**Issue by sprintershipmst** [jay0lee/GAM#1037]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  I have upgraded gam to the lates version 
bash <(curl -s -S -L https://git.io/install-gam) -l
You are running MacOS 10.15
Using GAM compiled on MacOS10.14.4

Checking GitHub URL https://api.github.com/repos/jay0lee/GAM/releases for latest GAM release...

Getting file and download URL...

Downloading file gam-4.95-macos-x86_64-MacOS10.14.4.tar.xz from https://github.com/jay0lee/GAM/releases/download/v4.95/gam-4.95-macos-x86_64-MacOS10.14.4.tar.xz to /var/folders/v8/3zx7qj0d5zg0hq25ss0hxjvh0000gp/T/tmp.JBiUVkDO.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   631    0   631    0     0   2792      0 --:--:-- --:--:-- --:--:--  2792
100 6311k  100 6311k    0     0  7091k      0 --:--:-- --:--:-- --:--:-- 21.4M

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):

3. now when I runs:
./gam user USER@EMAIL.COM show delegates

ERROR: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

**Comment by jay0lee** [comment]
The authentication error is unlikely to be related to 10.15. Try running:

    gam oauth revoke

and if that errors out also, just manually delete the `oauth2.txt` file. Then run:

gam oauth create

to reauthorize.

**Comment by sprintershipmst** [comment]
Thank you !!!!! I am back to the business !!! That fixed the issue.
