### ISSUE TITLE
GAM3DirectoryCommands page missing in GAM Wiki

### ISSUE THREAD

**Issue by iandaubney** [jay0lee/GAM#1042]
The tutorial page GAM3DirectoryCommands is missing from https://github.com/jay0lee/GAM/wiki

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. *(N/A)*
* *I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki*

Full steps to reproduce the issue:
1. Open https://github.com/jay0lee/GAM/wiki and attempt to open top GAM tutorial on "GAM Tutorials Managing Users, Groups, Aliases, Domains, Mobile and Chrome Devices, and Resource Calendars"

PAGE DOES NOT EXIST.
(Direct link https://github.com/jay0lee/GAM/wiki/GAM3DirectoryCommands )

Expected outcome (what are you trying to do?):
Trying to see the wiki page

Actual outcome (what errors or bad behavior do you see instead?):
Creates a blank page.

**Comment by iandaubney** [comment]
![image](https://user-images.githubusercontent.com/55225088/68102344-5c117980-ff26-11e9-968c-87ae2a23cbf5.png)

**Comment by jay0lee** [comment]
fixed

**Comment by iandaubney** [comment]
Thank you @jay0lee
