### ISSUE TITLE
gam org operations fail when orgnames contain spaces

### ISSUE THREAD

**Issue by charmparticle** [jay0lee/GAM#1045]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  create an OU path that includes spaces in the OU and the sub OU
2. create a user
3. try to move the user to the sub OU you created, quoting the name of the OU to avoid spaces, or using the id, to circumvent the whole spaces issue altogether

example:

gam update org id:someorgid users someuser

reports back:

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid

trying gam update user someuser org "Some Orgname With Spaces/Suborg With Spaces/SubSubOrg With Spaces"

reports back:
ERROR: Spaces/Suborg is not a valid argument for "gam update user"

Expected outcome (what are you trying to do?):

The user is successfully moved to the OU

Actual outcome (what errors or bad behavior do you see instead?):

error message resulting from spaces in the name

**Comment by taers232c** [comment]
It's working for me.

Ross
```
$ gam version
GAM 4.96 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.8.0 64-bit final
google-api-python-client 1.7.11
MacOS Sierra 10.12.6 x86_64
Path: /Users/admin/Documents/GoogleApps/GAM

$ gam info ou "/Test Space/Sub Space/Sub Sub Space"

 name: Sub Sub Space
 description: Sub Sub Space
 orgUnitPath: /Test Space/Sub Space/Sub Sub Space
 orgUnitId: id:03ph8a2z24acgk2
 parentOrgUnitPath: /Test Space/Sub Space
 parentOrgUnitId: id:03ph8a2z3h9j9wu
Got 0 Users:  -
Users:

$ gam update user testuser7 org "/Test Space/Sub Space/Sub Sub Space"
updating user testuser7@rdschool.org...

$ gam info user testuser7 nogroups nolicenses
User: testuser7@rdschool.org
First Name: Test
Last Name: User7
Is a Super Admin: False
Is Delegated Admin: False
2-step enrolled: False
2-step enforced: False
Has Agreed to Terms: False
IP Whitelisted: False
Account Suspended: False
Is Archived: False
Must Change Password: False
Google Unique ID: 666925742703179281666
Customer ID: C012345678
Mailbox is setup: True
Included in GAL: True
Creation Time: 2019-11-09T00:35:09.000Z
Last login time: Never
Google Org Unit Path: /Test Space/Sub Space/Sub Sub Space

$ gam info ou "/Test Space/Sub Space/Sub Sub Space"

 name: Sub Sub Space
 description: Sub Sub Space
 orgUnitPath: /Test Space/Sub Space/Sub Sub Space
 orgUnitId: id:03ph8a2z24acgk2
 parentOrgUnitPath: /Test Space/Sub Space
 parentOrgUnitId: id:03ph8a2z3h9j9wu
Got 1 Users: testuser7@rdschool.org - testuser7@rdschool.org
Users:
 testuser7@rdschool.org

This is not supported by Gam

$ gam update user testuser7 org id:03ph8a2z24acgk2

ERROR: id:03ph8a2z24acgk2 is not valid in this context
```

**Comment by charmparticle** [comment]
Found the problem, it had to do with how I was executing gam:

    #!/bin/bash
    pushd ~/Downloads/gam
    ./gam
    popd

Just calling gam directly negates the issue.
