### ISSUE TITLE
Feature request: List of deleted users with alias (enhancement)

### ISSUE THREAD

**Issue by TheMonitorLizard** [jay0lee/GAM#1048]
Hi 

I would like to be able to pull a list of deleted users alias. Right now I can only get a list of users that is deleted. So something like: GAM print users alias deleted_only command

Regards

**Comment by sorentorp** [comment]
+1

**Comment by taers232c** [comment]
The API doesn't support this so there is nothing GAM can do. Talk to Google about adding support for this.
All you can do now is undelete the user, get the aliases and then delete the user.

Ross
--
ross.scroggs@gmail.com
