### ISSUE TITLE
gam batch file error 

### ISSUE THREAD

**Issue by sergcourt** [jay0lee/GAM#105]
Hi Jay !

Here is some really odd behavior I am noticing: batch opreation worked flawlessly then suddenly I am getting this over and over: 

$ gam batch xen.txt
Traceback (most recent call last):
  File "<string>", line 8192, in <module>
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
279, in split
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
269, in next
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
96, in get_token
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
172, in read_token
ValueError: No closing quotation

Any suggestion/ideas would be much appreciated

thanks 
Sergio

**Comment by sergcourt** [comment]
Nevermind I figured it out. The apostrophe in one of the users (o'brianetc..) was throwing everything off. Is there a way to keep that from happening?

**Comment by daethnir** [comment]
Gam cannot prevent you from screwing up your she'll command, nor should it try; it's up to the user to handle quoting properly.

**Comment by sergcourt** [comment]
daethnir/Jay , speaking of how to "handle quoting properly" could not be more spot on 
see if can make sense of this please


gam print users query 'orgUnitPath="/early adopters"'
Error 400: Invalid Input: INVALID_OU_ID - invalid


 gam print users query "orgUnitPath='/early adopters'"
Error 400: Invalid Input: INVALID_OU_ID - invalid

gam print users query "orgUnitPath='/EARLY ADOPTERS'"
Error 400: Invalid Input: INVALID_OU_ID - invalid

gam print users query 'orgUnitPath="/EARLY ADOPTERS"'
Error 400: Invalid Input: INVALID_OU_ID - invalid

print orgs works just fine: org name was copy pasted from the output
no matter how I slice it and turn quotations around, I hit a wall every time

Any ideas??

**Comment by daniejstriata** [comment]
I'm getting the same errors:
$ ./gam.py ou_and_children OUNAME show filelist query "mimeType = 'application/pdf'"
Getting all users in the Google Apps organization (may take some time on a large domain)...
Error 400: Invalid Input: INVALID_OU_ID - invalid

**Comment by daniejstriata** [comment]
What was the reason for the error?
