### ISSUE TITLE
delete drivefile commands goes very slowly

### ISSUE THREAD

**Issue by TC-matthew-wenger** [jay0lee/GAM#1058]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. call gam user $userEmail delete drivefile $line

Expected outcome (what are you trying to do?):
The file is deleted in a timely manner

Actual outcome (what errors or bad behavior do you see instead?):
The command delays by a second, doing this in mass batches in a while loop is not very efficient.

**Comment by jay0lee** [comment]
Are you specifying the file by ID or by name or query? If you are specifying a name then GAM needs to first lookup the file and then delete it. 1 second isn't unreasonable here.
