### ISSUE TITLE
Crash on credential refresh

### ISSUE THREAD

**Issue by jay0lee** [jay0lee/GAM#1063]
https://travis-ci.org/jay0lee/GAM/jobs/630968578#L1068

we seem to crash when we get a 502 response and attempt to refresh. request is a function (at least it is when we're using service account credentials). Need to figure out how to properly refresh credentials here.

**Comment by jay0lee** [comment]
$gam users "$newbase-bulkuser-07 $newbase-bulkuser-08 $newbase-bulkuser-09" modify messages query in:anywhere maxtomodify 99999 addlabel IMPORTANT addlabel STARRED doit; fi
Searching messages for travis-test-7-1577718881679-bulkuser-07@pdl.jaylee.us
Got 3 messages for user travis-test-7-1577718881679-bulkuser-07@pdl.jaylee.us
modify 3 messages
Traceback (most recent call last):
  File "/home/travis/build/jay0lee/GAM/src/gapi/__init__.py", line 84, in call
    return method(**parameters).execute()
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 502 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/batchModify?prettyPrint=false returned "Bad Gateway">
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "gam.py", line 14689, in <module>
    sys.exit(ProcessGAMCommand(sys.argv))
  File "gam.py", line 14463, in ProcessGAMCommand
    doProcessMessagesOrThreads(users, 'modify', 'messages')
  File "gam.py", line 5853, in doProcessMessagesOrThreads
    userId='me', **kwargs)
  File "/home/travis/build/jay0lee/GAM/src/gapi/__init__.py", line 94, in call
    service._http.request.credentials.refresh(create_http())
AttributeError: 'function' object has no attribute 'credentials'

**Comment by taers232c** [comment]
I'll submit a PR for this when PR #1064 is done.

**Comment by taers232c** [comment]
Can you reproduce this? How does #1066 affect it?

**Comment by jay0lee** [comment]
Not easily reproducible. Above instance was on a command using SA and we have no way of knowing if we have SA or user credentials at this point.

Handling bad gateway with a normal backoff/retry may solve here.

**Comment by ejochman** [comment]
@jay0lee @taers232c Just curious if there's any backstory as to why this behavior was originally added (I just ported it over when I migrated)?

`service._http.request.credentials.refresh(create_http())`

As far as I can tell, when you're building a service object, you're forcing it to use a google_auth_htplib2.AuthorizedHttp [here](https://github.com/jay0lee/GAM/blob/master/src/gam.py#L952) and [here](https://github.com/jay0lee/GAM/blob/master/src/gam.py#L1053), but AuthorizedHttp is already purpose-built to [refresh credentials and retry the request when necessary](https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2/blob/master/google_auth_httplib2.py#L208).

Is this still needed?
