### ISSUE TITLE
Error 400: Invalid Input: Inconsistent Orgunit id and path in request - 1629090

### ISSUE THREAD

**Issue by ktillman** [jay0lee/GAM#107]
For some reason since moving up to 3.45, I am unable to run a mass moving command I have been running for the past year. C:\GAM>gam update org lps-k-3-students add file k3.csv

I am getting the following error:
Error 400: Invalid Input: Inconsistent Orgunit id and path in request - 1629090, /lps-k-3-students - invalid. 

The OU name is valid so I don't know what is going on. Any help is appreciated

**Comment by jay0lee** [comment]
The proper way to perform this update would be:

gam csv k3.csv gam update student ~email ou "/lps-k-3-students"

closing. Please re-open if you still see erros when using the latest version of GAM.
