### ISSUE TITLE
How do I prevent GAM from generating a new App ID every time it is executed

### ISSUE THREAD

**Issue by Echavez617** [jay0lee/GAM#1073]
We currently have a client that is using the GAM app to perform administrative tasks in their Google G Suite. However, every time the GAM is executed to run, it generates a new App ID. This causes an issue with Cisco Cloudlock (CASB Client) where the App gets revoked after the App ID has been set to "trusted" because a new App ID gets generated every time it runs. How we go about preventing the GAM app from generating a new App ID every time it is executed?

Thanks in advance!

**Comment by jay0lee** [comment]
Can you post this to the discussion group?

**Comment by Echavez617** [comment]
@jay0lee Where exactly do you need me to move this too? Sorry, new to Github..

**Comment by jay0lee** [comment]
https://groups.google.com/forum/?nomobile=true#!forum/google-apps-manager
