### ISSUE TITLE
[Drive] Transfer Ownership

### ISSUE THREAD

**Issue by j8erg** [jay0lee/GAM#108]
I've got a script using GAM and it can add, delete, remove users and such which is fantastic. 
If I need to remove a user though I don't want to just delete the account. Instead of using the transfer ownership gui from within google apps. Is it possible for GAM to do this? 
```
gam user [username] transfer drive [recieving username] 
```
To transfer/move all ownership to the new user but also keep the users that have permissions on those files to view/read/etc.

**Comment by decenari** [comment]
Hey guys, I have the same issue here. Is there a way that GAM can add this? I've just got a news from Google that transferring in bulk is now possible in Drive API. Here's the link of their announcement:

http://googleappsupdates.blogspot.com/2015/09/programmatically-transfer-ownership-of.html

Hope that this can be added in GAM soon! Thank you

**Comment by jay0lee** [comment]
Closing this now that Data Transfer API is supported:

https://github.com/jay0lee/GAM/wiki/Data-Transfers#request-a-data-transfer

**Comment by j8erg** [comment]
I need to get you a beer.

**Comment by obsidianjaguar** [comment]
just wondering , does this also create a folder in the target gdrive ,,,  I e when someone leafes the company usually the manager inherits the gdrive we usually do this through the GUI and the manager niw has a folder in ther drive with persons name on it

**Comment by davidcapling-article** [comment]
> just wondering , does this also create a folder in the target gdrive ,,, I e when someone leafes the company usually the manager inherits the gdrive we usually do this through the GUI and the manager niw has a folder in ther drive with persons name on it

Sorry to necro, but I hit this exact question myself. Tested and confirmed a new folder does get made for the user's files, just titled with their email address. Hope this helps the next person with this question!
