### ISSUE TITLE
print groups crashes on group with no members

### ISSUE THREAD

**Issue by preposthuman** [jay0lee/GAM#1080]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. On a Mac, with gam installed as instructed on 2020-01-06, and with credentials authenticated, and other gam commands run successfully. Also, gam reinstalled today, 2020-01-20, and issue persists
2. `gam print groups name aliases members >company-groups.csv`

Expected outcome (what are you trying to do?):
I have run this previously with success, and the output csv looked fine.

Actual outcome (what errors or bad behavior do you see instead?):
This time it processes about half the company groups, then errors with this output
```Traceback (most recent call last):
  File "gapi/__init__.py", line 85, in call
  File "site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
  File "site-packages/googleapiclient/http.py", line 857, in execute
  File "site-packages/googleapiclient/model.py", line 216, in response
  File "site-packages/googleapiclient/model.py", line 274, in deserialize
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gam.py", line 14747, in <module>
  File "gam.py", line 14230, in ProcessGAMCommand
  File "gam.py", line 11755, in doPrintGroups
  File "gapi/__init__.py", line 260, in get_all_pages
  File "gapi/__init__.py", line 129, in call
AttributeError: 'AuthorizedHttp' object has no attribute 'cache'
[39029] Failed to execute script gam
```
But this is right after the no-reply group which has no members/owners/etc. But even last week that no-reply group was the same, and I had run the same commands, but there was no crash.
I've rerun it several times, and each time it dies at one of the three company groups that have no members/owners/etc, but last week `gam print groups name aliases members >company-groups.csv` was working fine on with no changes in those groups.

**Comment by db0mz** [comment]
I'm receiving the same error.  Here is my version info:
GAM 4.97 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.8.1 64-bit final
google-api-python-client 1.7.11
MacOS Catalina 10.15.2 x86_64

**Comment by preposthuman** [comment]
And weirdly, I've been running it sporadically though the day to crashes every time, and I just reran the same command and it succeeded, even with those same 3 groups still with no members/owners/etc.
So I'm not sure what's going on, but it's unlikely to be a gam error since nothing has changed on my end in the few minutes between when it crashed and when it succeeded.
Still, the error output could be a lot better.

**Comment by db0mz** [comment]
I'm running on a tenant with 177 groups.  I've run it 3 times and it's crashed each time.  On the first run, i was able to parse 26 groups, on run two 33, on run three 30.

**Comment by jay0lee** [comment]
Thanks for the report. This is indeed a Google issue, not something GAM can resolve. See the long thread on the forum:

https://groups.google.com/d/msg/google-apps-manager/U7KUKqstPA8/DkQo2dLZCAAJ

as I asked on the forum, please submit a support ticket to Google about this issue and reference internal issue 147908850.

Jay

**Comment by jay0lee** [comment]
This should now be fixed on Google's end. If you are still seeing crashes when listing members of a group with zero members, or any similar crashes to this one, please let me know.

Jay

**Comment by preposthuman** [comment]
Seems to be fixed now
