### ISSUE TITLE
GAM just hangs.... 

### ISSUE THREAD

**Issue by Acerbellum** [jay0lee/GAM#1099]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Enter a command, such as gam user add forwardingaddress 
2. Gam shows no response 
3. If i push a key, it says process complete. 

Expected outcome (what are you trying to do?):
Add a forwarding email 
Actual outcome (what errors or bad behavior do you see instead?):
Just get a process complete, it's not actually done, and then terminal doesnt let me run another code, have to open a new window.

**Comment by taers232c** [comment]
What platform (LInux/MacOS/Windows) are you on?
What do these commands do:
gam version
gam info domain

Ross

**Comment by jay0lee** [comment]
Please move this to the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager
