### ISSUE TITLE
running GAM commands on remote VM terminates SSH session

### ISSUE THREAD

**Issue by tofr** [jay0lee/GAM#1106]
CONFIRMED as of time of filing this issue:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

After upgrading to 4.98 yesterday (and then running several GAM CSV jobs without issue) I am now having my remote session (to the virtual machine on which I run GAM) terminated every time I try to run any GAM command.

Full steps to reproduce the issue:
1. SSH to cloud VM running ubuntu 18.04
2. Run "gam" OR "gam info" OR "game delete user..." 
3. Watch as nothing happens for 1-3minutes, then the SSH session terminates

I sincerely apologize in advance if it turns out I am doing something stupid on my end re: linux/python config or otherwise. But I had this issue once before, and my fix was to roll back to an earlier version of GAM. Now that it is happening again, I wonder if it is a GAM issue.

**Comment by MorenoUniTN** [comment]
CONFIRMED me too have the same problem describe to @tofr.
Same system (Cloud VM on VMWare)
Same server (Ubuntu 18.04)

**Comment by taers232c** [comment]
Please try the following.
cd ~/bin/gam
./gam version
./gam info domain

Does this work?

Ross
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Need more details here and possible steps to reproduce:
- are you using the binary package or running GAM Python source with Python from Ubuntu 18.04?
- if you open a 2nd SSH session before running GAM and watch the output of something like `top` what does it show after running the GAM command?

**Comment by ngrcld** [comment]
I have the same issue.

> Please try the following.
> cd ~/bin/gam
> ...
> Does this work?

Yes, this works.

**Comment by taers232c** [comment]
Look for a line like this `gam() { "/home/abc/bin/gam/gam" "$@" ; }` in the following files in your home directory: .bash_aliases, .bash_profile, .bashrc, .zshrc. `abc` will be your user name.

Replace that line with this line `alias gam="/home/abc/bin/gam/gam"` and save the file. Then execute this command: `source xyz` replaceing `xyz` with the file you edited, e,g, `source .bash_aliases`.

Now do `gam version` and `gam 
info domain`

**Comment by MorenoUniTN** [comment]
> Need more details here and possible steps to reproduce:
> 
> * are you using the binary package or running GAM Python source with Python from Ubuntu 18.04?
> * if you open a 2nd SSH session before running GAM and watch the output of something like `top` what does it show after running the GAM command?

Hy @jay0lee thanks in advanced.
Today i try to update GAm and now it's all ok. I revert my VM to last snapshot and ri-update server patch and GAM programm (normally i update gam by "bash <(curl -s -S -L https://git.io/install-gam) -l" command). But in this case i came from gam version 4.97 and update direct to gam 4.99. 
Last time, when i had a problem i updated GAM from 4.98 version to 4.99 version.

**Comment by ngrcld** [comment]
> Replace that line with this line
I did the opposite:
# alias gam="/root/bin/gam/gam"
gam() { "/root/bin/gam/gam" "$@" ; }
and now it works...

**Comment by MorenoUniTN** [comment]
I update again my VM server (Ubuntu 18.04) with the patch and GAM to version 4.99, i do the following

> Look for a line like this `gam() { "/home/abc/bin/gam/gam" "$@" ; }` in the following files in your home directory: .bash_aliases, .bash_profile, .bashrc, .zshrc. `abc` will be your user name.
> 
> Replace that line with this line `alias gam="/home/abc/bin/gam/gam"` and save the file. Then execute this command: `source xyz` replaceing `xyz` with the file you edited, e,g, `source .bash_aliases`.
> 
> Now do `gam version` and `gam info domain`

and now it works...

**Comment by rdegennaro** [comment]
Thanks for figuring this out!  We just updated two servers and ran into this issue.  Commenting out the alias in .bashrc fixes things.  Thanks again!

**Comment by tofr** [comment]
Thanks much for the attention to this. With the alias= line in my .bashrc, GAM works fine again.
