### ISSUE TITLE
batch files with blank lines at the end fail 

### ISSUE THREAD

**Issue by brainysmurf** [jay0lee/GAM#111]
Duplicate by making a file with some blank lines at the end of test.txt, then run gam batch with that text file. Deleting those lines and it works.

**Comment by dwberry** [comment]
I have the same experience with a black line at the start of the txt file.

**Comment by jay0lee** [comment]
fixed in:

https://github.com/jay0lee/GAM/commit/2235c10df7d2b732965fbaa52728f03fcc53bf00

which should ship with GAM 3.62+

Jay
