### ISSUE TITLE
gam.exe being classified as virus by several AVs

### ISSUE THREAD

**Issue by jhaar** [jay0lee/GAM#1112]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. we got a report that our AV was alerting on gam.exe (gam-4.99-windows-x86.zip)
2. virustotal.com shows 11 AVs think it's malware (https://www.virustotal.com/gui/file/597f2d7451642c9ff110cba4737801b8a246a7cb5350c10bf51778c1ca5daa2f/detection)
3.  virustotal.com shows 3 AVs think the 64bit is malware too (https://www.virustotal.com/gui/file/6f3c9b076dd0885bb4ab9092c7c8983517a5128f58eb55ef3828ff9d23c942dd/detection)

Expected outcome (what are you trying to do?):

You might want to contact the vendors about this. I'd guess they are "upset" by your "make Win executable out of self-unpacking python package" trick

Or you might just want to document this in your wiki and make your users report it to their AV vendors if it happens? (less work for you ;-)

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jogold9** [comment]
I would be interested to hear from developers of this project as to why they think Virustotal.com has several vendors flagging the Windows MSI and ZIP downloads as containing a Trojan.

https://www.virustotal.com/gui/file/50c01444d6a88f3010eaf2c9358da66baba048f045c34242c7b6137e7494c3ee/detection
