### ISSUE TITLE
can i use multiple account ?

### ISSUE THREAD

**Issue by HaxorGaruda** [jay0lee/GAM#1119]
hello sir, can i use multiple account google admin and switch when use other ?  thanks..

**Comment by Katun79** [comment]
Hello friend, you should use GAMADV-XTD3.
With this version you can manage multiple domains with different instances
https://github.com/taers232c/GAMADV-XTD3/wiki/gam.cfg#multiple-customers-and-domains


Bye

Tommaso

**Comment by jay0lee** [comment]
Yes, see docs at:

https://github.com/jay0lee/GAM/wiki/OAuthKeyManagement#selecting-which-oauth-key-file-to-use
