### ISSUE TITLE
Trouble installing GAM on Mac OS Catalina.

### ISSUE THREAD

**Issue by DJBROKEBOY1** [jay0lee/GAM#1129]
During my install i keep getting stalled at the create GAM project step with this error:

ERROR: 400: The given public key has a lifetime of 315,446,400 seconds, which is longer than the max allowed lifetime of 315,360,000 seconds as specified in resource settings

**Comment by taers232c** [comment]
This is a known issue, Jay has fixed the problem but has not released it.
This works in Advanced GAM (https://github.com/taers232c/GAMADV-XTD3 <https://github.com/taers232c/GAMADV-XTD3>)

Ross
--
ross.scroggs@gmail.com

**Comment by DJBROKEBOY1** [comment]
Oh nice! DO you think i should use advanced GAM or just wait for the release?

**Comment by jay0lee** [comment]
The fix is out now:

https://git.io/gam-releases

**Comment by DJBROKEBOY1** [comment]
Thanks man!!
