### ISSUE TITLE
TypeError when doRequestOAuth is called

### ISSUE THREAD

**Issue by kimmoo** [jay0lee/GAM#113]
Hi,

I came to help when client had issue on updating their email list with GAM. They had the following error message:
Traceback (most recent call last):
  File "./gam/gam.py", line 8397, in <module>
    doUpdateGroup()
  File "./gam/gam.py", line 5228, in doUpdateGroup
    cd = buildGAPIObject(u'directory')
  File "./gam/gam.py", line 566, in buildGAPIObject
    doRequestOAuth()
  File "./gam/gam.py", line 8196, in doRequestOAuth
    selection = raw_input(menu % menu_fill)
TypeError: not all arguments converted during string formatting

My understanding is that on line 8195
    menu_fill = tuple(selected_scopes)+scope_choices
should be
    menu_fill = tuple(selected_scopes)

I saw from git history that this change was made in bbfe5d36e82138ea1348e8be5fcaa4e1e2bffa13 on 20.8.2015

Kimmo

**Comment by lukwam-alienwebshop** [comment]
Thanks, this fix worked for me as well.

**Comment by jay0lee** [comment]
This should be fixed in current 3.61 release. Re-open if it's not.
