### ISSUE TITLE
Installing gam cleanly. Error: Attribute: browser_download_url for macos-x86_64-MacOS10.14.4.tar.xz version latest not found

### ISSUE THREAD

**Issue by kwoest-hbc** [jay0lee/GAM#1131]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. I need to install gam cleanly on a new computer. My OS is 10.15.3.
2. I am following: https://github.com/jay0lee/GAM/wiki#mac-and-linux-users
3. The error I get: 
```$ bash <(curl -s -S -L https://git.io/install-gam) -l
You are running MacOS 10.15.3
Using GAM compiled on MacOS10.14.4

Checking GitHub URL https://api.github.com/repos/jay0lee/GAM/releases for latest GAM release...

Getting file and download URL...

ERROR: Attribute: browser_download_url for macos-x86_64-MacOS10.14.4.tar.xz version latest not found```

Expected outcome (what are you trying to do?): I should see the latest release of GAM installed at $HOME/bin/gam directory. There is nothing at that location (likely because it couldn't find that tar file).

Actual outcome (what errors or bad behavior do you see instead?): I just see the error listed above and the command prompt returned.

**Comment by jay0lee** [comment]
This is an issue with the install script still looking for 10.14.4 build when the builder moved to 10.14.6. I've updated the install script. You may need to wait up to an hour before re-running the curl command to pull the new version works though. Let me know how it goes.

**Comment by kwoest-hbc** [comment]
Understood. Thank you for your prompt response! I'll give it a try in an
hour or so. Will keep you posted.

Thanks, again!

**Comment by kwoest-hbc** [comment]
@jay0lee I have gotten to the point where I now must select scopes. After making my selection, I am prompted to follow a link and then paste the verification code. When I do that, I see this error:

`Enter verification code: *********************************************************
Traceback (most recent call last):
  File "gam.py", line 11600, in <module>
  File "gam.py", line 11161, in ProcessGAMCommand
  File "gam.py", line 10105, in doRequestOAuth
  File "auth/oauth.py", line 365, in from_client_secrets_file
  File "auth/oauth.py", line 306, in from_client_secrets
  File "auth/oauth.py", line 201, in from_google_oauth2_credentials
  File "site-packages/google/oauth2/credentials.py", line 294, in to_json
  File "json/__init__.py", line 231, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "json/encoder.py", line 179, in default
TypeError: Object of type set is not JSON serializable
[13725] Failed to execute script gam
Admin authorization failed. Trying again. Say N to skip admin authorization.`

Any advice on how to proceed? Thanks, again.

**Comment by jay0lee** [comment]
That issue is fixed and I'm pushing an emergency 5.01 release shortly.

Jay Lee

**Comment by jay0lee** [comment]
5.01 is released, you should be able to grab it by re-running the script.

Jay Lee

**Comment by kwoest-hbc** [comment]
Thank you. A bit further now. I'm at the point of entering in a service account. I expected some FAIL notifications but I also get a traceback:

`$ gam user gam-service-account@mydomain.com check serviceaccount
Computer clock status:
 Your system time differs from www.googleapis.com by less than 1 second     PASS
Service Account Private Key Authentication:
 Authenticating...                                                          PASS
Checking key age. Google recommends rotating keys on a routine basis...
 Key is 0 days old                                                          PASS
Domain-Wide Delegation authentication as gam_service_account@hbc.com:
 https://mail.google.com/                                                   FAIL
 https://www.googleapis.com/auth/activity                                   FAIL
 https://www.googleapis.com/auth/apps.alerts                                FAIL
 https://www.googleapis.com/auth/calendar                                   FAIL
 https://www.googleapis.com/auth/drive                                      FAIL
 https://www.googleapis.com/auth/gmail.settings.basic                       FAIL
 https://www.googleapis.com/auth/gmail.settings.sharing                     FAIL
 https://www.googleapis.com/auth/spreadsheets                               FAIL
Traceback (most recent call last):
  File "gam.py", line 11600, in <module>
  File "gam.py", line 11532, in ProcessGAMCommand
  File "gam.py", line 1024, in doCheckServiceAccount
NameError: name 'shorten_url' is not defined
[14388] Failed to execute script gam`

Thank you.

**Comment by jay0lee** [comment]
working on it...

**Comment by jay0lee** [comment]
OK, I just pushed 5.02 which should fix that.

**Comment by jay0lee** [comment]
marking this as closed now, if you find further issues please open a new bug
