### ISSUE TITLE
gam print crosactivity local variable assignment issue

### ISSUE THREAD

**Issue by gladiusaxelay** [jay0lee/GAM#1138]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
Yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
Yes

Full steps to reproduce the issue:
1. Execute "gam print crosactivity"

Expected outcome (what are you trying to do?):
Print CrOS devices activity

Actual outcome (what errors or bad behavior do you see instead?):

Traceback (most recent call last):
  File "gam.py", line 11600, in <module>
  File "gam.py", line 11089, in ProcessGAMCommand
  File "gapi/directory/cros.py", line 424, in doPrintCrosActivity
UnboundLocalError: local variable 'new_row' referenced before assignment
[2378] Failed to execute script gam

I suspect variable on line 424 should be 'newrow' instead of 'new_row'

**Comment by jay0lee** [comment]
fixed in #1139 and will be in next release.
