### ISSUE TITLE
can't download exported mailboxes

### ISSUE THREAD

**Issue by uobmally** [jay0lee/GAM#114]
Hi,

I'm trying to export a download, but it seems GAM errors and then downloads 0bytes?

using:
# ./gam audit export download xxxx 512064154
Downloading export-xxxx-512064154-0.mbox.gpg (1 of 1)
Dito GAM 3.03
jay@ditoweb.com (Jay Lee)
Python 2.7.9 64-bit final
google-api-python-client 1.2
Linux-3.2.0-0.bpo.4-amd64-x86_64-with-debian-6.0.10 x86_64
Path: /usr/local/projects/mailrelay/GAM/xxxxx

Usage: gam [OPTIONS]...

I'm confused, any ideas?

**Comment by jay0lee** [comment]
Closing as this is a howto question which belongs in the discussion group. Please use the issue tracker for verified bugs only.
