### ISSUE TITLE
/auth/apps.alerts FAILS

### ISSUE THREAD

**Issue by vmatt** [jay0lee/GAM#1143]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Run gam-setup.bat
2. Stuck @ Are you ready to authorize GAM to manage G Suite user data and settings? [y or n]

Expected outcome (what are you trying to do?):
"GAM installation and setup complete!"
Actual outcome (what errors or bad behavior do you see instead?):
https://www.googleapis.com/auth/apps.alerts will FAIL always, even with super admin user.
As I saw, Google modified the Alert Center on the GUI, maybe something wrong the API too on Google side.

**Comment by jay0lee** [comment]
Have you waited 24 hours after adding the scoped in the admin console?

**Comment by jay0lee** [comment]
What type of Google domain is this? (G Suite EDU / Business, Cloud Identity, etc). Can you post the output of:

```
gam info domain
gam info user
```

FYI, the Alert API fail really only matters if you are trying to use GAM commands that use the Alert Center API. If you just want to use other commands like Gmail, Calendar and Drive you can safely ignore this FAIL (though it would be good to understand why it's failing.)

Jay

**Comment by taers232c** [comment]
Jay,

This is resolved, I worked with him, he had not assigned the oauth2.txt user as a domain admin.

Ross

**Comment by vmatt** [comment]
Education.
I tried to run with the default super user account (the very first account in the organization), and with some regular user. But yeah, I'm not using the Alert Center API.. just the gam-setup.bat is failing.

thanks for your help!
