### ISSUE TITLE
Message Type Out Of Office AutoReplay

### ISSUE THREAD

**Issue by Silente** [jay0lee/GAM#1146]
Good morning, 
I've noticed an anomaly regarding the automatic out of office response when you have a signature in HTML format. It is necessary to set the message text in "Rich formatting" rather than "Plain Text".

Is it possible to set it massively Out-of-Office AutoReply in Rich formatting from GAM?

**Comment by jay0lee** [comment]
Please post "how do I?" type questions to the discussion forum:

https://groups.google.com/forum/#!forum/google-apps-manager

thanks,

Jay
