### ISSUE TITLE
Can't upgrade from 4.96 to 5.03

### ISSUE THREAD

**Issue by pstoric83** [jay0lee/GAM#1147]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  I've downloaded the "gam-5.03-windows-x86.msi" MSI and installed it. It installed to C:\GAM which is the correct folder. Nothing happened after but when I open GAM from cmd it show's it's still on version 4.96. Are there any additional commands I need to run to get it to update?

2.
3.

Expected outcome (what are you trying to do?): Update from 4.96 to 5.03

Actual outcome (what errors or bad behavior do you see instead?): No errors but the upgrade isn't happening.

**Comment by jay0lee** [comment]
Please post "how do I?" questions to the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager
