### ISSUE TITLE
Wipe mobile account on all devices for a user

### ISSUE THREAD

**Issue by adamehret** [jay0lee/GAM#116]
Is it possible to create a command to wipe all mobile accounts on all devices for a user? I am trying to use a for /f command with the CSV output of the 'print mobile query username' but having issues with blank fields. If there was just a command I could run that would wipe all accounts for a single user would be very helpful.

**Comment by jay0lee** [comment]
Please post this question to the mailing list:

https://groups.google.com/forum/#!forum/google-apps-manager
