### ISSUE TITLE
Ver 5.05 Error 409 and 500 when creating courses

### ISSUE THREAD

**Issue by Robin1824** [jay0lee/GAM#1161]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Command Issued: gam csv HVCLower.csv gam create course alias ~alias name ~alias section ~section heading ~heading teacher ~teacher status ACTIVE
2.
3.

Expected outcome (what are you trying to do?):

Create 144 google courses in classrooms and assign a specific owner to them.

Actual outcome (what errors or bad behavior do you see instead?):

The sequence partially completed and during the process, threw multiple Error 409 and Error 500 codes.
Only 47 of the 144 courses were created. If the same command if run again, it starts and identifies the duplicate classes and skips over them, creates a few more and gives the same error codes and completes. I have to run the process for 5 or 6 times to get all of the classes loaded.

Attached are the CSV file used, the output of the command screen and the listed courses printed after the command completed.

[Gam course creation issue.zip](https://github.com/jay0lee/GAM/files/4493436/Gam.course.creation.issue.zip)

**Comment by jay0lee** [comment]
Many of your aliases contain a space which is not valid. Replace the space with a _ and retry.

Closing this out, if you have further issues please post to the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager
