### ISSUE TITLE
AgreedtoTerms non-responsive when Updating User

### ISSUE THREAD

**Issue by Explore-OR** [jay0lee/GAM#1167]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
5.06 installed
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Select any user
2. Update user information and specifically the 'agreedtoterms' switch 
3. Other switch parameters work toggling between false and true: Changepassword, GAL, Suspended etc work properly. No combination of switches work with 'agreedtoterms' and I've made sure to copy & paste the command. 

Expected outcome (what are you trying to do?):
Turn the 'Has agreed to terms: False' into True

Actual outcome (what errors or bad behavior do you see instead?):
Running the line of code says updating user but subsequent user info command reveals no change.

**Comment by jay0lee** [comment]
AgreedToTerms is read only. GAM can try to update it but it's not allowed. Only the user logging in and accepting terms will toggle it.

**Comment by Explore-OR** [comment]
That was my suspicion, thanks for confirmation.

Robert Moore
Support Specialist
Clackamas ESD
503-675-4076(w)
