### ISSUE TITLE
Support for new option to allow less secure apps access?

### ISSUE THREAD

**Issue by ke43ro** [jay0lee/GAM#117]
I noticed that using GAM to set IMAP on, doesn't also set access for less secure apps.  Is there a plan to enable this or add it as a separate option?

**Comment by ke43ro** [comment]
See also: https://groups.google.com/d/topic/google-apps-manager/vV63aoBrnLY/discussion

**Comment by jay0lee** [comment]
Closing this as not feasible since there's no API to modify this setting.
