### ISSUE TITLE
Guardian invite not sending invitation when two children with similar email (same first name) are one following each other

### ISSUE THREAD

**Issue by pbeltran** [jay0lee/GAM#1172]
This issue happens with GAM 5.04. 
Today I have upgraded to 5.07, so I don't know if it's fixed.

Full steps to reproduce the issue:
1. csv with two lines in this way:
john.smith.05@domain.com, tutor@domain.com
john.garcia.09@domain.com, tutor@domain.com

2. run 
gam csv parents.csv gam create guardianinvite ~parent-email ~student-email

3. Only the first one is sent. However, both of them appears as "invite" when you go to Google Classroom to list people. 

It has happened three times with different classes.

Thanks
Pablo

**Comment by jay0lee** [comment]
This is likely Google avoiding spamming a parent with unnecessary emails, GAM doesn't send the emails, it merely tells Google to invite the guardian for the student. If this is a major problem for you I'd suggest opening a case with Google.
