### ISSUE TITLE
Signatures upload no longer worker

### ISSUE THREAD

**Issue by Viktor-913** [jay0lee/GAM#1175]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
Using Latest version of GAM.

GAM can pull down a signature just fine into an HTML file
gam user me show signature > me.html

I can make changes to the signature and upload it successfully with this command.
gam user me signature file me.html html

It even shows the signture that I uploaded
C:\Users\admin>gam user meshow signature
SendAs Address: <me@me.com> (1/1)
  IsPrimary: True
  Default: True
  Signature:
    <div dir="ltr"b style="font-size:12.8px"font size="2"

Unfortunately when I go into settings to view my signature in gmail it no longer shows the signature and when I go to compose it does not show it.

I see that gmail has updated to have the option for multiple signatures now. Maybe that is causing a conflict with GAM.

**Comment by taers232c** [comment]
If you are logged in to Gmail when the signature is updated, you have to log out and back in to see the new signature

Ross
--
ross.scroggs@gmail.com

**Comment by Viktor-913** [comment]
You are correct.

Thanks!

Should I open a new ticket regarding the option for different signatures and how to handle them now within GAM?

**Comment by taers232c** [comment]
When I looked a couple of days ago, there was no API support for named signatures.

--
ross.scroggs@gmail.com

**Comment by Viktor-913** [comment]
Ok thanks.
