### ISSUE TITLE
Temporary error: backendError, Backing off on License Change.

### ISSUE THREAD

**Issue by haroldstewart** [jay0lee/GAM#1176]
I am trying to changes assigned licenses.  I have tried the reassignment and the add command, and I get the same message.  I know I have done his in the past.  I have tried the latest GAM 5.07, and the version GAM 4.96 that I used previous.  Both are giving me the same errors.

C:\Users\HStew5>gam user <Email> add license 1010010001
Adding license 1010010001 (Cloud Identity) to user <Email>
Temporary error: backendError, Backing off: 16 seconds, Retry: 4/10
Temporary error: backendError, Backing off: 32 seconds, Retry: 5/10
Temporary error: backendError, Backing off: 60 seconds, Retry: 6/10

**Comment by jay0lee** [comment]
Can you provide a screenshot of your admin.google.com > Billing page? Most customers have Cloud Identity licensed for all users in the domain (domain-wide licensing) and there should be no need to apply the license to specific users.

**Comment by haroldstewart** [comment]
Hi Jay

Thank so much for the quick reply.   That was my understanding also, so maybe I doing wrong actions.  My goal is to remove the gsuitebusiness license in favor cloudIdentity license.   Here some of my attempts.


C:\Users\HStew5>gam user kevin.cen@nike.com update license gsuitebusiness to 1010010001
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com update license gsuitebusiness to cloudidentity
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com update license gsuitebusiness to identity
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com update license gau to 1010010001
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com update license unlimited to 1010010001
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com update license unlimited to cloudidentity
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com update license gau to 1010010001
Changing user kevin.cen@nike.com from license to to Google-Apps-Unlimited (G Suite Business)

ERROR: 400: Invalid skuId: to - invalid

C:\Users\HStew5>gam user kevin.cen@nike.com add license 1010010001
Adding license 1010010001 (Cloud Identity) to user kevin.cen@nike.com
Temporary error: backendError, Backing off: 16 seconds, Retry: 4/10
Temporary error: backendError, Backing off: 32 seconds, Retry: 5/10

**Comment by jay0lee** [comment]
Since the CI license is domain-wide, you just need to remove the G Suite license from the user. This of course assumes that you are not auto-assigning the G Suite license (you need to turn of G Suite auto-assing in admin.google.com > Billing for G Suite).

gam user whoever delete license Google-Apps-Unlimited

**Comment by haroldstewart** [comment]
So my auto-assigning is off, except for the GSuite OU.  The account I am trying to move is now it the CloudIdentity OU.  I still get an error message

C:\Users\HStew5>gam user <email> delete license Google-Apps-Unlimited
Removing license Google-Apps-Unlimited (G Suite Business) from user <email>

ERROR: 412: Auto License un-assignment is not allowed. - conditionNotMet

**Comment by jay0lee** [comment]
Did you first move the user out of the auto-assign OU?

Jay Lee

**Comment by haroldstewart** [comment]
I think I have identified the cause.  I test another account it worked.   So I executed my batch, and some worked and others didn’t.  The ones that failed, had all been suspended by GCDS.

Thanks you for all your help..
