### ISSUE TITLE
Error after successful install - Any help appreciated

### ISSUE THREAD

**Issue by MrAlgo** [jay0lee/GAM#1178]
![image](https://user-images.githubusercontent.com/30338279/80796243-9cc91300-8b96-11ea-856e-49837a9ed466.png)

**Comment by jay0lee** [comment]
What is the output of:
```gam version extended
gam oauth info```

**Comment by MrAlgo** [comment]
Thanks for coming back. I uninstalled and reinstalled to fix it.
