### ISSUE TITLE
Gam, cannot find export

### ISSUE THREAD

**Issue by mattbarham** [jay0lee/GAM#1184]
Full steps to reproduce the issue:
1. Create export using `gam create export matter "example" corpus mail accounts example@example.com`
2. Try to get info or download export using `gam download export "example" exportly-****`
3. I can see the export is finished in the G-Suite GUI

Expected outcome (what are you trying to do?):
I expect the export to download.

Actual outcome (what errors or bad behavior do you see instead?):
`could not find export name exportly-**** in matter example`

**Comment by mattbarham** [comment]
Seems like you can no longer export using the id and now have to use the export name.

**Comment by taers232c** [comment]
Exporting by ID works fine, you have to add the prefix id: to the exportID
```gam download export "example" id:exportly-****```

Ross
