### ISSUE TITLE
Win 10 GAM Project creation failed. "set up error 404  uploading new public certificate to google"

### ISSUE THREAD

**Issue by mbcsweb** [jay0lee/GAM#1185]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. yes gam 5.08 windows x86_64.msi
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. run gam-5.08-windows-x86_64.msi
2. enter G Suite admin email address
3. copy code from link provided in set up

Expected outcome (what are you trying to do?): Install GAM

Actual outcome (what errors or bad behavior do you see instead?): 
"...Setting GAM project consent screen...
Creating Service Account
 Generating new private key...
 Extracting public certificate...
 Done generating private key and public certificate.
 Uploading new public certificate to Google...

ERROR: 404: Requested entity was not found. - 404

Project creation failed. Trying again. Say n to skip project creation."

**Comment by jay0lee** [comment]
This is fixed in GAM 4.09.

git.io/gam-releases
