### ISSUE TITLE
GAM stopped working and is giving a 404 error

### ISSUE THREAD

**Issue by cbf305** [jay0lee/GAM#1186]
I last used GAM a few days ago on Thursday (5/7/2020) with no issue.  This morning I went to run a command to update a group and it gave me the authorize scopes prompt.  I though this was very odd, so I checked my oauth files and everything is in order and they have not been modified since Thursday.   When I type "c" it asks for my admin email address and then it says that I need to run "gam create project"  There is a valid project in the admin account, but clearly it doesn't care, so I ran the command.  I go through the process and then once I paste back in the verification code it runs through a bunch of checking and then at the line "Uploading new public certificate to Google..." it returns "ERROR: 404: Requested entity was not found. - 404" and exits

I was on version 5.05, so I checked the releases and I saw that 5.08 addresses some OAuth token issues, so I updated to 5.08 thinking maybe Google changed something and this addresses that.  It also fails in the same spot with the same error.

I downgraded back to 5.05 and still can't get it working.  So I am back on 5.08.  And I still have no clue why it just stopped working.  I am on Linux and have GAM installed via the AUR.  Here is the version output.

GAM 5.08 - https://git.io/gam - pythonsource
Jay Lee <jay0lee@gmail.com>
Python 3.8.2 64-bit final
google-api-python-client 1.8.0
Linux Manjaro 20.0.1 Lysia x86_64
Path: /usr/share/gam

My oauth files are located at ~/.config/gam, which is where they have been for several years now.  And I also tried various gam oauth commands and they say I need to run "gam create project".  I even checked the GSuite status page to see if there was any outages.
 
After two days of head scratching I decided test with a VM.  I had an Arch VM that I was going to use for another project but didn't get to yet so it was basically a fresh install.  I updated the VM, booted fresh and installed GAM from the AUR and ran "gam create project".  This time it didn't give me a 404 error, but it have me a file system permission error (see screenshot).
![screenshot_2020-05-12-12-50](https://user-images.githubusercontent.com/2612500/81723346-b3058780-9450-11ea-9239-856bbd3a558e.png)
I checked the ~/.config/gam directory that it created and it had weird permissions set on it.  Since it didn't write any of the oauth files, I deleted the directory, made it manually with mkdir and ran "gam create project" again.  Now I am back to the 404 error again and the only file written to the directory is the lastupdatecheck.txt file.

So now I am just stumped.  I am happy to provide more information if it would help, but any clue why it stopped work or why I am getting the 404 on now two different machines?

Thanks!

**Comment by jay0lee** [comment]
This is fixed in 5.09:

https://git.io/gam-releases
