### ISSUE TITLE
[report usageparameters user | customer] always fails

### ISSUE THREAD

**Issue by s-strydom** [jay0lee/GAM#1188]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam report usageparameters user
2.
3.

Expected outcome (what are you trying to do?):
Output usage parameters 

Actual outcome (what errors or bad behavior do you see instead?):
$ gam report usageparameters user
Traceback (most recent call last):
  File "gam\__main__.py", line 50, in <module>
  File "gam\__main__.py", line 45, in main
  File "gam\__init__.py", line 14434, in ProcessGAMCommand
  File "gam\gapi\reports.py", line 280, in showReport
  File "gam\gapi\reports.py", line 98, in showUsageParameters
KeyError: 'usageReports'
[15836] Failed to execute script __main__

**Comment by jay0lee** [comment]
This is now fixed in the master branch and will be in the next GAM release in the next few days.

**Comment by s-strydom** [comment]
That was quick, thank you
