### ISSUE TITLE
gam print transferapps - 403 insufficient permissions

### ISSUE THREAD

**Issue by benkoller** [jay0lee/GAM#119]
Hi,

when I run a gam print transferapps I get a "Error 403: Insufficient Permission - insufficientPermissions". I doublechecked, all APIs are active in the developer console. Any hints where to start looking into this?

Cheers!

**Comment by andrewbirch** [comment]
Works for me :)

**Comment by nferrell** [comment]
Sounds like your user account does not have sufficient permissions to use
the API'S you're trying to use, or you are accidentally using the wrong
domain credentials in a domain where you should have sufficient permissions.

Anyone can activate all of their API'S, but that doesn't necessarily means
you have the sufficient permissions to use them.

**Comment by jay0lee** [comment]
Run:

gam oauth revoke

To kil the old token and then run your command again. You'll be prompted to
authorize with the new scopes.

Jay

On Wed, Sep 30, 2015, 2:50 AM nferrell <notifications@github.com> wrote:

> Sounds like your user account does not have sufficient permissions to use
> the API'S you're trying to use, or you are accidentally using the wrong
> domain credentials in a domain where you should have sufficient
> permissions.
>
> Anyone can activate all of their API'S, but that doesn't necessarily means
> you have the sufficient permissions to use them.
> On Sep 29, 2015 11:45 PM, "Andrew Birch" <notifications@github.com> wrote:
>
> > Works for me :)
> >
> > On 30/09/2015 16:31, benkoller wrote:
> > >
> > > Hi,
> > >
> > > when I run a gam print transferapps I get a "Error 403: Insufficient
> > > Permission - insufficientPermissions". I doublechecked, all APIs are
> > > active in the developer console. Any hints where to start looking into
> > > this?
> > >
> > > Cheers!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/jay0lee/GAM/issues/119>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jay0lee/GAM/issues/119#issuecomment-144303693>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/119#issuecomment-144306321>.
>
-- 

Jay Lee

**Comment by benkoller** [comment]
Thx for that, fixed it.

**Comment by livingmurali** [comment]
Thanks for the solution.
