### ISSUE TITLE
Win 10 GAM 5.09 install fails at "select the authorized scopes" - no response or error

### ISSUE THREAD

**Issue by mbcsweb** [jay0lee/GAM#1190]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. Yes 5.09 msi
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
yes
Full steps to reproduce the issue:
1.Install 5.09
2.follow all command prompts
3.at "select the authorized scopes by entering a number" - the cmd line stops responding

Expected outcome (what are you trying to do?):
Install 5.09 on Win 10
Actual outcome (what errors or bad behavior do you see instead?): cmd line stops responding
-----------
Can't get past this. Tried s and then 1 and then 2 and then 3 and so on. No change in screen

------------
Select the authorized scopes by entering a number.
Append an 'r' to grant read-only access or an 'a' to grant action-only access.

[*]  0) Classroom API - counts as 5 scopes
[*]  1) Cloud Print API
[*]  2) Data Transfer API (supports readonly)
[*]  3) Directory API - Chrome OS Devices (supports readonly)
[*]  4) Directory API - Customers (supports readonly)
[*]  5) Directory API - Domains (supports readonly)
[*]  6) Directory API - Groups (supports readonly)
[*]  7) Directory API - Mobile Devices (supports readonly and action)
[*]  8) Directory API - Organizational Units (supports readonly)
[*]  9) Directory API - Resource Calendars (supports readonly)
[*] 10) Directory API - Roles (supports readonly)
[*] 11) Directory API - User Schemas (supports readonly)
[*] 12) Directory API - User Security
[*] 13) Directory API - Users (supports readonly)
[*] 14) Group Settings API
[*] 15) License Manager API
[*] 16) Pub / Sub API
[*] 17) Reports API - Audit Reports
[*] 18) Reports API - Usage Reports
[*] 19) Reseller API
[*] 20) Site Verification API
[*] 21) Vault Matters and Holds API (supports readonly)
[*] 22) Cloud Storage (Vault Export - read only)
[*] 23) User Profile (Email address - read only) [required]

     s)  Select all scopes
     u)  Unselect all scopes
     e)  Exit without changes
     c)  Continue to authorization

Please enter 0-23[r|a] or s|u|e|c:

**Comment by kashmirix** [comment]
Please read the hatnote once again: "The issue tracker is for reporting product deficiencies. 'How do I?' questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager."

**Comment by jay0lee** [comment]
Use "c" to continue to the next step.
