### ISSUE TITLE
Installing GAM on Catalina project error

### ISSUE THREAD

**Issue by jhesseg** [jay0lee/GAM#1205]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. YES
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
YES

Full steps to reproduce the issue:
Running through the installation of GAM. I get to that part where I need to create a project and it asks for the Gmail admin email. I enter my admin email, approve granting access to GAM, copy the link it gives me, paste in terminal and I end up with the following error. I have tried revoking the API permission and starting over and no luck. 

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: {'name': 'operations/cp.7503222764418340346', 'metadata': {'@type': 'type.googleapis.com/google.cloudresourcemanager.v1.ProjectCreationStatus', 'ready': True}, 'done': True, 'error': {'code': 7, 'message': "Permission 'resourcemanager.projects.create' denied on parent resource 'organizations/724465662266'.", 'details': [{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceType': 'project', 'resourceName': 'projects/gam-project-9p2-un3-y5u'}]}}
jhesse@lmjgarcia061221 ~ %

**Comment by jay0lee** [comment]
Permission 'resourcemanager.projects.create' denied on parent resource 'organizations/724465662266

you don't have rights to create projects in your GCP organization. you can:

1. Create the project under a GCP folder you DO have access to create projects under
```gam create project parent <name of folder resource>```
1. Pre-create the project, make sure you have full rights to update the project and then run:
```gam use project```

**Comment by jhesseg** [comment]
Thank you for the quick response! That was it.

**Comment by jpmckinney** [comment]
Just a note that despite having Owner and Organization Administrator roles in my organization, I somehow still lack the resourcemanager.projects.create permission. Adding the Project Creator role fixes it: https://console.cloud.google.com/iam-admin
