### ISSUE TITLE
Google API includeDerivedMembership=true return less members

### ISSUE THREAD

**Issue by eduardomazolini** [jay0lee/GAM#1210]
https://developers.google.com/admin-sdk/directory/v1/reference/members/list

I opened the issue as an alert and a request for help to have more evidence.
I suggested it and you guys helped me to create "group_inde" option to synchronize students in a course.
But I found a bug in the google API, a bug that returns a smaller number of members when includeDerivedMembership=true.
It is not a bug of this software or of the SDK I was able to verify in API Explorer.
The smallest value is always the same for a group, but random between groups.
I discover the problem when students called me saying they were not enrolled in the course.

G Suite support say API is not supported.

https://issuetracker.google.com/issues/158068869

**Comment by xdgc** [comment]
Your Google issue is not visible to me, but I'm seeing problems with this API suddenly too. I first saw it today, but am not sure for how long it's been failing. It has worked recently.

I am not using GAM in this instance; I'm calling API methods directly. I smell something awry at Google.

**Comment by xdgc** [comment]
I updated my GAM installation to GAMADVwhatever 5.04.08 to get support for includeDerivedMembership in `gam print group-members` and I can confirm the same incorrect (limited) response from the API using both GAM and my own API client, with two distinct service users. Google problem.

**Comment by taers232c** [comment]
David,

See: https://github.com/taers232c/GAMADV-XTD3/wiki/Groups-Membership#display-group-membership-in-csv-format <https://github.com/taers232c/GAMADV-XTD3/wiki/Groups-Membership#display-group-membership-in-csv-format>

Compare using recursive (GAM does the recursion) and includederivedmembership (API does the recursion).

Ross
--
ross.scroggs@gmail.com

**Comment by xdgc** [comment]
Ross, it's not a GAM problem. It's distinctly an API issue.

**Comment by taers232c** [comment]
David,

Yes, I understand, but by comparing the two outputs you can get a handle on what's missing.

Ross
--
ross.scroggs@gmail.com

**Comment by daethnir** [comment]
Still broken in the google world, per their support team:

> As is the end of the month, I checked in with our support engineers to get news on progress updates from our product engineer team in regards to the issue and currently we still don’t have any resolution. It is taking longer than expected but note that the ticket remains open as well as the technical investigation. I will update again next month or if I have news earlier, then.
> 
> Thanks again for your understanding, patience and time.

**Comment by daethnir** [comment]
I've gotten an update from the google development team on my open ticket #23803777 around the accuracy of this API:


They confirm that the API does not return accurate data immediately.

"Depending on the volume of the action, how many indirect memberships and system load, [accuracy is] up to 3 days, with a minimum time of 5 minutes."


I also asked if they could update the API documentation, and the response is

"There is no official documentation available for this specific topic, and currently there are no plans to create developer documentation any time soon."



My ticket remains open, but it's taken ~4 months to get to this point so I'm not very hopeful we'll get a proper resolution.
