### ISSUE TITLE
Resources.calendars missing functionality

### ISSUE THREAD

**Issue by zakkojo** [jay0lee/GAM#1214]
Is it possible to add methods to manage resourceCategory for Resources.calendars?

Property name: resourceCategory 
Value: string
Description: The category of the calendar resource. Either CONFERENCE_ROOM or OTHER. Legacy data is set to CATEGORY_UNKNOWN.
Acceptable values are: "CATEGORY_UNKNOWN""CONFERENCE_ROOM""OTHER" 
Notes: writable

Source: https://developers.google.com/admin-sdk/directory/v1/reference/resources/calendars

**Comment by jay0lee** [comment]
You can set `resourceCategory=CONFERENCE_ROOM` by appending `category room` to your command:

```
gam create resource testtest testtest category room capacity 5 building mybuilding floor 1
```

wiki may need to be updated.

**Comment by zakkojo** [comment]
thank you @jay0lee, what if I need to set OTHER instead?

**Comment by jay0lee** [comment]
"category other" should work. Give it a shot.

Jay Lee

**Comment by zakkojo** [comment]
it works! 
Thank you for your time
