### ISSUE TITLE
G-Suite Signatures

### ISSUE THREAD

**Issue by theo-up42** [jay0lee/GAM#1219]
Hello,

More of a question than an issue. Is there a way for the html signature to automatically fill in the user details like Full Name and Job Title?

Thanks in advance

**Comment by HJZWEERS** [comment]
Hi Thea,

I am not sure if it can be done in GAM but here is a Stackoverflow article on how to do it in Apps Script.

https://stackoverflow.com/questions/40936257/how-to-use-the-gmail-api-oauth2-for-apps-script-and-domain-wide-delegation-to/40936258#40936258

**Comment by taers232c** [comment]
This is available in Advanced GAM:
https://github.com/taers232c/GAMADV-XTD3/wiki/Tag-Replace#user-attribute-replace-tag-userreplacement-processing

Ross

**Comment by luke-carwowo** [comment]
You could print users organization details to a csv

`print users organizations >> ~/Desktop/orgusers.csv`

And then use the bulk command to add signatures for multiple users using the CSV file.

Add signatures for multiple users using that CSV file and a template .html file

`gam csv signatures-list.csv gam user ~primaryEmail signature file signature-template.html replace Job\ Title ~organizations.0.title`

**Comment by ZackCMC** [comment]
Not a GAM answer, but these guys work well if you need this quickly:
https://signaturesatori.com/
