### ISSUE TITLE
Can't Update Organization Name

### ISSUE THREAD

**Issue by pixelizoid** [jay0lee/GAM#122]
Hi,

I keep getting the following error when trying to change the nice name of my organization:

python gam.py update domain name "New Name"
ERROR: New Name is not a valid argument to "gam update domain"

Any ideas Jay?

Thanks!
Adi

**Comment by jay0lee** [comment]
Try:

python gam.py update instance name "New Name"

some of these commands got changed in order to make room for the new Domain
API support.

Jay

On Fri, Oct 2, 2015 at 6:27 AM pixelizoid <notifications@github.com> wrote:

> Hi,
>
> I keep getting the following error when trying to change the nice name of
> my organization:
>
> python gam.py update domain name "New Name"
> ERROR: New Name is not a valid argument to "gam update domain"
>
> Any ideas Jay?
>
> Thanks!
> Adi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/122>.
>
-- 

Jay Lee
