### ISSUE TITLE
GAM stopped working (not just for me) ERROR: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest returned "Request contains an invalid argument.">

### ISSUE THREAD

**Issue by HJZWEERS** [jay0lee/GAM#1221]
Hi all,

Me (and my colleagues) are unable to user GAM for any of our customers.
Error is: ERROR: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest returned "Request contains an invalid argument.">

Anyone else seeing this issue?

Thanks!
Henk

**Comment by rwatterson** [comment]
I am seeing that issues also, google searches are pointing me towards the
access token.
If anyone gets a fix please post !

On Thu, Jul 23, 2020 at 8:42 AM HJZWEERS <notifications@github.com> wrote:

> Hi all,
>
> Me (and my colleagues) ate unable to user GAM for any of our customers.
> Error is: ERROR: <HttpError 400 when requesting
> https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__www.googleapis.com_discovery_v1_apis_admin_directory-5Fv1_rest&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=WmIDKGSxcW04bMi1bMwbmXEpVvNnH6HxyizcKbHEvJo&m=sK21p5ECstjUgot6X6UHd4SedkxwU9Q4NMwW7Ea1i5k&s=_hkOlTpI8BlmOsFflju1d9oNgV9qgoM8j88ZNasyudU&e=>
> returned "Request contains an invalid argument.">
>
> Anyone else seeing this issue?
>
> Thanks!
> Henk
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jay0lee_GAM_issues_1221&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=WmIDKGSxcW04bMi1bMwbmXEpVvNnH6HxyizcKbHEvJo&m=sK21p5ECstjUgot6X6UHd4SedkxwU9Q4NMwW7Ea1i5k&s=jRXaxkqWYBtggvqBouYb-SULqi13_xsbYRzSLHmLw9E&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AICV2GJOCYLHMVBGJVJJVPLR5AV4NANCNFSM4PFV4N6A&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=WmIDKGSxcW04bMi1bMwbmXEpVvNnH6HxyizcKbHEvJo&m=sK21p5ECstjUgot6X6UHd4SedkxwU9Q4NMwW7Ea1i5k&s=WIlFLCBMwTVLlFTDf2aFRSAvBOk_OAE_BvMRXok-b-U&e=>
> .
>


-- 
Robert Watterson
University Computing Systems
210 Flagg Rd. URI
Kingston, RI 02881
rwatterson@uri.edu
phone: 401.874.2164
webex:  https://rhody.webex.com/meet/rwatterson

**Comment by cschicchi** [comment]
We're also seeing this issue. 

ERROR: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest returned "Request contains an invalid argument.">

**Comment by vinay-singh-in** [comment]
We are also facing the same issue.

ERROR: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest returned "Request contains an invalid argument.">

Updating gam doesn't solve the issue.

**Comment by jay0lee** [comment]
Ack. I'm assuming something changed on the Google side and I've reached out to them to understand. Hope to have an update soon.

**Comment by jay0lee** [comment]
Please submit a Google support ticket for this and ask it to be linked to Google internal issue 161970813.

**Comment by cg2v** [comment]
I followed a hunch, and it seems that not sending authentication with the discovery request allows it to succeed (my test was to not use the http parameter as discovery_http in discovery.build(), and instead always call build_http for that )

**Comment by rjwill** [comment]
same issue here

**Comment by ScienIT** [comment]
Same issue on Windows and Google Cloud Shell.

**Comment by pbyerly** [comment]
We are experiencing the same issue and have opened a support ticket and requested it to be linked to Google internal issue 161970813

**Comment by paulchauvet** [comment]
Yep - same issue here.  As requested, I've opened a support request with Google and asked it to be linked to 161970813.  Thanks for your efforts on this Jay!

P.S.  I'm currently only using the gam tool for a few things that I couldn't get working on my own.  I'm getting the same issue when trying to connect directly in Python: _**service = build(serviceName='admin', version='directory_v1', http=http_auth)**_

**Comment by cbf305** [comment]
Ditto.  Opened ticket and asked it to be linked as directed.

**Comment by jay0lee** [comment]
Quick update. Google is aware of the issue and is rolling out a fix though it may take a few hours to take effect. Please do continue with filing a case and ask that it be linked to internal issue 161970813 if you've not already.
Thanks all.

**Comment by jay0lee** [comment]
Quick update. Google is aware of the issue and is rolling out a fix though
it may take a few hours to take effect. Please do continue with filing a
case and ask that it be linked to internal issue 161970813 if you've not
already.

Thanks all.

Jay Lee

**Comment by npas** [comment]
Ticket opened by us as well.

**Comment by rjwill** [comment]
working now for me

**Comment by HJZWEERS** [comment]
> working now for me

Yes! for me too!

**Comment by cschicchi** [comment]
GAM is working for me now...

**Comment by pbyerly** [comment]
Working for me also!

**Comment by vinay-singh-in** [comment]
It's working now!

**Comment by jonlimmer** [comment]
GAM working for all on my team!

**Comment by rwatterson** [comment]
FYI, just started working again for me,  also had issues getting
kicked out of gmail, also resolved now.
Didn't see any service issues on the google status page, but clearly
they had some issues this morning.

**Comment by cbf305** [comment]
Working for me now too!
