### ISSUE TITLE
Request for uploading as multiple users

### ISSUE THREAD

**Issue by oddrabbit** [jay0lee/GAM#1222]
Hi there,

I have multiple files that I need to bulk upload to Google Drive for archiving.

I am just wondering if it is possible to upload files to Google Drive as another user other than administrator. I would like to bypass the 750GB limit that Google caps on each individual email by uploading with multiple email addresses. This is my code so far which does not account for the 750GB limit:

`#!/bin/bash
  
while read line
do
        gam user archive@example.com upload $line
done < $1`

Is this possible with GAM right now or can this be added later?

Thank you.

**Comment by taers232c** [comment]
Files are not uploaded as the administrator unless you request them to be.
gam <UserTypeEntity> create|add drivefile [drivefilename <DriveFileName>] <DriveFileAddAttributes>* 
Files are uploaded as the user referenced in <UserTypeEntity>, choose whatever user you'd like.

Ross

--
ross.scroggs@gmail.com
