### ISSUE TITLE
gam reports users does not return the `accounts:is_delegated_admin` parameter

### ISSUE THREAD

**Issue by muzbaw** [jay0lee/GAM#1224]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam reports users 
2. accounts:is_delegated_admin parameters are missing

Expected outcome (what are you trying to do?):
I would like to be able to use this parameter to easily verify which users have been delegated access to other mailboxes

Actual outcome (what errors or bad behavior do you see instead?):
I am unable to easily see a filtered list of users that have been delegated access to other mailboxes

**Comment by taers232c** [comment]
accounts:is_delegated_admin has nothing to do with Gmail delegation; it is about users that have been made domain admins with specific privileges.

You want: https://github.com/jay0lee/GAM/wiki/ExamplesEmailSettings#print-delegates

Ross

**Comment by muzbaw** [comment]
@taers232c thank you for clarifying.
