### ISSUE TITLE
unauthorized_client error

### ISSUE THREAD

**Issue by k9mjl** [jay0lee/GAM#1234]
ERROR: 

unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.

When updating email signatures from gam via csv

gam csv C:\GAM\CSVs\name.csv gam user ~Email signature file C:\GAM\name.txt

**Comment by jay0lee** [comment]
This is an expected error message, not a big. Please ask for help on the discussion group.
