### ISSUE TITLE
MacOS parse error and not a git repository

### ISSUE THREAD

**Issue by budda** [jay0lee/GAM#1240]
I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.

Full steps to reproduce the issue:
1. Install fresh GAM on MacOS
2. Restart Terminal

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behaviour do you see instead?):
Terminal opens and reports:
```/Users/mikec/.zshrc:102: defining function based on alias `gam'
/Users/mikec/.zshrc:102: parse error near `()'```

Running /bin/gam/gam command results in:
```fatal: not a git repository (or any of the parent directories): .git```

**Comment by Next-Door-Tech** [comment]
Are you using Oh-My-ZSH with the git plugin enabled in your .zshrc? If so, the plugin adds an alias for `gam='git am'`. The fix is as simple as adding the line `unalias gam` just before the actual gam command definition to your .zshrc

**Comment by budda** [comment]
Spot on with the Oh-My-ZSH!

The unalias did indeed fix the issue.
