### ISSUE TITLE
Print cros

### ISSUE THREAD

**Issue by dav1303** [jay0lee/GAM#125]
Hi 

When launching this command I've got an issue 
gam print cros
Retrieving All Chrome OS Devices for organization (may take some time for large
accounts)...
Error 403: Not Authorized to access this resource/api - forbidden

Regards

**Comment by jay0lee** [comment]
The issue tracker is for full bug reports. Please post your problem to the general discussion forum:

https://groups.google.com/forum/#!forum/google-apps-manager

Jay
