### ISSUE TITLE
multiple signature

### ISSUE THREAD

**Issue by lmmworksete** [jay0lee/GAM#1250]
Someone can tell me if there are controls for multiple signatures, even to control the use of signature and forwarding, thank a lot

**Comment by jay0lee** [comment]
Issues are for discussing bugs or feature requests. Please post "how do I?" questions to the group discussion:

groups.google.com/g/google-apps-manager

to answer your question, no, Google has not extended the Gmail signature API calls to support multiple signatures so there is no way to do this with GAM.
