### ISSUE TITLE
gam update org fails with - NameError: name 'getUsersToModify' is not defined

### ISSUE THREAD

**Issue by seedeewhy** [jay0lee/GAM#1256]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam update org xxx/yyy add user john
2.
3.

Expected outcome (what are you trying to do?):
User moved to specific OU.

Actual outcome (what errors or bad behavior do you see instead?):

Traceback (most recent call last):
  File "gam\__main__.py", line 50, in <module>
  File "gam\__main__.py", line 45, in main
  File "gam\__init__.py", line 11254, in ProcessGAMCommand
  File "gam\gapi\directory\orgunits.py", line 232, in update
NameError: name 'getUsersToModify' is not defined
[27208] Failed to execute script __main__

**Comment by taers232c** [comment]
You can work around this as follows:
gam update user john org xxx/yyy

Ross
