### ISSUE TITLE
GAM Create User with attributes

### ISSUE THREAD

**Issue by seppl1992** [jay0lee/GAM#126]
Hello there.
my company is using GAM to create Gmail accounts and i encounter the following problem in the console.

D:\GAM 3.5>gam create user testuser
Creating account for testuser@1worldsync.com

D:\GAM 3.5>firstname "Test"
'firstname' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>lastname "User"
'lastname' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>organization name 1WorldSync GmbH costcenter 9123
'organization' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>phonetype work value +42 221 32473 0 primary
'phonetype' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>address type work Streetaddress Maarweg 165 postalcode 50825 locality
 User countrycode Germany
'address' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>gal off
'gal' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>password '1234gdgdb'
'password' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>changepassword off
'changepassword' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>phonetype mobile value +49 231 93653 157 not primary
'phonetype' is not recognized as an internal or external command,
operable program or batch file.

D:\GAM 3.5>gam update group abcc@1worldsync.com add user user testuse
r@1worldsync.com
 adding member user@1worldsync.com...added user@1worldsync.com to group

D:\GAM 3.5>

the first & last command line works, everything else has a error inside because the programm doesnt understand the commands. any idea why this doesnt work? i followed the guideline on the main project

thanks for feedback in advance

Sebastian

**Comment by jay0lee** [comment]
Please post this to the GAM discussion group:

http://groups.google.com/group/google-apps-manager

**Comment by seppl1992** [comment]
how can i post there with a normal gmail account, cant find the option ;<
