### ISSUE TITLE
"Error 403: cannotAddParent" when uploading files to drive

### ISSUE THREAD

**Issue by kevinjjones** [jay0lee/GAM#1270]
Within approximately the past two weeks, our script which automatically uploads files from one of our servers (Ubuntu 16.04 running the GAM 5.23) to a folder in our users' Google Drive has begun to throw "ERROR: 403: Increasing the number of parents is not allowed - cannotAddParent" for certain users. This occurs for specifically for users which have a folder with a duplicate name in their Google Drive to the one that's being uploaded to, regardless of the directory of the folder with the duplicate name, or if the folder is in the trash.

This issue was not present until recently despite users having folders with duplicate names prior to the issue. Permanently deleting or renaming the folders with duplicate names resolves the issue, though this is not a true solution.

**Full steps to reproduce the issue:**
1. Create two folders with the same name in a user's Google Drive.
2. Run `gam user <user> add drivefile localfile <file> parentname <folder>`

**Expected outcome (what are you trying to do?):**
Upload a file into a specified folder in a user's Google Drive

**Actual outcome (what errors or bad behavior do you see instead?):**
The file is not uploaded and the error "ERROR: 403: Increasing the number of parents is not allowed - cannotAddParent" is thrown.

**Comment by taers232c** [comment]
Kevin,

You're going to have to change your procedures.
See: https://developers.google.com/drive/api/v3/ref-single-parent

Ross

**Comment by kevinjjones** [comment]
Understood. Thank you.
