### ISSUE TITLE
Installing GAM into an existing GCP project

### ISSUE THREAD

**Issue by dmcerik4512** [jay0lee/GAM#1278]
I was wondering if there would be any issues installing GAM into an existing GCP project. This GCP project is already in use by other engineers doing other, non GAM, things.

**Comment by pablorf-dev** [comment]
Just for reference, you can use [`gam use project <project id>`](https://github.com/GAM-team/GAM/blob/4ffe709ab95b9b4a138e9c0423b62ebc8153bd07/src/gam/__init__.py#L11383)
