### ISSUE TITLE
Error loading Python DLL 

### ISSUE THREAD

**Issue by GerasDraugas** [jay0lee/GAM#1279]
5.22 works fine.
5.23 and 5.24 gets error:

Error loading Python DLL 'c:\..\..\python39.dll'.
LoadLibrary: The specified module could not be found.

OS: win.

**Comment by Jarepa** [comment]
I have same problem on windows 7 
I found this:

https://bugs.python.org/issue40740

Windows 7 is no longer supported in Python 3.9

**Comment by jay0lee** [comment]
Yes, this is working as intended as GAM will use the latest Python release where possible.

Strong recommendation is to only use GAM on an OS that is still receiving security updates from it's vendor (Microsoft).
