### ISSUE TITLE
Gmail Signatures

### ISSUE THREAD

**Issue by fonty94** [jay0lee/GAM#1280]
Hello,

More of a question than an issue. Now that Gmail allow for multiple signatures, is it possible to create more than one signature using EmailSettings?
Right now when I create a new signature GAM generate one named "My signature" and when I do it again, GAM simply overwrite it. Is there a way to create a new one keeping the previous signature?

Thanks in advance

**Comment by regexaurus** [comment]
Pretty please? 🎁 🎄 🎅 🤶
:D

**Comment by taers232c** [comment]
You're pleading to the wrong people. GAM (Jay's and mine) use Google supplied APIs, if the API doesn't support a feature, there's nothing GAM can do.
Talk to Google, ask them to add multiple signature support to the Gmail API.

Ross
--
ross.scroggs@gmail.com

**Comment by regexaurus** [comment]
Got it. Thank you, Ross!
