### ISSUE TITLE
Trying To Update

### ISSUE THREAD

**Issue by derekritchison** [jay0lee/GAM#1282]
I am trying to update to 5.24 for Windows 64 but am running into a host of issues. The MSI hangs and will not complete. The EXE runs but "gam version" still gives me my current version. Is there a way to update via PowerShell?

**Comment by taers232c** [comment]
Derek,

When you run the GAM Windows installer, Windows seems to pop-up a dialog box where you have to approve the installation;
unfortunately, it doesn't pop up in the foreground. Look for a bouncing icon on the bat at the bottom of the screen.

Ross
--
ross.scroggs@gmail.com

**Comment by derekritchison** [comment]
Dang. I do not see that when I run the MSI, and when I run the EXE I see a Command Prompt window appear and disappear too suddenly to catch what it says.

**Comment by jay0lee** [comment]
closing this issue. If you need help, please reach out on the discussion forum.
