### ISSUE TITLE
Error when synching group with file

### ISSUE THREAD

**Issue by 4frjang** [jay0lee/GAM#1301]
**I confirm the following:**
* I have upgraded to the latest GAM release (=5.30) from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

**Problem Description**

When synching G Suite groups with a file
  `gam update group "${gruppe}" sync member file "${datei}"`

the command always runs and does most of its job, but more often than not shows this error:
>  ERROR: 404: Resource Not Found: email - resourceNotFound

- Each occurrence of this error relates to an E-Mail address which will not be correctly synched (=removed) from the group
- Errors appear for most, but not all of the groups I am trying to sync
- For a given group, however, the problem is always reproducible

**Full steps to reproduce the issue:**
1. Create a file which contains all but some E-Mail addresses of an already existing group. 
In my case these extra addresses are from outside of my domain

2. Synch G Suite group with your file
`gam update group <group> sync member file  <file>`

**Expected outcome (what are you trying to do?):**
- No error messages
- All extra E-mail addresses should be removed from the group

**Actual outcome (what errors or bad behavior do you see instead?):**
- ERROR: 404: Resource Not Found: email - resourceNotFound
- One or sometimes more E-Mail addresses remain in the group, although they are not contained in the file.

**Comment by taers232c** [comment]
I have see this before, it is a Google issue, not a GAM bug.

Start with an empty group.
$ gam print group-members group testgroup
Getting members for testgroup@domain.com (1/1)
group

Add a user with a proxy domain.
$ gam update group testgroup add member user@proxydomain.com
 Group: testgroup@domain.com, user@proxydomain.com Added as MEMBER

Add succeeds.
$ gam print group-members group testgroup
Getting members for testgroup@domain.com (1/1)
group,id,email,role,type
testgroup@domain.com,123706166545652211789,user@proxydomain.com,MEMBER,USER

Delete the user using the email address, it fails.
$ gam update group testgroup delete member user@proxydomain.com

ERROR: 404: Resource Not Found: email - resourceNotFound

Delete the user using the UID, it succeeds.
$ gam update group testgroup delete member uid:123706166545652211789
 Group: testgroup@domain.com, 123706166545652211789 Removed

$ gam print group-members group testgroup
Getting members for testgroup@domain.com (1/1)
group

Ross

**Comment by jay0lee** [comment]
closing this since, as Ross mentioned it's not a GAM issue. Please do feel free to discuss further as necessary in the GAM discussion group though.

**Comment by leato2010** [comment]
reopening this issue to see if there is also a similar problem with the api for gam print groups member.

in many cases when i run this command with an email address it returns 0 groups, but if i run the same command gam print groups member uid:<uid of member> it returns the full membership list.
