### ISSUE TITLE
Updating GAM Error: ERROR: Attribute: browser_download_url for macos-x86_64.tar.xz version latest not found

### ISSUE THREAD

**Issue by bahhhhh** [jay0lee/GAM#1302]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue - No
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki - Yes

Full steps to reproduce the issue:
1. With v5.30 installed, enter `bash <(curl -s -S -L https://git.io/install-gam) -l`

Expected outcome (what are you trying to do?):
- Update GAM to the latest version

Actual outcome (what errors or bad behavior do you see instead?):
```
$ bash <(curl -s -S -L https://git.io/install-gam) -l
You are running MacOS 11.1
Using GAM compiled on MacOS10.15.6

Checking GitHub URL https://api.github.com/repos/jay0lee/GAM/releases for latest GAM release...

Getting file and download URL...

ERROR: Attribute: browser_download_url for macos-x86_64.tar.xz version latest not found
```

**Comment by jay0lee** [comment]
Thanks for reporting this. It looks like the MacOS file was named wrong on this release. Can you try again? It should be corrected though it may take an hour or so for the change to be seen by GitHub.

**Comment by bahhhhh** [comment]
@jay0lee I confirm that everything is now working as expected. Thanks for the quick fix!
