### ISSUE TITLE
Remove Gmail signature

### ISSUE THREAD

**Issue by lucafabbri365** [jay0lee/GAM#1306]
Hello,
I was searching for a way to use gam tool for removing end user' signature on Gmail, completey:

- Unassign on new emails
- Unassign on reply/forward
- Delete all signatures

![image](https://user-images.githubusercontent.com/27311961/104010840-6f187d00-51ad-11eb-997b-0cdced86210f.png)

Thank you,
Luca

**Comment by lucafabbri365** [comment]
Hello @jay0lee,
excuse me, what did I miss ?

Thank you,
Luca

**Comment by taers232c** [comment]
Luca,

There is no Google Gmail API support for this, thus GAM can't help.

Ross
