### ISSUE TITLE
GAM 5.31 x86 is now detected by Microsoft AV

### ISSUE THREAD

**Issue by cogxgithub** [jay0lee/GAM#1307]
I have been using GAM 5.21 (x86 Windows) since 9/30/20 (been using GAM for a few years now).  I decided to download 5.31 and one of the first things I do with downloads is to use sigcheck.exe with the VirusTotal option enabled to show me if there are any malware detections.  It showed 0 hits.  I extracted the files and then all of a sudden Microsoft AV decided to quarantine gam.exe in a fit of hysteria.  That made no sense to me, so I went to the VirusTotal page - it showed it had last scanned that .zip 7 days ago and had 0 hits.  I clicked re-analyze and sure enough today though it shows two hits, Microsoft unfortunately being one of them:
https://www.virustotal.com/gui/file/774b89bd0a9e7ea35ecb6225b9eb9996ecc06875e63982dfacf49b549c0b5d95/detection

It first showed "Trojan:Win32/CryptInject!ml" this afternoon, but just now I had VT re-analyze again and now Microsoft has it listed as "PUA:Win32/Presenoker".

The Windows 64-bit .zip file also showed 0 hits from 7 days ago, but just re-analyzing it now and it comes back with Microsoft "Trojan:Win32/Fuerboos.D!cl".  

Crazy.

**Comment by jay0lee** [comment]
These are false positives because antivirus vendors tend to report Python apps compiled to executables as a virus. Report them as a false positive.

**Comment by jay0lee** [comment]
GAM is not a virus. There's nothing GAM can do to prevent lazy Antivirus vendors from reporting it as a virus. The issue lies with the AV vendors so please do report the issue there.
