### ISSUE TITLE
How can we remove all meeting if the meeting owner leaves the company

### ISSUE THREAD

**Issue by patelm63** [jay0lee/GAM#131]
How can we remove all meeting if the meeting owner leaves the company.

**Comment by liamcaproni** [comment]
Hi,

I know this is a bit late but if you wipe the user's calendar data then it will remove all meetings they have set up in the calendar and will remove them from events and will delete events they have created.

Does this answer your question?

**Comment by jay0lee** [comment]
This is an issue tracker for bugs. Please post questions to the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager
