### ISSUE TITLE
ERROR: 500: Internal error encountered. - 500

### ISSUE THREAD

**Issue by jcs808** [jay0lee/GAM#1311]
I'm getting this error when trying to amend new Google Classrooms.  I can edit older classrooms but not any that I've created in the last few days.
Error:
ERROR: 500: Internal error encountered. - 500

Can any one help?
Thank you.

**Comment by jay0lee** [comment]
What command are you using? Can you edit them in Classroom itself?

**Comment by jcs808** [comment]
I'm using this command
GAM.exe course <course id> add teacher <teacher email address>
GAM.exe course <course id> add student <student email address>

I've used this many times before and it works on older Google Classrooms.  I can edit the Google Classroom in the web interface but that only invites people and the command adds them, this is preferable when adding students.

**Comment by phximenes** [comment]
Same problem here.

**Comment by taers232c** [comment]
I get the same result here:
https://developers.google.com/classroom/reference/rest/v1/courses.students/create
So it's not a GAM issue.

**Comment by jcs808** [comment]
I've found this entry on the Google Classroom API issue tracker, but response from Google.
https://issuetracker.google.com/issues/178647877
