### ISSUE TITLE
Image files for setup instructions

### ISSUE THREAD

**Issue by bkgray** [jay0lee/GAM#132]
This issue holds the image files for the revised instructions for creating client_secrets and oauth2service.  No work required.

![gam06](https://cloud.githubusercontent.com/assets/1683475/11096311/07a59c42-885f-11e5-802a-08beea16ffa3.png)
![gam07](https://cloud.githubusercontent.com/assets/1683475/11096309/07a487f8-885f-11e5-99ef-487cdfdeb496.png)
![gam08](https://cloud.githubusercontent.com/assets/1683475/11096310/07a599a4-885f-11e5-9896-23364582e79a.png)
![gam09](https://cloud.githubusercontent.com/assets/1683475/11096313/07a72ae4-885f-11e5-8041-861e48f60af0.png)
![gam10](https://cloud.githubusercontent.com/assets/1683475/11096308/07a3a77a-885f-11e5-80d5-fc1467f4c60b.png)
![gam11](https://cloud.githubusercontent.com/assets/1683475/11096312/07a61654-885f-11e5-9697-cb581fe094fe.png)
![gam12](https://cloud.githubusercontent.com/assets/1683475/11096315/07b0ce00-885f-11e5-86dc-b84d3c2e94c5.png)
![gam13](https://cloud.githubusercontent.com/assets/1683475/11096316/07b12562-885f-11e5-9d9a-d6c7721f1b2d.png)
![gam14](https://cloud.githubusercontent.com/assets/1683475/11096314/07b00e02-885f-11e5-945e-3d9b2dfdc7b5.png)
![gam15](https://cloud.githubusercontent.com/assets/1683475/11096317/07b2dac4-885f-11e5-9283-bd7cc7141aff.png)
![gam17](https://cloud.githubusercontent.com/assets/1683475/11096318/07b2f450-885f-11e5-9597-c71cdcf13ecf.png)
![gam18](https://cloud.githubusercontent.com/assets/1683475/11096319/07b390a4-885f-11e5-859a-b96e8b4376dc.png)
![gam19](https://cloud.githubusercontent.com/assets/1683475/11096321/07bd277c-885f-11e5-9aeb-07df368265e2.png)
![gam20](https://cloud.githubusercontent.com/assets/1683475/11096320/07ba411a-885f-11e5-9b68-2956e3b44475.png)
![gam21](https://cloud.githubusercontent.com/assets/1683475/11096323/07be2bc2-885f-11e5-9822-35a6cd35b8e9.png)
![gam22](https://cloud.githubusercontent.com/assets/1683475/11096324/07c046f0-885f-11e5-9ece-2cc76b4bb59d.png)
![gam23](https://cloud.githubusercontent.com/assets/1683475/11096322/07bd8492-885f-11e5-9365-55a2dead8455.png)
![gam24](https://cloud.githubusercontent.com/assets/1683475/11096325/07c04498-885f-11e5-80af-b9a094520de3.png)
![gam25](https://cloud.githubusercontent.com/assets/1683475/11096326/07c5ce04-885f-11e5-8672-44ef02e8b454.png)
![gam26](https://cloud.githubusercontent.com/assets/1683475/11096329/07c82474-885f-11e5-9741-90121987b508.png)
![gam27](https://cloud.githubusercontent.com/assets/1683475/11096328/07c8fe30-885f-11e5-8db3-62cdd06bd626.png)
![gam01](https://cloud.githubusercontent.com/assets/1683475/11096327/07c89c6a-885f-11e5-8ada-49eb70b14b12.png)
![gam02](https://cloud.githubusercontent.com/assets/1683475/11096331/07cda872-885f-11e5-9061-f7db2e18183b.png)
![gam03](https://cloud.githubusercontent.com/assets/1683475/11096330/07caf00a-885f-11e5-9e1e-149c547c9154.png)
![gam04](https://cloud.githubusercontent.com/assets/1683475/11096332/07cf5492-885f-11e5-9793-3fc0651a0e31.png)
![gam05](https://cloud.githubusercontent.com/assets/1683475/11096333/07d4dcc8-885f-11e5-974e-80e374e98fc2.png)

**Comment by bkgray** [comment]
Additional images for newest version of console.developers.google.com

![gam-36](https://cloud.githubusercontent.com/assets/1683475/11098096/5134ff2a-8868-11e5-9f20-1c36b8720bf1.png)
![gam-37](https://cloud.githubusercontent.com/assets/1683475/11098095/5133dc44-8868-11e5-9025-deb568d793db.png)
![gam-31](https://cloud.githubusercontent.com/assets/1683475/11098097/51366f22-8868-11e5-929a-601fa481fcc4.png)
![gam-32](https://cloud.githubusercontent.com/assets/1683475/11098094/51338910-8868-11e5-97cb-c9d780d9184a.png)
![gam-33](https://cloud.githubusercontent.com/assets/1683475/11098098/5136c472-8868-11e5-9f11-31af28aafb16.png)
![gam-34](https://cloud.githubusercontent.com/assets/1683475/11098099/5138024c-8868-11e5-8749-fe996366a2d9.png)
![gam-35](https://cloud.githubusercontent.com/assets/1683475/11098100/51467d40-8868-11e5-8511-62086b45ac1c.png)

**Comment by bkgray** [comment]
Images for Service account scopes

![gam-41](https://cloud.githubusercontent.com/assets/1683475/11099925/d6e57b9e-8873-11e5-914e-6be3b72e1325.png)
![gam-42](https://cloud.githubusercontent.com/assets/1683475/11099924/d6e525c2-8873-11e5-82fe-eb33f3a6f5d6.png)
![gam-40](https://cloud.githubusercontent.com/assets/1683475/11099926/d6e6c710-8873-11e5-9cd4-5003218684da.png)

**Comment by bkgray** [comment]
![gam-40](https://cloud.githubusercontent.com/assets/1683475/11100314/130210ae-8876-11e5-9659-a902e4d929cf.png)
![gam-41](https://cloud.githubusercontent.com/assets/1683475/11100312/12fcd54e-8876-11e5-8252-6d721f9eb28e.png)
![gam-42](https://cloud.githubusercontent.com/assets/1683475/11100313/12ff4c02-8876-11e5-8a30-124985678a3d.png)

**Comment by bkgray** [comment]
![gam-30](https://cloud.githubusercontent.com/assets/1683475/11548007/02d69214-991e-11e5-8595-3ea6083776ab.png)

**Comment by bkgray** [comment]
Images for Dev Console update
![gam-56](https://cloud.githubusercontent.com/assets/1683475/11798254/d2ab70e4-a28e-11e5-8467-b88b2939eccf.png)
![gam-57](https://cloud.githubusercontent.com/assets/1683475/11798258/d2afd224-a28e-11e5-9d0e-64466ef3348f.png)
![gam-58](https://cloud.githubusercontent.com/assets/1683475/11798255/d2ae9468-a28e-11e5-8f6f-b7b492cbc19b.png)
![gam-59](https://cloud.githubusercontent.com/assets/1683475/11798256/d2af149c-a28e-11e5-837f-bc36e1e72442.png)
![gam-60](https://cloud.githubusercontent.com/assets/1683475/11798259/d2b077ce-a28e-11e5-992c-4d3e044ac610.png)
![gam-50](https://cloud.githubusercontent.com/assets/1683475/11798257/d2af222a-a28e-11e5-90dd-67e3dbbe3123.png)
![gam-51](https://cloud.githubusercontent.com/assets/1683475/11798260/d2b8b9b6-a28e-11e5-8228-9812fe53ac95.png)
![gam-52](https://cloud.githubusercontent.com/assets/1683475/11798262/d2bd882e-a28e-11e5-9c4d-6e258263c2c9.png)
![gam-53](https://cloud.githubusercontent.com/assets/1683475/11798264/d2c1e23e-a28e-11e5-9a98-54cd78ed420d.png)
![gam-54](https://cloud.githubusercontent.com/assets/1683475/11798261/d2bd37ca-a28e-11e5-95b6-4704771c3558.png)
![gam-55](https://cloud.githubusercontent.com/assets/1683475/11798263/d2bde0b2-a28e-11e5-82e8-de330e7f7f27.png)

**Comment by jay0lee** [comment]
closing issue as I don't think that will affect images (if it does, I can re-open).

Thanks for the Wiki updates!

Jay

**Comment by bkgray** [comment]
![gam-61](https://cloud.githubusercontent.com/assets/1683475/11919919/2953b4de-a725-11e5-9c00-dd8cc49d2d4c.png)

**Comment by jay0lee** [comment]
It is not necessary to authorize all of those scopes in the admin console. Only the scopes:

API scopes - Service Account:

https://mail.google.com/,
https://www.googleapis.com/auth/activity,
https://www.googleapis.com/auth/calendar,
https://www.googleapis.com/auth/drive

need to be authorized.

Are you able to update this bkgray?

Jay

**Comment by bkgray** [comment]
On Tue, Dec 22, 2015 at 3:58 PM, Jay Lee <notifications@github.com> wrote:

> It is not necessary to authorize all of those scopes in the admin console.
> Only the scopes:
>
> API scopes - Service Account:
>
> https://mail.google.com/,
> https://www.googleapis.com/auth/activity,
> https://www.googleapis.com/auth/calendar,
> https://www.googleapis.com/auth/drive
>
> need to be authorized.
>
> Are you able to update this bkgray?
>

I'm on the road for a few days, so I'm limited in what I can do right now.
I can edit the wiki but can't test anything or generate new screenshots.
First chance I will have to do anything other than trivial wiki edits will
be 12/31 or 1/1.

Do you mean that the 4 API scopes for the service accounts are required and
*no* API scopes are required for the OAuth2 ID?  I was working from a list
provided by Ross Scroggs.



Brian Gray
Austin, Texas
google.com/+BrianGray

**Comment by jay0lee** [comment]
+ @taers232c 

The 4 scopes above are all that need to be authorized for the service account client_id in the admin console. Other API scopes need their respective API turned on in the API console and are part of the installed application authorization request, they should not be included with the service account.

Jay

**Comment by taers232c** [comment]
It looks right to me: 6.ii authorizes client access and 6.iii authorizes service account access. Each section references the appropriate scope list at the bottom of the screen.

**Comment by jay0lee** [comment]
The issue is this image:

https://cloud.githubusercontent.com/assets/1683475/11919919/2953b4de-a725-11e5-9c00-dd8cc49d2d4c.png

which shows more scopes than necessary as authorized. Would also be good to get some [markdown formatting](https://guides.github.com/features/mastering-markdown/) on the page to give it a nicer look but that's a less pressing issue.

Thanks again for updating all this. The API console changes have been a major source of confusion for users.

**Comment by taers232c** [comment]
That's the image at the end of 6.ii, authorize the client, which is correct. The next step, 6.iii, does the authorization for the service account referencing the four scope list. When Brian gets back on the grid, he could put the similar image after step 6.iii.e.

**Comment by jay0lee** [comment]
quick note that we can use the URL:

https://console.developers.google.com/flows/enableapi?apiid=admin,appsactivity,calendar,classroom,drive,gmail,groupssettings,licensing

to simplify project creation.

**Comment by bkgray** [comment]
On Thursday, December 24, 2015, Jay Lee <notifications@github.com> wrote:

> quick note that we can use the URL:
>
>
> https://console.developers.google.com/flows/enableapi?apiid=admin,appsactivity,calendar,classroom,drive,gmail,groupssettings,licensing
>
> to simplify project creation.
>

I've never seen that before.  I'll test it and update the instructions when
I get back to my computer next week.


-- 

Brian Gray
Austin, Texas
google.com/+BrianGray

**Comment by taers232c** [comment]
You must have friends in high places.
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Nope, just found:

https://developers.google.com/drive/v2/web/quickstart/python

And mention of a"wizard".  Playing around to see if others parameters can
be passed like project name and consent screen.

Jay

On Thu, Dec 24, 2015, 11:15 AM Ross Scroggs <notifications@github.com>
wrote:

> You must have friends in high places.
> --
> ross.scroggs@gmail.com
>
>
>
> On Dec 24, 2015, at 4:30 AM, Jay Lee <notifications@github.com> wrote:
>
> > quick note that we can use the URL:
> >
> >
> https://console.developers.google.com/flows/enableapi?apiid=admin,appsactivity,calendar,classroom,drive,gmail,groupssettings,licensing
> >
> > to simplify project creation.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/132#issuecomment-167132070>.
>
-- 

Jay Lee

**Comment by bkgray** [comment]
I am (finally) able to do some work on this...I have a couple of questions:

1) URL to enable APIs: in my testing of the link that Jay provided above, I am getting inconsistent results.  Some of the APIs are not enabled, even though all of the pages say that all 8 will be enabled (or have been enabled).  

It does not appear to be consistent - one time the Classroom API was not enabled.  Another time, the Activity and Group Settings APIs were not enabled.  If I use the same URL a second time on the same project, the missing APIs are usually enabled.  In one trial, I had to do it 3 times to get them all enabled.  

I've tried a couple of different sequences for the API names in the URL.  The sequence did not change anything - some of the APIs were not enabled.  I've also tried splitting the URL into two parts - 4 APIs each.  I still did not get all of the APIs enabled on the first try.

In each case, the web page said (erroneously) that all of the APIs were enabled.  

**Do you think that we should document the use this URL (with the need to repeat the process to get all of the APIs enabled), or should we leave the documentation as it is (a manual process) for now?**

2) Comments from Jay and Ross seem to be in conflict about what (if any) APIs need to be authorized for the OAuth client ID and the service account client ID.  

Currently, in step 6.ii.l, the image shows 16 APIs authorized for the OAuth2 client ID.  Section 6.iii (missing an image) adds authorization for 4 APIs to the service account ID.

**Jay - do you think that the problem with the documentation is that the OAuth2 ID does not require any API authorization (and so section 6.ii should be removed), or that section 6.iii is confusing because it is missing an image for what the service account ID's authorization should look like in the Admin Console (and so 6.ii should remain as it is and section 6.iii should get an image)?**

I tested this today - I added the authorization of 4 APIs for the service account ID only - nothing for the OAuth2 ID.  The program worked as expected for the commands that I tested (including the resource calendar and admin commands added in 3.62).  I think that section 6.ii can be removed, but I did not do comprehensive testing to verify that authorizing APIs for the service account only is sufficient.

Ross & Jay - please advise.  I can make whichever changes are needed this weekend, but I'm really not sure which way to go with it.

Brian

**Comment by bkgray** [comment]
![gam-62](https://cloud.githubusercontent.com/assets/1683475/12075487/fda9ef9c-b147-11e5-8d7c-a2a417078f64.png)

**Comment by bkgray** [comment]
Yet another round of documentation updates due to changes in the developer's console.

![gam-83](https://cloud.githubusercontent.com/assets/1683475/14229293/1c131454-f8f6-11e5-917f-2fa47ad47ffd.png)
![gam-84](https://cloud.githubusercontent.com/assets/1683475/14229294/1c1ebc3c-f8f6-11e5-9aab-8d9e6a9095c2.png)
![gam-85](https://cloud.githubusercontent.com/assets/1683475/14229295/1c2b2396-f8f6-11e5-83d1-bd66b5ef703c.png)
![gam-89](https://cloud.githubusercontent.com/assets/1683475/14229296/1c36a98c-f8f6-11e5-8380-7db03a84c370.png)
![gam-90](https://cloud.githubusercontent.com/assets/1683475/14229297/1c4364ba-f8f6-11e5-82c5-dc9f84855b65.png)
![gam-91](https://cloud.githubusercontent.com/assets/1683475/14229298/1c4faf9a-f8f6-11e5-8340-79159289bce2.png)
![gam-92](https://cloud.githubusercontent.com/assets/1683475/14229299/1c5cbdde-f8f6-11e5-862d-afbd2f3f132f.png)
![gam-70](https://cloud.githubusercontent.com/assets/1683475/14229300/1c69ca88-f8f6-11e5-8e95-eefca3665b76.png)
![gam-71](https://cloud.githubusercontent.com/assets/1683475/14229301/1c77db96-f8f6-11e5-9dc3-a710576b1e0a.png)
![gam-78](https://cloud.githubusercontent.com/assets/1683475/14229302/1c89eb56-f8f6-11e5-82ba-fae6633212cd.png)
![gam-81](https://cloud.githubusercontent.com/assets/1683475/14229303/1c9bef68-f8f6-11e5-8c58-9ec5f40aed00.png)
![gam-82](https://cloud.githubusercontent.com/assets/1683475/14229304/1ca8cab2-f8f6-11e5-8388-83aeaaa7d791.png)

**Comment by bkgray** [comment]
![gam-75](https://cloud.githubusercontent.com/assets/1683475/14229405/c5013c2e-f8f8-11e5-84f5-3351968ec5e3.png)
![gam-74](https://cloud.githubusercontent.com/assets/1683475/14229406/c501aa6a-f8f8-11e5-84ae-0f6aabfe056c.png)

**Comment by bkgray** [comment]
![gam-95](https://cloud.githubusercontent.com/assets/1683475/14229585/7fd2e9e6-f8fc-11e5-80c1-c117b2f2eb15.png)

**Comment by bkgray** [comment]
![gam-82a](https://cloud.githubusercontent.com/assets/1683475/14229633/ad94f22e-f8fd-11e5-9e9e-2c2724baa41a.png)

**Comment by bkgray** [comment]
![gam-102](https://cloud.githubusercontent.com/assets/1683475/14234013/b7bc5904-f99d-11e5-9280-75544962df46.png)
![gam-103](https://cloud.githubusercontent.com/assets/1683475/14234014/b7c827d4-f99d-11e5-9fd9-75f9f08566a0.png)
![gam-104](https://cloud.githubusercontent.com/assets/1683475/14234015/b7cef2a8-f99d-11e5-8020-f56ca86ffa80.png)
![gam-105](https://cloud.githubusercontent.com/assets/1683475/14234017/b7cf53f6-f99d-11e5-8aff-3dcde1ae89eb.png)
![gam-106](https://cloud.githubusercontent.com/assets/1683475/14234016/b7cf3808-f99d-11e5-82d2-ad30b23bd967.png)
![gam-107](https://cloud.githubusercontent.com/assets/1683475/14234018/b7cf7700-f99d-11e5-8488-b357eaef8b00.png)
![gam-101](https://cloud.githubusercontent.com/assets/1683475/14234019/b7cfce9e-f99d-11e5-8ee0-9022f71c0301.png)
