### ISSUE TITLE
zsh No such file or named directory - csv issue

### ISSUE THREAD

**Issue by idzczakp** [jay0lee/GAM#1320]
Hello. I have a problem on MacOS, single-user commands are working fine, but the problem starts if I want to do it with a .csv file

Command:
`gam csv email.csv gam update group mailinggroup@domain.com add member user ~Email `

And the output:
`zsh: no such user or named directory: Email`

**Comment by taers232c** [comment]
Put ~Email ib quotes
> gam csv email.csv gam update group mailinggroup@domain.com add member user "~Email"
> 
> 
Ross
--
ross.scroggs@gmail.com

**Comment by idzczakp** [comment]
Works fine, but maybe you know why it requires quotes on MacOS but works fine without on Linux?

**Comment by daethnir** [comment]
Tilde means "expand this username to their home directory".

What is tilde in gam context? The two would be at odds without quoting.

**Comment by TravellingGuy** [comment]
> Works fine, but maybe you know why it requires quotes on MacOS but works fine without on Linux?

This is an issue with zsh, not MacOS specifically. zsh is the default shell on MacOS, bash is usually the default on Linux. Using zsh on Linux produces the same error. Enclosing it in quotes works.
