### ISSUE TITLE
issuecommand is not a valid argument for gam

### ISSUE THREAD

**Issue by dmd408** [jay0lee/GAM#1322]
Full steps to reproduce the issue:

1. gam issuecommand cros my-device-id-here command wipe_users doit
2. I've also run the command as:  gam cros my-device-id-here issuescommand command wipe_users doit

Expected outcome (what are you trying to do?):
Wipe user profiles from a Chromebook

Actual outcome (what errors or bad behavior do you see instead?):
"ERROR: issuecommand is not a valid argument for "gam""

I'm able to execute the command against the same device from Google's API explorer fine.  Other gam commands seem to work fine.

**Comment by jay0lee** [comment]
The most likely explanation is that you haven't upgraded to the latest version.

**Comment by dmd408** [comment]
I downloaded 5.33 and ran it, select U rather than N... any reason to think it wouldn't have updated (I believe those were the two options anyhow).  Used the windows 86 msi.  I will try uninstalling and re-installing.

**Comment by dmd408** [comment]
So you are right that it is not updated.  But I have run the update and it says update complete.  Very odd.  When I run gam version, I get 5.11.  But I have ran the 5.33 msi and tried downloading the zip and running the set from there with the same results.

**Comment by dmd408** [comment]
okay, just replaced the exe directly myself and it all worked.  Not sure why the update wasn't working, but fixed now.  Thanks.
