### ISSUE TITLE
gam info user

### ISSUE THREAD

**Issue by lvolkart** [jay0lee/GAM#1328]
I am trying to insert the item number 25 (25) User Profile (Email address - read only) [required]) does not command "gam info user", but is giving the following error (ERROR: Scope "User Profile (Email address - read only) "is required and cannot be unselected!) and returns to the prompt. What could be wrong?

**Comment by jay0lee** [comment]
Nothing is wrong, that scope is required and always set, the error is telling you you can't unset it.
