### ISSUE TITLE
Feature Request: include users.Signout API parameter to log out user 

### ISSUE THREAD

**Issue by joely0** [jay0lee/GAM#1348]
**Is your feature request related to a problem? Please describe.**
As an Admin I want to sign out all users in my domain because of a recent cyber attack. 

**Describe the solution you'd like**
An easy option to sign out all users or a subset of users ie; gam all users update user signOut

Users would be signed out of all web and device sessions and also have their their sign-in cookies reset. Users will have to sign in by authenticating again.

**Describe alternatives you've considered**
There are some workarounds, such as forcing them to change their password on next sign on, which has a similar effect (logging them out of the account) but isn't very elegant. See https://webapps.stackexchange.com/questions/76109/is-it-possible-to-reset-sign-in-cookies-for-all-gmail-users-in-google-admin

**Additional context**
This is now available via the Directory API: https://developers.google.com/admin-sdk/directory/reference/rest/v1/users/signOut

**Comment by taers232c** [comment]
This command is already implemented.
See: https://github.com/jay0lee/GAM/wiki/SecurityExamples#signing-a-user-out

**Comment by joely0** [comment]
Oh. I need to read the documentation a bit better. 

Thanks taers232c.
