### ISSUE TITLE
Having trouble creating sub ou or orgs

### ISSUE THREAD

**Issue by moondogluke007** [jay0lee/GAM#135]
running the command 
gam.exe create org "secondary-org/root-org"
and 
gam.exe create org "root-org/secondary-org"
and I get the error message "Error 400: Invalid OU Name - invalid"
What is the correct syntax to create a sub organization?

**Comment by nferrell** [comment]
https://github.com/jay0lee/GAM/wiki/ExamplesOrganizations


gam create org <name> [description <Description>] [parent <Parent
Org>] [noinherit]

**Comment by jay0lee** [comment]
This area is for issues / bugs. Please post howto questions to the discussion group. Thanks!

https://groups.google.com/forum/#!forum/google-apps-manager
