### ISSUE TITLE
Support Transferring "Data Studio" In Addition To C

### ISSUE THREAD

**Issue by derekritchison** [jay0lee/GAM#1353]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by derekritchison** [comment]
I do not see this in the documentation but I think it may be an important feature request.

**Comment by jay0lee** [comment]
GAM automatically supports any transfer app added by Google. See
````
gam print transferapps
```
and
```
gamd create datatransfer olduser@example.com "Google Data Studio" newowner@example.com PRIVACY_LEVEL SHARED,PRIVATE
