### ISSUE TITLE
Authorization Error Error 400: invalid_scope

### ISSUE THREAD

**Issue by Bajrangverma** [jay0lee/GAM#1358]
Hi Team,

We getting below error while configuring the GAM 6.0.

Please check or suggest.

Authorization Error
Error 400: invalid_scope
Some requested scopes cannot be shown: [https://www.googleapis.com/auth/chrome.management.policy, https://www.googleapis.com/auth/admin.contact.delegation, https://www.googleapis.com/auth/admin.chrome.printers, https://www.googleapis.com/auth/admin.directory.device.chromebrowsers, https://www.googleapis.com/auth/cloud-identity.userinvitations, https://www.googleapis.com/auth/cloud-identity.groups, https://www.googleapis.com/auth/classroom.guardianlinks.students, https://www.googleapis.com/auth/classroom.profile.emails, https://www.googleapis.com/auth/classroom.profile.photos, https://www.googleapis.com/auth/classroom.rosters, https://www.googleapis.com/auth/classroom.courses, https://www.googleapis.com/auth/ediscovery, https://www.googleapis.com/auth/siteverification, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/admin.datatransfer, https://www.googleapis.com/auth/admin.directory.customer, https://www.googleapis.com/auth/admin.directory.resource.calendar, https://www.googleapis.com/auth/admin.reports.audit.readonly, https://www.googleapis.com/auth/admin.reports.usage.readonly, https://www.googleapis.com/auth/admin.directory.userschema, https://www.googleapis.com/auth/admin.directory.domain, https://www.googleapis.com/auth/admin.directory.device.mobile, https://www.googleapis.com/auth/admin.directory.device.chromeos, https://www.googleapis.com/auth/admin.directory.orgunit, https://www.googleapis.com/auth/apps.licensing, https://www.googleapis.com/auth/admin.directory.group, https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.rolemanagement, https://www.googleapis.com/auth/admin.directory.user.security, https://www.googleapis.com/auth/apps.groups.settings]
Request Details
access_type=offline
login_hint=mailadmin@gogoletest.ga
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
state=RLK1wijo892UMF3QaSiZ6fStrFWJos
code_challenge_method=S256
hd=gogoletest.ga
prompt=consent
client_id=581253928847-a0n0bg7h2hrl0er0528fjvm80skbahu8
code_challenge=ssXNXEAOSaLzoqWfyBRHbbZ6W0azqiX5v_JQU5TMpNk
scope=https://www.googleapis.com/auth/classroom.courses https://www.googleapis.com/auth/classroom.rosters https://www.googleapis.com/auth/admin.directory.customer https://www.googleapis.com/auth/admin.directory.resource.calendar https://www.googleapis.com/auth/devstorage.read_only https://www.googleapis.com/auth/admin.directory.rolemanagement https://www.googleapis.com/auth/admin.datatransfer https://www.googleapis.com/auth/chrome.management.policy https://www.googleapis.com/auth/admin.directory.domain https://www.googleapis.com/auth/siteverification https://www.googleapis.com/auth/admin.directory.device.mobile https://www.googleapis.com/auth/ediscovery https://www.googleapis.com/auth/admin.reports.usage.readonly https://www.googleapis.com/auth/classroom.profile.photos https://www.googleapis.com/auth/apps.licensing https://www.googleapis.com/auth/admin.directory.user https://www.googleapis.com/auth/admin.reports.audit.readonly https://www.googleapis.com/auth/admin.contact.delegation https://www.googleapis.com/auth/cloud-identity.groups https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/admin.directory.group https://www.googleapis.com/auth/cloud-identity.userinvitations https://www.googleapis.com/auth/classroom.guardianlinks.students https://www.googleapis.com/auth/admin.directory.userschema https://www.googleapis.com/auth/classroom.profile.emails https://www.googleapis.com/auth/admin.directory.device.chromebrowsers https://www.googleapis.com/auth/admin.chrome.printers https://www.googleapis.com/auth/admin.directory.device.chromeos https://www.googleapis.com/auth/admin.directory.orgunit https://www.googleapis.com/auth/admin.directory.user.security https://www.googleapis.com/auth/apps.groups.settings openid
HelpPrivacyTerms

**Comment by sergeant-cj** [comment]
hi, having the same issue!

**Comment by kyomi44** [comment]
Also getting the below

Authorization Error
Error 400: invalid_scope
Some requested scopes cannot be shown: [https://www.googleapis.com/auth/chrome.management.policy, https://www.googleapis.com/auth/admin.contact.delegation, https://www.googleapis.com/auth/admin.chrome.printers, https://www.googleapis.com/auth/admin.directory.device.chromebrowsers, https://www.googleapis.com/auth/cloud-identity.userinvitations, https://www.googleapis.com/auth/cloud-identity.groups, https://www.googleapis.com/auth/classroom.guardianlinks.students, https://www.googleapis.com/auth/classroom.profile.emails, https://www.googleapis.com/auth/classroom.profile.photos, https://www.googleapis.com/auth/classroom.rosters, https://www.googleapis.com/auth/classroom.courses, https://www.googleapis.com/auth/ediscovery, https://www.googleapis.com/auth/siteverification, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/admin.datatransfer, https://www.googleapis.com/auth/admin.directory.customer, https://www.googleapis.com/auth/admin.directory.resource.calendar, https://www.googleapis.com/auth/admin.reports.audit.readonly, https://www.googleapis.com/auth/admin.reports.usage.readonly, https://www.googleapis.com/auth/admin.directory.userschema, https://www.googleapis.com/auth/admin.directory.domain, https://www.googleapis.com/auth/admin.directory.device.mobile, https://www.googleapis.com/auth/admin.directory.device.chromeos, https://www.googleapis.com/auth/admin.directory.orgunit, https://www.googleapis.com/auth/apps.licensing, https://www.googleapis.com/auth/admin.directory.group, https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.rolemanagement, https://www.googleapis.com/auth/admin.directory.user.security, https://www.googleapis.com/auth/apps.groups.settings]

**Comment by kyomi44** [comment]
Looks like there was already a report, disabling 4 Cloud identity - User invitations scope solved it for me as well.

https://github.com/jay0lee/GAM/issues/1351

@sergeant-cj @Bajrangverma

**Comment by sergeant-cj** [comment]
thanks so much @kyomi44

**Comment by Bajrangverma** [comment]
Yes its work with me as well

**Comment by jay0lee** [comment]
this is fixed with GAM 6.01
