### ISSUE TITLE
Error 403: Domain cannot use apis. - domainCannotUseApis

### ISSUE THREAD

**Issue by cksachdev** [jay0lee/GAM#137]
I am trying to setup gam on osx El Capitan. Below is a log
```
GAM 3.61 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.10 64-bit final
google-api-python-client 1.4.1
Darwin-15.0.0-x86_64-i386-64bit x86_64
Path: /Users/Sachdev/gam

Usage: gam [OPTIONS]...

GAM. Retrieve or set Google Apps domain,
user, group and alias settings. Exhaustive list of commands
can be found at: https://github.com/jay0lee/GAM/wiki

Examples:
gam info domain
gam create user jsmith firstname John lastname Smith password secretpass
gam update user jsmith suspended on
gam.exe update group announcements add member jsmith
```

I am getting the following error, when I run ``` gam info user ```
```
Error 403: Domain cannot use apis. - domainCannotUseApis
```

Any suggestion which setting is missing

**Comment by tgjones** [comment]
I'm getting this too, after following all the steps in the setup guide.

Some background info that may be useful: I just upgraded my domain, earlier today, from the free Google Apps to Google Apps for Work.

**Comment by tgjones** [comment]
Ah, I've found the solution: http://stackoverflow.com/questions/17888730/getting-domain-cannot-use-apis-when-using-google-admin-sdk-directory-api

You need to go to Security > API Reference > Enable API access.

**Comment by cksachdev** [comment]
Thanks. This fixed the issue.
