### ISSUE TITLE
Bulk Move Devices

### ISSUE THREAD

**Issue by SJAdmin** [jay0lee/GAM#138]
I am trying to move a bunch of devices from one sub OU to another and GAM seems to say it cannot find the devices.  The error I get is below.  I have tried moving the device to the main OU but GAM still cannot find it.  Any Ideas?

C:\gam>gam update cros deviceserialnumber ou "suborgou"
 updating deviceserialnumber (1 of 1)
Error 404: Resource Not Found: deviceserialnumber - notFound

Joe

**Comment by jay0lee** [comment]
This is an issue tracker for known bugs. Please discuss problems on the discussion group:

groups.google.com/group/google-apps-manager

Jay
