### ISSUE TITLE
Solve Windows AV malware false positive issues

### ISSUE THREAD

**Issue by jay0lee** [jay0lee/GAM#1388]
Windows AV software continues to flag GAM as malware because it's an unsigned executable that uses PyInstaller which is also used by some malware (guilty by association).

Potential solutions:

**Officially sign the Windows installler and executables.**
  - has real cost.
  - https://github.com/hankhank10/false-positive-malware-reporting
 
**convince AV vendors GAM is legit**
  - no single location to report FP.
  - Would take huge amount of time to chase down all these reports and convince AV vendors GAM is legit.

**build a process on Windows that uses official Python installer (which is signed by python.org) and the GAM Python source. Since GAM would not be an .exe it's less likely to be flagged.**
  - will require some scripting work to make experience as smooth as it is today with gam.exe installer and .zip
  - May require newer Windows 10 OS versions that ship with tools like curl and gzip to handle downloading / unpacking of GAM source in an automated fashion as well as a gam.bat file so users can still run commands like "gam info domain" instead of "python.exe \gam\gam.py info domain"

@taers232c FYI

**Comment by larsen161** [comment]
Alternative solution. Close the issue and provide the alternative for windows users to use the Windows Subsystem for Linux if they have misbehaving AV software

**Comment by jay0lee** [comment]
GAM 6.06 attempts to fix this issue by recompiling the PyInstaller bootloader on Windows (which seems to be what AV vendors flag on). Please give it a shot and report back results here.
