### ISSUE TITLE
GAM does not update the google group name

### ISSUE THREAD

**Issue by davidsev7** [jay0lee/GAM#1392]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. YES - 6.06
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki YES

Full steps to reproduce the issue:
1. sudo /usr/local/gam/gam update group ppp-awritingworkshop name "Postdisciplinary Perspectives on Politics"
2. /usr/local/gam/gam info group ppp-awritingworkshop

Group Settings:
 id: 03j2qqm31q38owh
 email: ppp-awritingworkshop@uci.edu
 name: Postdisciplinary Perspectives on Politics: A Writing Workshop
 directMembersCount: 10

3.

Expected outcome (what are you trying to do?):

Change the name field of the Google group.

Actual outcome (what errors or bad behavior do you see instead?):

The name is not changed.

**Comment by davidsev7** [comment]
I've updated to 6.07 hoping this would be fixed but it is not fixed. Can someone verify this is a repeatable bug?

**Comment by taers232c** [comment]
David,

It works fo me. Why are you running the update with sudo and the info without?

Ross
```
$ gam version
GAM 6.07 - https://git.io/gam - pythonsource
Jay Lee <jay0lee@gmail.com>
Python 3.9.6 64-bit final
google-api-python-client 2.3.0
MacOS High Sierra 10.13.6 x86_64
Path: /Users/admin/Documents/GoogleApps/GAMO

$ gam info group testgroup
Group: testgroup@rdschool.org
  Group Settings:
    id: 01302m923m7kxjj
    name: Test Group
    description:
...

$ gam update group testgroup name "Test	X Group"
updated group testgroup@rdschool.org

$ gam info group testgroup
Group: testgroup@rdschool.org
  Group Settings:
    id: 01302m923m7kxjj
    name: Test X Group
    description:
...
```

**Comment by taers232c** [comment]
David,

Contact me directly.

ross.scroggs @ gmail.com

**Comment by taers232c** [comment]
David and I resolved this. Yes, when gam updated the group name, it didn't change. Weird. We changed the name in the admin console; gam reflected the change. Subsequent gam commands to change the group name now work.

Ross

**Comment by davidsev7** [comment]
Thanks for all the help Ross. I enjoyed all the additional insights and information on GAM. Closing.
