### ISSUE TITLE
GAM 6.07 Windows 10 - ERROR: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by apg1980** [jay0lee/GAM#1404]
Hello we are getting following error while creating an new connect to google:

Steps we've done:
Is this a new install or an upgrade? [n or u] n

Are you ready to set up a Google API project for GAM? [y or n] y

Please enter your Google Workspace admin email address: googleemail...

Go to the following link in your browser:
copied the link tot browser and logged to google and accept data,,.,

Copied the code back to console and got this:

ERROR: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

We have tested several Versions of GAM but no success.

- No SSL Interception on Proxy is defined
- No Proxy Cache is configured

Thanks for your support,

**Comment by mrPsycho** [comment]
are you trying it in home? or in the office? 
if in the office so there might be transparent proxy which may spoil connection

**Comment by taers232c** [comment]
I'd start by installing the current version 6.25
----
Ross Scroggs
***@***.***
