### ISSUE TITLE
gam info user <username> not returning assigned licenses

### ISSUE THREAD

**Issue by sauced1** [jay0lee/GAM#1410]
I am using GAM 6.07 installed from the MSI, when running gam info for a user no license data is returned.

Full steps to reproduce the issue:
1. run gam.exe info user <usernname>

Expected outcome (what are you trying to do?):
Licenses assigned to the user should be output to std out

Actual outcome (what errors or bad behavior do you see instead?):
Licenses: section of gam info for the user is blank.

**Comment by jay0lee** [comment]
What happens when you run

gam print licenses

?

**Comment by sauced1** [comment]
After a minute or so I start getting rateLimitExceeded errors, then finally.
ERROR: 403: Quota exceeded for quota metric 'Queries' and limit 'Queries per day' of service 'licensing.googleapis.com' for consumer 'project_number:XXXXXXXXXXXX'. - rateLimitExceeded

**Comment by sauced1** [comment]
Well it looks like I can now see licensing information, I was processing our large student import for the beginning of the year so I guess we over ran the api quota. Can you point me in the direction of where I can find the api limits? Cursory google search I am only seeing for Google Analytics API calls.
