### ISSUE TITLE
GAM print licenses doesn't display full product number, causing issues reporting

### ISSUE THREAD

**Issue by ipsdmichael** [jay0lee/GAM#1420]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. run gam print licenses to produce list for entire domain
2. review list and compare license produced to actual product number

Expected outcome (what are you trying to do?):
the full license displayed or searchable, not just the first part

When i run:
gam print licenses products 1010310008 

Actual outcome (what errors or bad behavior do you see instead?):
i'd expect to see all students with the Google Workspace for Education licenses (or for 0009 it would include the (Staff)). no results are returned.

if i run it for just the first part - 101031 - all users are returned with either the "0008" or "0009" licenses, but that is not displayed, just 101031.

example results below. notice license is the same

student@studentdomain,101031,Google Workspace for Education Plus
staff@staffdomain,101031,Google Workspace for Education Plus (Staff)

when gam info user is run for the student:

Licenses:
  1010310008 (Google Workspace for Education Plus)

and for the staff member:

Licenses:
  1010310009 (Google Workspace for Education Plus (Staff))

i would expect those same license numbers to be visible across views

**Comment by taers232c** [comment]
When i run:
gam print licenses products 1010310008
*** is a SKU, not a product

Actual outcome (what errors or bad behavior do you see instead?):
i'd expect to see all students with the Google Workspace for Education licenses (or for 0009 it would include the (Staff)). no results are returned.
*** This is correct, you entered an invalid product

if i run it for just the first part - 101031 - all users are returned with either the "0008" or "0009" licenses, but that is not displayed, just 101031.
*** This is the correct way to run the command

example results below. notice license is the same

student@studentdomain,101031,Google Workspace for Education Plus
staff@staffdomain,101031,Google Workspace for Education Plus (Staff)

*** Look at the headers
userId,productId,skuId

*** Each of the two licenses in from the same product (101031) but have different SKUs, exactly what you'd expect

**Comment by ipsdmichael** [comment]
well that explains that then...thanks for the details. i was following this guide by AmplifiedIT

https://www.amplifiedit.com/everything-to-know-about-education-plus-licenses/

where they state to run exactly what i was. I appreciate you clarifying the difference between skuID and productID, which makes a lot of sense.

**Comment by ipsdmichael** [comment]
i appreciate the response @taers232c . it cleared up the issue for me.
