### ISSUE TITLE
ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by myossiv** [jay0lee/GAM#1427]
Hello, 
After I downland installed the GAM and trying to configure it I got this error:

**ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
Project creation failed. Trying again. Say N to skip project creation.**

Need help here, please
I am using Mac Big Sur version 11.6

**Comment by jay0lee** [comment]
Please post on:

git.io/gam-group
