### ISSUE TITLE
"ERROR: 400: Invalid Input: INVALID_OU_ID - invalid" when using a csv

### ISSUE THREAD

**Issue by ESD401** [jay0lee/GAM#1448]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
Confirmed. On GAM 6.10

* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
Confirmed.

Full steps to reproduce the issue:
1. run the command: gam csv name.csv gam update cros ~serial ou ~ou
2. 
3.

Expected outcome (what are you trying to do?): I'm trying to move many Chromebooks to different OU's. In my CSV file, I have a serial header and an ou header. When I use the command above, it's always hit or miss if each line in the CSV will work or not; some Chromebooks move and some don't. If I immediately run the command again and don't change a single thing, I'll get a different batch that worked and didn't.

Actual outcome (what errors or bad behavior do you see instead?): Here's a snippet of what I get when trying to use ~ou in my command (every row in the 'ou' header is the same except for the number at the end; in this case, I had a batch of Chromebooks going to an OU and another batch of Chromebooks going to a different OU):

 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-52
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-52
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-52

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-52

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-52
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-53

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-53

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-53

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid

ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-53
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-53
 moving 1 devices to /Devices/MSES/MSES Clever/Chromebook Cart-53
 
 
If I take out ~ou and specify the location within the command itself then every Chromebook move perfectly. When I have many Chromebooks and different OU's they each go into, this causes me to have to create multiple csv's and run the command multiple times each with a new specified OU. 

If you'd like the csv I'm using please let me know.

**Comment by jay0lee** [comment]
This looks like a config issue, not a bug. Please report the problem to the Google Group.

**Comment by ESD401** [comment]
I'm sorry, could you point me towards the Google Group?
