### ISSUE TITLE
Upgrade to Drive API v3

### ISSUE THREAD

**Issue by jay0lee** [jay0lee/GAM#151]
Drive API v3 has been released:

http://googleappsdeveloper.blogspot.com/2015/12/a-leaner-and-faster-google-drive-api.html

we should look at moving GAM to using v3.

@taers232c in case you're interested and have the time.

**Comment by taers232c** [comment]
And best of all, five new scopes! I'll look it over.
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Post 4.12 now allows some Drive v3 API calls (including all Team Drive specific API calls). We'll work to (slowly) move all calls of v2.
