### ISSUE TITLE
GAMCACHEDIR invalid path and gamscopes.json, Not Found

### ISSUE THREAD

**Issue by singularitytrav** [jay0lee/GAM#167]
Ran git clone https://github.com/jay0lee/GAM.git
on my mac with os 10.11.2 and Python 2.7.10. Copied my client_secrets.json from a previous gam install as well as my oauth2service.json. Ran python gam.py info domain, got:

WARNING: GAMCACHEDIR=/Users/trab/Documents/GAM/src/gamcache, Invalid Path
WARNING: GAMSCOPESFILE=/Users/trab/Documents/GAM/src/gamscopes.json, Not Found
Traceback (most recent call last):
  File "gam.py", line 9150, in <module>
    doGetDomainInfo()
  File "gam.py", line 1401, in doGetDomainInfo
    doGetInstanceInfo()
  File "gam.py", line 7104, in doGetInstanceInfo
    adm = buildGAPIObject(u'admin-settings')
  File "gam.py", line 854, in buildGAPIObject
    scopes = setCurrentAPIScopes(service)
  File "gam.py", line 805, in setCurrentAPIScopes
    systemErrorExit(15, MESSAGE_NO_SCOPES_FOR_API.format(api, version))
NameError: global name 'api' is not defined

that path to gamcache is valid though there is no gamscopes.json. I surely must be missing something obvious but I simply don't see it....

thanks!

**Comment by jay0lee** [comment]
git master is in a rather unstable state right now as Ross Scruggs and I
are working on some fairly large changes. For prod you should be using
latest release, 3.62:

git checkout tags/v3.62

or you could just grab the actual release tarball:

https://github.com/jay0lee/GAM/releases

Jay

On Mon, Jan 4, 2016 at 1:16 PM Trav <notifications@github.com> wrote:

> Ran git clone https://github.com/jay0lee/GAM.git
> on my mac with os 10.11.2 and Python 2.7.10. Copied my client_secrets.json
> from a previous gam install as well as my oauth2service.json. Ran python
> gam.py info domain, got:
>
> WARNING: GAMCACHEDIR=/Users/trab/Documents/GAM/src/gamcache, Invalid Path
> WARNING: GAMSCOPESFILE=/Users/trab/Documents/GAM/src/gamscopes.json, Not
> Found
> Traceback (most recent call last):
> File "gam.py", line 9150, in
> doGetDomainInfo()
> File "gam.py", line 1401, in doGetDomainInfo
> doGetInstanceInfo()
> File "gam.py", line 7104, in doGetInstanceInfo
> adm = buildGAPIObject(u'admin-settings')
> File "gam.py", line 854, in buildGAPIObject
> scopes = setCurrentAPIScopes(service)
> File "gam.py", line 805, in setCurrentAPIScopes
> systemErrorExit(15, MESSAGE_NO_SCOPES_FOR_API.format(api, version))
> NameError: global name 'api' is not defined
>
> that path to gamcache is valid though there is no gamscopes.json. I surely
> must be missing something obvious but I simply don't see it....
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/167>.
>
-- 

Jay Lee

**Comment by singularitytrav** [comment]
ah, I see, ok thanks!!
