### ISSUE TITLE
GAM-362

### ISSUE THREAD

**Issue by marianohare** [jay0lee/GAM#168]
I have just installed GAM 362-, created project with all API's I require, have authorized API clients, however I am getting this error:

D:\gam\gam-362\gam-64>gam info domain
Google Apps Domain: xxxx.ca
ERROR: 403: Access Not Configured. The API (Admin Directory API) is not enabled
for your project. Please use the Google Developers Console to update your config
uration. - accessNotConfigured

If this is referring to the Admin SDK, it is enabled

**Comment by jay0lee** [comment]
The error is coming from Google so Google seems convinced it's not enabled. Try running:

gam oauth info

and confirm your client id matches the one for the project you're looking at in console.developers.google.com.

Jay

**Comment by marianohare** [comment]
I ran 
gam oauth info
The Client ID has access to the following below, I want it to have access to everything, since I am the only one who will be running the scripts

Email (Read/Write/Send)  https://mail.google.com/ 
https://www.googleapis.com/auth/activity 
https://www.googleapis.com/auth/admin.datatransfer 
https://www.googleapis.com/auth/admin.directory.customer 
https://www.googleapis.com/auth/admin.directory.domain 
View and manage the provisioning of users on your domain  https://www.googleapis.com/auth/admin.directory.user 
https://www.googleapis.com/auth/admin.directory/activity 
https://www.googleapis.com/auth/admin.directory/calendar 
https://www.googleapis.com/auth/admin.directory/contacts 
https://www.googleapis.com/auth/admin.directory/drive 
https://www.googleapis.com/auth/admin.directory/email 
https://www.googleapis.com/auth/admin.directory/group 
Calendar (Read-Write)  https://www.googleapis.com/auth/calendar 
https://www.googleapis.com/auth/classroom.courses 
https://www.googleapis.com/auth/classroom.profile.emails 
https://www.googleapis.com/auth/classroom.profile.photos 
https://www.googleapis.com/auth/classroom.rosters 
https://www.googleapis.com/auth/cloudprint 
https://www.googleapis.com/auth/contacts 
https://www.googleapis.com/auth/drive 
https://www.googleapis.com/auth/email 
https://www.googleapis.com/auth/group 
https://www.googleapis.com/auth/plus.login 
https://www.googleapis.com/auth/plus.me 
https://www.googleapis.com/auth/siteverification

Can i also ask another question related to this.  When I install GAM, whether it be 35, 361 or 362 how many Client ID can it be associated with this gam.exe.  If I create another project and update the oauth2service.json and the client_services.json does this mean the other projects with no longer work.  How do I have more than one project running within GAM with different oauth2service.json and the client_services.json

Thank-You

**Comment by marianohare** [comment]
Ok, the above scopes are from the Admin console, after running 
gam oauth info
Results:
Scopes:
  https://www.googleapis.com/auth/userinfo.email
  https://www.googleapis.com/auth/admin.directory.group
  https://www.googleapis.com/auth/admin.directory.orgunit
  https://www.googleapis.com/auth/admin.directory.user
  https://www.googleapis.com/auth/admin.directory.device.chromeos
  https://www.googleapis.com/auth/admin.directory.device.mobile
  https://apps-apis.google.com/a/feeds/emailsettings/2.0/
  https://www.googleapis.com/auth/admin.directory.resource.calendar
  https://apps-apis.google.com/a/feeds/compliance/audit/
  https://apps-apis.google.com/a/feeds/domain/
  https://www.googleapis.com/auth/apps.groups.settings
  https://www.googleapis.com/auth/calendar
  https://www.googleapis.com/auth/admin.reports.audit.readonly
  https://www.googleapis.com/auth/admin.reports.usage.readonly
  https://www.googleapis.com/auth/drive.file
  https://www.googleapis.com/auth/apps.licensing
  https://www.googleapis.com/auth/admin.directory.user.security
  https://www.googleapis.com/auth/siteverification
  https://mail.google.com/
  https://www.googleapis.com/auth/admin.directory.userschema
  https://www.googleapis.com/auth/classroom.rosters
  https://www.googleapis.com/auth/classroom.courses
  https://www.googleapis.com/auth/classroom.profile.emails
  https://www.googleapis.com/auth/classroom.profile.photos
  https://www.googleapis.com/auth/cloudprint
  https://www.googleapis.com/auth/admin.datatransfer
  https://www.googleapis.com/auth/admin.directory.customer
  https://www.googleapis.com/auth/admin.directory.domain
  https://www.googleapis.com/auth/admin.directory.rolemanagement
  https://www.googleapis.com/auth/plus.me

They are different not sure why
