### ISSUE TITLE
20e8175 gam.py throws "gamscopes.json Not Found" error

### ISSUE THREAD

**Issue by funtasy** [jay0lee/GAM#169]
Since last commit 20e8175 I get these errors:
WARNING: GAMSCOPESFILE=/path/to/GAM/src/gamscopes.json, Not Found
Traceback (most recent call last):
  File "gam.py", line 9161, in <module>
    doDeleteGroup()
  File "gam.py", line 7255, in doDeleteGroup
    cd = buildGAPIObject(u'directory')
  File "gam.py", line 854, in buildGAPIObject
    scopes = setCurrentAPIScopes(service)
  File "gam.py", line 805, in setCurrentAPIScopes
    systemErrorExit(15, MESSAGE_NO_SCOPES_FOR_API.format(api, version))
NameError: global name 'api' is not defined

**Comment by jay0lee** [comment]
Sounds like you pulled the latest dev version of GAM. The dev version is undergoing some major changes and is not stable. For production work, please download a stable release:

https://github.com/jay0lee/GAM/releases

Jay

**Comment by funtasy** [comment]
i c - thx
