### ISSUE TITLE
GAM 3.62 Win x64 Hangs from PS

### ISSUE THREAD

**Issue by willpolley** [jay0lee/GAM#171]
When initiating gam.exe from powershell, the binary hangs when current working directory of the shell is not the installed directory. We use GAM in a web based AD management software to publish changes to GA without using GADS.

PS H:\> & C:\gam2\gam.exe info domain
Have to kill from taskman. Waited 2 mins.
PS H:\>

PS C:\gam2> & C:\gam2\gam.exe info domain
Google Apps Domain: {returns as expected}
PS C:\gam2>

**Comment by willpolley** [comment]
Seems like this is probably related to https://github.com/jay0lee/GAM/issues/82

Works prior to 3.62 however.

**Comment by erikpt** [comment]
I think the problem is due to the GC_Defaults array setting **GC_CONFIG_DIR** to null. I'm going to test with using *os.path.dirname(os.path.realpath(\_\_file\_\_))* as the default value  

183: GC_CONFIG_DIR: u''

**Comment by daemon-33** [comment]
I was able to bandaid this by copying the client_secrets.json and oauth2.txt to the same directory that our scripts are running from.
