### ISSUE TITLE
GAM - User Reports Errors

### ISSUE THREAD

**Issue by jkrizajku** [jay0lee/GAM#174]
This morning when I try to run "gam report users"  or "gam report users fields <blah blah blah>" I get the following errors. 

Linux (GAM 3.62)
Traceback (most recent call last):
  File "/usr/local/gam/gam/gam.py", line 9355, in <module>
    showReport()
  File "/usr/local/gam/gam/gam.py", line 1021, in showReport
    row = {u'email': user_report[u'entity'][u'userEmail'], u'date': str(try_date)}
KeyError: u'entity'

Windows (GAM 3.61 X64)
Traceback (most recent call last):
  File "<string>", line 8490, in <module>
  File "<string>", line 807, in showReport
KeyError: u'entity'

If I run "gam report users user <email address>" the command works fine. UP until today everything was working.

Thanks,

**Comment by SJarjoura** [comment]
We're seeing the same thing; tested with GAM versions 3.51 and 3.62.
Tried "gam report users user username@domain.com" and saw the same error message.

"gam print users" works, though.

**Comment by jkrizajku** [comment]
I tested my scripts again without any modification and everything seems to be working again. There must of been an issue with Googles API that is now resolved.
