### ISSUE TITLE
Shared Contacts

### ISSUE THREAD

**Issue by mcvpjd3** [jay0lee/GAM#175]
Is there some way of creating Shared contacts within GAMS - This is for external email addresses?

Thanks

**Comment by Servovicis** [comment]
In the past I was trying to find a way to do this within GAM, and was unable to find any way to manage individual contact lists, or modify the directory. It is accessible through API's however, and that ended up being my approach.

**Comment by jay0lee** [comment]
GAM does not support Shared Contacts API. If Google releases a newer version of the API that uses the "Google API" format instead of the legacy GData format I'll consider adding support to GAM.
