### ISSUE TITLE
Gam command to activate users vacation is not working

### ISSUE THREAD

**Issue by bisiolu** [jay0lee/GAM#177]
When a user is terminated, we activate their out of office / vacation setting and update the content via GAM. This morning we are unable to activate terminated users vacation. The script runs OK, but when we check the updated content it shows that the vacation is off. The start and end dates are the only thing that get updated. 
Below is a sample command issued today.

gam user xxxxx_departed_20151123@domain.org vacation on subject " first last is no longer with the Company:" message "first last is no longer with the Company, please contact first's manager Mr Manager by email at <Mr.Manager@domain.org> . \n Thank You \n  Support." startdate $(date +%Y-%m-%d) enddate 2099-12-30

**Comment by jay0lee** [comment]
This is fixed in master and will be in the next release of GAM.
