### ISSUE TITLE
GAM-    ERROR: 500: Backend Error - backendError

### ISSUE THREAD

**Issue by Mariano17** [jay0lee/GAM#180]
I have created a script to update 100 groups.  This same script has worked before but now I am getting the following error:
Temp error backendError. Backing off 16 seconds...attempt 5/10
Temp error backendError. Backing off 32 seconds...attempt 6/10
Temp error backendError. Backing off 60 seconds...attempt 7/10
Temp error backendError. Backing off 60 seconds...attempt 8/10
Temp error backendError. Backing off 60 seconds...attempt 9/10
Temp error backendError. Backing off 60 seconds...attempt 10/10
ERROR: 500: Backend Error - backendError
Temp error backendError. Backing off 16 seconds...attempt 5/10
Temp error backendError. Backing off 32 seconds...attempt 6/10
Temp error backendError. Backing off 60 seconds...attempt 7/10
Temp error backendError. Backing off 60 seconds...attempt 8/10
Temp error backendError. Backing off 60 seconds...attempt 9/10
Temp error backendError. Backing off 60 seconds...attempt 10/10
ERROR: 500: Backend Error - backendError

Part of the output txt file, does say "updated group xxx"

then I get the above error.
Running GAM 362
If anyone could help, would appreciate it.  I don't want to change the group settings manually.  I have these 100 plus another 150

**Comment by jay0lee** [comment]
This is generally a temp issue on Google's end, not a GAM bug. Closing. Re-open if you can consistently reproduce this issue.
