### ISSUE TITLE
Issue in Printing Resources

### ISSUE THREAD

**Issue by Kannan523** [jay0lee/GAM#181]
Hello,

we are facing issue in Printing Resources using Google apps Manager

We are using the following command 

gam print resources allfields > test.csv

however it throws an error 

"Retrieving All Resource Calendars for your account (may take some time on a larg
e domain)Traceback (most recent call last):
  File "<string>", line 7530, in <module>
  File "<string>", line 6530, in doPrintResources
KeyError: u'resourceCommonName'
"
The CSV file is created but looks empty
Please let us know why we are encountering this issue.

Regards
Kannan

**Comment by Kannan523** [comment]
I did try the same with Python encountering the same error.

Please find the Error Message for Python

Retrieving All Resource Calendars for your account (may take some time on a large domain)Traceback (most recent call last):

  File "gam.py", line 8303, in <module>

    doPrintResources()

  File "gam.py", line 7268, in doPrintResources

    resUnit.update({u'Name': resource[u'resourceCommonName']})

KeyError: u'resourceCommonName'

**Comment by jay0lee** [comment]
Sounds like you're using an old version of GAM. Please upgrade to the latest and try again.

http:/git.io/gamreleases
