### ISSUE TITLE
Push Image Profil

### ISSUE THREAD

**Issue by dav1303** [jay0lee/GAM#183]
Hi 

When Pushing Image profiles with GAM the image is visible on gmail but not on Drive when the user connects we only see a letter corresponding to is firstname.

Regards

**Comment by taers232c** [comment]
What command are you issuing?

Ross

**Comment by dav1303** [comment]
gam user <username>|group <groupname>|ou <ouname>|all users update photo <photo filename>

**Comment by jay0lee** [comment]
Closing as this is an issue (or feature) on Google's side, not GAM's. GAM is properly calling the photo API.
