### ISSUE TITLE
Bulk Update groups 

### ISSUE THREAD

**Issue by dastrixuk** [jay0lee/GAM#185]
Hi 

I am trying to update who can view membership of a group to all members can view, with the following ps script

`$list = Import-Csv groups.csv
foreach ($entry in $list){ .\gam.exe update group $($entry.Email) settings who_can_view_membership all_members_can_view; echo $entry.Email updated }`

However i am getting the following error any ideas?

ERROR: settings is not a valid argument for "gam update group"

**Comment by GI-thub** [comment]
The error message is correct, take a look at
https://github.com/jay0lee/GAM/wiki/GAM3GroupSettings#who-can-view-membership
for the syntax, no mention of SETTINGS


 Graham Ingleby |  Cloud Computing Consultant |  +44 1344 203395 |
gingleby@ancoris.com
[image: Google+] <http://google.com/+Ancoris>
<http://www.linkedin.com/company/98835>  <http://www.ancoris.com>
<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

On 8 February 2016 at 09:40, dastrixuk <notifications@github.com> wrote:

> Hi
>
> I am trying to update who can view membership of a group to all members
> can view, with the following ps script
>
> $list = Import-Csv groupscsv
> foreach ($entry in $list){ \gamexe update group $($entryEmail) settings
> who_can_view_membership all_members_can_view; echo $entryEmail updated }
>
> However i am getting the following error any ideas?
>
> ERROR: settings is not a valid argument for "gam update group"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/185>.
>

-- 


------------------------------

This message is for the named person's use only.  If you receive this message in error, please delete it and notify the sender.  Ancoris reserves the right to monitor all e-mail communications through its networks. Ancoris Limited, Registered in England Number: 04830784, Registered address: 5a Frascati Way, Maidenhead, Berkshire SL6 4UY. Trading Address: Lily Hill House, Lily Hill Road, Bracknell, Berkshire RG12 2SJ

------------------------------
