### ISSUE TITLE
About the Limits 

### ISSUE THREAD

**Issue by piqano** [jay0lee/GAM#190]
Hi, 

Thank you for this Program.. i would like to ask you about the limits of : 
- How many emails i can send per hour with google groups (business)
If we passed the limit of requests allowed by google with your prog... do they will charge me extra fees? if yes, How much!

Thank you so much

**Comment by GI-thub** [comment]
Not really GAM questions, but, The sending limits for groups can be found
at https://support.google.com/a/answer/6099642

If you try to exceed these limits then your messages are bounced, so no
charges


 Graham Ingleby |  Cloud Computing Consultant |  +44 1344 203395 |
gingleby@ancoris.com
[image: Google+] <http://google.com/+Ancoris>
<http://www.linkedin.com/company/98835>  <http://www.ancoris.com>
<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

On 15 February 2016 at 16:18, piqano <notifications@github.com> wrote:

> Hi,
>
> Thank you for this Program.. i would like to ask you about the limits of :
>
>    - How many emails i can send per hour with google groups (business) If
>    we passed the limit of requests allowed by google with your prog... do they
>    will charge me extra fees? if yes, How much!
>
> Thank you so much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/190>.
>

-- 


------------------------------

This message is for the named person's use only.  If you receive this message in error, please delete it and notify the sender.  Ancoris reserves the right to monitor all e-mail communications through its networks. Ancoris Limited, Registered in England Number: 04830784, Registered address: 5a Frascati Way, Maidenhead, Berkshire SL6 4UY. Trading Address: Lily Hill House, Lily Hill Road, Bracknell, Berkshire RG12 2SJ

------------------------------
