### ISSUE TITLE
Characters from the unicode in cpXXX not displayed

### ISSUE THREAD

**Issue by Polyakov-Andrey** [jay0lee/GAM#191]
Characters from the unicode in cpXXX not displayed 
D:\Projects\Scripte\gam-3.63-windows>gam info user ********
User: *********
Traceback (most recent call last):
File "", line 9136, in 
File "", line 6352, in doGetUserInfo
File "C:\Users\jlee\Documents\GitHub\gam363\src\build\gam\out00-PYZ.pyz\encodings.cp866", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0456' in position 16: character maps to

**Comment by Polyakov-Andrey** [comment]
OS: Windows 8.1 - Rus
Console in cp866 - Cyrillic script
User information have same fields in UTF-8 with char Cyrillic (not English)
Error: It is not translation ftom UTF-8 (not English) to cpXXX
Note: UTF-8 - 2-byte vs cpXXX - 1-byte

**Comment by taers232c** [comment]
If I look at this page: https://en.wikipedia.org/wiki/Code_page_866
I don't see a character with Unicode code point 0456 which is defined here: http://www.fileformat.info/info/unicode/char/0456/index.htm
