### ISSUE TITLE
ERROR: 404: File not found: <file id> - notFound

### ISSUE THREAD

**Issue by mazzproduction** [jay0lee/GAM#193]
Hi, I am trying to show/update/delete a specific file (with file id) for **ALL USERS** using a command like this:

`./gam.py all users update drivefile id <file id> trashed true`

I intend to make sure the specified file is trashed/removed from all the users, but the following error is shown right after getting users:

> Getting all users in Google Apps account (may take some time on a large account)...
> Got XX users...
> done getting XX users.
> ERROR: 404: File not found: <file id> - notFound

I suspect this error is shown as the first user doesn't have that file, but I expect it will continue looking for the file from the next user account until all the users have been gone through.

So, am I correct to say it is a bug? If not, how should I get rid of this error and make sure a specific file is removed from all user accounts?

Thank you very much in advance.

**Comment by jay0lee** [comment]
Please upgrade to the latest version of GAM 3.8 and confirm the issue still exists.
