### ISSUE TITLE
Exporting Users as .csv file from Google Admin Console

### ISSUE THREAD

**Issue by mariavalenmitra14** [jay0lee/GAM#194]
Hi!

I really need to download all the users in my Google Admin Console. I have tried using "gam print users allfields >users.csv" command and it successfully displayed some output. I just want to ask where can I find the users.csv file? Is my code correct? or do you have any suggestion for exporting all the users? 

Looking forward  for your response. Thank you.

**Comment by GI-thub** [comment]
It will be in the folder you ran the command from


 Graham Ingleby |  Cloud Computing Consultant |  +44 1344 203395 |
gingleby@ancoris.com
[image: Google+] <http://google.com/+Ancoris>
<http://www.linkedin.com/company/98835>  <http://www.ancoris.com>
<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

<http://www.ancoris.com/news-and-views/ancoris-blog/crn-recognises-ancoris-with-2015-cloud-services-provider-award.html>

On 19 February 2016 at 03:12, mariavalenmitra14 <notifications@github.com>
wrote:

> Hi!
>
> I really need to download all the users in my Google Admin Console. I have
> tried using "gam print users allfields >users.csv" command and it
> successfully displayed some output. I just want to ask where can I find the
> users.csv file? Is my code correct? or do you have any suggestion for
> exporting all the users?
>
> Looking forward for your response. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/194>.
>

-- 


------------------------------

This message is for the named person's use only.  If you receive this message in error, please delete it and notify the sender.  Ancoris reserves the right to monitor all e-mail communications through its networks. Ancoris Limited, Registered in England Number: 04830784, Registered address: 5a Frascati Way, Maidenhead, Berkshire SL6 4UY. Trading Address: Lily Hill House, Lily Hill Road, Bracknell, Berkshire RG12 2SJ

------------------------------

**Comment by mariavalenmitra14** [comment]
Than you very much for your help.

In St. La Salle,

*Maria Valen M. Mitra*
Technical Support Staff

Information and Communication Technology Center
