### ISSUE TITLE
Output regarding reminder to update

### ISSUE THREAD

**Issue by brainysmurf** [jay0lee/GAM#196]
I use tools such as python gam.py print users username lastlogintime and redirects that to a text file, and then other tools reading in that file, expecting it to have a header on top, etc. More than once now I have had things break because it is outputting a reminder (with blank lines and such), which is not in the expected format.

**Comment by taers232c** [comment]
What does the reminder say? Is it about updating GAM? If so, make an empty file, noupdatecheck.txt in the same directory as gam.py/gam.exe.

Ross
