### ISSUE TITLE
GAM not functioning within PHP script

### ISSUE THREAD

**Issue by lsaintignan** [jay0lee/GAM#197]
Forgive me as I am not a programmer and the programmer that created this is no longer with us. We use GAM to auto create our student email accounts. Yesterday morning, it stopped working. I noticed there was an update recently and I remember being told that it would break if there was a new update. I updated it, successfully, but the issue still remains.

The issue seems to be related to gam running from within the PHP code. I can run gam create user just fine from within the command line, but when running via the script I get an add error...and it's not so much an error as it needs to just "continue." Here's what's in the logs:

Gmail Add Error
array (
  'command' => 'C:\\gam\\gam.exe create user "*********" firstname "LIZZBETH" lastname "FERGUSON" password "********"',
  'input' => '',
  'stdout' => ' 
Select the authorized scopes for this token. Include a \'r\' to grant read-only
access or an \'a\' to grant action-only access.

[*]  0)  Group Directory API (supports read-only)
[*]  1)  Organizational Unit Directory API (supports read-only)
[*]  2)  User Directory API (supports read-only)
[*]  3)  Chrome OS Device Directory API (supports read-only)
[*]  4)  Mobile Device Directory API (supports read-only and action)
[*]  5)  User Email Settings API
[*]  6)  Resource Calendar API (supports read-only)
[*]  7)  Audit Monitors, Activity and Mailbox Exports API
[*]  8)  Admin Settings API
[*]  9)  Groups Settings API
[*]  10)  Calendar Data API (supports read-only)
[*]  11)  Audit Reports API
[*]  12)  Usage Reports API
[*]  13)  Drive API (create report documents for admin user only)
[*]  14)  License Manager API
[*]  15)  User Security Directory API
[ ]  16)  Notifications Directory API
[*]  17)  Site Verification API
[*]  18)  IMAP/SMTP Access (send notifications to admin)
[*]  19)  User Schemas (supports read-only)
[*]  20)  Classroom API
[*]  21)  Cloud Print API
[*]  22)  Data Transfer API (supports read-only)
[*]  23)  Customer Directory API (supports read-only)
[*]  24)  Domains Directory API (supports read-only)
[*]  25)  Roles API (supports read-only)

      26)  Select all scopes
      27)  Unselect all scopes
      28)  Continue
',
  'stderr' => 'Traceback (most recent call last):
  File "", line 9072, in 
  File "", line 5048, in doCreateUser
  File "", line 804, in buildGAPIObject
  File "", line 8905, in doRequestOAuth
EOFError: EOF when reading a line
',
  'return' => -1,

As you can see, it seems to be running the initial setup to configure the API's, yet I've already done this. Even when I run that same gam create command from within the command line, it creates the user with no issues. Here's part of the PHP code:

if( ! $studentNew && ! $studentOld ) {  // neither account exists, create one
				// C:\gam\gam.exe create user <email address> firstname <First Name> lastname <Last Name> password <Password>
				// C:\gam\gam.exe create user droth firstname "David Lee" lastname Roth password 'MightAsWellJump!'
				$output = my_exec( 'C:\gam\gam.exe create user "' . $studentUsername . '" firstname "' . $exStudents[$j]['FIRST_NAME'] . '" lastname "' . $exStudents[$j]['LAST_NAME'] . '" password "' . $studentPassword . '"' );  // send account info to Gmail
				if( $output['return'] === 0 ) {  // account added
					$logfile->showNote( 'Created student Gmail account: ' . $studentUsername . ' for &ldquo;' . htmlentities( $exStudents[$j]['LAST_NAME'] . ', ' . $exStudents[$j]['FIRST_NAME'] ) . '&rdquo; (' . $exStudents[$j]['ID_NUM'] . ')' );
					$studentNew = array( 'EMAIL_ADDRESS' => $studentEmail, 'LAST_NAME' => $exStudents[$j]['LAST_NAME'], 'FIRST_NAME' => $exStudents[$j]['FIRST_NAME'], 'USER_ID' => $studentUsername );

Any guidance/help would be greatly appreciated!

**Comment by yubbie** [comment]
Make sure you're running the gam out of the same directory interactively as in the job that runs the script; check to see if there are environment variables being defined to change where it loads its config - if it has it's own json files and oauth file, it would do exactly what you're seeing, be trying to complete the authentication for that context.

Note that this forum is for bugs in the gam code itself, if you need additional help, check out the user forum at https://groups.google.com/forum/#!forum/google-apps-manager

**Comment by lsaintignan** [comment]
Are you saying that the php script needs to be in the same location as the gam files? I'm dense when it comes to programming...

The script is in another location (C:\inetpub\wwwroot\mykc\tasks\sync.php) while gam and it's files are located C:\gam.

It has been working this way for years. I may not be understanding you and for that I apologize.  And thanks for that link, I posted over there as well.

**Comment by lsaintignan** [comment]
Looks like it was a bug in the version 3.63 that I upgraded. I went here: https://github.com/taers232c/GAM/releases/tag/v3.63 and installed this version 3.63. This has the issue I was encountering solved!
