### ISSUE TITLE
Group add user not working

### ISSUE THREAD

**Issue by Jan-Zoudlik** [jay0lee/GAM#198]
Hello, 

used to use gam to add users into groups with no issues.
Wanted to use it again today finding that it no longer works...

I used to use:
gam csv file.csv gam update group groupname add member user ~EMAIL > log.txt

According to "new documentation" I tried to use:
gam update group groupname@mydomain.net  add member file file.csv > log.txt

This is what I get:
gam.py:8739: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "<string>", line 9103, in <module>
  File "<string>", line 5951, in doUpdateGroup
  File "<string>", line 8741, in getUsersToModify
  File "C:\Users\jlee\Documents\GitHub\gam363\src\build\gam\out00-PYZ.pyz\encodings.utf_8", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 0: invalid start byte

when I do gam user info, I do get correct response therefore no issue with json file...

Any response will be welcome

Thanks
Regards
Jan

**Comment by jay0lee** [comment]
This error generally is due to a invalid / corrupt CSV file. Closing issue but feel free to re-open if you can provide a sample CSV that produces the issue.
