### ISSUE TITLE
Remove Members In Group

### ISSUE THREAD

**Issue by piqano** [jay0lee/GAM#202]
Hi,

I would like to know if there is a way to empty the group (remove all members from it by using GAM)
==> gam update group <group email> remove <Email> 
This order will remove a specific user ... if there is a way to remove all users please let me know..

Thank you for your Help!

**Comment by jay0lee** [comment]
The issue tracker is meant for actual bugs and feature requests. Please post "how do I?" questions to the discussion group:

https://groups.google.com/group/google-apps-manager
