### ISSUE TITLE
Getting Users' Info by Using a CSV file

### ISSUE THREAD

**Issue by mariavalenmitra14** [jay0lee/GAM#203]
Hi!
I'm on the process of deleting user accounts in our Gmail Admin Console and I'm using GAM which I find very useful. By doing this, first I need to make sure that these students' accounts were no longer active. I've already created a csv file of their email addresses. My question is, how can I get these users' information by using GAM (i.e. name, last login) by just using the csv file?

Looking forward for your response. Thank you.

**Comment by taers232c** [comment]
Doing this with a CSV file will be difficult.
Do: gam print users fullname lastlogintime > Users.csv
Users.csv will have columns: primaryEmail,lastLoginTime,name.familyName,name.fullName,name.givenName

Look up your user accounts to delete in this file.

You'll get a faster response via one of these methods:
To post to this group, send email to google-apps-manager@googlegroups.com.
Visit this group at https://groups.google.com/group/google-apps-manager.

**Comment by jay0lee** [comment]
Closing non-bug issue.
