### ISSUE TITLE
Error 400: Invalid Input: INVALID_OU_ID - invalid only on route Organizaztion Sub Orgs

### ISSUE THREAD

**Issue by DougBelina** [jay0lee/GAM#204]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1. gam update org kmbs.konicaminolta.us add file OrgUserMov
eList.txt

2.Generates the following: moving tony.stark@kmbs.konicaminolta.us to /kmbs.konicaminolta.us (1/1)
Error 400: Invalid Input: INVALID_OU_ID - invalid

3. If I change the org to a sub org it works OK

Expected outcome (what are you trying to do?):move users from sub org to mail org

Actual outcome (what errors or bad behavior do you see instead?):Error 400: Invalid Input: INVALID_OU_ID - invalid

**Comment by jay0lee** [comment]
Try:

gam update org / add file OrgUserMoveList.txt

the admin console lies about the root OU being named after your domain,
it's really just /.

Jay

On Wed, Mar 2, 2016 at 10:46 AM DougBelina <notifications@github.com> wrote:

> The issue tracker is for reporting product deficiencies. How do I
> questions should be posted to the discussion forum at
> https://groups.google.com/group/google-apps-manager. When in doubt, start
> at the discussion forum and return here only when instructed to do so.
>
> Please confirm the following:
>
>    - I have upgraded to the latest GAM release from
>    http://git.io/gamreleases and I still have this issue.
>    - I am typing the command as described in the GAM Wiki at
>    https://github.com/jay0lee/GAM/wiki
>    - I am using a Google Apps for Work, Unlimited or EDU account (Google
>    Apps Standard / Free is not supported)
>
> Full steps to reproduce the issue:
> 1. gam update org kmbs.konicaminolta.us add file OrgUserMov
> eList.txt
>
> 2.Generates the following: moving tony.stark@kmbs.konicaminolta.us to /
> kmbs.konicaminolta.us (1/1)
> Error 400: Invalid Input: INVALID_OU_ID - invalid
>
>    1. If I change the org to a sub org it works OK
>
> Expected outcome (what are you trying to do?):move users from sub org to
> mail org
>
> Actual outcome (what errors or bad behavior do you see instead?):Error
> 400: Invalid Input: INVALID_OU_ID - invalid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/204>.
>
-- 

Jay Lee

**Comment by DougBelina** [comment]
>gam update org "/" add file OrgUserMoveList.txt worked like a charm.  Thank you for your quick response.
