### ISSUE TITLE
Invalid whoCanPostMessage value

### ISSUE THREAD

**Issue by josemdv** [jay0lee/GAM#205]
Not sure if this issues is related with GAM or this is a bug with the Google Groups API. 

I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1.  Create a Google Groups under admin.google.com
2.  Change the "Post" permission to **public** using the web interface groups.google.com. 
3.  Run GAM to export all the settings for that group

Expected outcome:

I'm expecting ANYONE_CAN_POST

Actual outcome:

The value is always: ALL_IN_DOMAIN_CAN_POST

No matter the value is set using groups.google.com.

Any ideas?

Thanks!

**Comment by jay0lee** [comment]
You need to set groups to "public on the Internet" in the admin console
settings:

https://support.google.com/a/answer/167097?hl=en#outside_domain

Jay

On Wed, Mar 2, 2016 at 4:04 PM Just my stuff <notifications@github.com>
wrote:

> Not sure if this issues is related with GAM or this is a bug with the
> Google Groups API.
>
> I have upgraded to the latest GAM release from http://git.io/gamreleases
> and I still have this issue.
> I am typing the command as described in the GAM Wiki at
> https://github.com/jay0lee/GAM/wiki
> I am using a Google Apps for Work, Unlimited or EDU account (Google Apps
> Standard / Free is not supported)
>
> Full steps to reproduce the issue:
> 1. Create a Google Groups under admin.google.com
> 2. Change the "Post" permission to *public* using the web interface
> groups.google.com.
> 3. Run GAM to export all the settings for that group
>
> Expected outcome:
>
> I'm expecting ANYONE_CAN_POST
>
> Actual outcome:
>
> The value is always: ALL_IN_DOMAIN_CAN_POST
>
> No matter the value is set using groups.google.com.
>
> Any ideas?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/205>.
>
-- 

Jay Lee

**Comment by josemdv** [comment]
Hi Jay, 

We don't want to open all to groups to the public. Just retrieve if the posting permission is set to public so it allows emails from external senders.

**Comment by marianohare** [comment]
You need to set this option once you do this go back to the. Group Settings there will be options to select view to public and post to public. Choose this,,,this will allow external users that are members of the grp                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Just my stuffSent: Wednesday, March 2, 2016 5:01 PMTo: jay0lee/GAMReply To: jay0lee/GAMSubject: Re: [GAM] Invalid whoCanPostMessage value (#205)Hi Jay, 

We don't want to open all to groups to the public. Just retrieve if the posting permission is set to public so it allows emails from external senders. 

—Reply to this email directly or view it on GitHub.

**Comment by jfongatyelp** [comment]
Jay & marianohare we're not interested in modifying the "allow public to post" setting, we only want to be able to get the accurate value of that setting (whoCanPostMessage in the Groups Settings API).

But I think this is indeed a Groups Settings API bug, as I can reproduce with https://developers.google.com/oauthplayground/

Steps to reproduce:
1. create a group foo@yourdomain.com
2. set posting permissions to Public in the web ui
2.5 verify you can indeed post to the group from an external address
3. Go to https://developers.google.com/oauthplayground/ and request https://www.googleapis.com/groups/v1/groups/foo%40yourdomain.com
4. Results show: <apps:whoCanPostMessage>ALL_IN_DOMAIN_CAN_POST</apps:whoCanPostMessage>

when it should be ANYONE_CAN_POST.

Doesn't seem to be A GAM bug after all.  Josemdv has already created the bug report w/ Google at https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=4346

**Comment by jay0lee** [comment]
Thanks for the description. Closing as this is not a GAM bug.
