### ISSUE TITLE
Setting vacation not working

### ISSUE THREAD

**Issue by jonasedh** [jay0lee/GAM#206]
I installed the last version and I cannot set a vacation message, it appears message "Setting vacation", but when I use command "show vacation" no vacation is set. I was forced to downgrade to version 3.61, in that version the vacation options function normally.
I hope you can help me with this issue.

**Comment by MrRoub** [comment]
I ran into this same issue and thanks @jonasedh for suggesting to downgrade. It resolved the issue for me as well.

**Comment by JochenLeppin** [comment]
In the forum somebody mentioned this fix in gam.py (enable = True / False was incorrect):

def doVacation(users):
  subject = message = u''
  if sys.argv[4].lower() in true_values:
    enable = True
  elif sys.argv[4].lower() in false_values:
    enable = False
  else:

**Comment by jonasedh** [comment]
So, @JochenLeppin... are you suggesting to write "True" with capital T or what exactly?
Thank you!

**Comment by Olivier-gPartner** [comment]
Hello All,

The latest version 3.65 seems to solve the issue. However, if I use an external txt file I have this issues: 
- ANSI txt file containing the character "é" : I have an error

`C:\gam>gam.exe user oj@*******.eu vacation on subject "Absence" file away.txt startdate "2016-03-16" enddate "2016-03-18"
Traceback (most recent call last):
  File "<string>", line 9681, in <module>
  File "<string>", line 5006, in doVacation
  File "C:\Users\jlee\Documents\GitHub\gam\src\build\gam\out00-PYZ.pyz\encodings.utf_8", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 40: invalid continuation byte`

- UTF-8 txt file containing the character "é" : It works, but then when I tried to check, I have an error:

`C:\gam>gam.exe user oj@******.eu show vacation
Traceback (most recent call last):
  File "<string>", line 9541, in <module>
  File "<string>", line 5039, in getVacation
  File "C:\Users\jlee\Documents\GitHub\gam\src\build\gam\out00-PYZ.pyz\encodings.cp850", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\ufeff' in position 106: character maps to <undefined>`

Any ideas regarding this behaviour ?

Regards,

Olivier

**Comment by jaydombroski** [comment]
@jonasedh I think @JochenLeppin is referencing this thread: https://github.com/jay0lee/GAM/issues/184
