### ISSUE TITLE
transfer drive produces a mess

### ISSUE THREAD

**Issue by djettah** [jay0lee/GAM#207]
I try to do drive transfers in a batch but the result is that some user data is moved to the target user root folder making a total mess.

Full steps to reproduce the issue:
1. gam csv ~/gam/ga_data/do_suspend_p2.1.txt gam user ~email transfer drive archive@domain.com
using gam v3.63

Expected outcome (what are you trying to do?):
Each user's data should be placed into individual folder named "user's old files"

Actual outcome (what errors or bad behavior do you see instead?):
Some folders are placed into the intended folder but some are placed to the root folder.

**Comment by jay0lee** [comment]
This isn't something GAM has any control over. GAM simply tells Google to perform the transfer, how the files are sorted in the target user's Google Drive is determined by Google's servers, not GAM.
