### ISSUE TITLE
Updating signature returns a 500 error

### ISSUE THREAD

**Issue by jaydombroski** [jay0lee/GAM#208]
Hi all, I am trying to update a signatures on my users and keep getting the following error.

`gam user jay@email.com signature "Jay"`

`gam user jay@email.com signature "Jay"
Setting Signature for jay@email.com (1 of 1)
Traceback (most recent call last):
  File "/Users/jayd/Tools/GAM/gam.py", line 9679, in <module>
    doSignature(users)
  File "/Users/jayd/Tools/GAM/gam.py", line 4928, in doSignature
    callGData(service=emailsettings, function=u'Put', soft_errors=True, data=xmlsig, uri=uri)
  File "/Users/jayd/Tools/GAM/gam.py", line 635, in callGData
    return method(**kwargs)
  File "/Users/jayd/Tools/GAM/gdata/service.py", line 1394, in Put
    media_source=media_source, converter=converter)
  File "/Users/jayd/Tools/GAM/gdata/service.py", line 1357, in PostOrPut
    'reason': server_response.reason, 'body': result_body}
gdata.service.RequestError: {'status': 500, 'body': '<?xml version="1.0" encoding="UTF-8"?>\r\n<AppsForYourDomainErrors>\r\n  <error errorCode="1000" invalidInput="" reason="UnknownError" />\r\n</AppsForYourDomainErrors>\r\n\r\n', 'reason': 'Internal Server Error'}`

This is a new google apps account, but I have followed setup instructions to the letter. I can check my oauth token, I can pull domain info. Just not update a signature. 

I am using the latest version of GAM. Any advice would be great!

Thanks
Jay

**Comment by jay0lee** [comment]
Closing this issue as signature code has been migrated off old Email Settings API to new Gmail API. Please upgrade to latest GAM 3.8. If you still see issues please open a new bug.
