### ISSUE TITLE
OAUTHFILE no longer being seen/used?

### ISSUE THREAD

**Issue by NMCPaul** [jay0lee/GAM#210]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

_Please confirm the following:_
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue. - **I have updated to 3.62 this morning via git.**
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki - **Correct.**
* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported) - **EDU**

_Full steps to reproduce the issue:_
1. Run gam.py as such: `OAUTHFILE=oauth2-employee.txt python2 ~/Apps/gam/src/gam.py info domain`
2. Then run it using another OAUTHFILE: `OAUTHFILE=oauth2-student.txt python2 ~/Apps/gam/src/gam.py info domain`
3. Even when using separate OAUTHFILEs, it's still referencing the first domain.

_Expected outcome (what are you trying to do?):_
I have two entries in my .bash_aliases file, so I can manage 2 EDU domains with one install (as directed at [https://github.com/jay0lee/GAM/wiki/OAuthKeyManagement#selecting-which-oauth-key-file-to-use](https://github.com/jay0lee/GAM/wiki/OAuthKeyManagement#selecting-which-oauth-key-file-to-use)).  They're set up as such:
`alias gam='OAUTHFILE=oauth2-employee.txt python2 ~/Apps/gam/src/gam.py'`
`alias gamstudent='OAUTHFILE=oauth2-student.txt python2 ~/Apps/gam/src/gam.py'`
I've had these aliases set up and working ever since I started using GAM.  I expect that when I specific the oauth file for separate domains, GAM would use that specific oauth file and access the correct domain.

_Actual outcome (what errors or bad behavior do you see instead?):_
GAM is no longer accessing the correct domain and will only access the first one.  I have tried using my aliases, as well as EXPORTing the variable prior to running the command, but it never uses my second domain.

**Comment by taers232c** [comment]
In each of your two oauth2-xxx.txt files, what is the value of the "hd" field?
Do you have the environment variable GA_DOMAIN set?

Ross

**Comment by NMCPaul** [comment]
In the first one, it's: nmc.edu (this is the domain that's getting defaulted to).

In the second one, it's: mail.nmc.edu.

I do not have the GA_DOMAIN environment variable set.

**Comment by taers232c** [comment]
Paul,

As you are on a Unix version of GAM, we can toss in some debugging and figure this out.
Send me a direct email at ross.scroggs@gmail.com and I'll reply with some instructions.
I've tested the 3.62 version and it's properly reading the oauth2.txt specified by OAUTHFILE; I wonder if it has something to do with sub-domains?

Ross
