### ISSUE TITLE
Gam - Admin report Errors

### ISSUE THREAD

**Issue by cdtphenix** [jay0lee/GAM#216]
Hello,

When I try a "gam print admins" to have a list of the administrators of my domain (Google Apps for Work). I have this error (on windows) : 

> Traceback (most recent call last):
  File "<string>", line 9292, in <module>
  File "<string>", line 1673, in doPrintAdmins
  File "<string>", line 1692, in orgunit_from_orgunitid
KeyError: u'id:00qxvc5l3neclo1'

Someone has the same problem ? My colleague has the same error message.

thx

**Comment by Dreyfuzz** [comment]
Check your version number (gam info). Admin roles is a more recent addition. Latest is 3.62

**Comment by cdtphenix** [comment]
No one ?

**Comment by Dreyfuzz** [comment]
Fixed in latest release!

**Comment by jay0lee** [comment]
fixed by #257
