### ISSUE TITLE
gam info group output issue

### ISSUE THREAD

**Issue by Arthur-Upwork** [jay0lee/GAM#220]
I am using "gam info group mygroup@mydomain.com" to look up the group setting, I was specifically looking for whoCanPostMessage setting. 

As I notice, results of whoCanPostMessage: ALL_IN_DOMAIN_CAN_POST for mygroup@mydomain.com is the same as for both "Public" and "all org members". 

Is there a way to differentiate those setting better on thru the GAM output?

**Comment by Arthur-Upwork** [comment]
I am using "gam info group mygroup@mydomain.com" to look up the group setting, I was specifically looking for whoCanPostMessage setting. 

As I notice, results of whoCanPostMessage: ALL_IN_DOMAIN_CAN_POST for mygroup@mydomain.com is the same as for both "Public" and "all org members". 

Is there a way to differentiate those setting better on thru the GAM output?

**Comment by jay0lee** [comment]
Please post "how do I" questions to the discussion forum:

http://groups.google.com/group/google-apps-manager

Jay
