### ISSUE TITLE
gam info group output issue

### ISSUE THREAD

**Issue by Arthur-Upwork** [jay0lee/GAM#221]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue. - yes 3.65

* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki - yes

* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported) - using google apps for work

Full steps to reproduce the issue:
1.  am using "gam info group mygroup@mydomain.com" to look up the group setting, I was specifically looking for whoCanPostMessage setting. 

Expected outcome (what are you trying to do?): I want to look up whoCanPostMessage setting, and know if it's "public" or "all org members"( which is not totally open to public)

Actual outcome (what errors or bad behavior do you see instead?): both "Public" and "all org members" shown as whoCanPostMessage: ALL_IN_DOMAIN_CAN_POST, which is not very useful in this case. 

Is there a way to differentiate those setting better on thru the GAM output?

**Comment by jay0lee** [comment]
One issue please
