### ISSUE TITLE
Issue Updating ProfilePhotos

### ISSUE THREAD

**Issue by misto1234** [jay0lee/GAM#222]
Hi All ,

Im having an issue with changing profile photos using GAM.  What i am doing is changing users photo to a standardized photo. I have had much success and the photos display correctly in the admin console and the contacts page however they are incorrect in the Gmail autocomplete field.  Any ideas?

Full steps to reproduce the issue:
1. Change your photo in Gmail manually.
2. Change photo your photo using GAM
3. Check Admin Console users area for user.
4. Type the name in gmail and wait for the autocomplete 

Expected outcome (what are you trying to do?):   Photo is the same in all areas (Gmail,contacts and admin panel)

Actual outcome (what errors or bad behavior do you see instead?): Photo is different in Gmail, contact, admin panel)

Its worth noting that this is only an issue when the user has previously changed their photo in gmail. 

Thanks!

**Comment by jay0lee** [comment]
Closing as this is not a GAM issue, it's a profile / Google+ issue (or function depending on how you look at it.
