### ISSUE TITLE
List this group in directory not working

### ISSUE THREAD

**Issue by nzuzarte** [jay0lee/GAM#223]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1. Change group setting to list the group in directory "gam update group group@domain.com show_in_group_directory true"
2. Go to https://groups.google.com/a/domain/
3. Select Browse All

Expected outcome (what are you trying to do?):
I'm trying to list all the groups in my Google Groups directory so all users can see all the groups existing in domain.

Actual outcome (what errors or bad behavior do you see instead?):
The groups modified to list in groups directory should be listed in the groups directory. The setting is actually selected, and if I edit a group and save again without modifying anything, the group begins to show in directory.

**Comment by Servovicis** [comment]
Isn't this caused by how Google handles caching rather then doing an Api call every time in browser? How long after making this change will the symptoms persist? Do they persist after logging out and/or clearing cache?

**Comment by nzuzarte** [comment]
I did the change with GAM last week. At the beginning I was thinking that this is just a propagation time "issue", but unfortunately it's not. Already tried different browsers and anonymous browsing.

**Comment by Servovicis** [comment]
So the changes exist, but don't display until another change in groups is made?

**Comment by nzuzarte** [comment]
Affirmative. I recently discovered that the group only starts to appear if I edit the "view members" option (the equivalent to "who can view membership" GAM command). Already tried to change it to all_members_can_view and change it back to all_in_domain_can_view again with GAM, but no luck :/

**Comment by nzuzarte** [comment]
When I say "edit" I mean in the google groups web interface, not in GAM.

**Comment by nzuzarte** [comment]
This issue is now solved. The problem I was having was due to propagation time, a huge propagation time (8 days) :)
