### ISSUE TITLE
Data Transfers functionality

### ISSUE THREAD

**Issue by astreeter** [jay0lee/GAM#224]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1. Run the 'gam print datatransfers' command to print all
2. Run the 'gam print datatransfers status pending'
3. Returns: ERROR: no such user <built-in function id>

Expected outcome (what are you trying to do?):
Print all of the datatransfers for the account or a list of the various statuses.

Actual outcome (what errors or bad behavior do you see instead?):
We have reproduced this error with two different credentials. This did work several times but is now not functioning at all. It is extremely inconsistent. Sometimes when I run the command with 'status failed' it works perfectly. Other status commands result in an error. The print command is not working at all right now but worked before.

**Comment by jay0lee** [comment]
Can you try this on GAM 3.8 and confirm issue still exists?
