### ISSUE TITLE
Disable date?

### ISSUE THREAD

**Issue by vonlamela** [jay0lee/GAM#225]
Hi,

This might be an enhancement request as currently when doing this command:

gam print users allfields > (target csv)

It does not include when an account was Suspended (it only shows TRUE or FALSE and by ADMIN)

Is it possible to include the timestamp when an account was disabled?

Thanks,

Von

**Comment by jay0lee** [comment]
Closing as date of disable is not provided by Google API, thus no way for GAM to add.
