### ISSUE TITLE
Calendar Sync doesn't set CalDav subscription

### ISSUE THREAD

**Issue by markaltmann** [jay0lee/GAM#227]
i have verified this error with GAM 3.65 and 3.66 (has the advanced subscription options for calendars)

Full steps to reproduce the issue:
1. gam user name.surname@domain.com add calendar test@domain.com selected true colorindex 14 reminder popup 60 reminder popup 1440 summary 'my test calendar' 
2. the calendar pops up in google calendar web view, but does not display in iCal/iOS etc.

Expected outcome (what are you trying to do?):
If i subscribe to a calendar, i expect the calendar also subscribed in CalDAV applications.
At least, if i select it as true (forced display in google calendar web view)

Actual outcome (what errors or bad behavior do you see instead?):
Calendar subscription works, but no CalDav functionality.
And here the site, where to set it manually: https://calendar.google.com/calendar/syncselect 
Is there maybe a possiblity to include it in the subscription of calendars?

**Comment by taers232c** [comment]
I can find nothing in the Calendar API that supports this desired functionality.
See: https://developers.google.com/google-apps/calendar/v3/reference/
See: https://groups.google.com/forum/#!topic/google-calendar-api/67QSu7-gz9g
