### ISSUE TITLE
Refactor GAM to be "import"able

### ISSUE THREAD

**Issue by daethnir** [jay0lee/GAM#23]
I'd like to use some of the GAM logic in separate scripts. GAM already does a lot of the hard work to set up API objects and the like.

I'd like to refactor the code to start making it reusable in new scripts.

My first step would be to pull out the object initialization into a new file, such as gamlib.py, which would be used by gam.py. Everything that ends up in gamlib.py would be something that is built to be reused - all OO, no globals, etc.

Would you like to discuss this and tell me what requirements you'd have for it to be something you're willing to merge in?

**Comment by bpabel** [comment]
I too would like gam to be an importable package.  Another idea instead of a gamlib package with a gam py2exe wrapper would be to just make "gam" the python package, and then use python entry points to declare a "gam" console script to be used much like the current gam executable.

**Comment by bpabel** [comment]
You can kind of hack it by making a small modification to gam.py and creating a custom setup.py script.

At the bottom of gam.py, move all the command line parsing logic under a `if __name__ == '__main__'` block to prevent it from executing when importing the module.  It will still work when used with py2exe.

Then create another setup script.

setup-package.py
```
from setuptools import setup, find_packages

requires = []

setup(
    name='gam',
    version='0.2',
    packages=['atom', 'gdata', 'googleapiclient', 'httplib2', 'oauth2client', 'passlib', 'uritemplate'],
    zip_safe=False,
    install_requires=requires,
    py_modules=['gam'],
)
```

Alternatively, you could specify the required packages (ie. httplib2, passlib, etc.) as dependencies using `requires`.  The only one that wouldn't install from pypi is `atom`.  That way they're installed as they're own package and can have they're versions and dependencies managed by pip/easy_install.

```
from setuptools import setup, find_packages

requires = ['gdata', 'googleapiclient', 'httplib2', 'oauth2client', 'passlib', 'uritemplate']

setup(
    name='gam',
    version='0.2',
    packages=['atom'],
    zip_safe=False,
    install_requires=requires,
    py_modules=['gam'],
)
```

Then just run the setup script.

`python setup-package.py install`

**Comment by Turin86** [comment]
Making GAM a library which the GAM cmd parser would use makes perfect sense to me. I had thought some time ago that if GAM was be like this and would raise catchable exceptions then I could even drop my own Google API client.

**Comment by benkoller** [comment]
That would be great. Ideally you move the conversion of json to "human readable" to '''of __name__=="__main__"''' as well!

**Comment by benkoller** [comment]
That would be great. Ideally you move the conversion of json to "human readable" as well!

**Comment by jkrauska** [comment]
I also would find this incredibly useful.  I end up wrapping some more complex gam runs in subprocess, and it would be so much nicer to keep it all in python.

**Comment by cbini** [comment]
This would kick some serious ass

**Comment by timbre** [comment]
Was considering writing tab-completion for GAM, but holding off in hope that this happens

**Comment by brainysmurf** [comment]
Importable module would be great. +1

**Comment by PPGDa5id** [comment]
This would be so nice.  Please and thank you!

**Comment by april-easypost** [comment]
This would be awesome.  When writing automation scripts, I hate having to either a) run the bash command, or b) re-invent the wheel by figuring out the API by hand.  +1 from me.

**Comment by jmagnusson** [comment]
Distributed through PyPI please! :-)

**Comment by bondr007** [comment]
Would really like to see this happen.

Thanks!

**Comment by bforesman** [comment]
**+1;** I am currently using `subprocess.check_call` in my python classes in order to use `gam`; I'd love to have direct access to its methods.

**Comment by LewisLebentz** [comment]
Has there been any progress with this?

Would love to be able to import this too.

**Comment by thalesvon** [comment]
Is this still a thing?

**Comment by Epy** [comment]
Helloo
sorry to bother, as this is closed and PR is merged, work seems done for this ?
Do someone have a draft of documentation for this ?

Thanks
