### ISSUE TITLE
Show Calendars Error

### ISSUE THREAD

**Issue by bschwar2** [jay0lee/GAM#231]
Confirmed
I am trying to view all calendars of a particular user to be able to give access to someone else. 

Full steps to reproduce the issue:
1. gam user (useremail) show calendars 

Expected outcome (what are you trying to do?):

A list of a users calendars

Actual outcome (what errors or bad behavior do you see instead?):

returns ERROR: invalid_client: Malformatted scope detected: 112346693690397093281
Does this for all users.

**Comment by bschwar2** [comment]
Rebuilt secrets file and oauth2 file, now getting...

Traceback (most recent call last):
  File "<string>", line 9515, in <module>
  File "<string>", line 3101, in showCalendars
  File "<string>", line 869, in buildGAPIServiceObject
NameError: global name 'scope' is not defined

**Comment by ktillman** [comment]
Having this issue as well. GAM 3.72

**Comment by jay0lee** [comment]
Please make sure you are properly creating the service account and oauth2service.json file according to Wiki instructions.
