### ISSUE TITLE
Is it possible to print members of just ONE group and not the entire domain?

### ISSUE THREAD

**Issue by 1moeups** [jay0lee/GAM#233]
Is it possible to print members of just ONE group and not the entire domain?

**Comment by benkevan** [comment]
To get information of a single group you could do the following: 

gam info group <group-name> 
or
gam.exe info group <group-name> 

if you want only the members with their role run
Windows: 
gam.exe info group <group-name> | findstr member:
Linux: 
gam info group <group-name> |  grep member:

**Comment by jay0lee** [comment]
Please post how-to questions to the discussion group.
