### ISSUE TITLE
Set delivery and posting optons when adding users to group

### ISSUE THREAD

**Issue by sheldon74** [jay0lee/GAM#234]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1.gam csv update.csv gam update group ml_test@nlesd.ca  add member ~email 

Expected outcome (what are you trying to do?):

The above command adds the correct users to the group as it should, just wondering if there is a way to set the delivery and posting options on the group for each user during this process.

thanks

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jay0lee** [comment]
There is no API to set delivery/posting options per user. Thus there's no way for gam to set them.

**Comment by dineiar** [comment]
The Google Admin FAQ have this issue registered, and the current "solution" is: "Use the group's web management interface": https://support.google.com/a/answer/6261704?hl=en

Just to link a reference for future readers, there is an idea registered on Google Cloud to solve this issue: https://www.cloudconnect.goog/ideas/5087
