### ISSUE TITLE
Cannot update user first or last name on GAM 3.7

### ISSUE THREAD

**Issue by roxasvalor** [jay0lee/GAM#238]
Full steps to reproduce the issue:
1. Set up GAM 3.7.
2. Add user with:
`gam.exe create user test.test@test.com firstname test lastname testsingle password testtesttest`
3. Run command:
`gam update user test.test@test.com lastname testmarried`

Expected outcome: The test user's last name will be be changed from "testsingle" to "testmarried".

Output on GAM 3.65:
```
gam update user test.test@test.com lastname testmarried
updating user test.test@test.com...
```

Actual outcome( on GAM 3.7 ): User's name is not changed and error below is generated.

```
Traceback (most recent call last):
  File "<string>", line 11132, in <module>
  File "<string>", line 10511, in ProcessGAMCommand
  File "<string>", line 6985, in doUpdateUser
  File "<string>", line 6470, in getUserAttributes
KeyError: u'name'
gam returned -1
```

Aside from the "firstname" and "lastname" parameters the "gam update user" command seems to work fine for other attributes.

Some things I've tried to resolve the problem:

- Different permutations of the above commands, substituting usernames and emails or changing attributes to update.
- Compared gam.py from 3.65 to 3.7 to check for possible typos - Ultimately seemed fruitless because of how different the two are.
- Completely removing GAM from my Google Apps account and setting it up from scratch.

**Comment by jay0lee** [comment]
This is fixed in source now. I'll see about pushing out a 3.71 in a few days to cover some of these issues.

**Comment by roxasvalor** [comment]
Fantastic. Awesome app and awesome support!
