### ISSUE TITLE
KeyError: u'client_email'

### ISSUE THREAD

**Issue by rinchen** [jay0lee/GAM#25]
Using

>Dito GAM 3.42 - http://git.io/gam
>Jay Lee <jay0lee@gmail.com>
>Python 2.7.8 64-bit final
>google-api-python-client 1.3.1
>Linux-3.16.0-25-generic-x86_64-with-Ubuntu-14.10-utopic x86_64

I run (with the user@domain replaced here in this ticket)

>./gam.py user test@domain.com show filelist

and I get

>Traceback (most recent call last):
>  File "./gam.py", line 7599, in <module>
>    showDriveFiles(users)
>  File "./gam.py", line 1873, in showDriveFiles
>    drive = buildGAPIServiceObject(u'drive', user)
>  File "./gam.py", line 589, in buildGAPIServiceObject
>    SERVICE_ACCOUNT_EMAIL = json_data[u'client_email']
>KeyError: u'client_email'

If I try 

> ./gam.py all users show filelist query "fullText contains 'TEST'" 

I get the same thing.

**Comment by DanielAjoy** [comment]
Same problem.

After getting oauth2service.json by following these instructions

https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile#creating-your-own-oauth2servicejson

and successfully running

gam oauth info

and

gam info domain

I tried:

gam user XXX@YYYY.org show filelist

But I got:

Traceback (most recent call last):
  File "gam.py", line 7599, in <module>
    showDriveFiles(users)
  File "gam.py", line 1873, in showDriveFiles
    drive = buildGAPIServiceObject(u'drive', user)
  File "gam.py", line 589, in buildGAPIServiceObject
    SERVICE_ACCOUNT_EMAIL = json_data[u'client_email']
KeyError: u'client_email'


What could be going on?

**Comment by rinchen** [comment]
@DanielAjoy if it's the same as my problem, your keys are out of sync. If you can regenerate them as per my comment above it should work again....at least, it did for me.
