### ISSUE TITLE
Tried to create a datatransfer request, but it failed with error “Error: invalid argument to "gam create..."

### ISSUE THREAD

**Issue by Napster158** [jay0lee/GAM#251]
Full steps to reproduce the issue:
1. Used command   gam create datatransfer <old owner> drive <new owner> [parameter <value>]
2. My version is 3.7.
3.

Expected outcome (what are you trying to do?): Trying to transfer data from old user to new user.

Actual outcome (what errors or bad behavior do you see instead?): Error.

**Comment by taers232c** [comment]
The syntax for this command is:
`gam create datatransfer <OldOwnerID> <DataTransferService> <NewOwnerID> (<Parameter> <Value>)*`
`<DataTransferService> ::= googleplus|google+|gplus|g+|googledrive|gdrive`

Please show the actual command you entered, change email addresses if necessary, but leave the form of the command intact.
