### ISSUE TITLE
ERROR: method() keywords must be strings

### ISSUE THREAD

**Issue by joselimajr** [jay0lee/GAM#252]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
* I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1.  ./gam.py info domain

Expected outcome (what are you trying to do?):
Show domain info

Actual outcome (what errors or bad behavior do you see instead?):
Google Apps Domain: xyz.br

**ERROR: method() keywords must be strings**

**Comment by jay0lee** [comment]
Please provide full details on your os and Python versions.

**Comment by joselimajr** [comment]
```
./gam.py version
GAM 3.7 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.6.0 64-bit final
google-api-python-client 1.5.0
Linux-3.0.13-0.27-default-x86_64-with-SuSE-11-x86_64 x86_64
Path: /root/GAM/GAM-3.7/src
```


```
./gam.py version
GAM 3.65 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.6.0 64-bit final
google-api-python-client 1.5.0
Linux-3.0.13-0.27-default-x86_64-with-SuSE-11-x86_64 x86_64
Path: /root/GAM/GAM-3.65/src
```

**Comment by joselimajr** [comment]
```
GAM 3.7 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.5 64-bit final
google-api-python-client 1.5.0
Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-centos-7.2.1511-Core x86_64
Path: /root/GAM-3.7/src
```
I used another computer and now it's fine. Thank you.

**Comment by jay0lee** [comment]
I am guessing this is a Python 2.6 vs 2.7 issue. Will take a look. If it's to hard tier 2.6 working we may need to check for and require 2.7.

Jay

**Comment by joselimajr** [comment]
Ok. Thanks Jay. It's ok now on Python 2.7.5.
