### ISSUE TITLE
"delegate to" command fails consistently 

### ISSUE THREAD

**Issue by ahundt74** [jay0lee/GAM#26]
Using either Gam 3.42 or older versions on either MAC or Windows with a couple of different accounts we consistently receive an error when attempting the "delegate to" command. 

Verified accounts are active and not requiring password change and that E-mail is not alias and primary address. 

All other gam commands work fine including "show delegate" on the same mailboxes. 

When a "delegate to" command is run the error received is 

Temp Error. Backing off 16 seconds......attempt 5/10
Temp Error. Backing off 32 seconds......attempt 6/10 
.
.
.
Temp Error. Backing off 60 seconds......attempt 10/10
-giving up 

These commands had worked in the past and recently became a problem about 3 or 4 weeks ago. At first error was intermittent and now command seems to fail every time in all scenarios. 

Wondering if there was any ideas on why this no longer seems to be working?

**Comment by kenrblan1901** [comment]
I am experiencing the same issue now. Even with the command doesn't generate an error, that delegation is not added.

**Comment by ahundt74** [comment]
The problem for me went away on it's own. I had this for about a week and then everything started working as normal again. No changes that I made to correct - it just seemed to fix itself. Have not had a problem since. Tested just now and still working for me without those errors. 

Sorry - wish I had more helpful info for you.

**Comment by daubneyi** [comment]
This seems to be an intermittent issue for me on the latest edition and the one prior.  I find it works eventually.
