### ISSUE TITLE
Vacation responder set by GAM has wrapped lines.

### ISSUE THREAD

**Issue by kmoore-grnds** [jay0lee/GAM#263]
With GAM 3.65 we're seeing vacation messages working again thanks to  @taers232c,however we're noticing that the message text is auto-wrapping lines.  When the same response message is set manually from the google GUI as a user the lines do not wrap.

e.g. Manually set
```
Out of Office: Re: Vacay Test
Me <me@domain.com>	Tue, Aug 30, 2016 at 5:25 PM
To: someguy@gmail.com
I will be out of the office 8/23.  If you have a support need or request, please email helpdesk@domain.com and someone from the IT or Operations team will be able to handle your request.
-- 
```

Set via GAM:

```
Out Of Office: Re: Ignore - vacay test
User <user@domain.com>	Tue, Aug 30, 2016 at 4:36 PM
To: me@domain.com
Thank you for your message. I will be away from the office for an
extended time and I will not be able to respond.
Please contact General Counsel Some Guy
(lawyer@domain.com)

Kind Regards,
User
```

To replicate:

```bash
#!/bin/bash

VacaySubject='You have reached an inactive account.'
VacayMessage_l1='Thank you for your email, you have reached an account that is not monitored and is no longer active.'
VacayMessage_l2='Here is a long line of text that should just auto wrap. Please contact the Support Helpdesk for further assistance. <support@domain.com>'

UserName=$1
VacayMessage="${VacayMessage_l1}\n${VacayMessage_l2}\n\n"

# Get today's date and year +1 date for start and end of vacay responder
Today=`date +%F`
NextYear=`date -v+1y +%F`

gam.py user "${UserName}" vacation on subject "$VacaySubject" message "$VacayMessage"  startdate $Today enddate $NextYear
```

**Comment by taers232c** [comment]
Kevin,

What do you see when you say: gam user@domain.com show vacation

Ross

**Comment by taers232c** [comment]
Kevin,

Here is the data that Google sends back when I do a show vacation. You'll see that the message is exactly as your script specified; there are no extra line breaks.

Ross

`{u'responseSubject': u'You have reached an inactive account.', u'responseBodyPlainText': u'Thank you for your email, you have reached an account that is not monitored and is no longer active.\nHere is a long line of text that should just auto wrap. Please contact the Support Helpdesk for further assistance. <support@domain.com>\n\n', u'restrictToContacts': False, u'enableAutoReply': True, u'startTime': u'1472540400000', u'endTime': u'1504076400000', u'restrictToDomain': False}
`

**Comment by kmoore-grnds** [comment]
Ross,

It looks correct in the return from `show vacation`. i.e. full untruncated
or wrapped strings.

```bash
MyMac:~$ gam user beverly.thornton show vacation
User beverly.thornton@grandrounds.com
 Enabled: true
 Contacts Only: false
 Domain Only: false
 Subject: Out Of Office:
 Message: Thank you for your message. I will be away from the office for an
extended time and I will not be able to respond.
Please contact General Counsel David Thompson (
david.thompson@grandrounds.com) or Associate Counsel Beth Jacobson (
beth.jacobson@grandrounds.com) if your message r

Kind Regards,
Beverly Thornton
 Start Date: 2016-08-30
 End Date: 2017-08-30
```

But this is what I'm seeing when I email a user and get the responder:

[image: Inline image 1]




Kevin Moore /  Sr Manager IT Operations & Facilities

Grand Rounds

Direct: 415-233-4352 / Fax: 1-866-435-4269

360 3rd St Suite 425, San Francisco, CA 94107

http://www.grandrounds.com <https://www.facebook.com/GrandRoundsHealth>
<https://www.linkedin.com/company/grandrounds>

**Comment by taers232c** [comment]
Kevin,

I see exactly what you do in the email response, I'm just showing that gam sent exactly what you specified.

But never mind, I have the answer. The vacation API will take plain text or html.
You can say: gam user foo@domain.com vacation on subject "Blah" html message "blah" ...
And exactly the right thing happens.

Here's the return from Google:
`{u'responseSubject': u'You have reached an inactive account.', u'restrictToContacts': False, u'enableAutoReply': True, u'startTime': u'1472540400000', u'endTime': u'1504076400000', u'responseBodyHtml': u'Thank you for your email, you have reached an account that is not monitored and is no longer active.<br>Here is a long line of text that should just auto wrap. Please contact the Support Helpdesk for further assistance. <br><br>', u'restrictToDomain': False}`
The key is responseBodyHtml here but responseBodyPlainText in the previous case.
But now, the sender gets the auto wrapped response.

Check it out, let me know what your see

Ross

**Comment by taers232c** [comment]
San Francisco! I'm over in Oakland.

**Comment by kmoore-grnds** [comment]
I'm not having luck w/ html under GAM 3.65 - has this been updated in 3.7x?

```
gam.py user "${UserName}" vacation on subject "$VacaySubject" html message "$VacayMessage"  startdate $Today enddate $NextYear
    
ERROR: html is not a valid argument for "gam <users> vacation"

```

**Comment by kmoore-grnds** [comment]
NVM - I just pulled the 3.71 source and see the new feature.  I'll close this out.
