### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 1446

### ISSUE THREAD

**Issue by josemdv** [jay0lee/GAM#270]
Please confirm the following:
I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.   Run the following command in powershell:
`gam user foo@bar.com signature "."` 

Expected outcome (what are you trying to do?):

Signature updated for user foo@bar.com

Actual outcome (what errors or bad behavior do you see instead?):

> Setting Signature for foo@bar.com (1/1)
> Traceback (most recent call last):
>   File "<string>", line 11234, in <module>
>   File "<string>", line 11183, in ProcessGAMCommand
>   File "<string>", line 6244, in doSignature
>   File "<string>", line 1019, in callGAPI
>   File "<string>", line 971, in checkGAPIError
>   File "<string>", line 459, in stderrErrorMsg
>   File "encodings\cp850.py", line 12, in encode
> UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 1446: character maps to <undefined>
> gam returned -1

This doesn't really happen with all the users. I tried with foo2@bar.com and it's working fine (same command). If I try with foo21@bar.com I'm getting the same error. The permissions level for all those account are exactly the same.

**Comment by josemdv** [comment]
I edited the bug report with more information.

**Comment by jay0lee** [comment]
Can you test this on GAM 3.8 and confirm the issue still exists?
