### ISSUE TITLE
Uploading docx file and converting to native Gdocs format issue

### ISSUE THREAD

**Issue by BradGraham** [jay0lee/GAM#271]
using Gam 3.71 

Full steps to reproduce the issue:
1.  From (https://github.com/jay0lee/GAM/wiki/GoogleDriveManagement#updating-drive-files-for-users)

Example command:  gam user jjones@acme.com add drivefile localfile MyRamblings.docx convert drivefilename "My Ramblings"
2.  The file is uploaded, but will render as a downloadable file (not a Google Doc).
3.  Changing the command to "gam user jjones@acme.com add drivefile localfile MyRamblings.docx convert drivefilename "My Ramblings.docx"  corrects the file format, but leaves the ".docx" on the file name.

Expected outcome (what are you trying to do?):
 Upload a docx file, convert it to native Google Docs and give it a "pretty" name (remove the .docx from the name).

The file can be renamed via the file ID.

**Comment by taers232c** [comment]
Brad,
If you don't want the .docx extension, don't include it in drivefilename.
gam user jjones@acme.com add drivefile localfile MyRamblings.docx convert drivefilename "My Ramblings" 

Ross

**Comment by BradGraham** [comment]
Yes - I understand.   That's how it should work per the documentation.  Unfortunately, the command does not render a native Google doc unless you do add the .docx extension.  See number 2 above.  If the extension is left off the target name, a binary file is rendered, not a Google doc.

The only way I can get this work is to leave the extension on the target document name, let it convert and then rename inside Drive as a second step.
