### ISSUE TITLE
ERROR: 1801 - Invalid value

### ISSUE THREAD

**Issue by plyko** [jay0lee/GAM#272]
Full steps to reproduce the issue:
1. command:
 C:\GAM>gam user pavel@xyz.cz language en-US

Setting the language for pavel@xyz.cz to en-US (1/1)

Expected outcome (what are you trying to do?):
change language to en

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: 1801 - Invalid value

**Comment by fleveque** [comment]
I'm getting similar issues with v3.72, but it seems it's working on some accounts and failing on others...

`gam all users language en-GB`

> Setting the language for xxxxxxxx to en-GB (1/51)
> Setting the language for yyyyyy to en-GB (2/51)
> 
> ERROR: 1801 - Invalid value
> ...
> ...

**Comment by jay0lee** [comment]
Closing as this is related to the deprecated (and removed in GAM 3.8) Email Setting API.
