### ISSUE TITLE
Downloading drive files to location does not work on linux

### ISSUE THREAD

**Issue by jessecrayston** [jay0lee/GAM#273]
I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki: 
gam user <username>|group <groupname>|ou <ouname>|all users get drivefile [id <file id> | query <query>] [format <openoffice|microsoft|pdf>] [targetfolder <local path>]

Full steps to reproduce the issue:
1. In a linux environment
2. Try to download drive files to a specific location ie:
./GAM/src/gam.py user jsmith@acme.com get drivefile query "'me' in owners" format microsoft /home/jsmith

Expected outcome (what are you trying to do?):
Drive files should be downloaded to /home/jsmith

Actual outcome (what errors or bad behavior do you see instead?):
Drive files are downloaded to ./GAM/src/

Side note:
The wiki suggests that when no targetfolder arg is set, drive files will be downloaded to c:\jsmith-files despite linux not having a "C:" and the drive files are actually downloaded to the scripts location.

**Comment by taers232c** [comment]
The command should be:
./GAM/src/gam.py user jsmith@acme.com get drivefile query "'me' in owners" format microsoft targetfolder /home/jsmith
targetfolder is a keyword indicating that the next argument is the path

**Comment by jessecrayston** [comment]
Thanks that was it :)
