### ISSUE TITLE
ERROR: 404: Resource Not Found: resource.fields[-1].formula.operand[0].custom_field - notFound

### ISSUE THREAD

**Issue by alex-deneuvillers** [jay0lee/GAM#274]
I have the following issue when trying to update a custom field in my domain : 

`ERROR: 404: Resource Not Found: resource.fields[-1].formula.operand[0].custom_field - notFound`

Here is the command I use : 

`gam update schema Intranet field Business-unit-orga type string endfield field Business-unit-activite type string endfield field site-administratif type string endfield field site-geographique type string endfield field Pays type string endfield field Pays-activite type string endfield field Phone type phone endfield field Phone-mobile type phone endfield field Phone-extension type string endfield field Languages type string endfield field BU-et-pays type string endfield field site-organisationel type string endfield field BU-et-site type string endfield`

When I do `gam info schema Intranet` :

`Schema: Intranet                         
 schemaId: AeHCcMB_Qhy8z7eYQrcVRA==      
 Field: Business-unit-orga               
  fieldId: -VMw8Z5xSgafMv0ITxpKSA==      
  fieldType: STRING                      
 Field: Business-unit-activite           
  fieldId: WFQGvBsHQhyq3k7vlwKVLw==      
  fieldType: STRING                      
 Field: site-administratif               
  fieldId: D9eqR22KT_eqqBb6rhnyrQ==      
  fieldType: STRING                      
 Field: site-geographique                
  fieldId: Qv6r-cxWQOqPdCM-wdp8MQ==      
  fieldType: STRING                      
 [...]                   
 `

I'm on windows 7 with the latest version of GAM.
I tried with a colleague, he got the same issue.

EDIT : 

I tried with a new schema, with exactly the same command : the command succeed.

**Comment by jay0lee** [comment]
Closing since you reported as successful.
