### ISSUE TITLE
gam on CentOS-6 doesn't like python-2.6?

### ISSUE THREAD

**Issue by jhaar** [jay0lee/GAM#276]
Full steps to reproduce the issue:
1. installed gam
2. ran "gam report users"
3. watched all the nice data downloading
4. gam failed on CSV conversion with

Got 1 users
Traceback (most recent call last):
  File "/usr/local/google-gam/gam.py", line 11234, in <module>
    sys.exit(ProcessGAMCommand(sys.argv))
  File "/usr/local/google-gam/gam.py", line 10894, in ProcessGAMCommand
    showReport()
  File "/usr/local/google-gam/gam.py", line 1401, in showReport
    writeCSVfile(csvRows, titles, u'User Reports - %s' % try_date, to_drive)
  File "/usr/local/google-gam/gam.py", line 8730, in writeCSVfile
    writer.writeheader()
AttributeError: DictWriter instance has no attribute 'writeheader'

Expected outcome (what are you trying to do?):

Looks desperately close to working. I was wondering if there's a different way of accessing the data for older systems like CentOS/Redhat 6?

gam --version

GAM 3.71 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.6.6 64-bit final
google-api-python-client 1.5.1
Linux-2.6.32-504.1.3.el6.centos.plus.x86_64-x86_64-with-centos-6.8-Final x86_64

**Comment by jhaar** [comment]
Wow I just commented out "writer.writeheader()" and now it works fine - only the CSV header was lost. 

Actually, I replaced that line with

print "#"+",".join(titles)

and that seems to work just as well

**Comment by jay0lee** [comment]
Python 2.6 is anciently old and I'm not interested in supporting it anymore. In fact, I plan to start moving to Python 3 soon.

Can you try using the attached, compiled version of GAM? It was built with pyinstaller on CentOS 6 and using Python 2.7.12 from https://ius.io/. The binary works for me on CentOS 6 as well as Ubuntu 12.04.

Or if you prefer you can just install Python 2.7.12 from isu.io and use that.

Jay
[gam.zip](https://github.com/jay0lee/GAM/files/511577/gam.zip)

**Comment by jhaar** [comment]
No joy - keeps prompting to initialize it. Even when I run it from the directory I have my working gam in. I think it's a packaging issue - maybe it chdir's to a /tmp/XXX directory and therefore doesn't have creds/etc?

The binary ran - but I didn't get as far as to make it tickle the CSV issue

**Comment by jay0lee** [comment]
Sorry, can you clarify what the actual errors you saw were?

**Comment by jhaar** [comment]
My mistake. If I was in the directory from which ./gam.py works, and then ran /tmp/gam (because that's where I put the binary), then it doesn't work - I get prompted to initialize OAUTH.

However, if I copy the binary into the same directory, then ./gam.py and ./gam work just fine. 

So I'd say that is a workable solution for CentOS-6. :-)
