### ISSUE TITLE
wiki on "gam report mobile" claims IP field exists when it doesn't

### ISSUE THREAD

**Issue by jhaar** [jay0lee/GAM#277]
Full steps to reproduce the issue:
1.  ran "gam report mobile"
2. got full dump of mobile devices
3. none contained IP fields

Expected outcome (what are you trying to do?):
your wiki says you can search by IP, but I see no evidence that is an actual option

In fact, my own experiments with the SDK makes me think Google doesn't provide that data. Same thing goes for "token" reports - no IP addresses.

I'd love to be wrong on this, but I think your wiki may need correcting?

**Comment by jay0lee** [comment]
you're misunderstanding the IP argument, the IP argument allows filtering down the results based on the acting IP. It does not allow reporting the IP of mobile devices.
