### ISSUE TITLE
gam print users | Not Working

### ISSUE THREAD

**Issue by VipulSoni22** [jay0lee/GAM#278]
The issue tracker is for reporting product deficiencies. 

I am running the following and get the following errors.

**[myntra@gapptest src]$ gam print users
Getting all users in Google Apps account (may take some time on a large account)...
Got 10 users: admin@dev.myntra.com - vinoth@dev.myntra.com
Traceback (most recent call last):
  File "gam.py", line 11234, in <module>
    sys.exit(ProcessGAMCommand(sys.argv))
  File "gam.py", line 10778, in ProcessGAMCommand
    doPrintUsers()
  File "gam.py", line 8971, in doPrintUsers
    writeCSVfile(csvRows, titles, u'Users', todrive)
  File "gam.py", line 8730, in writeCSVfile
    writer.writeheader()
AttributeError: DictWriter instance has no attribute 'writeheader'
[myntra@gapptest src]$** 

* I am using **GAM 3.71 on Linux system with CentOS**

Full steps to reproduce the issue:
1. gam print users

Expected outcome (what are you trying to do?): print the list of all users.

Actual outcome (what errors or bad behavior do you see instead?): It seems that there is an error in gam.py script.

Troubleshooting steps did so far:

- Installed/Uninstalled GAM 3.71 twice, still the same issue.

**Comment by jay0lee** [comment]
CentOS 6 uses Python 2.6 which is anciently old and no longer supported. Try using the new binary Linux release:

https://github.com/jay0lee/GAM/releases/download/v3.71/gam-3.71-linux-x86_64.tar.xz
