### ISSUE TITLE
Error with updating users firstname and lastname 

### ISSUE THREAD

**Issue by Mugulane** [jay0lee/GAM#279]
Upgraded to Gam 3.71

**Full steps to reproduce the issue:**
1. From https://github.com/jay0lee/GAM/wiki/GAM3DirectoryCommands#update-and-rename-a-user

**Example command:** gam update user dummy@tktk.ee firstname "TTK" lastname "Dummy"
and also tried without quotationmarks.

**Expected outcome (what are you trying to do?):**
Tried to rename one users first and lastname

**Full steps to reproduce the issue:**
1.  gam update user user@yourdomainname.com firstname "TTK" lastname "Dummy"

**Expected outcome (what are you trying to do?):**
A text "updating account for dummy@tktk.ee" and users renamed firstname and lastname

**Actual outcome (what errors or bad behavior do you see instead?):**
Traceback (most recent call last):
  File "/home/mugulane/gam/gam.py", line 11132, in <module>
    sys.exit(ProcessGAMCommand(sys.argv))
  File "/home/mugulane/gam/gam.py", line 10511, in ProcessGAMCommand
    doUpdateUser([sys.argv[3],], 4)
  File "/home/mugulane/gam/gam.py", line 6985, in doUpdateUser
    body, admin_body = getUserAttributes(i, updateCmd=True)
  File "/home/mugulane/gam/gam.py", line 6467, in getUserAttributes
    body[u'name'][u'givenName'] = sys.argv[i+1]
KeyError: u'name'

**Comment by Mugulane** [comment]
updated to GAM 3.72 and still same error

**Comment by jay0lee** [comment]
Are you sure you successfully updated your GAM install? No one else is reporting this issue but it did exist in an older version. I suspect you've not completely overwritten the old version with GAM 3.72.

Jay

**Comment by Mugulane** [comment]
Thank you. That was the case. It wasn't upgraded properly. 
I suggest to add one paragraph to wiki of updating GAM.
