### ISSUE TITLE
Linux binary (3.72) - Unable to set Sendas

### ISSUE THREAD

**Issue by jkrizajku** [jay0lee/GAM#287]
I am running the new Linux binary ver. 3.72 on CentoOS 6.5.

When I try to add a Send As to an user I get the error message "User: xxx@xxx.xxx, Does not exist"

The command that I ran was "gam user xxx@xxx.xxx sendas testgroup@xxx.xxx "Test Group Test"".

I tried with multiple users that exist and groups that exist.

This command was working before I upgraded to this version. The old version was 3.61.

I also copied and pasted the command and tried on a Windows box with version 3.5.

Thank you,

**Comment by jkrizajku** [comment]
I don't know if this should go under a different issue, but I just noticed the show command does not work either.

"gam user xxx@xxx.xxx show imap" or anything like pop, vacation, signature.

The  error message is "User: xxx@xxx.xxx, Does not exist"

I also get the same error message if I try to set one of the items above.

"gam user xxx@xxx.xxx imap on"

**Comment by jay0lee** [comment]
GAM 3.7+ uses the new Gmail Settings API for these settings. You need to authorize your service account to make these changes. Run through the steps at:

https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile#authorize-the-api-scopes-for-use-with-gam-in-the-admin-console

again.
