### ISSUE TITLE
Please help with "ERROR: 404: Not Found - notFound" message

### ISSUE THREAD

**Issue by Az0101** [jay0lee/GAM#295]
Please confirm the following: Yes
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam user *** delete forwardingaddress ***
2. 
3. 

Expected outcome (what are you trying to do?): remove forwarding from a users account

Actual outcome (what errors or bad behavior do you see instead?):  

Deleting forwarding Address ***@***.com for ***@***.com

ERROR: 404: Not Found - notFound

**Comment by jay0lee** [comment]
Can you start a post in the group with the exact command you are running? This doesn't sound like a bug / issue, just getting the command formatting right.
