### ISSUE TITLE
GAM sync seems to be working like update

### ISSUE THREAD

**Issue by peng1can** [jay0lee/GAM#30]
We've tried this on multiple machines - it seems that at some point
gam update group xx@xx.com sync user file name.txt
changed behavior.  It used to work as documented, but after a recent update, it now will overwrite the status of existing members and make existing managers into users - much like the update command.

This has broken our global mailing lists.  Any help would be appreciated.  Thanks!

**Comment by jay0lee** [comment]
Closing as this is pretty old and there have been updates to sync. If you can still reproduce the issue on the latest release of GAM feel free to re-open.
