### ISSUE TITLE
A way to update non primary email adresses signature ?

### ISSUE THREAD

**Issue by YannickBiet** [jay0lee/GAM#301]
Using "gam all users signature" we can setup the default signature to our GSuite users
but if they have multiple accounts (like the default in .com and an alias in .fr), we can't programatically setup the .fr alias account signature ?

Am I wrong ?

Any help appreciated

**Comment by jay0lee** [comment]
Please post "how do I" or "can I"? questions to the discussion group:

https://groups.google.com/forum/?nomobile=true#!forum/google-apps-manager
