### ISSUE TITLE
New Lines not preserved in Notes field of ChromeOS Devices

### ISSUE THREAD

**Issue by seanatcesa** [jay0lee/GAM#307]
The "Notes" field under ChromeOS device management in the G Suite Admin Console allows for linebreaks, however the GAM command used to edit this field does not.  The string "\n" is taken literally by the notes parameter when performing a gam update cros command.  Linebreaks are especially helpful in the notes field.

An example of a command where this might be used:
`gam update cros 647cf127-ab85-4c2b-b07e-63ad1b705c19 notes "Screen broken 2016-09-15\nSent out for repair 2016-09-16.  See Ticket #1234.\nReturned to service 2016-09-22"`

**Full steps to reproduce the issue:**
1. Run a command to update the notes field containing "\n" for line breaks, such as our example above
2. View the Notes field of the record edited in the G Suite Admin Console under Device Management>Chrome Devices>{Serial number of the device}

**Expected outcome:** The notes should appear with linebreaks where "\n" was entered

> Screen broken 2016-09-15
> Sent out for repair 2016-09-16.  See Ticket #1234.
> Returned to service 2016-09-22

**Actual outcome:** The full notes string is shown, including "\n" which are interpreted literally, with no linebreaks.

> Screen broken 2016-09-15\nSent out for repair 2016-09-16.  See Ticket #1234.\nReturned to service 2016-09-22

**Comment by jay0lee** [comment]
fixed by #308 and GAM 3.8 release.
