### ISSUE TITLE
GAM.wiki - cannot clone to desktop

### ISSUE THREAD

**Issue by ur006327** [jay0lee/GAM#31]
Tried to clone the GAM.wiki to GitHub Desktop but it says that the repository is invalid.  The URL being used is github-windows://openRepo/https://github.com/jay0lee/GAM.wiki

Any ideas how to get this cloned to the desktop?dir

**Comment by Drolla** [comment]
I encountered the same problem with the wiki of my project.

**Comment by Loycifer** [comment]
Me too.
