### ISSUE TITLE
Bug in doCalendarDelACL()

### ISSUE THREAD

**Issue by glenusmaximus** [jay0lee/GAM#32]
doCalendarDelACL() has a bug with setting "entity" to the wrong argument (line 1327, GAM 3.42). It is using argv[4] but should use argv[5]. The effect of this is to use the keyword "user" rather than the actual entity. This results in attempting to delete the ACL for "user@domain" and effectively causing the delete function to not work (with the possible side effect of deleting the ACL for user@domain if such a user exists and has an ACL).

The fix is to change line 1327 to
  entity = sys.argv[5].lower()

**Comment by jay0lee** [comment]
fixed in master and will be included in next release:

https://github.com/jay0lee/GAM/commit/e37e6935c48fd42818a1b9e7bf8526f829183fcf
