### ISSUE TITLE
Bug in doCalendarAddACL

### ISSUE THREAD

**Issue by glenusmaximus** [jay0lee/GAM#33]
doCalendarAddACL() has a bug in the "except KeyError:" at line 1311 (GAM 3.42). This appears to be for picking up an exception when there's no 6th argv. However, sys.arg is a sequence, not a dictionary so the exception should be IndexError. The effect of the bug is that when attempting to use "domain" for add, update or delete, GAM fails with an error. Note that this is a separate bug to Issue 32.

The fix is to change line 1311 to
    except IndexError:

**Comment by jay0lee** [comment]
fixed in master and will be included in next release:

https://github.com/jay0lee/GAM/commit/e37e6935c48fd42818a1b9e7bf8526f829183fcf
