### ISSUE TITLE
Gapps for government

### ISSUE THREAD

**Issue by jamenlang** [jay0lee/GAM#349]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. use gam
2. check user info
3. see that licenses do not include google apps for government

Expected outcome (what are you trying to do?):
remove users from google apps for government 

Actual outcome (what errors or bad behavior do you see instead?):
nothing shows up except the supported gam license
![nolicenses](https://cloud.githubusercontent.com/assets/6394127/20571546/23bca24c-b165-11e6-8166-e34341043a0d.png)
s

**Comment by jay0lee** [comment]
Thanks, I don't have a GAfG test domain so I don't know which license type these even are. What does the output of:

gam print licenses

show? It should show some license type for some users like Google-Apps-For-Gov or similar.

Jay

**Comment by jamenlang** [comment]
Google-Apps-For-Government

**Comment by jay0lee** [comment]
fixed by #362
