### ISSUE TITLE
Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) 

### ISSUE THREAD

**Issue by StevenOstergren** [jay0lee/GAM#352]
When I upgraded to GAM 3.51 on Windows I got the SSL: CERTIFICATE_VERIFY_FAILED error.
I was able  to get it working by putting the cacert.pem + the additional certificate in the same folder as GAM. So I know that the issue is our firewall.

I upgrading to GAM 4.03 it again is getting the SSL: CERTIFICATE_VERIFY_FAILED error.
The same technique does not work.
I assume the new GAM is specifying a specific folder of where to find the certificates.
I think this certificate folder should be documented or the search in the local folder like GAM 3.51 should have been maintained for users having firewall issues.

**Comment by jay0lee** [comment]
The cacert.pem file is embedded in gam.exe in later releases and cannot be edited. You can disable the cert check by creating a file called noverifyssl.txt in the same folder as gam.exe.

**Comment by jconnor2209** [comment]
jay0lee I had a question regarding this issue since we are also experiencing something similar. If we do disable the cacert.pem file, does this disable SSL in any manner or cause a security risk? Thank you for your time!

**Comment by StevenOstergren** [comment]
I was able to get with our firewall admins.
They said the traffic was using ssh.

**Comment by jay0lee** [comment]
GAM does not make SSH connections.

**Comment by StevenOstergren** [comment]
Traffic was using ssl.

**Comment by jay0lee** [comment]
Correct, GAM uses port 443 SSL / TLS HTTPS connections.

**Comment by askvictor** [comment]
I understand that it's possible just skip SSL verification by creating the text file, but a more secure solution would be to either honour the OS's SSL root certs, or allow the user to install additional certs. Given that GAM is most likely used in corporate and school environments, these are places that are more likely to have a custom MITM SSL cert to monitor traffic.
