### ISSUE TITLE
Unable to finish GAM authentication

### ISSUE THREAD

**Issue by ragimiri** [jay0lee/GAM#355]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. 
2.
3.

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by ragimiri** [comment]
I am trying to setup new GAM project. All works OK, but final step "c)  Continue to authorization" always failed with this error:

Error: invalid_client

The OAuth client was not found.
Request Details

    login_hint=MY_ADMIN_EMAIL
    access_type=offline
    scope=email https://www.googleapis.com/auth/admin.directory.group https://www.googleapis.com/auth/admin.directory.orgunit https://www.googleapis.com/auth/admin.directory.user https://www.googleapis.com/auth/admin.directory.device.chromeos https://www.googleapis.com/auth/admin.directory.device.mobile https://apps-apis.google.com/a/feeds/emailsettings/2.0/ https://www.googleapis.com/auth/admin.directory.resource.calendar https://www.googleapis.com/auth/apps.groups.settings https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/admin.reports.audit.readonly https://www.googleapis.com/auth/admin.reports.usage.readonly https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/apps.licensing https://www.googleapis.com/auth/admin.directory.user.security https://www.googleapis.com/auth/admin.directory.notifications https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/admin.directory.userschema https://www.googleapis.com/auth/classroom.rosters https://www.googleapis.com/auth/classroom.courses https://www.googleapis.com/auth/classroom.profile.emails https://www.googleapis.com/auth/classroom.profile.photos https://www.googleapis.com/auth/classroom.guardianlinks.students https://www.googleapis.com/auth/cloudprint https://www.googleapis.com/auth/admin.datatransfer https://www.googleapis.com/auth/admin.directory.customer https://www.googleapis.com/auth/admin.directory.domain https://www.googleapis.com/auth/admin.directory.rolemanagement
    response_type=code
    redirect_uri=urn:ietf:wg:oauth:2.0:oob
    client_id=MY_CLIENT_ID

I am logged in as admin, I tried nobrowser.txt, but no succes. I also tried to delete and recreate project, but still nothing.

**Comment by jay0lee** [comment]
Please post to the discussion group:

https://git.io/gam-group

**Comment by ragimiri** [comment]
Fix was simple - when copying client ID from Google, there was leading and trailing spaces. GAM accepted them as another ID. So I removed them manually from client_secrets.json. :)
