### ISSUE TITLE
CURL install has an input bug

### ISSUE THREAD

**Issue by bhuddleston** [jay0lee/GAM#356]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. YES
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki YES

Full steps to reproduce the issue:
1. in a Mac Terminal run "curl -s -S -L https://git.io/install-gam | bash"

Expected outcome (what are you trying to do?):

- Install GAM

Actual outcome (what errors or bad behavior do you see instead?):

- Asking for input from the terminal in a curl piped install script will not get the correct readline and will endlessly cycle with no input.  When I run the CURL install command I get 1000's of these prompts "Please answer yes or no.". 

![screen shot 2016-12-08 at 10 28 16 am](https://cloud.githubusercontent.com/assets/1291628/21022321/13535428-bd31-11e6-88f9-24d065a9e378.png)

ANSWER:  We have found that the best way to run a curl piped install that requires user input is to run it this way: 

` bash -c "$(curl -s -S -L https://git.io/install-gam)"`

**Comment by jay0lee** [comment]
This was a change made by @daethnir that seems to have broken Macs. I've reverted the blog to the old install command:

bash <(curl -s -S -L https://git.io/install-gam)

Jay
