### ISSUE TITLE
print users firstname lastname is not working

### ISSUE THREAD

**Issue by moore1emu** [jay0lee/GAM#36]
the command print users firstname 
pulls back first, full, and last name
any combinations of the name options pulls backs all three columns

**Comment by medina** [comment]
To get any of those fields, the user `name` value is queried, which populates an object like:

```
{u'name': {u'familyName': u'Bach',
           u'fullName': u'Johann Sebastian',
           u'givenName': u'Johann Sebastian'},
 u'primaryEmail': u'j.s.bach@example.com'}
```

By the time the output is printed with `attributes.append(flatten_json(user))`, `gam`'s lost track of what it was you were looking for, so you get back everything,

```
primaryEmail,name.familyName,name.fullName,name.givenName
```

That's the "why", not sure it helps any :-)
