### ISSUE TITLE
GData Admin Settings API shut down

### ISSUE THREAD

**Issue by ismgr** [jay0lee/GAM#361]
I received the below from Google today - will this hurt GAM ?

Hello G Suite Administrator,

We found that one or more applications being used in your organization is using the GData Admin Settings API, which is in the process of being deprecated and will be shut down on October 30, 2017. Where possible, we have contacted all developers who own applications using the GData Admin Settings API, and provided the appropriate guidance for migration to the Google Admin SDK. However, to ensure uninterrupted service, we recommend reaching out to any developer of the app(s) used in your organization to confirm that they migrate to Google Admin SDK within the specified timeframe.

Background

In 2013, we launched the G Suite Admin SDK, and in 2014, we announced that several outdated G Suite Admin APIs would be deprecated and shut down in April 2015 as a result. In our effort to remove older, less-used functionality, we’re now announcing the deprecation of the GData Admin Settings API.

The G Suite Admin SDK enables developers to build customized administrative tools for organizations that use G Suite. The new Admin SDK consolidates many of the existing domain APIs into a new uniform structure, and introduces new functionality with the Directory API and Reports API.

GData API Functionality in Admin SDK, Directory API

The new Directory API in Admin SDK provides a simple, RESTful interface to support all basic operations required to query and manage users, groups, organizational units, Chromebooks, and mobile devices.

Some GData API functionality will find a replacement in the Directory API, while other features will be discontinued.

What does this shutdown mean for your app between now and October 30, 2017?

While applications using the GData Admin Settings API will continue to work until October 30, 2017, we recommend that you migrate your project to use Google Admin SDK before then to ensure uninterrupted service.

**Comment by jay0lee** [comment]
Only if you haven't upgraded. GAM 4.0 and above do not use any GData APIs. Upgrade to the latest and you have nothing to worry about.
