### ISSUE TITLE
Feature Request: Allow querying/updating of a user account via Employee ID

### ISSUE THREAD

**Issue by bondurantdt** [jay0lee/GAM#394]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Currently GAM's method of user lookup is only via email address/account.  It would be very helpful if there was a possibility to lookup via the employeeID schema field in GAM.

An example: gam info user employeeID 4111

which would query the default schema field of Employee Details.employeeID and return the same info as gam info user <emailaddress@domain.com>

Thanks!

**Comment by taers232c** [comment]
David,

gam supports this: gam query "<Schema>.<Field>=<Value>" ...
Ex: gam query "Employee Details.employeeID=4111" show filelist
Unfortunately, info is not available.

Send me an email directly and I'll let you know what other options you have.

Ross
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
You can use something like:

gam print users query EmployeeData.EmployeeID=4111 | gam csv - gam info user ~primaryEmail

not the easiest to remember but you can put it in a script to make it simpler to call.

Jay
