### ISSUE TITLE
Gam Bulk Update Groups - System error

### ISSUE THREAD

**Issue by bhuddleston** [jay0lee/GAM#40]
I've upgraded to (GAM 3.42) I've tested access successfully with:

```
$ gam update group it@our_domain.com maxMessageBytes 25M
updated group it@sumologic.com
```

But when I try to do a bulk operation (via a pipe), I get this output:

```
$ gam print groups | gam update group ~Email maxMessageBytes 25M
Retrieving All Groups for Google Apps account (may take some time on a large account)...
Error 400: A system error has occurred - invalid

Got 159 groups: 305main@our_domain.com - zuora-notifications-group@sour_domain.com
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
$
```

**Comment by jay0lee** [comment]
This is not a bug. Please post your question on the group:

https://groups.google.com/forum/#!forum/google-apps-manager

**Comment by bhuddleston** [comment]
Sorry about that, wasn't sure what it would fall under.  

I'll post it to the group now.


----
Brian Huddleston
Open I.T. Design (I.T. Engineer)
+1.510.460.1444 (main)
+1.510.780.2425 (fax)
bhuddleston@openitdesign.com
