### ISSUE TITLE
create a group with GAM as a collaborative mailbox

### ISSUE THREAD

**Issue by arouthier** [jay0lee/GAM#41]
Hi, 

I don't find the command line to change the group type, I need to create a lot of group for a public folder migration and i love your tools but i can't manage to create that kind of group.

Thanks for your help and keep up the good work!

Very usefull :)

**Comment by jay0lee** [comment]
The Google APIs do not allow specifying group types like collaborative inbox. The setting is only available in the browser UI. Closing this issue as not currently feasible.
