### ISSUE TITLE
Feature request: update timezone calendar

### ISSUE THREAD

**Issue by PcoWegenenVerkeer** [jay0lee/GAM#42]
Hi,

Could GAM implement the https://developers.google.com/google-apps/calendar/v3/reference/calendars/update api to be able to update calendar timezone's (and other calendar attributes)?

This is an example I had to do for some calendars:
PUT https://www.googleapis.com/calendar/v3/calendars/calendar%40domain.be?key={YOUR_API_KEY}
{
 "summary": "calendar@domain.be",
 "timeZone": "Europe/Brussels"
}

Thnx in advance!

**Comment by dallin** [comment]
I'd also like to see this feature.
