### ISSUE TITLE
2SV status?

### ISSUE THREAD

**Issue by medina** [jay0lee/GAM#43]
Is there a way to query a user's 2SV status?

In the Google Admin Web UI:

![2sv](https://cloud.githubusercontent.com/assets/54688/6549137/677964c0-c5e4-11e4-821f-c023806599c7.png)

**Comment by medina** [comment]
Leaving this open, but looking at the Directory API **[user resource](https://developers.google.com/admin-sdk/directory/v1/reference/users#resource)** I don't see anything that would indicate 2SV status.

**Comment by geoghegan** [comment]
There is a round about way of doing this - run a report on all users with 2SV / 2FA disabled.
`gam report users filter "accounts:is_2sv_enrolled==false"`

The report lags somewhat behind real life - a user could enable 2FA a number of hours (or even days) ago, and the report will show 2FA is disabled for said user.

**Comment by jay0lee** [comment]
Closing this issue. Please ask "is there a way" questions in the GAM forum:

https://groups.google.com/forum/#!forum/google-apps-manager

**Comment by hajdbo** [comment]
Now, yes: https://github.com/jay0lee/GAM/pull/414
You can thank Google, they recently added the 2SV status in the API: https://developers.google.com/admin-sdk/directory/v1/reference/users#resource
