### ISSUE TITLE
Delegation fails with error code 1300

### ISSUE THREAD

**Issue by daparker** [jay0lee/GAM#433]
I am using GAM 4.11 on Linux.  We have a user who used to have delegated access to another account, but no longer seems to have it.  This user does not appear in the list of delegates for the target account.  But when I try to add him as a delegate, I get an error saying his account already exists.  In the examples below, **target** is the account to which delegated access is being granted, **user1** is a user who has delegated access, and **user2** is the user who used to have delegated access but does not anymore.

```
$ gam version
GAM 4.11 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.12 64-bit final
google-api-python-client 1.6.1
Linux-3.16.0-4-amd64-x86_64-with-debian-8.7 x86_64
Path: /home/dparker/bin/gam

$ gam user target show delegates
Getting delegates for target@mydomain.edu...
Delegator: target@mydomain.edu
 Delegate: Some User
 Status: ACCEPTED
 Delegate Email: user1@mydomain.edu
 Delegate ID: user1@mydomain.edu

$ gam user target delegate to user2@mydomain.edu
Giving user2@mydomain.edu delegate access to target@mydomain.edu (1/1)
ERROR: Could not create delegation - 400 - <?xml version="1.0" encoding="UTF-8"?>
<AppsForYourDomainErrors>
  <error errorCode="1300" invalidInput="user2@mydomain.edu" reason="EntityExists" />
</AppsForYourDomainErrors>
```

Full steps to reproduce the issue:
1. Attempt to grant delegated access for this specific user to this specific target account (I don't know what caused the delegated access to disappear in the first place, so I can't give any more steps)

Expected outcome (what are you trying to do?):
The user should gain delegated access to the target account.

Actual outcome (what errors or bad behavior do you see instead?):
I get an error which indicates that Google thinks the user already has delegated access to the target account.

This is the first time I have ever seen this problem.  Any help is greatly appreciated.  Thanks!

**Comment by daparker** [comment]
I have also opened a support case with Google regarding this.  I will update this issue if I get a solution from them.

**Comment by daparker** [comment]
I heard back from Google.  They said that this error is known to happen intermittently under the current Email Settings API, and often the delegation works if you wait a day or so and try again.  They have been working to solve it, but the Email Settings API is being deprecated and most efforts have been redirected to the upcoming Gmail API, which does not have this problem.  So, it sounds like this is a bug which they never really tracked down, and have now given up on fixing because it's not present in the newer API.

Definitely not a GAM issue.

**Comment by plyko** [comment]
hi guys, find reason and solution :)
it happens when you want to give access to account, which was never opened - you have to open this account in browser and accept fiorst page...
then run GAM...

**Comment by bar1kenoby** [comment]
@jay0lee 
This issue is preventing us to create delegations since, at least the 11/3/17

Any suggestion?

gam user user1@domain.org delegate to user2@domain.org
Giving user1@domain.org delegate access to user2@domain.org (1/1)
ERROR: Could not create delegation - 400 - <?xml version="1.0" encoding="UTF-8"?>
<AppsForYourDomainErrors>
  <error errorCode="1300" invalidInput="user2@domain.org" reason="EntityExists" />
</AppsForYourDomainErrors>

The accounts are both active and they are not admin accounts.

Thank you!
