### ISSUE TITLE
Lack of unicode support in filename causes application to crash when downloading gdrive file

### ISSUE THREAD

**Issue by jaredfolkins** [jay0lee/GAM#435]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

**Please confirm the following:**

***I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.**

Yes

***I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki**

Yes

**Full steps to reproduce the issue:**
1. Create a file in G suite where the filename contains only emojis
2. gam user  YOUR_GSUITE_EMAIL_HERE get drivefile id YOUR_FILE_ID_HERE

**Expected outcome (what are you trying to do?):**

Download the file

**Actual outcome (what errors or bad behavior do you see instead?):**

GAM will error because the safe_filename_chars map doesn't allow for unicode, stripping the entire filename, and trying to write a file named the directory

**Offending line:**

https://github.com/jay0lee/GAM/blob/0d7028416a557a4069541e733b06128191bf70f3/src/gam.py#L4112

```python
      #safe_file_title = ''.join(c for c in file_title if c in safe_filename_chars)
      # jared found the bug here
      # the safe_filename_chars don't allow for unicode characters
      # when a file is named only with a unicode character(s) nothing is returned
      # causing the application error as the file tries to name itself the directory
      safe_file_title = ''.join(c for c in file_title)
```

**Comment by jaredfolkins** [comment]
🦄 🦄

^ That was what the file was named.

**Comment by jay0lee** [comment]
Fixed by:

https://github.com/jay0lee/GAM/commit/3ffa3ca5e58b1154f87eca72655e0063a8218463

will be in next release (post 4.12) of GAM.

Jay
