### ISSUE TITLE
Authentication Token Error

### ISSUE THREAD

**Issue by JanWitt** [jay0lee/GAM#438]
I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Open Powershell
2. Type "C:\gam\gam user sadmin signature "hallo"" or  "C:\gam\gam user sadmin vacation on subject "hallo" message "hallo""
3. Error Message: "ERROR: Authentication Token Error - unauthorized_client: Client is unauthorized to retrieve access tokens using this method."

Expected outcome: I wanted to change the signature

Actual outcome: ERROR: Authentication Token Error - unauthorized_client: Client is unauthorized to retrieve access tokens using this method.

Some more background: I'm using GAM on a regular basis, and, until yesterday, it worked fine. Now, yesterday we tried to set up GAM for a customer, with reduced rights to just be able to access the mail API's. Here, I first saw this error message.

Now today I tried to use my usual GAM Account (all API Accesses granted), wich I used to create signatures and thelikes countless times, and got the same error message, when I tried to write a script to create signatures.

gam version shows the following:
GAM 4.02 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.12 64-bit final
google-api-python-client 1.5.2
Windows-8.1-6.3.9600 AMD64

I then head to the release page, and downloaded the up to date version of gam, so version is now showing this:
PS X:\> C:\gam\gam version
GAM 4.12 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.12 64-bit final
google-api-python-client 1.6.1
Windows-8.1-6.3.9600 AMD64
Path: C:\gam

And I still get the same error message.

Any ideas?

**Comment by jay0lee** [comment]
What does

gam user <email> check serviceaccount

Show?

**Comment by jay0lee** [comment]
Sorry:

gam user (email) check serviceaccount

**Comment by JanWitt** [comment]
Ok, that did it, I somehow missed that change, thanks!
