### ISSUE TITLE
ERROR: 403: Domain cannot use apis. - domainCannotUseApis

### ISSUE THREAD

**Issue by Jan-Zoudlik** [jay0lee/GAM#442]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
 - both yes... Actually I am using GAM-B version 4.12.06 as official release did not work

Full steps to reproduce the issue:
 - pick group with lots of users and try to print the list of members(in my case 1800 users)...

 - command:
 - gam print group-members group group@domain.com membernames > user.csv

 - Same command works fine with just a few users in the group

Expected outcome (what are you trying to do?):
get a list of users from group

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: 403: Domain cannot use apis. - domainCannotUseApis

**Comment by taers232c** [comment]
Jan,

GAM-B is my version, not Jay's, please close this issue and post here: https://github.com/taers232c/GAM-B

Ross
