### ISSUE TITLE
PROBLEM TO UPDATE GROUPS

### ISSUE THREAD

**Issue by aryelnr** [jay0lee/GAM#448]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Try to update owner for groups running the command bellow:
**D:\gam>gam update group cit-pms update owner emerson@ciandt.com**
 updating owner emerson@ciandt.com...
ERROR: 400: Missing required field: memberKey - required

**D:\gam>gam update group cit-pms@ciandt.com update owner emerson@ciandt.com**
 updating owner emerson@ciandt.com...
ERROR: 400: Missing required field: memberKey - required

Expected outcome (what are you trying to do?):
Change permission member for an group

Actual outcome (what errors or bad behavior do you see instead?):
**ERROR: 400: Missing required field: memberKey - required**

VERSION
GAM 4.12 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.12 64-bit final
google-api-python-client 1.6.1
Windows-10-10.0.14393 AMD64

**Comment by taers232c** [comment]
Aryel,

What version are you on? gam version

Ross
--
ross.scroggs@gmail.com

**Comment by aryelnr** [comment]
Hello Ross:

D:\gam>gam version
*GAM 4.12 - http://git.io/gam <http://git.io/gam>*
Jay Lee <jay0lee@gmail.com>
Python 2.7.12 64-bit final
google-api-python-client 1.6.1
Windows-10-10.0.14393 AMD64
Path: D:\gam



Att,

​Aryel Nouer Ribeiro • Product Engineer
ITIL V3® Foundation Certified, Google® Deployment Specialist
CI&T • Collaborate. Innovate. Transform.
+55
​(​
19
​) ​
​9.9902-99
6
​7​

​
​
•
​
 aryel@ciandt.com
​​
• ciandt.com

**Comment by aryelnr** [comment]
Today started this problem in addition to others where I need at all times
to put the domain of the user, the group etc ...

D:\gam>gam info user* aryel*
ERROR: 403: Not Authorized to access this resource/api - forbidden


D:\gam>gam info user *aryel@ciandt.com <aryel@ciandt.com>*
User: aryel@ciandt.com
First Name: Aryel
Last Name: Nouer Ribeiro



Att,

​Aryel Nouer Ribeiro • Product Engineer
ITIL V3® Foundation Certified, Google® Deployment Specialist
CI&T • Collaborate. Innovate. Transform.
+55
​(​
19
​) ​
​9.9902-99
6
​7​

​
​
•
​
 aryel@ciandt.com
​​
• ciandt.com

**Comment by aryelnr** [comment]
Hey Ross.

Forget the first error.
The error was mine, the username was wrong but this bellow still occur

D:\gam>gam info user* aryel*
ERROR: 403: Not Authorized to access this resource/api - forbidden


D:\gam>gam info user *aryel@ciandt.com <aryel@ciandt.com>*
User: aryel@ciandt.com
First Name: Aryel
Last Name: Nouer Ribeiro



Att,

​Aryel Nouer Ribeiro • Product Engineer
ITIL V3® Foundation Certified, Google® Deployment Specialist
CI&T • Collaborate. Innovate. Transform.
+55
​(​
19
​) ​
​9.9902-99
6
​7​

​
​
•
​
 aryel@ciandt.com
​​
• ciandt.com

**Comment by taers232c** [comment]
Aryel,

Set the following environment variable on the command line or in the Control Panel as a system environment variable.

set GA_DOMAIN=ciandt.com

Ross
--
ross.scroggs@gmail.com

**Comment by aryelnr** [comment]
Hmm...cool.
It worked, the problem is that I use several domains.
But no problem, I enter the domain manually or with each new OAUTHFILE, I
create a GA_DOMAIN set manually.

Many thanks for the help and agility.

Best Regards




Att,

​Aryel Nouer Ribeiro • Product Engineer
ITIL V3® Foundation Certified, Google® Deployment Specialist
CI&T • Collaborate. Innovate. Transform.
+55
​(​
19
​) ​
​9.9902-99
6
​7​

​
​
•
​
 aryel@ciandt.com
​​
• ciandt.com
