### ISSUE TITLE
transferownership is not a valid argument for "gam <users> update drivefileacl"

### ISSUE THREAD

**Issue by jgonzalez-nubalia** [jay0lee/GAM#455]
Full steps to reproduce the issue:
1. Configure and authorize GAM for your domain
2. Run the command to transfer ownership of a file from user1 to user2 according to the wiki:
`gam user user1@your.domain.com update drivefileacl <fileId> user2@your.domain.com role owner transferownership true
`

Expected outcome (what are you trying to do?):
- User user2 becomes the owner of the file with ID `<fileId>`

Actual outcome (what errors or bad behavior do you see instead?):
- GAM exits with `ERROR: transferownership is not a valid argument for "gam <users> update drivefileacl`

**Comment by jay0lee** [comment]
transferownership is not necessary on the command any longer after gam 4.2 just remove it and the true. I need to update the wiki.

**Comment by jgonzalez-nubalia** [comment]
Thank you for the prompt reply.  
However, if user2 has no permissions on the file, the `update` command fails with `Error 404 Permission not found`. The `add` command works but also adds the file to the root folder of user2's Drive. Is there any way to avoid that?

**Comment by jay0lee** [comment]
No. Transferring ownership automatically adds to root. That's what the API does and there's no way for GAM to handle it differently. You can always move the file to a subfolder or remove root with another GAM command after transfer.
