### ISSUE TITLE
gam-4.2-windows.zip treated as a threat by Symantec

### ISSUE THREAD

**Issue by vimsree** [jay0lee/GAM#459]
I tried to configure GAM in one my office machine and I got a warning from Symantec antivirus that the gam-4.2-windows version has traces of [SONAR.Heuristic.159](http://securityresponse.symantec.com/security_response/print_writeup.jsp?docid=2017-010520-1048-99). I've not seen this with earlier versions of GAM and I was pretty surprised to see it!

Attaching the screenshots for your reference.
![gam viral](https://cloud.githubusercontent.com/assets/2288379/24402021/6a3b64f2-13d4-11e7-9560-e814fb0359a8.PNG)
![gam viral1](https://cloud.githubusercontent.com/assets/2288379/24402022/6a66f50e-13d4-11e7-813c-ae174c051001.PNG)

**Comment by jay0lee** [comment]
AV vendors flag legit files as viruses all the time. There's nothing GAM can really do about this. Thanks for raising though.
