### ISSUE TITLE
Set organization settings

### ISSUE THREAD

**Issue by Huviel** [jay0lee/GAM#46]
Hi there,

I've been trying to update organization information such as title or name but it doesn't seem to be working with the following syntax :

> sudo gam.py update darth.vader@deathstar.com organization title "Test Inc."

I always get this error **Error: invalid argument to "gam update..."**

I don't understand what I'm doing wrong as I'm following what's wrotte on the documentation.

If there's anyone out there having or had this problem I'll be glad to hear from you.

Regards,

**Comment by jay0lee** [comment]
This is not a bug. Please ask your question in the mailing list, not here.

https://groups.google.com/forum/#!forum/google-apps-manager
