### ISSUE TITLE
Change instructions in CreatingClientSecretsFile for renaming API project to reflect new UI

### ISSUE THREAD

**Issue by stackedsax** [jay0lee/GAM#462]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Start running through CreatingClientSecretsFile (https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile)
2. Get to the step "Rename the project."
3. Look in vain for the "project selection menu".  Click the dropdown to the left of the search bar if you like.  There won't be a way to rename it in there, either.

Expected outcome (what are you trying to do?):
1. Hoping to rename.

Actual outcome (what errors or bad behavior do you see instead?):
1. Can't rename.

I'd like to update the steps in the document to reflect where users should go to rename their project:
1. Click on the vertical 3-dot icon, "Utilities and more", option.  This 3-dot icon is in the right-top corner click to the right of the notifications icon. 
2. Click "Project Settings"
3. In the Project name textbox, rename the API project
4. Click Save

I can easily drop these steps into the instructions, but I wasn't prepared to make nice screenshots like there are right now.  Let me know if you'd like me to go ahead even without the graphics for now -- at least the text will be correct.

Let me know if others don't see what I'm seeing.  However, I think this update occurred last September -- I'd be surprised if this wasn't what everyone sees these days.

**Comment by jay0lee** [comment]
Thanks, the wiki is editable by anyone with a GitHub account so go ahead.
