### ISSUE TITLE
403 error when trying to update Custom Schema fields via CSV

### ISSUE THREAD

**Issue by exodus2287** [jay0lee/GAM#463]
Looking to update custom schema fields using the following command

gam csv file.csv gam update user ~Email customschema.field1 ~field1 customschema.field2 ~field2

working under the understanding that entries starting with "~" are the CSV column names

output result is

Using 2 processes...
updating user testuser1@domain.com...
updating user testuser2@domain.com...

ERROR: 403: Not Authorized to access this resource/api - forbidden

If i use a manual command without the CSV it works fine.

gam update user customschema.field1 value 

What API should it be enabling access to in order to utilize the CSV

**Comment by exodus2287** [comment]
Interesting resolution?

I included my email in the CSV containing the updates.

Updates now go through fine.

**Comment by jay0lee** [comment]
Seems like a temporary issue or something with your CSV that got updated when you added your email.
