### ISSUE TITLE
Gam upgrade Issue

### ISSUE THREAD

**Issue by Sathyanarayanakumar** [jay0lee/GAM#474]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. I have run set up file gam version 4.21.
2. But i am getting the error "ERROR: [Errno 10061] No connection could be made because the target machine actively refused it"
3.

Expected outcome (what are you trying to do?):

Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jay0lee** [comment]
This error usually is caused by firewall / antivirus / security software on your computer or network. Try disabling them and rerunning. If you still have issues, report them to the discussion group.
