### ISSUE TITLE
Proxy CONNECT uses IP address rather than domain name (issue #45 continued)

### ISSUE THREAD

**Issue by rjaffey** [jay0lee/GAM#48]
Please refer to issue #45 for background.

... Actually, it looks like the version of httplib2 included in GAM and how GAM calls it that affects this:

The following code is present in the version of httplib2/&#95;&#95;init&#95;&#95;.py included in GAM 3.42:

```
    def __init__(self, proxy_type, proxy_host, proxy_port,
                 proxy_rdns=None, proxy_user=None, proxy_pass=None):
```
Whereas the following code is present in the current master branch of httplib2/&#95;&#95;init&#95;&#95;.py:

```
    def __init__(self, proxy_type, proxy_host, proxy_port,
                 proxy_rdns=True, proxy_user=None, proxy_pass=None):
```
along with the comment:
```
          proxy_rdns: If True (default), DNS queries will not be performed
          locally, and instead, handed to the proxy to resolve.  This is useful
          if the network does not allow resolution of non-local names.  In
          httplib2 0.9 and earlier, this defaulted to False.
```
Patching the version distributed with GAM, changing "proxy_rdns=None" to "proxy_rdns=True" addresses the issue.

I'd say, either updating the version of httplib2 or overriding the default when ProxyInfo is initialized would address the issue.  In either case this would point back at GAM as the place to fix this.

**Comment by jay0lee** [comment]
Updated GAM to use httplib v0.9.1 which will ship with GAM 3.5 (due out real soon now).
