### ISSUE TITLE
Feature Request: Restore a user's Gmail and Drive Data

### ISSUE THREAD

**Issue by Stevenlastax** [jay0lee/GAM#485]
Hey Jay,

I went through the Wiki and didn't see any way to Restore user data on gmail and drive. Do you have any plans to add this feature down the road map?

https://support.google.com/a/answer/6052340?hl=en

**Comment by jay0lee** [comment]
There's no API to do this, thus it's not possible for GAM to do it. Should Google add an API to do this down the line we can reevaluate then.
