### ISSUE TITLE
Can not get GAM authorized to manage data and settings

### ISSUE THREAD

**Issue by moshinh** [jay0lee/GAM#486]
Can not get GAM authorized to manage data and settings

 Scope: https://mail.google.com/                                     FAIL
 Scope: https://www.googleapis.com/auth/activity                     FAIL
 Scope: https://www.googleapis.com/auth/calendar                     FAIL
 Scope: https://www.googleapis.com/auth/drive                        FAIL
 Scope: https://www.googleapis.com/auth/gmail.settings.basic         FAIL
 Scope: https://www.googleapis.com/auth/gmail.settings.sharing       FAIL
 Scope: https://www.googleapis.com/auth/plus.me                      FAIL

Tells me to grab coffee and come back, but time does not heal this wound.

It tells me 
ERROR: Some scopes failed! Please go to:

https://admin.google.com/emoshin.com/AdminHome?#OGX:ManageOauthClients

and grant Client name:

111201402506781364553

Access to scopes:

https://mail.google.com/,
https://www.googleapis.com/auth/activity,
https://www.googleapis.com/auth/calendar,
https://www.googleapis.com/auth/drive,
https://www.googleapis.com/auth/gmail.settings.basic,
https://www.googleapis.com/auth/gmail.settings.sharing,
https://www.googleapis.com/auth/plus.me

But i've verified that even.

Stumped.

**Comment by jay0lee** [comment]
Give it 24-48 hours and try again.

**Comment by moshinh** [comment]
Thanks for the prompt response!

**Comment by oliverhext** [comment]
I seem to be having exactly the same issue, but still have another 24 hours to wait.  Will report back.

**Comment by oliverhext** [comment]
Still no joy, client name is okay.  Have tried both manually and using supplied batch file on linux and windows to create project but it still fails as above.  Can I check anything else?  Cheers

**Comment by jadethaveekij** [comment]
Had the same issue before.  But following this and copy-pastes the https... to the list and that works almost instantly

It tells me
ERROR: Some scopes failed! Please go to:

https://admin.google.com/emoshin.com/AdminHome?#OGX:ManageOauthClients

and grant Client name:

111201402506781364553

Access to scopes:
=== start copy these lines and paste ===
_https://mail.google.com/,
https://www.googleapis.com/auth/activity,
https://www.googleapis.com/auth/calendar,
https://www.googleapis.com/auth/drive,
https://www.googleapis.com/auth/gmail.settings.basic,
https://www.googleapis.com/auth/gmail.settings.sharing,
https://www.googleapis.com/auth/plus.me_
=== end copy these lines and paste ===
But i've verified that even.
