### ISSUE TITLE
Spaces in installation path not handled gracefully

### ISSUE THREAD

**Issue by Shotster** [jay0lee/GAM#487]
My user directory name contains a space. Attempting to update GAM results in the following:

`bash <(curl -s -S -L https://git.io/install-gam)
Good, you're running MacOS 10.12...

Checking GitHub URL https://api.github.com/repos/jay0lee/GAM/releases for latest GAM release...

Getting file and download URL...

Downloading file gam-4.21-macos.tar.xz from https://github.com/jay0lee/GAM/releases/download/v4.21/gam-4.21-macos.tar.xz to /var/folders/gv/ws3xtwxj19zc6ft18sdyf6_00000gp/T/tmp.eaGYSmt9.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   597    0   597    0     0   1265      0 --:--:-- --:--:-- --:--:--  1267
100 6129k  100 6129k    0     0  1510k      0  0:00:04  0:00:04 --:--:-- 1711k
Extracting archive to /Users/shot 1/bin

tar: 1/bin: Not found in archive
tar: Error exit delayed from previous errors.
ERROR: extracting the GAM archive with tar failed with error 1. Exiting.`

The name of my home directory is "shot 1".

**Comment by jay0lee** [comment]
Thanks for the heads up. I made some adjustments to the install script, can you try again as this should be fixed now.

**Comment by taers232c** [comment]
Jay,

The spaces in the alias have to be escaped with \
 alias_line="alias gam=\"${target_dir// /\\ }/gam/gam\""

Quotes required here:
      touch "$target_dir/gam/nobrowser.txt" > /dev/null 2>&1

Ross
