### ISSUE TITLE
GAM v.4.11, Error: API Access Denied

### ISSUE THREAD

**Issue by tsrofj** [jay0lee/GAM#502]
First, jay0lee, thanks for the awesome tool, it's quite useful.

Receiving this error when trying to connect to a (previously) working implementation:

gam print group-members group all@some-domain.com
Version Check:
 Current: 4.11
 Latest: 4.22

GAM 4.22 release notes:

Validate client id and secret from user input (reduces user errors on create project)
Ross - optimize "gam print printjobs"
Ross - countsonly option for gam print courses
"gam info domain" now shows G Suite basic/business/enterprise license counts
Ross - calendar commands now work for user secondary calendars
Ross - Group create/update fixes for description newlines and other fixes

Hit CTRL+C to visit the GAM website and download the latest release or wait 15 seconds continue with this boring old version. GAM won't bother you with this announcement for 1 week or you can create a file named noupdatecheck.txt in the same location as gam.py or gam.exe and GAM won't ever check for updates.
Getting members for all@some-domain.com (1/1)

ERROR: API access Denied.

Please make sure the Client ID: None is authorized for the API Scope(s): 

ERROR: API access is configured in your Control Panel under: Security-Show more-Advanced settings-Manage API client access

------------
this had worked a few weeks ago.

I did experiment with 2FA on google, but have disabled 2FA last week due to conflicts with another application.

Is this solvable from the gam side (e.g. I saw a reference in a search result referring to delete a couple files and re-configure) or from google side?

Thanks,
tsrofj

**Comment by jay0lee** [comment]
Upgrade to the latest version.
