### ISSUE TITLE
"gam all users delegate to" fails on own user

### ISSUE THREAD

**Issue by KroniK907** [jay0lee/GAM#509]
If I try to run 

`gam all users delegate to admin@example.com`

It works until it encounters the delegate's own email and then fails, stopping all further delegation. 

This command should probably have some logic that prevents it from trying to delegate a user to its self. 

output with personal info removed:
```
$ gam all users delegate to admin@example.com
Getting all users in G Suite account (may take some time on a large account)...
Got 17 users...
done getting 17 users.
Giving admin@example.com delegate access to alice@example.com (1/17)
Giving admin@example.com delegate access to bob@example.com (2/17)
Giving admin@example.com delegate access to sue@example.com (3/17)
Giving admin@example.com delegate access to frank@example.com (4/17)
Giving admin@example.com delegate access to admin@example.com (5/17)
ERROR: Could not create delegation - 400 - <?xml version="1.0" encoding="UTF-8"?>
<AppsForYourDomainErrors>
  <error errorCode="1303" invalidInput="admin@example.com" reason="EntityNameNotValid" />
</AppsForYourDomainErrors>
```

**Comment by plyko** [comment]
hi, find reason and solution :)
it happens when you want to give access to account, which was never opened - you have to open this account in browser and accept fiorst page...
then run GAM...

**Comment by KroniK907** [comment]
This is not the problem. I used admin@example.com in my example for a reason, and that is because I was trying to deleage users to my primary admin account which I use on a regular basis. 

I'm sure that GAM will probably fail on actions that relate to an account that has never fully been set up, but that is not the problem I'm describing.

**Comment by jay0lee** [comment]
Try a command like:

gam print users | gam csv - gam user ~primaryEmail delegate to admin@example.com

instead. This command will run faster and even though the delegation to self will still fail, the rest of the delegations should continue.
