### ISSUE TITLE
deprovision_same_model_replace does not work

### ISSUE THREAD

**Issue by ahmetshen-us** [jay0lee/GAM#511]
Full steps to reproduce the issue:
1. gam update cros "$deviceIdOld" action deprovision_retiring_device acknowledge_device_touch_requirement

Expected outcome (what are you trying to do?):
Available Licenses should increase
Actual outcome (what errors or bad behavior do you see instead?):
Instead No Longer Available License numbers increase, Available Licenses stay the same.

**Comment by jay0lee** [comment]
This is not a GAM issue, this is a question of how Google handles Chrome licensing and re-use. See:

https://support.google.com/chrome/a/answer/3523633?hl=en
