### ISSUE TITLE
Courses created with provisioned status missing folder

### ISSUE THREAD

**Issue by blackwellm** [jay0lee/GAM#514]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Create a course with someone else as the teacher.  Do not set a status.
2. Have the teacher accept the course.
3.  Check the teacher's classroom and drive.

Expected outcome (what are you trying to do?):
After the teacher activates the course, a new folder should appear in his Classroom folder in Drive.  There should be a link to it from the course's card on his Classroom home page, and on the Course's about tab.

Actual outcome (what errors or bad behavior do you see instead?):
The folder icon is greyed out on the card on the home page, and is completely missing from the about tab.  The folder is not in Drive.

If I create the course with status active, the folder works correctly.  Setting the status from GAM does not fix a course.

If I create a course with myself as the teacher, the problem does not occur.

Thanks,
Matt

**Comment by kbwebsolutions** [comment]
I can confirm this is a live issue.  I'm having the same problem when creating classrooms.  The version I'm using is 4.23

**Comment by NoSubstitute** [comment]
As a follow-up question, what happens if you, I mean the teacher, add an assignment and publish, and then have a student submit the assignment? Is the folder then created, or where does that student's submitted document go?

**Comment by blackwellm** [comment]
NoSubstitute,
The folders were created and  everything worked properly.  It looks like this will not be a problem after all.

Thanks,
Matt
