### ISSUE TITLE
Users report field missed

### ISSUE THREAD

**Issue by aldiserg** [jay0lee/GAM#516]
recently, gam report users doesn't show the usage of google space colomns, 
The folow picture show the diff from old file (right side) to new colomns (left side):

![1](https://user-images.githubusercontent.com/29753315/27637331-0729bbe8-5c18-11e7-9b90-b90558aabeeb.png)

New report doesn't have needed colomns
How can i restore colomns of usage?

**Comment by taers232c** [comment]
Here is the API documentation: https://developers.google.com/admin-sdk/reports/v1/reference/usage-ref-appendix-a/users-drive

What fields do you see there that Gam is not returning?

Ross
--
ross.scroggs@gmail.com

**Comment by aldiserg** [comment]
accounts:used_quota_in_mb

**Comment by taers232c** [comment]
This has come up before: https://groups.google.com/forum/#!topic/google-apps-manager/4CRGAjRkCkE

Try specifiy a date a few days prior to today.

Ross
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
closing as this is not a GAM issue. Please continue discussion on group.
