### ISSUE TITLE
Group sync cmds in batch file not completing/running

### ISSUE THREAD

**Issue by cbf305** [jay0lee/GAM#529]
I was running GAM 4.11, but the issue still persists after upgrading to the latest 4.23.

I have a program that is updating the several thousand groups in our domain.  It's spitting out a text file for each group with a listing of member emails.  I am then populating a command file and using the batch command to update the groups.  These are samples of what my files look like:

Member listing filenames:
```
mygroup1
mygroup2
...
mygroupX

```
File contents of mygroup1
```
john@domain.com
steve@domain.com
marsha@domain.com
...
gary@domain.com
```

Contents of GAM command file `commands.txt`:
```
gam update group mygroup1 sync member file mygroup1
...
gam update group mygroupX sync member file mygroupX
```

If I run `gam batch commands.txt` I get the following output:
```
Using X processes...
Getting members of mygroup1@domain.com (may take some time for large groups)...
Got 0 members
Need to add 20 MEMBER and remove 0
```
Clearly GAM is reading in the membership files because it correctly displays the number of changes needed, but it never actually does the work. And yes the group already exists or it was processed in a prior `commit-batch`.

However, if I copy the command out of the `commands.txt` file and run `gam update group mygroup1 sync member file mygroup1` on the command line, I get the following output:
```
Using X processes...
Getting members of mygroup1@domain.com (may take some time for large groups)...
Got 0 members
Need to add 20 MEMBER and remove 0
Using X processes...
  adding member john@domain.com...
  adding member steve@domain.com...
  adding member marsha@domain.com...
  ...
  adding member gary@domain.com...
```

I put all the daily changes into the `commands.txt` file and GAM batch command does not have trouble running any other commands, just the group sync ones.

What's even more interesting is if I instead `source commands.txt` it runs everything as expected even the groups sync ones, but I've lost the speed since it's running them one at a time.

Thanks!

**Comment by taers232c** [comment]
John,

With standard GAM, you can't put gam update group sync commands in a gam batch file, they will not excute correctly. Both processing the batch file command and the group update syncs use the same multiprocess code and the two interfere.

My advanced version handles this correctly: https://github.com/taers232c/GAMADV-X

I will submit a change to Jay such that his version will do this successfully.

Ross
--
ross.scroggs@gmail.com
