### ISSUE TITLE
Plain text Client ID and Secret in gam folder

### ISSUE THREAD

**Issue by goneafk** [jay0lee/GAM#531]
There is a .json file saved in the GAM folder that contains the Client ID and Client Secret for the service account. This seems quite dangerous and opens up that service account to have the credentials exfiltrated and used illicitly.

Thoughts?

My layman's idea of a solution:

These credentials should be encrypted and then decrypted by the gam executable after initial write so that you can't access that information without it being processed by the gam binary that saved them during enrollment.

If people are cycling the keys, there could be a way to pass the credentials through the gam binary so that they are also encrypted.

**Comment by jay0lee** [comment]
But the decryption would still be stored locally so what's the point?

GAM has always depended on the local device to be secured. You can handle that with your built in OS encryption.
