### ISSUE TITLE
No Logging of actions to create Chain of Custody for actions

### ISSUE THREAD

**Issue by goneafk** [jay0lee/GAM#532]
In testing a drive transfer between two users, I found that there was no chain of custody to prove that GAM was the actor that changed the permissions on the file.

I was able to find in the Drive Reports that the user I acted upon (User A) transferred directly from their account driveacls to another user (User B).

The Token logs show that User A used my GAM App's ID to do an action, but nothing that directly tied them together. If I was to make actions with a live users account, I may not be able to tell what was actioned by GAM and what was the actual user. If trying to do some forensics about what took place if there was a malicious action with a compromised GAM install, I would have to manually tie these events together.

I understand the limitations of GAM in that to action that transfer it does have to become that user and then make an API call on their behalf, which is creating the log situation above.

Is there a way to create, from GAM, a log of all actions taken by the client that is attached to that Service Account? This way, if the GAM service account gets compromised there are detailed logs showing the actions taken by GAM? Likely not possible in the Google Reports interface, but attached to the App backend, or, at the least, locally?

(My apologizes if something like this already exists, I didn't find it while researching.)

**Comment by jay0lee** [comment]
There's really no way to do this authoritatively. GAM runs locally. The admin audit log shows details of most admin actions. GAM logging something locally would only be prone to modifications locally.
