### ISSUE TITLE
ERROR: 403: Service 'vault-json.googleapis.com' not found or permission denied

### ISSUE THREAD

**Issue by neilwa** [jay0lee/GAM#536]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Run installer bash <(curl -s -S -L https://git.io/install-gam)
2. Attempt to setup GAM project
3. 

Expected outcome (what are you trying to do?):

Install GAM

Actual outcome (what errors or bad behavior do you see instead?):
```
Authentication successful.
Creating project "GAM Project"...
Checking project status...
Project still being created. Sleeping 1 seconds
Checking project status...
Project still being created. Sleeping 4 seconds
Checking project status...
 enabling API admin.googleapis.com...
 enabling API appsactivity.googleapis.com...
 enabling API calendar-json.googleapis.com...
 enabling API classroom.googleapis.com...
 enabling API contacts.googleapis.com...
 enabling API drive.googleapis.com...
 enabling API gmail.googleapis.com...
 enabling API groupssettings.googleapis.com...
 enabling API licensing.googleapis.com...
 enabling API plus.googleapis.com...
 enabling API reseller.googleapis.com...
 enabling API siteverification.googleapis.com...
 enabling API vault-json.googleapis.com...

ERROR: 403: Service 'vault-json.googleapis.com' not found or permission denied. - forbidden
Project creation failed. Trying again. Say N to skip project creation.
```

**Comment by jay0lee** [comment]
This should be fixed, try again now.
