### ISSUE TITLE
print error for group with most 2000 member

### ISSUE THREAD

**Issue by lonix86** [jay0lee/GAM#538]
I'm trying to make a print of all groups in a domain, some of these groups have more than 2000 members, for all of them are not printed in the csv or even on the spreadsheet.

**Comment by j1schan** [comment]
https://support.google.com/a/answer/6099642
Can a group with more than 2000 (direct) members? it says not....

**Comment by lonix86** [comment]
From what I see the limit is 2000 groups of which the user should be part, not 2000 members for the single group,

**Comment by lonix86** [comment]
![console_di_amministrazione](https://user-images.githubusercontent.com/30172663/28614834-6c041e10-71f7-11e7-9f6b-722a3496acd1.jpg)

**Comment by j1schan** [comment]
ops yes sorry, I misread that sentence, thanks~
