### ISSUE TITLE
Enabling and Setting a Vacation (Away) Message Vacation 

### ISSUE THREAD

**Issue by hgentryib** [jay0lee/GAM#54]
using gam 3.41, submitted the following (edited) command:
gam user user@domain.com vacation on subject "Out of Office" message "Please note that user is currently out of the office.  In her absence, please contact our Customer Service Department at (800) 555-1212 for immediate assistance.\n\n" startdate 2015-03-30 enddate 2015-04-04

Text for message was set, vacation was turned on, but neither start nor end dates were set.

**Comment by jay0lee** [comment]
This command worked as expected for me. Can you try it on another account?
