### ISSUE TITLE
ERROR: 403: Service 'contacts.googleapis.com' not found or permission denied. - forbidden

### ISSUE THREAD

**Issue by ChronomegaIV** [jay0lee/GAM#547]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Ran GAM 64-bit for windows
2. Authed in through web site
3. Accepted TOS for Google Cloud
4. Failed during project creation

Expected outcome (what are you trying to do?):
Attempting to create APIs for GAM

Actual outcome (what errors or bad behavior do you see instead?):
Creating project "GAM Project"...
Checking project status...
Project still being created. Sleeping 1 seconds
Checking project status...
Project still being created. Sleeping 4 seconds
Checking project status...
 enabling API admin.googleapis.com...
 enabling API appsactivity.googleapis.com...
 enabling API calendar-json.googleapis.com...
 enabling API classroom.googleapis.com...
 enabling API contacts.googleapis.com...

ERROR: 403: Service 'contacts.googleapis.com' not found or permission denied. - forbidden

Projection creation failed. Trying again. Say n to skip projection creation.

**Comment by jay0lee** [comment]
This was an issue on Google's side that has since been resolved.
