### ISSUE TITLE
Setting Vacation Responder

### ISSUE THREAD

**Issue by andrewfantone** [jay0lee/GAM#548]
run gam  user <username> vacation on subject <subject text> [message <message text>] produces the error attached
![gam error atb](https://user-images.githubusercontent.com/30907458/29183491-be658dbc-7db7-11e7-9236-c17290f7adf3.PNG)

Is this currently a working command?

**Comment by jay0lee** [comment]
Yes, it works. Did you run the commands the error message tells you to run? Please reach out to the discussion group for help as this does not look like a bug:

https://git.io/gam-group

**Comment by gokeefe** [comment]
We have a working service account and every other gam command seems to work... adding and removing delegates, changing user information, etc etc, but the vacation command just doesn't work for some reason.
