### ISSUE TITLE
Setting GAM up, Google's ToS not a pop up

### ISSUE THREAD

**Issue by michaeljones1234** [jay0lee/GAM#551]
Full steps to reproduce the issue:
1. Installing latest version of GAM (4.30) 
2. All fine until asking to go to https://console.cloud.google.com/start and when going to site, there is no pop up. Assuming that means it must have been OK'd previously.
3. Clicking enter just reloads the prompt asking to accept the ToS

Expected outcome (what are you trying to do?):

Install GAM

Actual outcome (what errors or bad behavior do you see instead?):

Not being installed due to no pop up - not sure if this is something that Google has recently changed that breaks the install?

**Comment by Wobak** [comment]
Hi,

Try to check when you enter the URL that you're logged in to the correct account. I found out that even though I accepted the ToS, I still got an error until I figured out I was logged in to another account than the one I provided in the CLI.
