### ISSUE TITLE
Feature request: changing the owner of a Google Classroom

### ISSUE THREAD

**Issue by jschlackman** [jay0lee/GAM#552]
Following an API update in August 2017, Google now support [changing the owner of a Google Classroom course via the API](https://support.google.com/edu/classroom/answer/7477648). Could this feature be considered for implementation in GAM?

This would be especially useful since Google provide no first-party UI for G Suite admins to alter course owners - at present, it can only be done by the owner themselves in the Classroom web interface.

**Comment by jay0lee** [comment]
This is added and will be in the next GAM release.
