### ISSUE TITLE
Admin Actions Report relative time syntax

### ISSUE THREAD

**Issue by danielx** [jay0lee/GAM#559]
Would you be interested in a pull request for functionality that would allow usage of relative time syntax for admin action reports?

Proposed syntax:
```bash
$ gam report admin start -4h end -30m
```

Thought it would be best to discuss this before starting work on a patch.

**Comment by taers232c** [comment]
Daniel,

Send me the code directly, I'll take a look at it.

Ross (ross.scroggs@gmail.com)

**Comment by danielx** [comment]
@taers232c see #563
