### ISSUE TITLE
implement skip_notification for sharing Google Cloud Print printer

### ISSUE THREAD

**Issue by chaplina** [jay0lee/GAM#561]
Currently, if I share a Google Cloud Printer (gam printer id add USER ...) they do not receive a notification that the printer was shared with them.

This is controlled by the skip_notification field as described in the JSON for GCP /share at https://developers.google.com/cloud-print/docs/shareApi#share.

Please implement at your convenience. :)

**Comment by chaplina** [comment]
It looks like doPrinterAddACL has the field defined with a default of True.

The field just needs to be added as an optional arg.

**Comment by taers232c** [comment]
chaplina,

As you have the source, the following gets you what you want.
```
def doPrinterAddACL():
  cp = buildGAPIObject(u'cloudprint')
  printer = sys.argv[2]
  role = sys.argv[4].upper()
  scope = sys.argv[5]
  notify = True if len(sys.argv) > 6 and sys.argv[6].lower() == u'notify' else False
  public = None
  skip_notification = True
  if scope.lower() == u'public':
    public = True
    scope = None
    role = None
    skip_notification = None
  elif scope.find(u'@') == -1:
    scope = u'/hd/domain/%s' % scope
  else:
    skip_notification = not notify
  result = callGAPI(cp.printers(), u'share', printerid=printer, role=role, scope=scope, public=public, skip_notification=skip_notification)
  checkCloudPrintResult(result)
  who = scope
  if who is None:
    who = u'public'
    role = u'user'
  print u'Added %s %s' % (role, who)
```

Ross

**Comment by jay0lee** [comment]
this is in 4.31
