### ISSUE TITLE
doRemoveUsersGroups

### ISSUE THREAD

**Issue by lerklompen** [jay0lee/GAM#57]
Definitely a minor issue:
gam.py
line 4283
variable i remains "1" in all iterations of group removals, there is no "i += 1".

Therefor it prints out for example (1/10) for all lines, instead of (1/10), (2/10) ... (10/10).

Thanks for a great tool!

**Comment by jay0lee** [comment]
Fixed in GAM 3.5 (to be released real soon now). Thanks for the report.
