### ISSUE TITLE
Problem with gam print licenses

### ISSUE THREAD

**Issue by ABRustam** [jay0lee/GAM#599]
I was running GAM 4.30
When I try to execute a command

`gam print users ou licenses`
To get a list of users with all licenses, by ou and users

I get the list from email, ou, license. But there is nothing in the license field.
Though at us in a domain it is a lot of users with 50/200/400GB gdrive lic.

I also tried
`gam print licenses products Google-Drive-storage sku drive50gb`
According to https://gamcheatsheet.com/GAM%20Cheat%20Sheet%20A3.pdf
And I get it.
userid, ProductID, skuId

There was somebody with this problem, and how you solve this question.

**Comment by ABRustam** [comment]
ps: i using Windows  7 x64

**Comment by jay0lee** [comment]
Did the end users purchase the storage themselves or did you purchase it in admin console?

If end users purchased the storage there is no admin console "license" and nothing for GAM to show.

Check also the billing section of the admin console. If the licenses don't show there they won't show in GAM either.

**Comment by ABRustam** [comment]
All licenses provided from admin console.
And i can see their in billing section about 150pcs. 20/50/200GB
If i use `gam print users licenses >full.txt`
I receive this result  `primaryEmail,Licenses
login@domain,` for all users. 
pls help. 
We prepare such reports every month.

**Comment by jay0lee** [comment]
What does:

gam print licenses

Show?

**Comment by ABRustam** [comment]
`C:\Users\rustal-usr>gam print licenses
userId,productId,skuId`

**Comment by ABRustam** [comment]
if i execute `C:\Users\rustal-usr>gam print licenses`
i receive `userId,productId,skuId`

**Comment by jay0lee** [comment]
Did this *ever* work for you? Did the Drive licenses show in GAM at some point? Are you using the latest GAM version?

**Comment by ABRustam** [comment]
No, GAM doesn`t ever show Drive licenses in our domain.
I tried versions: 4.3, 4.31, 4.32, 4.40.

**Comment by jay0lee** [comment]
What about:

gam oauth info

Does that show the super admin user you expect who is in the same domain as the users?

**Comment by ABRustam** [comment]
execute `gam oauth info`
 receive 
`OAuth File: D:\GAM\oauth2.txt
Client ID: **********************************************.apps.googleusercontent.
com
Secret: ********************
Scopes (30):
  https://apps-apis.google.com/a/feeds/emailsettings/2.0/
  https://www.googleapis.com/auth/admin.datatransfer
  https://www.googleapis.com/auth/admin.directory.customer
  https://www.googleapis.com/auth/admin.directory.device.chromeos
  https://www.googleapis.com/auth/admin.directory.device.mobile
  https://www.googleapis.com/auth/admin.directory.domain
  https://www.googleapis.com/auth/admin.directory.group
  https://www.googleapis.com/auth/admin.directory.notifications
  https://www.googleapis.com/auth/admin.directory.orgunit
  https://www.googleapis.com/auth/admin.directory.resource.calendar
  https://www.googleapis.com/auth/admin.directory.rolemanagement
  https://www.googleapis.com/auth/admin.directory.user
  https://www.googleapis.com/auth/admin.directory.user.security
  https://www.googleapis.com/auth/admin.directory.userschema
  https://www.googleapis.com/auth/admin.reports.audit.readonly
  https://www.googleapis.com/auth/admin.reports.usage.readonly
  https://www.googleapis.com/auth/apps.groups.settings
  https://www.googleapis.com/auth/apps.licensing
  https://www.googleapis.com/auth/apps.order
  https://www.googleapis.com/auth/classroom.courses
  https://www.googleapis.com/auth/classroom.guardianlinks.students
  https://www.googleapis.com/auth/classroom.profile.emails
  https://www.googleapis.com/auth/classroom.profile.photos
  https://www.googleapis.com/auth/classroom.rosters
  https://www.googleapis.com/auth/cloudprint
  https://www.googleapis.com/auth/ediscovery
  https://www.googleapis.com/auth/plus.me
  https://www.googleapis.com/auth/pubsub
  https://www.googleapis.com/auth/siteverification
  https://www.googleapis.com/auth/userinfo.email
G Suite Admin: user@domain`
I also try execute `gam print licenses` with Gsuite superadmin credentials API and result the same.
`userId,productId,skuId`

**Comment by vincentteo** [comment]
Hi , I also facing the same issue when i try to execute a command below .
 gam print users allfields license >13.06.18.csv

The users licenses fields is only show blank only in the csv format .

**Comment by vincentteo** [comment]
Hi Ross , 

Below is the output when i execute gam print licenses .

userId,productId,skuId

Regards,
Vincent

**Comment by jay0lee** [comment]
Some domains like Google Apps Standard/Free and EDU don't have per-user licenses. Unless you're on G Suite Basic, Business or Enterprise this is expected output.

What exactly are you trying to see with the licenses anyway?

**Comment by vincentteo** [comment]
Hi Jay , 

Currently I'm using G-Suite Business . And I need to generate report using GAM for each user is using what type of licenses . As i remember before i update the latest version still able to generate the licenses type for the users .

Vincent

**Comment by jay0lee** [comment]
Can you share a screenshot of the billing page in admin.google.com?

**Comment by vincentteo** [comment]
Hi Jay ,

Here is the billing page in the admin console .
![billing page](https://user-images.githubusercontent.com/31163326/41346497-3fbb417c-6f39-11e8-963e-92ec7b7b4bfd.PNG)

**Comment by jay0lee** [comment]
When you run:

gam oauth info

Can you confirm that the user listed for G Suite admin is a super admin?

If you go to:

https://developers.google.com/apis-explorer/#p/licensing/v1/licensing.licenseAssignments.listForProduct?productId=Google-Apps&customerId=ENTER+YOUR+DOMAIN&_h=3&

And enter your own primary domain for customer ID, then authorize and execute, what output do you see?
