### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by gezafodor** [jay0lee/GAM#6]
GAM 3.32 Windows x64
gam report users todrive

This report could not finish on a large database (almost 500.000 users). Always finished with this error message you can see on the attached screenshot.

![gam-error](https://cloud.githubusercontent.com/assets/7516383/4260309/3362def8-3b35-11e4-8274-859298140820.png)

**Comment by jay0lee** [comment]
Closing this issue as there have been numerous unicode fixes to GAM in past 2 years. if this can still be reproduced, please re-open.
