### ISSUE TITLE
'download_url' referenced before assignment

### ISSUE THREAD

**Issue by jkrauska** [jay0lee/GAM#61]
Attempting to do a doc download using GAM-3.43a.

$ gam user myuser@mydomain.org get drivefile query "'me' in owners"
Searching for files with query: "'me' in owners"...

yields

  File ".../gam/gam.py", line 2360, in downloadDriveFile
    resp, content = drive._http.request(download_url)
UnboundLocalError: local variable 'download_url' referenced before assignment

**Comment by lerklompen** [comment]
GAM defaults to 'openoffice' as format. It seems as spreadsheets nolonger presents an exportlink in this format via the API response!

If you specify  'format pdf' or 'format ms' instead it should work.

**Comment by jay0lee** [comment]
Please confirm you still see this issue with GAM 3.8. Closing issue for now.
