### ISSUE TITLE
Move Users to another sub-organizational ou

### ISSUE THREAD

**Issue by selcukkubur** [jay0lee/GAM#610]
Hi GAM community,

Im new on gam and gam really amazing tool for who managing GSuite.I have a problem to moving users to another sub org. 

I searched articles for that and try many times but I coulndt be successfull could someone help me ? 
I wanna move users class by class I already created ou's for every class.

[https://imgur.com/a/Pujfd](url)

"gam update org 5A / add file 5A.txt" 

which command I can successfully move users to another ou?

Note: Im using last version of gam tool.

**Comment by taers232c** [comment]
This is the command, replace /Path/To/Org with the full path to the OU, /5A, /Students/Grade5/5A, ...
Replace filename with the actual filename; this should be a one column file with no header.

gam update org /Path/ToOrg add file filenname

Ross
--
ross.scroggs@gmail.com
