### ISSUE TITLE
GAM python output error

### ISSUE THREAD

**Issue by huynhbaoan** [jay0lee/GAM#624]
I update to GAM 4.32, then I noticed a bug (maybe a python exception error).
Here is how to reproduce the bug:
- Assume we have an user and a group.
- Add user to group by 'gam update group <grp> add member <mem>'.
- Add user to group again by executing the previous command again.
- Then, instead of a normal output like this: 
 Adding MEMBER <> to <>

ERROR: 409: Member already exists. - duplicate

I got this error: 

Traceback (most recent call last):
  File "gam.py", line 12345, in <module>
  File "gam.py", line 11685, in ProcessGAMCommand
  File "gam.py", line 7984, in doUpdateGroup
__main__.GAPI_duplicate: Member already exists.
[17444] Failed to execute script gam

Both Windows and Linux version have this bug.

Btw: thanks you guys very much for working hard on such a great app  :)

**Comment by taers232c** [comment]
This is already fixed in the code, it will appear in the next release.
--
ross.scroggs@gmail.com
