### ISSUE TITLE
'gam info user' command

### ISSUE THREAD

**Issue by IRISPAT** [jay0lee/GAM#629]
Hi,

On gam, I use the 'gam info user' command to see the details of google accounts.
Accounts are synchronized with GDCS. Synchronizations are running correctly.
At the launch of the command, I do not have the same information while google and Active Directory accounts are created in the same way.
See Attachment

Thank you for your answers.

Regards,

![gam1](https://user-images.githubusercontent.com/33458203/32500681-49e23778-c3d6-11e7-99b4-484ed04ffee7.jpg)
![gam2](https://user-images.githubusercontent.com/33458203/32500682-4a00fea6-c3d6-11e7-81d4-08195abd9f78.jpg)
![gam3](https://user-images.githubusercontent.com/33458203/32500683-4a1d97b4-c3d6-11e7-8b16-483178748e4f.jpg)

**Comment by IRISPAT** [comment]
It's google support that asked me to open an ticket here ;)

**Comment by jay0lee** [comment]
GAM is simply displaying what Google servers are telling it for the user. If the issue is setting the values in Google then it's a problem with your GCDS setup or on Google's end.
