### ISSUE TITLE
Help in updating a list of users in csv file. 

### ISSUE THREAD

**Issue by SumitKumarS** [jay0lee/GAM#637]
I have to update a list of users with their Phone number, Title, department, Extension number, manager's name.  I have used gam commands to update single user at a time but never with multiple users using csv or batch file.

Any help will be appreciated.

**Comment by taers232c** [comment]
See: https://github.com/jay0lee/GAM/wiki/BulkOperations <https://github.com/jay0lee/GAM/wiki/BulkOperations>
--
ross.scroggs@gmail.com

**Comment by SumitKumarS** [comment]
Hello,

I did try to follow the article but no luck.  Can you help with with me command ? I hope I am not asking too much.

I have CSV sheet with below header to update in G suite.
Empl ID | Name | Title | EMail Address | Phone | Department | Location Description | Manager

**Comment by jay0lee** [comment]
Please move this discussion to the mailing list, the issue tracker is for bugs / FRs.

https://groups.google.com/group/google-apps-manager
