### ISSUE TITLE
ERROR: 1411 - Invalid Encryption Public Key Format

### ISSUE THREAD

**Issue by tony-nz** [jay0lee/GAM#638]
I have followed the steps on the wiki (https://github.com/jay0lee/GAM/wiki/ExamplesAccountAuditing#using-gpg-with-audits) but still seem to get the 1411 error.  I have tried gpg --gen-key --expert and also gpg --full-generate-key

Here is the key I have generated:

```
Sysadmins-iMac:gam sysadmin$ gpg --list-keys
/Users/sysadmin/.gnupg/pubring.kbx
----------------------------------
pub   rsa1024 2017-12-13 [SC]
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
uid           [ultimate] sysadmin <sysadmin@XXXXXXXXXXX>
sub   rsa1024 2017-12-13 [E]
```

And this is how I am uploading the key,

```
Sysadmins-iMac:gam sysadmin$ gpg --export --armor -a "sysadmin" | /Users/sysadmin/Downloads/gam/gam audit uploadkey

ERROR: 1411 - Invalid Encryption Public Key Format
```

**Comment by jay0lee** [comment]
Audit exports / keys were removed from GAM some time ago and are no longer supported.

Having said that, you may want to try generating a 2048 bit key and see if that works.
