### ISSUE TITLE
ERROR: 403: Not Authorized to access this resource/api

### ISSUE THREAD

**Issue by jcogo** [jay0lee/GAM#639]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
- running GAM 4.32
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
gam delete alias <alias>

Full steps to reproduce the issue:
1. Run: gam delete alias <alias> -- This works but break inside of a loop
2. Run: for i in $(cat /Users/Shared/emails.csv); gam delete alias "$i"; done -- This receives the error ERROR: 403: Not Authorized to access this resource/api 

Expected outcome (what are you trying to do?):
The removal on the alias

Actual outcome (what errors or bad behavior do you see instead?):
I receive the ERROR: 403: Not Authorized to access this resource/api when placing the command in the loop. If I take one of the accounts and run it outside of the loop I do no receive the error. I've tried starting gam from scratch with no luck. Kind of at a lost on this.

**Comment by jay0lee** [comment]
This is a permissions issue, not a GAM bug. Please report it to the mailing list for help.

https://groups.google.com/group/google-apps-manager
