### ISSUE TITLE
Unable to get Drive Quota from gam report users

### ISSUE THREAD

**Issue by joaovitoriasilva** [jay0lee/GAM#646]
Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. YES 4.32
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki YES gam report users > something.csv

Full steps to reproduce the issue:
1. Two weels ago, more or less, I did a "gam report users" and one of the CSV columns was drive quota in MB
2. Today I did the command again and that column is not there.

Can you please provided some input on this behavior? I believe I'am doing the right command.
BTW, the "gam report drive" reports 0 data, but I know for sure the users have data in Drive.

**Comment by gabrs88** [comment]
Hi, I have the same problem 
BR

**Comment by taers232c** [comment]
This is not a Gam issue, it is how Google operates.
Do the following two commands and compare the results:
gam report users user testuser1 > today.csv
gam report users user testuser1 date 2018-03-10 > before.csv

The quota values are not available immediately.

Ross

**Comment by jay0lee** [comment]
Right, API is returning some but not all fields here so not a GAM issue. However we can probably improve what GAM does here:

1) API returns a "missing from this report" field on 1st page, we should capture that and add a "required in report" command option that basically says "I want the newest report that contains these fields".

Jay

**Comment by taers232c** [comment]
Jay,

Where do you see a "missing from this report" field?
Here's what I get back from gam report users user testuser1
```
{
u'date': u'2018-03-13',
u'kind': u'admin#reports#usageReport',
u'etag': u'"QNNojSN613EjCqWMovWbEZj8Fik/vyfCADhZNWduBTa27uK46o7Ug9U"',
u'parameters':
 [
  {u'intValue': u'0', u'name': u'classroom:num_courses_created'},
  {u'intValue': u'0', u'name': u'classroom:num_posts_created'},
  {u'stringValue': u'student', u'name': u'classroom:role'},
  {u'datetimeValue': u'1970-01-01T00:00:00.000Z', u'name': u'classroom:last_interaction_time'},
  {u'stringValue': u'Test User1', u'name': u'accounts:admin_set_name'},
  {u'boolValue': False, u'name': u'accounts:is_disabled'},
  {u'stringValue': u'', u'name': u'accounts:disabled_reason'},
  {u'stringValue': u'Test', u'name': u'accounts:first_name'},
  {u'boolValue': False, u'name': u'accounts:is_2sv_enforced'},
  {u'boolValue': False, u'name': u'accounts:is_2sv_enrolled'},
  {u'boolValue': True, u'name': u'accounts:is_delegated_admin'},
  {u'boolValue': False, u'name': u'accounts:is_less_secure_apps_access_allowed'},
  {u'boolValue': False, u'name': u'accounts:is_super_admin'},
  {u'boolValue': False, u'name': u'accounts:is_suspended'},
  {u'stringValue': u'User1', u'name': u'accounts:last_name'},
  {u'intValue': u'2', u'name': u'accounts:num_authorized_apps'},
  {u'intValue': u'1', u'name': u'accounts:num_roles_assigned'},
  {u'intValue': u'0', u'name': u'accounts:num_security_keys'},
  {u'datetimeValue': u'2015-06-29T19:52:28.000Z', u'name': u'accounts:creation_time'},
  {u'datetimeValue': u'2018-03-12T18:30:54.000Z', u'name': u'accounts:last_login_time'},
  {u'datetimeValue': u'1970-01-01T00:00:00.000Z', u'name': u'accounts:last_sso_time'},
  {u'boolValue': False, u'name': u'accounts:user_has_overridden_name'}
  ],
u'entity': {u'profileId': u'xxx', u'userEmail': u'testuser1@rdschool.org', u'type': u'USER', u'customerId': u'xxx'}
}
```

Ross

**Comment by jay0lee** [comment]
Ross, take a look at the full response for all users:

https://developers.google.com/apis-explorer/#p/admin/reports_v1/reports.userUsageReport.get?userKey=all&date=2018-03-13&customerId=PUTSOMETHINGHERE&_h=2&

there's more data than the list of users available but we lose all of that within callGAPIpages()

We need to modify it to return the first page dict plus additional pages instead of a list.

What's sig. here is PARTIAL_DATA_AVAILABLE

**Comment by taers232c** [comment]
Jay,

Thanks, I see it now.

Ross

**Comment by taers232c** [comment]
Jay,

I see a straightforward way to do this, I'll let you know when I've got it.

Ross
