### ISSUE TITLE
`update` command reports success incorrectly

### ISSUE THREAD

**Issue by siminm** [jay0lee/GAM#67]
I've noticed when iterating through a large number of files that sometimes the `update` command will respond with `Successfully updated drive file/folder ID 0B1H-....` but in fact the file remains not updated.

In particular I've tried changing the parentname of a file:

```
10459 2015-05-21 15:23:22,231 [DEBUG] interfaces: Executing: gam_cmd user user1@example.com update drivefile id 0B1H-... parentname "subdir"
10460 2015-05-21 15:23:25,324 [DEBUG] interfaces: Searching for files with query: "mimeType = "application/vnd.google-apps.folder" and "me" in owners and title = "subdir""...
10461 Successfully updated drive file/folder ID 0B1H-...
```

Iterating through a couple hundred files this succeeds most of the time, but ~5% of the time it reports Success while the file remains in the original directory.

**Comment by jay0lee** [comment]
This is likely a propogation issue. Give it 24 hours and then check to see if all the files are moved. When you make a lot of changes all at once in Drive it's possible you may see some inconsistency for a period of time.
