### ISSUE TITLE
Group add - Add as MEMBER Failed: Invalid Input: memberKey

### ISSUE THREAD

**Issue by jkrizajku** [jay0lee/GAM#674]
I am currently on version GAM 4.40. I updated today from GAM 4.32. I am having the issue on both versions.

I noticed today that the command gam update group *group name* add *user name* gives me the error  "Group: *group name*, *user name* Add as MEMBER Failed: Invalid Input: memberKey".

The command gam update group *group name* remove user *user name* gives me this error as well.
"Group: *group name*, *user name* Remove Failed: Resource Not Found: memberKey

This is generated from a script that has multiple groups and uses that has worked in the past. I have not modified the script or Google API settings.

I can run gam info user *user name* and gam info group *group name* with no issues. I can see all the correct output information, so I know I have a valid users and groups.

Gam update org *org name* add user *user name* works correctly.

**Comment by cnottin** [comment]
I have always been on 4.40 at my new job. I just got this same error when trying to update a groups photo. 

gam update group {group email} update photo C:\photo.png
Group: {group email}, photo Update to MEMBER Failed: Missing required field: memberKey

**Comment by taers232c** [comment]
There is no photo attribute for groups, thus Gam assumes that photo is a member.
Are you trying to give all of the members of the group the same photo?
If so, then do: gam group GroupName update photo c:\photo.png

Ross
--
ross.scroggs@gmail.com

**Comment by cnottin** [comment]
This worked! huge oversight on my end. Thanks!
