### ISSUE TITLE
Code cleanup 

### ISSUE THREAD

**Issue by alexwennerberg** [jay0lee/GAM#678]
I want to help contribute to GAM, and in order to do so most effectively, I think there needs to be some housekeeping on the code.

I think a good idea would be to use Pip and a requirements.txt to manage dependencies instead of copy pasting the libraries into the codebase. This could help make #28 easier as well

Currently the bulk of gam is in the 13,000-line gam.py file. I think #147 is a really good idea. Also there are very few classes here, mostly functions. I think separating things into classes would help make the code easier to maintain and document. It also would make pull requests easier.

In reference to #392, I think I good first step would be to [from __future__ import unicode_literals](http://python-future.org/unicode_literals.html) so that the code can use 'somestring' instead of u'somestring'. Do you foresee this causing any issues?

Most of the functions are not documented in the codebase, which makes it difficult to follow and contribute to, since I may inadvertently disrupt a key component. I also think adding some tests would make development a lot easier. 

Stylistically, I think [PEP-8](https://www.python.org/dev/peps/pep-0008/) is a good guide to follow. For example, right now the code uses camelcase and 2 space indents, while using underscores and 4 space indents would make the code more readable & easier for others to contribute to.

I may submit some pull requests for these issues, but given that they would certainly disrupt the codebase a lot, I wanted to OK it with you first. Thanks for all your work on this project!

**Comment by ainola** [comment]
This sort of thinking be most helpful for packaging as currently custom patches need to be applied.

**Comment by jay0lee** [comment]
I think all of these sound very reasonable. Let's start with something relatively simple like unicode_literals. The PR will be huge but in general it should *just work* or fall over completely. Then we can move towards more disruptive changes.
