### ISSUE TITLE
Delete user's calendar data 

### ISSUE THREAD

**Issue by YohanPAY** [jay0lee/GAM#682]
Hi All,

When i use GAM detele user, it doesn't delete user's events.

I have often this question : 

"Could you remove Audrey's( for example) calendar invitations.They block rooms unnecessarily?
Besides, what is the process during departures? It often happens that rooms are reserved for people who are no longer there. "

I search command line for delete events user ?

Someone can help me please?

Regards,

**Comment by ticoombs** [comment]
https://github.com/jay0lee/GAM/wiki/CalendarExamples
