### ISSUE TITLE
Space in home directory name still an issue?

### ISSUE THREAD

**Issue by Shotster** [jay0lee/GAM#686]
I'm running Mac OS 10.12 and just upgraded GAM. Now all I get when typing the "gam" command is

```
-bash: /Users/shot: is a directory
```

The name of my home directory is "shot 1" (there's a space before the 1), although there is another user account named "shot". I suspect this issue might be similar to https://github.com/jay0lee/GAM/issues/487.

I can't do anything at all with GAM right now. Is there anything else I can try?

**Comment by taers232c** [comment]
Your alias for Gam is not properly quoted, look in /Users/shot 1/.bash_profile, what does your alias for gam look like?

Ross
--
ross.scroggs@gmail.com

**Comment by Shotster** [comment]
Ah, ok. I actually copied and pasted exactly what was output by the program when it instructed me to issue that command, so perhaps that message can be updated? Thanks for the tip.

**Comment by jay0lee** [comment]
This should be fixed in the curl installation one liner now. Closing but let me know if you still see issues when rerunning the curl install.
