### ISSUE TITLE
ChromeBooks  Chrome OS

### ISSUE THREAD

**Issue by lamarcheW** [jay0lee/GAM#688]
How do i update Chrome OS using Gam in Bulk (can it be done)
Here is my issue .I'm in a school district that has 10,000 chromebooks half are under ChrOS Ver57.00. I want to update to the latest Version which is 63/64 .after trying to do it Auto. through Google Console . with know success . I contacted Google they Inform me that the console can not be used to update chrome OS that is More than 3 version behind the current version. they said we would have to Touch all 5000

**Comment by jay0lee** [comment]
I've already answered your question here:

https://groups.google.com/d/msg/google-apps-manager/MfRqymMz_DA/BBtQUI3QBQAJ

Jay

**Comment by lamarcheW** [comment]
yes ! thank you Sorry


Lamarche White
Senior Computer Technician/ Data Systems
Cell:862-223-5010
Office:973-470-5236
<mailto:lwhite@passaic-city.k12.nj.us>
<mailto:lwhite@passaic-city.k12.nj.us>lwhite@passa<mailto:lwhite@passaic-city.k12.nj.us>icschools.org
Passaic Public School District

“A winner is someone who recognizes his God-given talents, works his tail off to develop them into skills, and uses these skills to accomplish his goals.”
                                                                                                                        Larry Bird
________________________________
