### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by robbybarnes** [jay0lee/GAM#69]
Is it possible to set this up to work with and authenticate with multiple domains?  I am a super admin in two different domains, and would love to be able to use this in both domain systems without having to switch users on my computer.

**Comment by andrewbirch** [comment]
I have a fairly friendly system on my Mac, where I have three aliases in 
.bashrc as follows:

alias gamd1='python ~/sysadmin/googlemail/gamd1/gam.py'
alias gamd2='python ~/sysadmin/googlemail/gamd2/gam.py'
alias gamd3='python ~/sysadmin/googlemail/gamd3/gam.py'

where the folders are each tailored copies of the GAM distribution.

That is to say I expand the source distribution into each of the 
tailored folders and in each one I set up the apporpriate .json files 
for OAUTH and so on for the relevant domain.

It works well.  One of the really neat things about GAM is that each 
'installation' is independent of each other installation.

**Comment by robbybarnes** [comment]
Perfect.  I will give something like this a try.  Thank you.



robby barnes | robby.barnes@icloud.com <mailto:robby.barnes@icloud.com> | 801.419.6332

**Comment by GI-thub** [comment]
You could just use different OAUTH files, whole lot easier than multiple
installs - I manage several Google Apps instance from the single GAM
installation

https://github.com/jay0lee/GAM/wiki/OAuthKeyManagement#selecting-which-oauth-key-file-to-use


 Graham Ingleby | Cloud Computing Consultant | 01344 203395 |
gingleby@ancoris.com
[image: Google+] <http://google.com/+Ancoris>
<http://www.linkedin.com/company/98835>  <http://www.ancoris.com>

On 12 June 2015 at 07:35, Robby Barnes <notifications@github.com> wrote:

> Perfect. I will give something like this a try. Thank you.
>
>
>
> robby barnes | robby.barnes@icloud.com <mailto:robby.barnes@icloud.com> |
> 801.419.6332
>
> > On Jun 12, 2015, at 12:33 AM, Andrew Birch <notifications@github.com>
> wrote:
> >
> > I have a fairly friendly system on my Mac, where I have three aliases in
> > .bashrc as follows:
> >
> > alias gamd1='python ~/sysadmin/googlemail/gamd1/gam.py'
> > alias gamd2='python ~/sysadmin/googlemail/gamd2/gam.py'
> > alias gamd3='python ~/sysadmin/googlemail/gamd3/gam.py'
> >
> > where the folders are each tailored copies of the GAM distribution.
> >
> > That is to say I expand the source distribution into each of the
> > tailored folders and in each one I set up the apporpriate .json files
> > for OAUTH and so on for the relevant domain.
> >
> > It works well. One of the really neat things about GAM is that each
> > 'installation' is independent of each other installation.
> >
> >
> > On 12/06/2015 16:21, Robby Barnes wrote:
> > >
> > > Is it possible to set this up to work with and authenticate with
> > > multiple domains? I am a super admin in two different domains, and
> > > would love to be able to use this in both domain systems without
> > > having to switch users on my computer.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/jay0lee/GAM/issues/69>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/jay0lee/GAM/issues/69#issuecomment-111378594>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/69#issuecomment-111378907>.
>

-- 


------------------------------

This message is for the named person's use only.  If you receive this message in error, please delete it and notify the sender.  Ancoris reserves the right to monitor all e-mail communications through its networks. Ancoris Limited, Registered in England Number: 04830784, Registered address: 5a Frascati Way, Maidenhead, Berkshire SL6 4UY. Trading Address: Lily Hill House, Lily Hill Road, Bracknell, Berkshire RG12 2SJ

------------------------------

**Comment by philippescar** [comment]
I create a bash script to do this:

#!/bin/bash
#GAM change Domain Script

echo "Please inform yor domain domain.com"
read filename

if [ ! -f oauth2.txt ]; then
mv oauth2.txt oauth2.txt.old
cp $filename.txt oauth2.txt
else
cp $filename.txt oauth2.txt

python gam.py info domain

fi

Philippe Carvalho
*Contato:* bakudani <http://goog_55869262>@gmail.com | *Twitter: *
philippescar <http://twitter.com/philippescar>
*Linkedin: *http://br.linkedin.com/in/philippescar | *Google+: *http://
<http://goog_2091940453>google.com/+PhilippeCarvalhoScar
*Blog: *www.casadeinverno.wordpress.com

*"Where there is a shell, there is a way"*

**Comment by jay0lee** [comment]
Should not be necessary to have multiple installs of GAM. Use the OAUTHFILE environment variable to switch between accounts. Closing this out now.
