### ISSUE TITLE
whocanleavegroup

### ISSUE THREAD

**Issue by chandruzinka** [jay0lee/GAM#694]
i see gam update group <group> who_can_leave_group is not reacting any idea whats the issue?

**Comment by chandruzinka** [comment]
Hi

**Comment by chandruzinka** [comment]
@taers232c : Any idea on this issue?

**Comment by taers232c** [comment]
This is a Google issue, not a GAM issue; see https://issuetracker.google.com/issues/71387748 <https://issuetracker.google.com/issues/71387748>
--
ross.scroggs@gmail.com

**Comment by chandruzinka** [comment]
Thanks Joyolee,

Do we have any gui options to do it?

or

do we have any work around?



Regards,
Chandra shekar.N
Information Technology - II

*Zinka Logistics Solutions Private Limited*
Follow BlackBuck on LinkedIn
<https://www.linkedin.com/company/blackbuck?trk=top_nav_home> | Facebook
<https://www.facebook.com/blackbucklogistics/>

**Comment by chandruzinka** [comment]
Hi Jay,

Is this issue resolved?




Regards,
Chandra shekar.N
Information Technology - II

*Zinka Logistics Solutions Private Limited*
Follow BlackBuck on LinkedIn
<https://www.linkedin.com/company/blackbuck?trk=top_nav_home> | Facebook
<https://www.facebook.com/blackbucklogistics/>

**Comment by jay0lee** [comment]
This is not a GAM issue. Please track G Suite bug above and feel free to discuss on the group:

https://git.io/gam-group
