### ISSUE TITLE
Permission denied in zsh

### ISSUE THREAD

**Issue by martin-juul** [jay0lee/GAM#696]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. **yes**
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
**yes**

**OS**: macOS 10.13.2
**Shell**: zsh 5.4.2 (x86_64-apple-darwin17.3.0)
First time install of GAM.

Full steps to reproduce the issue:
1. Install GAM and setup as described in wiki
2. Type gam in a zsh shell

Expected outcome (what are you trying to do?):

In bash it works as expected.

**Bash**

```
bash-3.2$ gam
GAM 4.40 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.14 64-bit final
google-api-python-client 1.6.4
oauth2client 4.1.2
Darwin-17.3.0-x86_64-i386-64bit x86_64
Path: /Users/snowy/bin/gam

Usage: gam [OPTIONS]...

GAM. Retrieve or set G Suite domain,
user, group and alias settings. Exhaustive list of commands
can be found at: https://github.com/jay0lee/GAM/wiki

Examples:
gam info domain
gam create user jsmith firstname John lastname Smith password secretpass
gam update user jsmith suspended on
gam.exe update group announcements add member jsmith

bash-3.2$ gam info domain
Customer ID: XXXXXXXXX
Primary Domain: XXXXX.com
Primary Domain Verified: True
Customer Creation Time: 2018-01-19T00:22:03.602Z
Default Language: da
Address: ...
```

Actual outcome (what errors or bad behavior do you see instead?):

When i execute GAM in zsh, it errors with `zsh: permission denied: gam`

`sudo` doesn't make a difference, so i guess the issue lies elsewhere. Though i couldn't figure out, how to get GAM to spit out a verbose error.

**Comment by jlmaners** [comment]
Sounds like a local configuration issue. I use gam in zsh on a Mac daily. Would you mind providing the output of the following command when using zsh:

-  `which gam`

**Comment by jay0lee** [comment]
Closing as this is a zsh config issue, not GAM. Feel free to start a discussion on the list though:

https://git.io/gam-group
