### ISSUE TITLE
Sync group with google sheet

### ISSUE THREAD

**Issue by chandruzinka** [jay0lee/GAM#708]
Can you please help me how can we achieve this?

**Comment by jay0lee** [comment]
Please ask how to questions on the mailing list:

https://groups.google.com/forum/m/#!forum/google-apps-manager

**Comment by chandruzinka** [comment]
Hi Jayolee,

No one responded in the google group can you please suggest?

**Comment by taers232c** [comment]
You should post these questions to the Google Groups "GAM for G Suite" group.
To post to this group, send email to google-apps-manager@googlegroups.com.
Visit this group at https://groups.google.com/group/google-apps-manager.

**Comment by chandruzinka** [comment]
Hi Ross,

I have posted it but I did not get any response.

**Comment by taers232c** [comment]
You didn't post it to the discussion group, you posted it to Gam's Issues page which is where you post bug reports.

Follow these directions:

You should post these questions to the Google Groups "GAM for G Suite" group.
To post to this group, send email to google-apps-manager@googlegroups.com <mailto:google-apps-manager@googlegroups.com>.
Visit this group at https://groups.google.com/group/google-apps-manager <https://groups.google.com/group/google-apps-manager>.

Ross
--
ross.scroggs@gmail.com
