### ISSUE TITLE
cannot create group using subdomain

### ISSUE THREAD

**Issue by vinczente** [jay0lee/GAM#709]
Hi,

Just trying to create a group with a subdomain email address:

gam create group name@subdomain.domain.com

the output is:

Creating group name@subdomain.domain.com

ERROR: 403: Domain cannot use apis. - domainCannotUseApis

I can create groups on primary domain using GAM.
Anything obvious I am missing?

**Comment by jay0lee** [comment]
Please move this to the discussion group.

https://git.io/gam-group
