### ISSUE TITLE
Wipe Mobile Account as part of deprovision

### ISSUE THREAD

**Issue by adamehret** [jay0lee/GAM#71]
As part of the de-provisioning process I would like to automate mobile account wipe. I know I can capture a user's device ID's via gam print mobile query , however there does not appear to be a command to just wipe account and not the entire device. Any assistance/advice would be helpful.

**Comment by jay0lee** [comment]
Try:

gam mobile <id> account_wipe

the command has been there for ages it just wasn't documented. I've updated the docs and will close this out now.
