### ISSUE TITLE
Google alert regarding JSON-RPC phase out by March 26, 2019.

### ISSUE THREAD

**Issue by mrunkel** [jay0lee/GAM#711]
Full steps to reproduce the issue:
1. Install GAM
2. Receive email from Google

Expected outcome (what are you trying to do?):
Don't receive email from Google. ;)
Actual outcome (what errors or bad behavior do you see instead?):

Google sent me an email today with the following info:

> Hello Google API Developer,
> 
> We are writing to let you know that the JSON-RPC and Global HTTP batch endpoints will be deprecated on March 26, 2018, and no longer functional from March 25, 2019.
> 
> What is changing?
> We are moving towards a more distributed, high performance architecture where requests go directly to the appropriate API server. Support for the JSON-RPC protocol and Global HTTP Batch was based on an architecture using a single shared proxy to receive requests for all APIs, so we can no longer support these global endpoints. As a result, we will discontinue support for both of these features.
> 
> What do I need to do?
> Please migrate your applications for your affected projects listed below before March 25, 2019. We know that these changes have customer impact and have worked to make the transition steps as clear as possible. Detailed information on how to migrate your existing API Client Libraries can be found on the Google Developers Blog post.
> 
> Your projects listed below will be affected by this change;

_gam created project ID listed here_

> API: licensing@v1
> Global HTTP Batch Endpoint

For easy reference, here are the API docs. https://developers.google.com/api-client-library/javascript/features/batch    No mention there of the impending deprecation and no info on migration.

**Comment by delize** [comment]
Seems like this was "fixed" in this push: https://github.com/jay0lee/GAM/commit/a9025e2abae6eb55b97fec603f021b13c51e1f10

**Comment by jay0lee** [comment]
Yes, this is fixed and will be in next release.
