### ISSUE TITLE
Make GAM pip installable

### ISSUE THREAD

**Issue by jay0lee** [jay0lee/GAM#720]
It should be possible to install GAM via pip. This does not replace the binary installation scripts but does offer a simple install for users who already have Python 2.7 and pip on their system.

First step is to complete #719 but once that's done the process should be pretty straightforward:

https://packaging.python.org/tutorials/distributing-packages/

**Comment by LewisLebentz** [comment]
Would be super useful for FaaS, unfortunately I don't have the knowledge to create a PR to help.

It's the one thing that would fully unlock GAMs potential for us, helping with automation and delegating out controls that aren't possible via admin roles.
