### ISSUE TITLE
Batch Issue - Removing Group Members

### ISSUE THREAD

**Issue by TohokuNick** [jay0lee/GAM#723]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

* Running GAM 4.40 on Windows x64

We have a number of groups we're trying to clean-up as part of a script. 

If I run the batch script below normally, the groups are cleared. 

```
gam update group ttt-KG clear member
gam update group ttt-G12 clear member
gam update group ttt-G34 clear member
gam update group ttt-G56 clear member
gam update group ttt-G7 clear member
gam update group ttt-G8 clear member
gam update group ttt-HSB clear member
gam update group ttt-HSA clear member
```

If I run the script using the command line "GAM batch cleangroups.bat" I get the following results (addresses changed!)

```
Using 8 processes...
Getting members of ttt-g56@ttt.net (may take some time for large groups)...
GGGetting members of ttt-g8@ttt.net (may take some time for large groups)...
etting members of ttt-g12@ttt.net (may take some time for large groups)...
Getting members of ttt-kg@ttt.net (may take some time for large groups)...
etting members of ttt-hsb@ttt.net (may take some time for large groups)...
GGetting members of ttt-g34@ttt.net (may take some time for large groups)...
etting members of ttt-g7@ttt.net (may take some time for large groups)...
Getting members of ttt-hsa@ttt.net (may take some time for large groups)...
Got 25 members...
Group: ttt-g56@ttt.net, Will remove 25 MEMBERs.
Got 33 members...
Group: ttt-g12@ttt.net, Will remove 33 MEMBERs.
Got 20 members...
Group: ttt-kg@ttt.net, Will remove 20 MEMBERs.
Got 42 members...
Group: ttt-hsb@ttt.net, Will remove 42 MEMBERs.
Got 17 members...
Group: ttt-g8@ttt.net, Will remove 17 MEMBERs.
Got 13 members...
Group: ttt-g7@ttt.net, Will remove 13 MEMBERs.
Got 31 members...
Group: ttt-g34@ttt.net, Will remove 31 MEMBERs.
Got 21 members...
Group: ttt-hsa@ttt.net, Will remove 21 MEMBERs.

```
Expected outcome (what are you trying to do?):

When I run the script without the batch - I get the following results
```
Group: ttt-hsa@ttt.net, Will remove 21 MEMBERs.
Using 21 processes...
 Group: ttt-hsa@ttt.net, abc@def.ghi Removed
```

But in the output above, it never uses more processes to actually delete members. 

For now, not running this as a batch command is an easy enough fix - but it is unexpected behavior!

**Comment by taers232c** [comment]
Due to the way Gam is coded you can't do can't do group bulk membership operations inside a gam batch command.
As you've discovered, you must use an external bact scripting method.

Ross
--
ross.scroggs@gmail.com
