### ISSUE TITLE
Group: test@domain.com, naim,hfghf,naim@gmail.com Add as MEMBER Failed: Invalid Input: memberKey

### ISSUE THREAD

**Issue by Wittentry** [jay0lee/GAM#725]
hi every one , i m trying to add members to a group via csv file using this  command
gam update group test@domain.com add member file Desktop\test.csv

but i git this error ! 
Group: test@domain.com, naim,hfghf,naim@gmail.com Add as MEMBER Failed: Invalid Input: memberKey

in the csv file  are they inputs all in one column like this  firstname,lastname,email

any ideas! ?
thankou

**Comment by taers232c** [comment]
If you have a CSV file with a column header, email for example, the command should be:
> gam update group test@domain.com <mailto:test@domain.com> add member csvfile Desktop\test.csv:email
> 
> 
Ross
--
ross.scroggs@gmail.com
