### ISSUE TITLE
Error creating schema

### ISSUE THREAD

**Issue by lacycc** [jay0lee/GAM#726]
When trying to create a custom schema from a batch file, I keep getting Error: Invalid: Expected <gam|commit-batch> even if I use the commit-batch command.

**Comment by taers232c** [comment]
What does your batch file contain? You can have blank lines, lines that start with #, lines that start with gam and lines that contain the word commit-batch.
For example, this line is invalid: create schema MyNewSchema field MyField type bool endfield
It must be: gam create schema MyNewSchema field MyField type bool endfield

Ross
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Let's move the discussion over to:

http://groups.google.com/group/google-apps-manager/

for now, if this is indeed a bug we can re-open but we need full steps to reproduce.
