### ISSUE TITLE
Can't delegate, "Temporary error: 500, Backing off..."

### ISSUE THREAD

**Issue by captainhook** [jay0lee/GAM#727]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
`C:\GAM>gam user finance@domain.com delegate to john@domain.com`

Error:
```
Giving john@domain.com delegate access to finance@domain.com (1/1)
Temporary error: 500, Backing off: 16 seconds, Retry: 4/10
Temporary error: 500, Backing off: 32 seconds, Retry: 5/10
Temporary error: 500, Backing off: 60 seconds, Retry: 6/10
Temporary error: 500, Backing off: 60 seconds, Retry: 7/10
Temporary error: 500, Backing off: 60 seconds, Retry: 8/10
Temporary error: 500, Backing off: 60 seconds, Retry: 9/10
Temporary error: 500, Backing off: 60 seconds, Retry: 10/10
```

Not sure why this is happening today; it was fine on the latest release a few days ago. Is anyone else experiencing this? I'm not sure how to debug.

**Comment by jimcollierGF** [comment]
I'v been seeing the same thing for the last two days.  I'm using newest version (4.40).  Are there any issues I'm not aware of?

**Comment by gokeefe** [comment]
I typically see this when either the delegate or delegator account are suspended. Have you verified that both the delegate and the delegator are active and not suspended?

**Comment by P1err0** [comment]
I have the same problem for a long time. But sometimes it's works, sometimes not. With the same commande to give delegate access.

**Comment by alexcher84** [comment]
Seeing this issue today after I tried the command for this first time.

Is this happening to anyone else? How did you resolve?

Both accounts are active. I even created 2 brand new account and logged into them prior to running command.

Thanks

**Comment by captainhook** [comment]
I suspect this is an issue on Google's side and unfortunately there's no logs to see to help pin down what exactly it is. I have done a clean setup of GAM and it worked for some of the accounts after a few days.

**Comment by Frem0nt** [comment]
For me, to gets the same error.

Here is what worked for me.

Make sure Delegator xxx account shouldn't be assigned Google vault ( if the delegator account is in Google Vault that account will be not having mail access so gam fails therein delegating because Mail service not enabled Turn off Google Vault that automatically assigns G Suite Enterprise license enables mail services. wait for 10 - 20 mins then run gam.

gam user xxx delegate to yyyy
