### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by captainhook** [jay0lee/GAM#733]
Would it be possible to share build instructions in the main README? I understand it's really just running the build scripts, but getting the pre-requisites is the difficult part.
I have tried to figure out from the script files, and it seems on Windows I would need something like VS 2008!

**Comment by taers232c** [comment]
Captain Hook,

Here's a start.

You need:
Python 2.7; either 32-bit or 64-bit or both based on your needs: https://www.python.org/downloads/windows/
PyInstaller: https://www.pyinstaller.org/downloads.html
7-Zip: https://www.7-zip.org/
WiZ Toolset: http://wixtoolset.org/releases/

windows-build.bat has three build sections: 32-bit .zip, 64-bit .zip, 64-build .msi; eliminate the ones you don't want
Edit the path/program names for Python, 7-Zip and WiX Toolset as required.

windows-build.bat 4.4x

Ross
--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
Readme is probably not right for this but a wiki page would be great (pro
tip: anyone with a free GitHub account can edit the wiki)

Jay
