### ISSUE TITLE
Problem running gam batch commands in .sh file on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by wicknet** [jay0lee/GAM#734]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:

1. Installed latest version of gam in /Users/admin/bin/gam
2. created txt file as myshell.sh with gam commands, one per line, such as gam create user xxx or gam update user xxx
3. chmod 755 shell file and then run with bash command.

Expected outcome (what are you trying to do?):

Each line in shell file should run as a gam command: Eg
gam user joe@myschool.org update photo joe.jpg
gam user moe@myschool.org update photo moe.jpg
gam user curly@myschool.org update photo curly.jpg
(the jpg are stored in same directory as shell file, hence no path is given)

Actual outcome (what errors or bad behavior do you see instead?):
myshell.sh: line 1: gam: command not found
myshell.sh: line 2: gam: command not found
myshell.sh: line 3: gam: command not found
myshell.sh: line 4: gam: command not found
myshell.sh: line 5: gam: command not found
myshell.sh: line 6: gam: command not found

However, if I change each gam command in shell file as ./gam, then the batch file runs as expected.
Adding an alias before the commands with  alias gam="/Users/admin/bin/gam/gam" 
does not work. 

This seems to be new behavior of the gam command, as I've been using it for years and setting an alias or using gam.py in bulk batch updates used to work fine.

**Comment by taers232c** [comment]
Wick,

In general aliases are not effective in shell scripts.
I do the followingij my scripts:
#!/bin/bash
gam="/Users/admin/bin/gam/gam"
$gam user joe@myschool.org <mailto:joe@myschool.org> update photo joe.jp
$gam user moe@myschool.org <mailto:moe@myschool.org> update photo moe.jp
$gam user curly@myschool.org <mailto:curly@myschool.org> update photo curly.jpg

Or add ""/Users/admin/bin/gam" tp $PATH.

Ross

--
ross.scroggs@gmail.com

**Comment by wicknet** [comment]
Just tested it.. works great.
Thank you SO much!
