### ISSUE TITLE
Homebrew Formula v2

### ISSUE THREAD

**Issue by Cancun101** [jay0lee/GAM#737]
Back in 2015, Issue #66 brought up the idea of creating a homebrew formula, but the pull request to homebrew never went through.

A later pull request [here](https://github.com/Homebrew/homebrew-core/pull/17416) did not get finished seemingly because they could not create a valid functionality test required in the homebrew formula. Checking gam --version is not good enough, apparently.

As far as I can tell, we may need to build a functionality test for homebrew into gam in order to get a pull request into homebrew-core validated.

Could we get a task team working on this?

**Comment by Cancun101** [comment]
Would it be possible to get a help wanted tag on this?

**Comment by brianyoungblood** [comment]
Happy to help with this effort. I did the pull request last year that never got accepted. Worth noting that during the homebrew formula updates, the formula should handle transferring over oauth2service.json and client_secrets.json to the new version. Or, gam might use a better spot like ```~/.gam``` and instruct new installs to save them there.

**Comment by JP-WBRP** [comment]
Would it help to simply use the commands outlined here for installation and updating using homebrew?
https://github.com/jay0lee/GAM/wiki#mac-and-linux-users

+1 for a homebrew formula to install and update GAM
