### ISSUE TITLE
exit codes

### ISSUE THREAD

**Issue by sewdan11** [jay0lee/GAM#74]
The older versions of gam, prior to the versions using oauth 2.0 used exit codes that can be checked from a dos batch. We upgraded all of our processes using gam ver 3.41 and was disappointed that we can no longer check the errorlevel to find the error numbers. The errors are now sent to stderr. 

We have to redirect stdout to a file to capture the error codes and the format for the user errors are in a different format from the group errors.

Group error examples:
adding owner user@domain.com...Error 409: Member already exists. - duplicate  [returns errorlevel 0 instead of 409]
adding owner user@domain.com...Error 404: Resource Not Found: groupKey - notFound  [returns errorlevel 0 instead of 404]

User error example:
Error 404: Resource Not Found: userKey - notFound [returns errorlevel 404]
exitste is not a valid argument for gam info user [returns errorlevel 3]
Error 404: Resource Not Found: userKey - notFound [returns errorlevel 0 instead of 404]

This issue requires us to parse the stderr to find the error number. Without knowing where the errors numbers will appear in the output, we have missed some. 

Please restore all of the exit codes like the older versions of GAM had.

**Comment by daethnir** [comment]
Exiting with the actual HTTP error codes is not possible. Unix error codes are 0 (success) and 1-255 (failure). So an exit code of 404 would come out as 148, which is meaningless.

Gam absolutely should exit w/ non-zero status when there's a problem (currently will exit success when there are errors) but should pick different error codes. For example it could use

0 - success
1 - failure
2 - partial failure (e.g. some of the commands completed, others did not)
3 - command line unrecognized
4 - not found (your 404)
etc

Could collapse just to 0 (success) and 1 (full or partial error) and have a well-formatted error string to stderr for parsing.

**Comment by sewdan11** [comment]
I understand. Years ago, DOS only supported a limited number of errorlevels too. For my purposes an exit code of 1 for failure would not work for all error conditions. For example, in our password change program, an error 503 (temp backend error) would reschedule this password change in successive retries. An error 404 or 1301 would schedule this for a much later future retry to give the account creation process a chance to catch up. A syntax error is something that would generate an alert.

I don't know what all the errors are. Below are the only ones I found. Is it possible to get a list of the error numbers so that similar error conditions could be considered if they will be combined or replaced? The errors 1301 and 404 could be combined as exit code 4 - 'Resource Not Found'. 

Or, replace these two error numbers with 41 and 44 respectively where 40 indicates "Not Found", the 1 could be a user and 4 a resource. Another suggestion would be to reverse that and make 14 "User Not Found" and 44 "Resource Not Found" where 10 identifies a user and 40 a resource. 4 in the Ones position could mean "Not Found". The single digit errors (0 in Tens position) could include Success and Syntax errors. Whatever a 'Precondition Failed' is could be some other code in the 100's or 200' series or be place in the single digit range (and have a better explanation for what a precondition is). 

Thought?

0 - Success
2 - GAM Syntax Error
404 - Resource Not Found
412 - Precondition Failed - conditionNotMet
503 - Temp backendError
1301 - User Does Not Exist

**Comment by daethnir** [comment]
Why'd you close this issue? I think it would be a great improvement.

**Comment by jwagnerLegacy** [comment]
As much as I'd hate to bring up such an old issue, Exit codes would be tremendously helpful. In Bash, I'd have to do some sort of string manipulation in order to determine the error code, and there's no guarantee that they'll actually be consistent. With Exit codes, I could just do:
```bash
echo $?
```

Even if it were to exit with a status of 1 when there was an error, and 0 when there wasn't, it'd help to narrow down if you'd actually need to waste time with string manipulation, or could just continue on.
