### ISSUE TITLE
Getting "Select Authorized scopes by entering number"

### ISSUE THREAD

**Issue by DesignTrade** [jay0lee/GAM#740]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. I have been using GAM without any issues then suddenly I started getting this.
Please enter 0-23[a|r] or s|u|e|c: 
Select the authorized scopes by entering a number.
Append an 'r' to grant read-only access or an 'a' to grant action-only access.

[*]  0)  Classroom API - counts as 5 scopes
[*]  1)  Cloud Print API
[*]  2)  Data Transfer API (supports readonly)
[*]  3)  Directory API - Chrome OS Devices (supports readonly)
[*]  4)  Directory API - Customers (supports readonly)
[*]  5)  Directory API - Domains (supports readonly)
[*]  6)  Directory API - Groups (supports readonly)
[*]  7)  Directory API - Mobile Devices (supports readonly and action)
[*]  8)  Directory API - Notifications
[*]  9)  Directory API - Organizational Units (supports readonly)
[*] 10)  Directory API - Resource Calendars (supports readonly)
[*] 11)  Directory API - Roles (supports readonly)
[*] 12)  Directory API - User Schemas (supports readonly)
[*] 13)  Directory API - User Security
[*] 14)  Directory API - Users (supports readonly)
[*] 15)  Email Settings API - Delegation
[*] 16)  Group Settings API
[*] 17)  License Manager API
[ ] 18)  Pub / Sub API
[*] 19)  Reports API - Audit Reports
[*] 20)  Reports API - Usage Reports
[ ] 21)  Reseller API
[*] 22)  Site Verification API
[*] 23)  Vault Matters and Holds API (supports readonly)

     s)  Select all scopes
     u)  Unselect all scopes
     e)  Exit without changes
     c)  Continue to authorization
I am not sure what to enter to move past this. everything I have tried does not work.

2. I am using admin login and event went through the installation on another computer, got credentials through google and accepted all.
3.

Expected outcome (what are you trying to do?): I am only adding email address to groups using gam csv /Users/sam/Desktop/arizonaantique.csv gam update group ArizonaAntique add member user ~Email
And it has been working until recent

Actual outcome (what errors or bad behavior do you see instead?): see above returned when I start GAM and run the gam csv

**Comment by PennStater2007** [comment]
Did you ever find a solution to this? I'm running into the same issue.

**Comment by jay0lee** [comment]
Press c to continue. Your seeing this list because GAM doesn't think it's authorized, something happened to your previous authorization....

We are....

**Comment by wingyeonglee** [comment]
When I saw this screen, I wrongly selected "0" only and press continue.  Because of this selection, I cannot use group information in GAM.  Can I select the APIs again?
-----------------------------------------------------------------
Full steps to reproduce the issue:

I have been using GAM without any issues then suddenly I started getting this.
Please enter 0-23[a|r] or s|u|e|c:
Select the authorized scopes by entering a number.
Append an 'r' to grant read-only access or an 'a' to grant action-only access.
[] 0) Classroom API - counts as 5 scopes
[] 1) Cloud Print API
[] 2) Data Transfer API (supports readonly)

**Comment by taers232c** [comment]
Do:
gam oauth delete
gam oauth create
--
ross.scroggs@gmail.com
