### ISSUE TITLE
Google Classroom API Integration?

### ISSUE THREAD

**Issue by ChThomas** [jay0lee/GAM#76]
Any chance you guys would be implementing the new Classroom API into GAM?

http://googleforeducation.blogspot.com/2015/06/new-ways-to-integrate-with-Google-Classroom.html

**Comment by jay0lee** [comment]
Yes, I plan to release this late this week or next.

Out of curiosity, how would you use this?

Jay

**Comment by ChThomas** [comment]
Thanks for the quick reply. Requesting features from developers is
something new to me and I'm surprised with how quickly the developers on
larger projects respond.

I'm not completely sure right now. I'm about to request early access so I
can see what the API would allow us to do.

First thoughts, as their post says, would be to take an export from our
SIS/LMS (MIStar/Moodle) and create Google Classrooms for our teachers and
populate the classes with students. One of the complaints I had from
teachers this year when they did test out Classrooms was that it was
cumbersome to get the class going.

With the shared teaching model they added recently I could also see
throwing a script that would, let's say, take all the teachers in one
middle school and I could share the Classroom with their Principal or
Assistant Principal.

I guess a lot will depend on what Google allows us access to in the API.

Chris Thomas
Technical Systems Coordinator
Bloomfield Hills Schools
p: 248.341.6362
f:  248.341.6399
