### ISSUE TITLE
GAM usage by non super admins 

### ISSUE THREAD

**Issue by daubneyi** [jay0lee/GAM#77]
gam 3.45 x64 (Windows 8.1).

I am wondering if the tool supports admins who are user created (non super admins)?

Does anyone have any experience with this?

Also how does one get back to the original scopes screen?

Select the authorized scopes for this token. Include a 'r' to grant read-only
access or an 'a' to grant action-only access.

[*]  0)  Group Directory API (supports read-only)
[*]  1)  Organizational Unit Directory API (supports read-only)
[*]  2)  User Directory API (supports read-only)
[*]  3)  Chrome OS Device Directory API (supports read-only)
[*]  4)  Mobile Device Directory API (supports read-only and action)
[*]  5)  User Email Settings API
[*]  6)  Calendar Resources API
[*]  7)  Audit Monitors, Activity and Mailbox Exports API
[*]  8)  Admin Settings API
[*]  9)  Groups Settings API
[*] 10)  Calendar Data API (supports read-only)
[*] 11)  Audit Reports API
[*] 12)  Usage Reports API
[*] 13)  Drive API (create report documents for admin user only)
[*] 14)  License Manager API
[*] 15)  User Security Directory API
[*] 16)  Notifications Directory API
[*] 17)  Site Verification API
(*) 18)  IMAP/SMTP Access (send notifications to admin)
(*) 19)  User Schemas (supports read-only)

     20)  Select all scopes
     21)  Unselect all scopes
     22)  Continue

Thanks in advance,

**Comment by jay0lee** [comment]
Can you post your question in the GAM discussion list:

https://groups.google.com/forum/#!forum/google-apps-manager

the issue tracker is meant for bug reports and doesn't do well with discussions. Happy to respond over on the list.
