### ISSUE TITLE
Vault export with everyone and other parameters syntax issue

### ISSUE THREAD

**Issue by maroc-cloud** [jay0lee/GAM#779]
GAM Version 4.60

The following command returns an error : 

`gam create export matter daily-exports name "2018-08-06" corpus mail scope all_data everyone start 2018-08-06 end 2018-08-07 format pst`

`ERROR 2018-08-06 is not a valid argument for "gam create export".`

It works when using everyone to the end of the command : 

`gam create export matter daily-exports name "2018-08-06" corpus mail scope all_data start 2018-08-06 end 2018-08-07 format pst everyone`

**Comment by taers232c** [comment]
This is corrected in PR #777
