### ISSUE TITLE
Update Course Command ERROR

### ISSUE THREAD

**Issue by MagnoliaGirl** [jay0lee/GAM#780]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Running the following command to update the Google Classroom course: 
scrowell-mbp:gam scrowell$ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course alias ~alias name ~name section ~section description ~description teacher ~teacher status ~status

2018-9011-01 is the alias of my course

2. I've also tried using the courseID in the CSV file instead of the alias
3.

Expected outcome (what are you trying to do?): I'm trying to update the status of the course that I just created to make sure I can runs these commands properly. I have many courses that need to be updated and they must be done in bulk.

Actual outcome (what errors or bad behavior do you see instead?):

ERROR: 2018-9011-01 is not a valid argument to "gam update course"

**Comment by taers232c** [comment]
MagnoliaGiri,

You haven't indicated what course you're trying to update:

$ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course alias ~alias name ~name section ~section description ~description teacher ~teacher status ~status

If you're trying to update the course with alias ~alias then the proper command is:

$ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course d:~~alias~~ name ~name section ~section description ~description teacher ~teacher status ~status

You specify a course by it's id or alias, if you're using the alias you put d: infront of the alias.

Ross
--
ross.scroggs@gmail.com

**Comment by MagnoliaGirl** [comment]
But I have the all of the aliases in the CSV. I’m trying to do them in bulk because I have so many.

Suzanne Magnolia Crowell ‘95
Technology Integrator
scrowell@olgchs.org<mailto:scrowell@olgchs.org>

17301 Old Vic Blvd
Olney, MD 20832
p: 240.283.3220
OLGCHS.ORG<http://www.olgchs.org/>
WE INSPIRE OUR STUDENTS TO EXCEL, SERVE, AND LOVE.

On Aug 19, 2018, at 11:07 AM, Ross Scroggs <notifications@github.com<mailto:notifications@github.com>> wrote:

MagnoliaGiri,

You haven't indicated what course you're trying to update:

$ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course alias ~alias name ~name section ~section description ~description teacher ~teacher status ~status

If you're trying to update the course with alias ~alias then the proper command is:

$ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course d:~~alias~~ name ~name section ~section description ~description teacher ~teacher status ~status

You specify a course by it's id or alias, if you're using the alias you put d: infront of the alias.

Ross
--
ross.scroggs@gmail.com<mailto:ross.scroggs@gmail.com>

**Comment by taers232c** [comment]
Suzanne,

You can stll use the CSV file, it's just that the format of your command is incorrect.

This is the command you want:
> $ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course d:~~alias~~ name ~name section ~section description ~description teacher ~teacher status ~status 

It specifies:
   the source (csv 2018classesupdate.csv)
   the action (update)
   the object (course d:~~alias~~)
   the changes: name ~name section ~section description ~description teacher ~teacher status ~status


Ross
--
ross.scroggs@gmail.com

**Comment by MagnoliaGirl** [comment]
Now I’m getting the following errors:

scrowell-mbp:gam scrowell$ /Users/scrowell/bin/gam/gam csv archivetest.csv gam update course d:~~id~~ status ~status
Using 2 processes...

ERROR: 404: Requested entity was not found. - notFound

ERROR: 404: Requested entity was not found. - notFound


My CSV looks like this. I pulled those IDs from a command to print courses to drive since I don’t know the alias’s of them.
[cid:1E048201-B4C6-4518-A58E-A33BA4756794@OLGCHS.ORG]


This is what printed to drive so I grabbed the IDs from here.
[cid:F2538FA3-2117-4EE4-A455-A40FA96C0245@OLGCHS.ORG]




Suzanne Magnolia Crowell ‘95
Technology Integrator
scrowell@olgchs.org<mailto:scrowell@olgchs.org>

17301 Old Vic Blvd
Olney, MD 20832
p: 240.283.3220
OLGCHS.ORG<http://www.olgchs.org/>
WE INSPIRE OUR STUDENTS TO EXCEL, SERVE, AND LOVE.

On Aug 19, 2018, at 7:29 PM, Ross Scroggs <notifications@github.com<mailto:notifications@github.com>> wrote:

Suzanne,

You can stll use the CSV file, it's just that the format of your command is incorrect.

This is the command you want:
> $ /Users/scrowell/bin/gam/gam csv 2018classesupdate.csv gam update course d:~~alias~~ name ~name section ~section description ~description teacher ~teacher status ~status

It specifies:
the source (csv 2018classesupdate.csv)
the action (update)
the object (course d:~~alias~~)
the changes: name ~name section ~section description ~description teacher ~teacher status ~status


Ross
--
ross.scroggs@gmail.com<mailto:ross.scroggs@gmail.com>
