### ISSUE TITLE
gam info domain - KeyError: u'language'

### ISSUE THREAD

**Issue by jalmeroth** [jay0lee/GAM#787]
Full steps to reproduce the issue:
1. gam info domain

Actual outcome (what errors or bad behavior do you see instead?):
Traceback (most recent call last):
<code>
  File "/Users/jan/R-D/gam/src/gam.py", line 13170, in <module>
    sys.exit(ProcessGAMCommand(sys.argv))
  File "/Users/jan/R-D/gam/src/gam.py", line 12575, in ProcessGAMCommand
    doGetDomainInfo()
  File "/Users/jan/R-D/gam/src/gam.py", line 1722, in doGetDomainInfo
    doGetCustomerInfo()
  File "/Users/jan/R-D/gam/src/gam.py", line 1752, in doGetCustomerInfo
    print u'Default Language: %s' % customer_info[u'language']
KeyError: u'language'
</code>

I checked the response for this client from the [API](https://developers.google.com/admin-sdk/directory/v1/reference/customers/get). It is actually not returning any language-key, so I suppose it should default to 'en' as stated in the [overview](https://developers.google.com/admin-sdk/directory/v1/reference/customers).

**Comment by jay0lee** [comment]
What do you see if you go to admin.google.com > Company profile > Profile ?

Jay

**Comment by jalmeroth** [comment]
![screen shot 2018-08-29 at 14 36 50](https://user-images.githubusercontent.com/4163868/44788023-31e16080-ab99-11e8-8e72-513d27971786.png)
