### ISSUE TITLE
Removing / Updating an Alias that contains uppercase letters

### ISSUE THREAD

**Issue by Henriquezla** [jay0lee/GAM#795]
Version: 4.61

Full steps to reproduce the issue:

1. Use GAM to delete an Alias that contains uppercase characters. For instance:
Gam delete Alias John.smith@domain.xyz

Expected outcome (what are you trying to do?):
The Alias should be deleted. 

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: 400: Type not supported: userKey - badRequest

More details:
The directory API allows for deletion of aliases. The Alias key provided is case-sensitive. 

What I found out after enabling debugging in GAM is that the POST request to delete the Alias is always sent as all lower-case:
send: 'DELETE /admin/directory/v1/users/john.smith%40domain.xyz/aliases/john.smith%40domain.xyz

Also, creating an Alias or username is always sent as lower-case, even when the user entered in the command line contains uppercase letters.

**Comment by taers232c** [comment]
It only seems to be delete where Google is case sensitive.
These work:
gam whatis john.smith@domain.xyz <mailto:john.smith@domain.xyz>
gam info user john.smith@domnain.xyz <mailto:john.smith@domnain.xyz>
gam info alias john.smith@domain.xyz <mailto:john.smith@domain.xyz>

Ross

--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Report: gam version
--
ross.scroggs@gmail.com

**Comment by Henriquezla** [comment]
Edited original post to add version.
