### ISSUE TITLE
gam create guardianinvite Error: 403

### ISSUE THREAD

**Issue by christbate** [jay0lee/GAM#797]
I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
**1. gam create guardianinvite student@schooldomain.edu parent@gmail.com**

Expected outcome (what are you trying to do?):
**Send a guardian invite to the parent of the student**

Actual outcome (what errors or bad behavior do you see instead?):
**ERROR: 403: The caller does not have permission - forbidden**

Following other advise I have revoked OAuth token and rerun the command, ensuring all scopes have been enabled. Many other commands work, including printing course info, however gam create guardianinvite is always 403ing.

**Comment by taers232c** [comment]
You've reversed the student and guardin email addresses:
gam create guardian|guardianinvite|inviteguardian <EmailAddress> <StudentItem>
> gam create guardianinvite parent@gmail.com <mailto:parent@gmail.com> student@schooldomain.edu <mailto:student@schooldomain.edu>
Ross
--
ross.scroggs@gmail.com
