### ISSUE TITLE
Showing Delegated Contacts

### ISSUE THREAD

**Issue by lucafabbri365** [jay0lee/GAM#798]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. `gam user <address> delegate to <address>`

Expected outcome (what are you trying to do?):
I'm trying to assign contacts delegation (not only email).
As written here [GAM --> Delegates](https://github.com/jay0lee/GAM/wiki/ExamplesEmailSettings#delegates): "_A delegate is someone who has been given access to someone else's email and contacts. The delegator is the one whose email and contacts are accessible by the delegate._"

Actual outcome (what errors or bad behavior do you see instead?):
I don't see any error, however I cannot see contacts from delegated mailbox. How can I access to contacts from delegated mailbox ?

Thank you,
Luca

**Comment by mattfippard** [comment]
I don't see that this is a GAM issue, it appears that this is a side effect of the new Gmail and contacts being split into different apps

> Use the old Contact Manager. Delegation won't work in Contacts preview.
from [G Suite Administrator help](https://support.google.com/a/answer/2590392?hl=en)

**Comment by lucafabbri365** [comment]
Hello @mattfippard,
yes you are right. It isn't present in Contacts preview yet.

Thank you,
Luca
