### ISSUE TITLE
gam setting user forwarding address

### ISSUE THREAD

**Issue by fogait** [jay0lee/GAM#799]
Hi,

i'm trying to set a forwarding address to a set of users to an external domain.
I can add the external address to each user but when i want to enable the forwarding i received an error message.

Cmdlets:
gam user jane.doe@xpto.com add forwardingaddress jane.do@xpto.onmicrosoft.com
gam user jane.doe@xpto.com forward on jane.do@xpto.onmicrosoft.com keep

ERROR: 400: Invalid forwarding address - failedPrecondition

is there a workaround or correction required?

Thanks!
Best Regards

**Comment by jay0lee** [comment]
Please move this to the discussion group.

**Comment by AllenBaugh** [comment]
@jay0lee i am new here were is this discussion group for the above forwarding topic? thanks
