### ISSUE TITLE
error 404 show delegates

### ISSUE THREAD

**Issue by picklzfan** [jay0lee/GAM#801]
I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  Type gam group legal show delegates

Expected outcome (what are you trying to do?):
Show all accounts who have delegate access to the legal mailbox.

Actual outcome (what errors or bad behavior do you see instead?):
Command returns: 
Getting all members of legal@ourdomain.org (may take some time for large groups)...

ERROR: 404: Resource Not Found: groupKey - groupNotFound

**Comment by jay0lee** [comment]
This is most likely due to an issue with that Group (like it not existing) not a GAM issue.
