### ISSUE TITLE
Running `gam calendar` via `gam csv` ignores the `sendnotifications false` flag

### ISSUE THREAD

**Issue by arkadiyt** [jay0lee/GAM#802]
Full steps to reproduce the issue:
Run the command `gam print users | gam csv - gam calendar ~primaryEmail add editor group google-calendar-admin@mydomain.com sendnotifications false`

Expected outcome (what are you trying to do?):
Should add people without sending notification emails

Actual outcome (what errors or bad behavior do you see instead?):
Sends 1 notification email per person in the organization

**Comment by taers232c** [comment]
This option is not included in standard Gam; i have submitted code to Jay that adds support for sendnothfications.

Ross
--
ross.scroggs@gmail.com

**Comment by arkadiyt** [comment]
My bad, I was searching for google calendar admin solutions and came upon this thread:
https://groups.google.com/forum/#!topic/google-apps-manager/aI2eSb-1MMo

and didn't realize that there were actually 2 GAM projects
