### ISSUE TITLE
gam print cros full

### ISSUE THREAD

**Issue by irichardsonMarkerstudy** [jay0lee/GAM#804]
Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. I previously ran the command (gam print cros full | convertfrom-csv) in powershell and it would return all the values as you would expect.  I then selected the columns for device, asset and recentUsers.0.email so i can pass this onto our asset management team.
2. Now when i run the above command all of the formatting is way off.
3. If i run Basic or target a single deviceid i'm able to get the information but not in the format i need.

Expected outcome (what are you trying to do?):
The expected outcome is the objects are all returned in a csv file

Actual outcome (what errors or bad behavior do you see instead?):
Below is a extract from the top of the output file.

Thanks for any help

deviceId                                            : 037ca4b0-cce2-40c0-9115-3ee96cfd0872
activeTimeRanges.0.activeTime                       : 240002
activeTimeRanges.0.date                             : 2018-09-27
activeTimeRanges.1.activeTime                       : 3810033
activeTimeRanges.1.date                             : 2018-10-04
activeTimeRanges.10.activeTime                      : 
activeTimeRanges.10.date                            : 
activeTimeRanges.11.activeTime                      : 
activeTimeRanges.11.date                            : 
activeTimeRanges.12.activeTime                      : 
activeTimeRanges.12.date                            : 
activeTimeRanges.2.activeTime                       : 23700176
activeTimeRanges.2.date                             : 2018-10-05
activeTimeRanges.3.activeTime                       : 60000
activeTimeRanges.3.date                             : 2018-10-08
activeTimeRanges.4.activeTime                       : 
activeTimeRanges.4.date                             : 
activeTimeRanges.5.activeTime                       : 
activeTimeRanges.5.date                             : 
activeTimeRanges.6.activeTime                       : 
activeTimeRanges.6.date                             : 
activeTimeRanges.7.activeTime                       : 
activeTimeRanges.7.date                             : 
activeTimeRanges.8.activeTime                       : 
activeTimeRanges.8.date                             : 
activeTimeRanges.9.activeTime                       : 
activeTimeRanges.9.date                             : 
annotatedAssetId                                    : CB104425
annotatedLocation                                   : 
annotatedUser                                       : enrolme@markerstudy.com
bootMode                                            : Verified
cpuStatusReports.0.cpuTemperatureInfo.0.label       : iwlwifi
cpuStatusReports.0.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.0.cpuTemperatureInfo.1.label       : 
cpuStatusReports.0.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.0.cpuTemperatureInfo.2.label       : 
cpuStatusReports.0.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.0.cpuTemperatureInfo.3.label       : 
cpuStatusReports.0.cpuTemperatureInfo.3.temperature : 
cpuStatusReports.0.cpuTemperatureInfo.4.label       : 
cpuStatusReports.0.cpuTemperatureInfo.4.temperature : 
cpuStatusReports.0.cpuTemperatureInfo.5.label       : 
cpuStatusReports.0.cpuTemperatureInfo.5.temperature : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.0.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.0.reportTime                       : 
cpuStatusReports.1.cpuTemperatureInfo.0.label       : 
cpuStatusReports.1.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.1.cpuTemperatureInfo.1.label       : 
cpuStatusReports.1.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.1.cpuTemperatureInfo.2.label       : 
cpuStatusReports.1.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.1.cpuTemperatureInfo.3.label       : 
cpuStatusReports.1.cpuTemperatureInfo.3.temperature : 
cpuStatusReports.1.cpuTemperatureInfo.4.label       : 
cpuStatusReports.1.cpuTemperatureInfo.4.temperature : 
cpuStatusReports.1.cpuTemperatureInfo.5.label       : 
cpuStatusReports.1.cpuTemperatureInfo.5.temperature : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.1.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.1.reportTime                       : 
cpuStatusReports.2.cpuTemperatureInfo.0.label       : 
cpuStatusReports.2.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.2.cpuTemperatureInfo.1.label       : 
cpuStatusReports.2.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.2.cpuTemperatureInfo.2.label       : 
cpuStatusReports.2.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.2.cpuTemperatureInfo.3.label       : 
cpuStatusReports.2.cpuTemperatureInfo.3.temperature : 
cpuStatusReports.2.cpuTemperatureInfo.4.label       : 
cpuStatusReports.2.cpuTemperatureInfo.4.temperature : 
cpuStatusReports.2.cpuTemperatureInfo.5.label       : 
cpuStatusReports.2.cpuTemperatureInfo.5.temperature : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.2.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.2.reportTime                       : 
cpuStatusReports.3.cpuTemperatureInfo.0.label       : 
cpuStatusReports.3.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.3.cpuTemperatureInfo.1.label       : 
cpuStatusReports.3.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.3.cpuTemperatureInfo.2.label       : 
cpuStatusReports.3.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.3.cpuTemperatureInfo.3.label       : 
cpuStatusReports.3.cpuTemperatureInfo.3.temperature : 
cpuStatusReports.3.cpuTemperatureInfo.4.label       : 
cpuStatusReports.3.cpuTemperatureInfo.4.temperature : 
cpuStatusReports.3.cpuTemperatureInfo.5.label       : 
cpuStatusReports.3.cpuTemperatureInfo.5.temperature : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.3.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.3.reportTime                       : 
cpuStatusReports.4.cpuTemperatureInfo.0.label       : 
cpuStatusReports.4.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.4.cpuTemperatureInfo.1.label       : 
cpuStatusReports.4.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.4.cpuTemperatureInfo.2.label       : 
cpuStatusReports.4.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.4.cpuTemperatureInfo.3.label       : 
cpuStatusReports.4.cpuTemperatureInfo.3.temperature : 
cpuStatusReports.4.cpuTemperatureInfo.4.label       : 
cpuStatusReports.4.cpuTemperatureInfo.4.temperature : 
cpuStatusReports.4.cpuTemperatureInfo.5.label       : 
cpuStatusReports.4.cpuTemperatureInfo.5.temperature : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.4.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.4.reportTime                       : 
cpuStatusReports.5.cpuTemperatureInfo.0.label       : 
cpuStatusReports.5.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.5.cpuTemperatureInfo.1.label       : 
cpuStatusReports.5.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.5.cpuTemperatureInfo.2.label       : 
cpuStatusReports.5.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.5.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.5.reportTime                       : 
cpuStatusReports.6.cpuTemperatureInfo.0.label       : 
cpuStatusReports.6.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.6.cpuTemperatureInfo.1.label       : 
cpuStatusReports.6.cpuTemperatureInfo.1.temperature : 
cpuStatusReports.6.cpuTemperatureInfo.2.label       : 
cpuStatusReports.6.cpuTemperatureInfo.2.temperature : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.1   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.2   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.3   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.4   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.5   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.6   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.7   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.8   : 
cpuStatusReports.6.cpuUtilizationPercentageInfo.9   : 
cpuStatusReports.6.reportTime                       : 
cpuStatusReports.7.cpuTemperatureInfo.0.label       : 
cpuStatusReports.7.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.7.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.7.reportTime                       : 
cpuStatusReports.8.cpuTemperatureInfo.0.label       : 
cpuStatusReports.8.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.8.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.8.reportTime                       : 
cpuStatusReports.9.cpuTemperatureInfo.0.label       : 
cpuStatusReports.9.cpuTemperatureInfo.0.temperature : 
cpuStatusReports.9.cpuUtilizationPercentageInfo.0   : 
cpuStatusReports.9.reportTime                       : 
diskVolumeReports.0.volumeInfo.0.storageFree        : 
diskVolumeReports.0.volumeInfo.0.storageTotal       : 
diskVolumeReports.0.volumeInfo.0.volumeId           : 
diskVolumeReports.0.volumeInfo.1.storageFree        : 
diskVolumeReports.0.volumeInfo.1.storageTotal       : 
diskVolumeReports.0.volumeInfo.1.volumeId           : 
diskVolumeReports.0.volumeInfo.2.storageFree        : 
diskVolumeReports.0.volumeInfo.2.storageTotal       : 
diskVolumeReports.0.volumeInfo.2.volumeId           : 
diskVolumeReports.0.volumeInfo.3.storageFree        : 
diskVolumeReports.0.volumeInfo.3.storageTotal       : 
diskVolumeReports.0.volumeInfo.3.volumeId           : 
diskVolumeReports.0.volumeInfo.4.storageFree        : 
diskVolumeReports.0.volumeInfo.4.storageTotal       : 
diskVolumeReports.0.volumeInfo.4.volumeId           : 
ethernetMacAddress                                  : 
firmwareVersion                                     : 
lastEnrollmentTime                                  : 
lastSync                                            : 
macAddress                                          : 
model                                               : 
notes                                               : 
orgUnitPath                                         : 
osVersion                                           : 
platformVersion                                     : 
recentUsers.0.email                                 : 
recentUsers.0.type                                  : 
recentUsers.1.email                                 : 
recentUsers.1.type                                  : 
recentUsers.10.email                                : 
recentUsers.10.type                                 : 
recentUsers.11.email                                : 
recentUsers.11.type                                 : 
recentUsers.12.email                                : 
recentUsers.12.type                                 : 
recentUsers.13.email                                : 
recentUsers.13.type                                 : 
recentUsers.14.email                                : 
recentUsers.14.type                                 : 
recentUsers.15.email                                : 
recentUsers.15.type                                 : 
recentUsers.16.email                                : 
recentUsers.16.type                                 : 
recentUsers.17.email                                : 
recentUsers.17.type                                 : 
recentUsers.18.email                                : 
recentUsers.18.type                                 : 
recentUsers.19.email                                : 
recentUsers.19.type                                 : 
recentUsers.2.email                                 : 
recentUsers.2.type                                  : 
recentUsers.3.email                                 : 
recentUsers.3.type                                  : 
recentUsers.4.email                                 : 
recentUsers.4.type                                  : 
recentUsers.5.email                                 : 
recentUsers.5.type                                  : 
recentUsers.6.email                                 : 
recentUsers.6.type                                  : 
recentUsers.7.email                                 : 
recentUsers.7.type                                  : 
recentUsers.8.email                                 : 
recentUsers.8.type                                  : 
recentUsers.9.email                                 : 
recentUsers.9.type                                  : 
serialNumber                                        : 
status                                              : 
systemRamFreeReports.0.reportTime                   : 
systemRamFreeReports.0.systemRamFreeInfo.0          : 
systemRamFreeReports.0.systemRamFreeInfo.1          : 
systemRamFreeReports.0.systemRamFreeInfo.2          : 
systemRamFreeReports.0.systemRamFreeInfo.3          : 
systemRamFreeReports.0.systemRamFreeInfo.4          : 
systemRamFreeReports.0.systemRamFreeInfo.5          : 
systemRamFreeReports.0.systemRamFreeInfo.6          : 
systemRamFreeReports.0.systemRamFreeInfo.7          : 
systemRamFreeReports.0.systemRamFreeInfo.8          : 
systemRamFreeReports.0.systemRamFreeInfo.9          : 
systemRamFreeReports.1.reportTime                   : 
systemRamFreeReports.1.systemRamFreeInfo.0          : 
systemRamFreeReports.1.systemRamFreeInfo.1          : 
systemRamFreeReports.1.systemRamFreeInfo.2          : 
systemRamFreeReports.1.systemRamFreeInfo.3          : 
systemRamFreeReports.1.systemRamFreeInfo.4          : 
systemRamFreeReports.1.systemRamFreeInfo.5          : 
systemRamFreeReports.1.systemRamFreeInfo.6          : 
systemRamFreeReports.1.systemRamFreeInfo.7          : 
systemRamFreeReports.1.systemRamFreeInfo.8          : 
systemRamFreeReports.1.systemRamFreeInfo.9          : 
systemRamFreeReports.2.reportTime                   : 
systemRamFreeReports.2.systemRamFreeInfo.0          : 
systemRamFreeReports.2.systemRamFreeInfo.1          : 
systemRamFreeReports.2.systemRamFreeInfo.2          : 
systemRamFreeReports.2.systemRamFreeInfo.3          : 
systemRamFreeReports.2.systemRamFreeInfo.4          : 
systemRamFreeReports.2.systemRamFreeInfo.5          : 
systemRamFreeReports.2.systemRamFreeInfo.6          : 
systemRamFreeReports.2.systemRamFreeInfo.7          : 
systemRamFreeReports.2.systemRamFreeInfo.8          : 
systemRamFreeReports.2.systemRamFreeInfo.9          : 
systemRamFreeReports.3.reportTime                   : 
systemRamFreeReports.3.systemRamFreeInfo.0          : 
systemRamFreeReports.3.systemRamFreeInfo.1          : 
systemRamFreeReports.3.systemRamFreeInfo.2          : 
systemRamFreeReports.3.systemRamFreeInfo.3          : 
systemRamFreeReports.3.systemRamFreeInfo.4          : 
systemRamFreeReports.3.systemRamFreeInfo.5          : 
systemRamFreeReports.3.systemRamFreeInfo.6          : 
systemRamFreeReports.3.systemRamFreeInfo.7          : 
systemRamFreeReports.3.systemRamFreeInfo.8          : 
systemRamFreeReports.3.systemRamFreeInfo.9          : 
systemRamFreeReports.4.reportTime                   : 
systemRamFreeReports.4.systemRamFreeInfo.0          : 
systemRamFreeReports.4.systemRamFreeInfo.1          : 
systemRamFreeReports.4.systemRamFreeInfo.2          : 
systemRamFreeReports.4.systemRamFreeInfo.3          : 
systemRamFreeReports.4.systemRamFreeInfo.4          : 
systemRamFreeReports.4.systemRamFreeInfo.5          : 
systemRamFreeReports.4.systemRamFreeInfo.6          : 
systemRamFreeReports.4.systemRamFreeInfo.7          : 
systemRamFreeReports.4.systemRamFreeInfo.8          : 
systemRamFreeReports.4.systemRamFreeInfo.9          : 
systemRamFreeReports.5.reportTime                   : 
systemRamFreeReports.5.systemRamFreeInfo.0          : 
systemRamFreeReports.5.systemRamFreeInfo.1          : 
systemRamFreeReports.5.systemRamFreeInfo.2          : 
systemRamFreeReports.5.systemRamFreeInfo.3          : 
systemRamFreeReports.5.systemRamFreeInfo.4          : 
systemRamFreeReports.5.systemRamFreeInfo.5          : 
systemRamFreeReports.5.systemRamFreeInfo.6          : 
systemRamFreeReports.5.systemRamFreeInfo.7          : 
systemRamFreeReports.5.systemRamFreeInfo.8          : 
systemRamFreeReports.5.systemRamFreeInfo.9          : 
systemRamFreeReports.6.reportTime                   : 
systemRamFreeReports.6.systemRamFreeInfo.0          : 
systemRamFreeReports.6.systemRamFreeInfo.1          : 
systemRamFreeReports.6.systemRamFreeInfo.2          : 
systemRamFreeReports.6.systemRamFreeInfo.3          : 
systemRamFreeReports.6.systemRamFreeInfo.4          : 
systemRamFreeReports.6.systemRamFreeInfo.5          : 
systemRamFreeReports.6.systemRamFreeInfo.6          : 
systemRamFreeReports.6.systemRamFreeInfo.7          : 
systemRamFreeReports.6.systemRamFreeInfo.8          : 
systemRamFreeReports.6.systemRamFreeInfo.9          : 
systemRamFreeReports.7.reportTime                   : 
systemRamFreeReports.7.systemRamFreeInfo.0          : 
systemRamFreeReports.8.reportTime                   : 
systemRamFreeReports.8.systemRamFreeInfo.0          : 
systemRamFreeReports.9.reportTime                   : 
systemRamFreeReports.9.systemRamFreeInfo.0          : 
systemRamTotal                                      : 
tpmVersionInfo.family                               : 
tpmVersionInfo.firmwareVersion                      : 
tpmVersionInfo.manufacturer                         : 
tpmVersionInfo.specLevel                            : 
tpmVersionInfo.tpmModel                             : 
tpmVersionInfo.tpmVulnerability                     : 
tpmVersionInfo.vendorSpecific                       : 

deviceId                                            : ,23,,,,,,,,,,,62,,,,,,,,,,2018-10-08T07:35:28.954Z,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
                                                      ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2016665600,2016665600,/media/archive,11685888,12042240,/usr/share/oem,2016665
                                                      600,2016665600,/media/removable,,,,,,,0050b697c168,Google_Lars.7820.376.0,2018-09-27T11:21:59.255Z,2018-10-10T07:45:34.091Z,38baf8ce2
                                                      e6c,Chromebook 14 for work (CP5-471),,/,69.0.3497.95,10895.56.0 (Official Build) stable-channel lars,sswaisland@markerstudy.com,USER_
                                                      TYPE_MANAGED,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NXGDDEK0108341791E7600,ACTIVE,2018-10-08T07:35:28.954Z,2889936896,,,,,,,,,,,,,,,,,
                                                      ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,4033331200,312e3200,628,49465800,200000003,ffffffff,VULNERABLE,06280
                                                      0BE0074706D733135FFFF
activeTimeRanges.0.activeTime                       : 
activeTimeRanges.0.date                             : 
activeTimeRanges.1.activeTime                       : 
activeTimeRanges.1.date                             : 
activeTimeRanges.10.activeTime                      : 
activeTimeRanges.10.date                            : 
activeTimeRanges.11.activeTime                      : 
activeTimeRanges.11.date                            : 
activeTimeRanges.12.activeTime                      : 
activeTimeRanges.12.date                            : 
activeTimeRanges.2.activeTime                       : 
activeTimeRanges.2.date                             : 
activeTimeRanges.3.activeTime                       : 
activeTimeRanges.3.date                             : 
activeTimeRanges.4.activeTime                       : 
activeTimeRanges.4.date                             : 
activeTimeRanges.5.activeTime                       : 
activeTimeRanges.5.date                             : 
activeTimeRanges.6.activeTime                       : 
activeTimeRanges.6.date                             : 
activeTimeRanges.7.activeTime                       : 
activeTimeRanges.7.date                             : 
activeTimeRanges.8.activeTime                       : 
activeTimeRanges.8.date                             : 
activeTimeRanges.9.activeTime                       : 
activeTimeRanges.9.date                             : 
annotatedAssetId                                    : 
annotatedLocation                                   :

**Comment by taers232c** [comment]
Google has added some new fields, one of which has an embedded newline in the field name which is throwing everything off. Change your command to selected just the fields you're interested in:
gam print cros fields deviceid,assetid recentusers listlimit 1

Ross

**Comment by irichardsonMarkerstudy** [comment]
Hi Ross,
Thanks yes, I've managed to fix as i saw your other comment on another thread about 20 seconds after i posted this.
Not sure if there is a place for this here or what the scope would be but I've done a simple script that pulls active devices and then shows the most recent person to use it.  I pass this onto the asset dept every 1/2 hour so they have a semi-realtime usage.
