### ISSUE TITLE
gam print groups - Missing group members for some groups

### ISSUE THREAD

**Issue by Hooch76** [jay0lee/GAM#805]
Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki
=> Both confirmed.

Full steps to reproduce the issue:
1. Run: gam print groups name description members delimiter " " sortheaders
2. The output states the following: 
![image](https://user-images.githubusercontent.com/25639197/46734244-f1462e00-cc92-11e8-8adf-1faf94b4b834.png) 
when ennumerating groups (this is correct. The group contains 7 users).

3.The final listing/output but then states 
![image](https://user-images.githubusercontent.com/25639197/46734347-34080600-cc93-11e8-8d83-ea89ebd98ba3.png). 
So the user count is not correct and no users are listed then. This does not happen on all groups, but only a handful of them).

Expected outcome (what are you trying to do?): All group members should be listed and the count is correct.

Actual outcome (what errors or bad behavior do you see instead?): Group member count is zero and no group members are listed.

**Comment by taers232c** [comment]
Gam has code to work around a bug that has come up twice in the Directory AP.I. If Gam asked for members only (what you've done) the API would return members, managers and owners all labelled as members. To avoid this bug in case it returns, Gam downloads the entire group membership and then does it's own filtering to select the membership category you specified. If you want to see all membership categories, your command should be: gam print groups name description members managers owners delimiter " " sortheaders

Ross

**Comment by Hooch76** [comment]
That did the trick. Thank you!
