### ISSUE TITLE
User Calendar Objects are not accessible for suspended users - 403

### ISSUE THREAD

**Issue by ticoombs** [jay0lee/GAM#806]
### Full steps to reproduce the issue:

```
1. gam create user joe@acme.com
2. gam user joe@acme.com add calendar joe@acme.com selected false
3. gam user joe@acme.com show calendars
3.1 #output shows calendars
4. gam update user joe@acme.com suspended on
5. gam user joe@acme.com show calendars

ERROR: 403: The user must be signed up for Google Calendar. - notACalendarUser

```

This also happens to all gam commands I've tested on the user regarding calendars. 
- gam user <user> show calendars
- gam user <user> print calendars

This also happens when trying to access the "calendar" as well. (which is weird)
- gam calendar <user> showacl

### Expected outcome (what are you trying to do?):

Returns a list of all attached calendars that the user has access to. 

### Actual outcome (what errors or bad behavior do you see instead?):

I am getting a 403 as if the user does not exist anymore inside the "Calendar" 

### Workaround:

I can blindly assign the suspended users calendar to the "newuser".
By doing a `gam user bill@acme.com add calendar joe@acme.com` 

### Notes:

This does not affect creating a document transfer of calendar resources.

**Comment by ticoombs** [comment]
Cheers Ross! Figured as such 👍

**Comment by jdsalaro** [comment]
For those facing this issue and looking to follow progress on this, I've opened an issue on the Google Calendar issue tracker over at https://issuetracker.google.com/issues/175796488
