### ISSUE TITLE
Question: Group membership for a specific user

### ISSUE THREAD

**Issue by jonathanjacob** [jay0lee/GAM#81]
Is there a command to "Retrieve all groups for a member"? I can't seem to find one in the wiki section. I See that this is possible in the directory api (https://developers.google.com/admin-sdk/directory/v1/guides/manage-groups#get_all_member_groups)

Thanks!

**Comment by jonathanjacob** [comment]
I found the answer. It seems like it is possible by using "info user.name" and some flags.

**Comment by jonathanjacob** [comment]
I see that per the documentation for `gam info user user.name` "GAM will retrieve the user's group membership which results in an additional API call." Is it possible to create a command that will run only this command without any user information(or am I missing one)?

**Comment by jay0lee** [comment]
This is an issue/bug tracker. Please post general how to questions to the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager
