### ISSUE TITLE
Finished process issue

### ISSUE THREAD

**Issue by Quiita** [jay0lee/GAM#812]
Is there a way to remove this error from repeating, is there a way to put like a condition to kill the process once this error appears!
https://image.ibb.co/kBGPJA/D0-B73-B1-E-B6-CE-4216-B57-B-C648-EC9-EF838.jpg

**Comment by jay0lee** [comment]
there's not. This indicates most processes are done but one has hung or is taking a really long time to finish. Does this reproduce consistently for you?
