### ISSUE TITLE
Feature Request, Add --customerId and --gaDomain as parameters

### ISSUE THREAD

**Issue by ghost** [jay0lee/GAM#815]
Hi there,

Could you add customerId and gaDomain as parameters to the gam command?
This would help using a CSV over multiple domains.

Regards,

Thomas

**Comment by taers232c** [comment]
Thomas,

My Advanced Gam (https://github.com/taers232c/GAMADV-XTD) supports multiple customers/domains see: https://github.com/taers232c/GAMADV-XTD/wiki/gam.cfg <https://github.com/taers232c/GAMADV-XTD/wiki/gam.cfg>

There are sections in the gam.cfg that identify customers/domains; if you have a column in your CSV file that identifes the section, then you can do whatt you want.
Sample.csv
Section,Header1.Header2
customer1,blah,blah
customer2,blah,blah

gam csv Sample.csv gam select ~Section some command ~Header1 ... ~Header2


Ross

--
ross.scroggs@gmail.com

**Comment by jay0lee** [comment]
You can set these parameters with environment variables:
export CUSTOMER_ID=nnnn
export GAM_DOMAIN=nnnn
