### ISSUE TITLE
gam info user --- Profile Thumbnail URL

### ISSUE THREAD

**Issue by DarkSir23** [jay0lee/GAM#817]
Recently, gam info user &lt;user&gt; has started returning the missing picture silhouette url rather than an actual profile picture URL.  Has something changed in gam, or perhaps in what google returns from the API?

**Comment by jay0lee** [comment]
As far as I can tell you may need to be a member of the user's domain to retrieve the URL (and authenticated, not just calling CURL or wget). GAM can download the photo since it authenticates to do so.
