### ISSUE TITLE
GAM only checks current directory for client_secrets.json

### ISSUE THREAD

**Issue by KeenRivals** [jay0lee/GAM#82]
**Platform**: Windows 64-bit
**Version**: 3.51

I have GAM installed to `C:\users\user\Applications\gam` and have that included in my PATH variable so I can use GAM anywhere. After updating to 3.51 I'm being prompted to create my client_secrets.json file whenever the gam directory is not my current path. Here's a sample CMD session which recreates the issue:

```
C:\Users\user> gam info user test

<Blurb about creating client_secrets.json>

C:\Users\user> cd Applications\gam

C:\Users\user\Applications\gam> gam info user test

<Displays information about username test>
```

I don't remember what version it was I upgraded from (it was quite old) but using GAM from arbitrary paths worked fine back then. It seems like GAM expects client_secrets.json to exist in your current directory and fails if it does not--even if it exists in the path GAM is installed in.

**Comment by GJP123** [comment]
Getting this too with a recent install after upgrade to Windows 10. Use to work fine.

**Comment by erikpt** [comment]
I think the problem is due to the GC_Defaults array setting GC_CONFIG_DIR to null. I'm going to test with using os.path.dirname(os.path.realpath(__file__)) as the default value

183: GC_CONFIG_DIR: u''
