### ISSUE TITLE
Gam Login Report issue

### ISSUE THREAD

**Issue by Sathyakumar93** [jay0lee/GAM#825]
Hi Jaylee / Team,

One of our user use to run the below script on daily basis and it was working fine till 26th Oct 2018 with correct report, but after 26th user getting report with Incorrect header (Multiple column information has been inserted.  Could you please assist us to fix this issue.

Please refer the script and the reports below.
Gam Version: 4.32

Script:
gam report logins start %date:~10,4%-%date:~7,2%-%date:~4,2%T00:00:00.000+10:00 end %date:~10,4%-%date:~7,2%-%date:~4,2%T23:59:59.999+10:00 > \\nnorsovmdb222\Staging\Google_Logins\logins_%date:~4,2%-%date:~7,2%-%date:~10,4%.csv

Normal Report Header:
name,actor.email,actor.profileId,id.applicationName,id.customerId,id.time,id.uniqueQualifier,ipAddress,parameters.0.name,parameters.0.value,parameters.1.name,parameters.1.value,type

Incorrect Header Report:
name, actor.email, actor.profileId, id.applicationName, id.customerId, id.time, id.uniqueQualifier, ipAddress, parameters.0.name, parameters.0.value, parameters.1.multiValue.0, parameters.1.multiValue.1, parameters.1.multiValue.2,parameters.1.multiValue.3, parameters.1.multiValue.4, parameters.1.multiValue.5, parameters.1.multiValue.6, parameters.1.multiValue.7, parameters.1.multiValue.8, parameters.1.name, parameters.2.boolValue, parameters.2.name, parameters.2.value, parameters.3.boolValue, parameters.3.name, type

**Comment by taers232c** [comment]
This is not an incorrect header, Google is now reporting more information, Gam is just outputting what Google provides.
Here is the API documentation, it does not seem to accurately reflect what Google is returning .
A login_success event is documented to return two parameters: login_type and is_suspicious.
It seems to be returning an undocumented third parameter: login_challenge_method

Ask Google to update the documentation.

Ross
--
ross.scroggs@gmail.com
