### ISSUE TITLE
extract list of all groups and their emails

### ISSUE THREAD

**Issue by marianohare** [jay0lee/GAM#84]
I need a to extract a list of all groups and their emails
I want to change who can leave group, but before I can do this I need to get a list of all groups. 
I want to run this cmd

gam update group test@xxx.ca who_can_leave_group All_Managers_can_leave

**Comment by jay0lee** [comment]
The issue tracker is for reporting bugs. For general "howto" questions, please post on the discussion group:

https://groups.google.com/forum/#!forum/google-apps-manager

Jay

**Comment by marianohare** [comment]
thanks

**Comment by marianohare** [comment]
can you add me to this group

**Comment by jay0lee** [comment]
You can join the group from the link I provided and then post.
