### ISSUE TITLE
Error logging in batch mode

### ISSUE THREAD

**Issue by giko45** [jay0lee/GAM#840]
Hi,

When running GAM with the batch option with multiple treads the error logging is not usable since it gives no information on what command is generating the error.  For example a file with 100 create users gives the following output.

ERROR: 409: Entity already exists. - duplicate
ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
Using 25 processes...

Expected outcome whould be for example the orginal command that failed together with the error

GAM: create user "email@domain.com" lastname "my lastname" org "/path/to/org" 
ERROR: 409: Entity already exists. - duplicate
GAM: create user "email2@domain.com" lastname "my lastname" org "/path/to/org2" 
ERROR: 400: Invalid Input: INVALID_OU_ID - invalid
Using 25 processes...

Regards Gijs

**Comment by rcoleman91** [comment]
I'm running into this as well.
Updating user info from a CSV and im getting errors, but the error is not for the user above/below the message:

updating user renee.mcelroy@[redacted]...
updating user robyn.thomas@[redacted]...

ERROR: 404: Resource Not Found: userKey - userNotFound
updating user sarah.lee@[redacted]...

**Comment by bshogeman** [comment]
problem stil exists

**Comment by tolgaozel** [comment]
Same issue still continues. Errors from batch run are not usable.

**Comment by taers232c** [comment]
This all works quite well in Advanced GAM (https://github.com/taers232c/GAMADV-XTD3)
https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM

Contact me directly via Google Hangouts or Meet.

ross.scroggs@gmail.com
