### ISSUE TITLE
Google Notice Question

### ISSUE THREAD

**Issue by Robert-D** [jay0lee/GAM#845]
I've received a notice from Google that the Google+ API is being shutdown which may effect our processing.

Is GAM going to be effected by this? It's showing use of a method that I've never used before "plus.me"

![googlenotice](https://user-images.githubusercontent.com/18011822/51922976-ad954280-23af-11e9-83e7-5437a40230b5.png)

**Comment by glmyers** [comment]
I also received the same notice and started looking for an answer.

**Comment by dennisse718** [comment]
Same here and my team and I are wondering the same thing.

**Comment by keithhir** [comment]
Google+ APIs were likely enabled when setting up the scopes for GAM.  You can verify this by checking your oauth2.txt file for the existence of https://www.googleapis.com/auth/plus.me.

Follow-up question, will removing this scope from our oauth2.txt file meet this new requirement?  When I try to refresh the client API scopes with gam oauth create, I do not see Google+ as an available scope.

**Comment by jay0lee** [comment]
1) Don't panic.
2) if you are panicking, see #1
3) GAM *barely* uses the Google+ APIs. My general expectation here is those
few unusual commands that do use Google+ will stop working but not
interfere with other commands.
4) I'll work on determining which commands those are, again I expect it's
few uncommonly used commands.
5) worst case scenario you might need to revoke your oauth credentials and
recreate them. Don't do that now but if it's necessary it's a <5 minute
process.

GAM isn't going anywhere

Jay

**Comment by Robert-D** [comment]
Thanks Jay!

**Comment by jay0lee** [comment]
See:

https://developers.google.com/+/api-shutdown

For some clarification. GAM does not directly request plus.me and will not
be impacted by this deprecation.
