### ISSUE TITLE
error "NONE Failed: Cyclic memberships not allowed" is too restricted

### ISSUE THREAD

**Issue by bokky** [jay0lee/GAM#847]
The error "NONE Failed: Cyclic memberships not allowed" is a default error when you add a member to a group which is an other group itself (group in group), this is correct in the default way.

The is 1 specific case where it needs to be allowed (it is allowed via groups web interface)
If you make the new member (the group) with option "noemail" it must be allowed, today this is not the case.
Little example for the case that it needs to be allowed:
"mylist" is an automatically populated group based on certain criteria. We include a sub group called "mylist-ext" which is a manual maintained list for external people.
Both lists have approval enabled! 
To allow mylist to send emails without approval to mylist-ext it needs to be member of mylist-ext.
The default way (send mail) will make a loop ofc. but if the "mylist" is added to mylist-ext with "nomail" option there is no mail loop.
As said, via the web it is allow, via GAM it is not, please add an exception in your code for it.

writing it is more complicated than showing it :-)

**Comment by taers232c** [comment]
The error "NONE Failed: Cyclic memberships not allowed" is not generated by GAM but by Google. You'll have to ask Google to update the Directory API to allow this behavior.
