### ISSUE TITLE
Changes to Google Groups May 2019

### ISSUE THREAD

**Issue by timwsuqld** [jay0lee/GAM#848]
I just want to flag that there are changes coming to Google Groups Settings.
https://support.google.com/a/answer/9191148

I expect someone will want to register for alpha testing of the Group Settings API so that these changes can be made to GAM and tested.
https://cloud.google.com/blog/products/g-suite/upcoming-changes-to-the-google-groups-settings-api

Signup wills be come available March 11th and the alpha test is live on April 8th.

There are a bunch of settings that are merging into a single setting (like whoCanInvite and whoCanAdd becomes whoCanModerateMembers).

**Comment by josemdv** [comment]
There are two different action items:

* Removing the properties that are going away
* Merging properties

I'll submit a PR for the first.

**Comment by jay0lee** [comment]
As far as I'm aware, these changes should not "break" GAM as GAM dynamically determines the group settings that are available to set and should adjust to the changes automatically. As long as that's the case I'm going to hold on accepting a PR on this until we actually get access to the preview API changes.

**Comment by idaliatorres** [comment]
I would like to be able to list all my groups' relevant settings and see how they will be affected. According to this update, seems that should be possible with the new features in the groups settings API. 

https://support.google.com/a/answer/9191148?hl=en#Latest&Newsettings&Prepare2&Member&Content&Metadata&Directory&Footer&Removed&Prepare&SpreadTheWord&Update&Nothing

New features in the Groups Settings API 
On March 25, 2019, we'll introduce new API features. You'll be able audit your groups, update settings, and see how your permissions map to the new settings using the Groups Settings API.

New API features will include:

View and update all the settings being merged.
View who will receive the new settings at launch time. For example, the API will return the value for "Who can manage members," which will take effect after launch. After the Groups settings launch, the API will support applying the new settings.
Check if a group has a custom role that's included in one of the settings being merged. If your groups have custom roles, you must review the group settings in the Groups interface. The Groups API might not return accurate values for settings. Learn more about custom roles.
Check whether a collaborative inbox will remain turned on for a group. After the Groups settings launch, the API will support turning on collaborative inboxes. Learn more about collaborative inboxes.

**Comment by taers232c** [comment]
Yes, it should be possible starting on Monday; we'll have to wait until then to see the initial changes.

Ross

**Comment by idaliatorres** [comment]
Thank you, waiting with bated breath. We have about 1700 groups with hundreds of very dependent owners...
