### ISSUE TITLE
Getting CERTIFICATE_VERIFY_FAILED error using GAM 3.51 to show delegates for a user

### ISSUE THREAD

**Issue by josjonkers** [jay0lee/GAM#85]
Getting the following error using GAM 3.51 to show delegates for a user.
"Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"
Using 3.45 everything is ok.

**Comment by killebrewj** [comment]
Same here, even with 3.61. I'm using 3.45 just for delegation.

**Comment by alldredgec** [comment]
I am also running into the same issue for:
GAM 3.61 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.10 64-bit final
google-api-python-client 1.4.1
Windows-7-6.1.7601-SP1 AMD64

C:\GAM>gam user calldredge show forward

Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
