### ISSUE TITLE
No option to see the full emailaddresses in Google Groups

### ISSUE THREAD

**Issue by bokky** [jay0lee/GAM#853]
There is an option in Gam to configure to view the members of a list, this option only gives partial emailaddresses visibility in Google groups.
There needs to be a additional option set "View Email Addresses" in the web interface to see the email addresses completely. This option is not yet available in GAM

**Comment by taers232c** [comment]
What command are you issuing? What email addresses are missing?
GAM has nothing to do with the Web interface, if you want a change there you'll have to ask Google.

Ross

**Comment by bokky** [comment]
Maybe my request was not clear enough, nothing is broken, just a configure option missing in GAM which you can set in Groups web interface. 
As I am adding hundreds of groups I would like the set this setting in bulk, not by clicky clicky via the web for all these groups.

When you issue command : gam update group XXX who_can_view_membership all_in_domain_can_view

Everybody can see the list of members of the group, but by default is is in a masked mode like "a???e@google.com", in the web there an additional option to set "view Email address" to uncover the mask and see the whole emailaddress.

I looked yesterday quickly through the API's of groups but could not immediately find this specific option back. Not sure if it is something new, I never noticed this option before in Groups.

**Comment by jay0lee** [comment]
There's no API support for this setting, thus nothing GAM can do here. Closing.
