### ISSUE TITLE
New Google Contact delegation 

### ISSUE THREAD

**Issue by goldPrashantB1995** [jay0lee/GAM#859]
Hi All,

I am trying to add the Contact delegation explicitly using the following command but it only delegates to the email but not for the contacts.

gam user DELEGATOR delegate to DELEGATE

In the GAM Article, they have mentioned that we could use the same command for both delegations. I think it might be working earlier but now not as Google has split the Contact Delegation from Gmail explicitly. 

Could someone please suggest that the API feature is not available from Google or we don't have command in GAM Tool for this yet.

Thanks
Prashant

**Comment by jay0lee** [comment]
See:

https://support.google.com/a/answer/6166309#gmail
