### ISSUE TITLE
ou_and_children input selector not documented [well]

### ISSUE THREAD

**Issue by nickofferman** [jay0lee/GAM#860]
The `ou_and_children selector` is not well documented globally.  I needed this for the `delete token ` operation. I found a post in Google Groups with it for a different command and decided to try it with my command.   

Possible resolutions:

- Add it to the more general list on the wiki explaining how to select what users/objects are desired.  I can't find a great page off the top of my head.
-Add it to the text for the specific entries.  I was able to find references to the selector in other parts of the wiki.
-Change the error/info message about users not being directly in the OU to suggest `ou_and_children`
Currently, it is:
> Got 701 Users...
>0 Users are directly in the OU.

I am interested in responses.  I am happy to submit PRs myself for either the info message or wikitext.

**Comment by jay0lee** [comment]
Wiki can be edited by anyone with a GitHub account...

**Comment by Blacksm1th** [comment]
Hi, I'd also like to understand the behavior and am more than willing to update the wiki. Unfortunately I'm a sysadmin not a developer and can't seem to find where I could read the code to document this properly. Can you at least point me in the right direction?

**Comment by gdm-hanoverwork** [comment]
Updated the Wiki with information from: 
https://github.com/GAM-team/GAM/blob/4ffe709ab95b9b4a138e9c0423b62ebc8153bd07/src/gam/__init__.py#L10091
