### ISSUE TITLE
Using CSV getting ERROR: 403: Not Authorized to access this resource/api - forbidden

### ISSUE THREAD

**Issue by neckhardt1** [jay0lee/GAM#868]
I can delete a user using a single GAM command as well as using the command prompt FOR loop method.

If I try to use the CSV method i get:

ERROR: 403: Not Authorized to access this resource/api - forbidden

One user MAY get deleted, but the rest fail.

Any ideas?

**Comment by taers232c** [comment]
Please show the command you are using, the header row and the first line of the CSV file.

Ross
--
ross.scroggs@gmail.com

**Comment by neckhardt1** [comment]
Command:  gam csv gam2.txt gam delete user ~Email

File contents:

Email
User1@xxx.com

Neal

**Comment by taers232c** [comment]
Neal,

Are there trailing blanks on the data lines?

Ross

**Comment by neckhardt1** [comment]
It appears that yes! There is one trailing blank. The data was copied from a spreadsheet.

Neal

**Comment by taers232c** [comment]
Does it work after stripping the trailing blank?

Ross

**Comment by neckhardt1** [comment]
That did seem to make all the difference in the world!

Thanks!
