### ISSUE TITLE
403: Insufficient Permission - insufficientPermissions

### ISSUE THREAD

**Issue by yodadada** [jay0lee/GAM#869]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command:
gyb --email aarchive@company.com --action restore --local-folder GYB-GMail-Backup-mjimenez@company.com --label-restored "Mireya"

Expected outcome (what are you trying to do?): Have used this in the past to restore data to existing email account under a new label but haven't had to do this for about a year.

Actual outcome (what errors or bad behavior do you see instead?):  This is what I see when I run the command: 
Using backup folder GYB-GMail-Backup-mjimenez@company.com
403: Insufficient Permission - insufficientPermissions

I have tried this on and existing account and on a new account with same results. 
I deleted the .cfg file but also got same results. 
Need to get this restored for legal department.

Thanks for any help,

**Comment by Dreyfuzz** [comment]
Shouldn't this be moved to the [GYB wiki](https://github.com/jay0lee/got-your-back/issues)?
