### ISSUE TITLE
gam batch operations - 

### ISSUE THREAD

**Issue by RobertDavidson** [jay0lee/GAM#87]
Hi there,
We started using GAM early this year after Google stopped supporting their provision api.. We use gam to create and manage student and faculty user accounts. We had been running on version 3.43 until recently we discovered new users were not creating with our gam batch scripts because of "Error 400: Invalid Password - invalid". After upgrading to version 3.51 the accounts now create properly, however now running "gam batch OurBatchFile.txt" gam doesn't process the file if it has too many records. It just returns this message:

    GAM 3.51 - http://git.io/gam
    Jay Lee <jay0lee@gmail.com>
    Python 2.7.10 64-bit final
    google-api-python-client 1.4.1
    Windows-2012Server-6.2.9200 AMD64
    Path: c:\gam-64\
    
    Usage: gam [OPTIONS]...
    
    GAM. Retrieve or set Google Apps domain,
    user, group and alias settings. Exhaustive list of commands
    can be found at: https://github.com/jay0lee/GAM/wiki
    
    Examples:
    gam info domain
    gam create user jsmith firstname John lastname Smith password secretpass
    gam update user jsmith suspended on
    gam.exe update group announcements add member jsmith
    ...

The OurBatchFile.txt contains ~50,000 commands (I know it's a big batch, but this has worked before). The strange thing is if I remove almost all commands from the file and only leave about 10 lines the same command works and process the batch without an issue. 

Suggestions?

Thanks

**Comment by jay0lee** [comment]
can you email me a sample batch file that triggers the issue? jay0lee@gmail.com. The user data can of course be bogus.

Jay

**Comment by RobertDavidson** [comment]
So after a bit more troubleshooting it appears to have nothing to do with the length of the text file. It looks like gam batch does not like setting passwords?:
    gam update user UserNameHere password 'password'
If this same command is run directly with gam it works, but not with it contained in a batch file.

**Comment by RobertDavidson** [comment]
Sorry jay... GAM batch is working fine. It was failing because I had an empty line in the file. I guess I need to coalesce my sql fields.

**Comment by jay0lee** [comment]
No problem. Going to close this now.
