### ISSUE TITLE
Unable to delegate email

### ISSUE THREAD

**Issue by trevorlewis1** [jay0lee/GAM#870]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. Yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

**Full steps to reproduce the issue:**
1. type: gam user test1 delegate to test2@companydomain.com

**Expected outcome (what are you trying to do?):**

Email for test1 is delgated to test2@companydomain.com

I am able to perform other GAM administrative actions. Delegate throws the error below. I have tried this on two different installs of GAM on two different systems. This error happens for all users and emails.

**Actual outcome (what errors or bad behavior do you see instead?):**

ERROR: Authentication Token Error - unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.

**Comment by jay0lee** [comment]
Run:

gam user test1@companydomain.com check serviceaccount

and follow all instructions until you get all PASS returned.

Closing this issue as this doesn't sound like an actual bug, if you still have trouble feel free to start a thread in the group:

git.io/gam-group

Jay
