### ISSUE TITLE
Deleting Groups in bulk.  Can I use wildcards?

### ISSUE THREAD

**Issue by MelancholyOcelot** [jay0lee/GAM#88]
Long story short, a 3rd party vendor created about 45k+ google groups that I need to kill.  Luckily, they're all in a secondary domain.

1) Can I use wildcard * to select groups?
>gam delete group *@domain.com

2) If wildcards do not work, can I export groups to a .csv?  I haven't found a method yet, but if I can get my hands on the total list of groups, I can build a batch from there.  I don't care about group membership.  I only need the list.

Thanks

**Comment by jay0lee** [comment]
This issue tracker is for bug reports. Please post general how to questions to:

https://groups.google.com/forum/?nomobile=true#!forum/google-apps-manager
