### ISSUE TITLE
Unable to run gam commands after installing

### ISSUE THREAD

**Issue by macmills** [jay0lee/GAM#887]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  Install GAM using the steps described in the Wiki
2. At the end of the installation, run "gam() { "/Users/kgadmin/bin/gam/gam" "$@" ; }"
3. Run either "gam info" or "gam info user" to being using GAM.

Expected outcome (what are you trying to do?):
Run gam info or gam info user successfully.

Actual outcome (what errors or bad behavior do you see instead?):

I get "-bash: gam: command not found".

**Comment by jay0lee** [comment]
Have you tried restarting your terminal? What if you run:

/Users/kgadmin/bin/gam/gam version

**Comment by macmills** [comment]
I've restarted Terminal and ran "/Users/kgadmin/bin/gam/gam version"

This is the result I get:

"MacBook-Pro-75:~ kgadmin$ /Users/kgadmin/bin/gam/gam version
GAM 4.70 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.15 64-bit final
google-api-python-client 1.7.8
oauth2client 4.1.3
Darwin-17.7.0-x86_64-i386-64bit x86_64
Path: /Users/kgadmin/bin/gam"

When I then try to run "gam" or "gam info", I still get the command not found message. I've been trying to install GAM for about a week now on two different Macs. I've also tried two different OSes and still cannot get this running.

**Comment by jay0lee** [comment]
This indicates GAM wasn't able to add itself to your shell correctly. Try doing it manually:

https://coolestguidesontheplanet.com/make-an-alias-in-bash-shell-in-os-x-terminal/

**Comment by garcia-cag** [comment]
Hi there! I was hoping to not have to tag into a forum thread, but just haven't been able to troubleshoot myself with the documentation. I'm having the exact same issue as macmills above.

I have also attempted to reinstall GAM 3 times. Each time, when I close the terminal session, I end up stuck not being able to re-run the program using any of the commands. Using the prompts above I have gotten to this:
`Last login: Mon Aug 19 12:52:33 on ttys000
C02K77YXFFT1-CG:~ cgarcia$ /Users/cgarcia/bin/gam/gam version
GAM 4.93 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.7.4 64-bit final
google-api-python-client 1.7.11
Darwin-18.7.0-x86_64-i386-64bit x86_64
Path: /Users/cgarcia/bin/gam
C02K77YXFFT1-CG:~ cgarcia$ ./gam user info
-bash: ./gam: No such file or directory
C02K77YXFFT1-CG:~ cgarcia$ gam() {"/Users/cgarcia/bin/gam""$@";}
-bash: syntax error near unexpected token `{"/Users/cgarcia/bin/gam""$@"'
C02K77YXFFT1-CG:~ cgarcia$ `

jay0lee, you mentioned the shell install portion with aliasing, but there's not more information on what needs to be aliased once you follow the steps in the guide.

**Comment by jay0lee** [comment]
please post this to the discussion group, not here:

https://groups.google.com/forum/#!forum/google-apps-manager
