### ISSUE TITLE
Weird response to bad command

### ISSUE THREAD

**Issue by yubbie** [jay0lee/GAM#89]
I accidentally  did this:
 gam group vt-nis-g add member nis-4b14-g@vt.edu

when I meant to do:
 gam update group vt-nis-g add member nis-4b14-g@vt.edu

And got:

Got 31 all members...f vt-nis-g@vt.edu (may take some time for large groups)...
starting 5 worker threads...
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."
Error: invalid argument to "gam <users> add..."

**Comment by jay0lee** [comment]
should be fixed in newer versions where GAM does not automatically batch these commands.
