### ISSUE TITLE
Unable to run version 4.70

### ISSUE THREAD

**Issue by seanwlk** [jay0lee/GAM#891]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Running on Windows 10 subsystem folder 
2. Version 4.65 runs fine, 4.70 doesnt
3. Simply download gam 4.70 and run ./gam 

Expected outcome (what are you trying to do?):
./gam 

Actual outcome (what errors or bad behavior do you see instead?):
```
root@seanwlk:/mnt/c/Users/seanwlk/Desktop# ./gam
Traceback (most recent call last):
  File "gam.py", line 14053, in <module>
  File "gam.py", line 13263, in ProcessGAMCommand
IndexError: list index out of range
[30] Failed to execute script gam
```

Also tried to delete alias from bashrc and whole folder to reinstall later. Doesn't work with 4.70

uname -a
```
Linux seanwlk 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jay0lee** [comment]
Does:

./gam version

show anything? What about:

gam info domain

**Comment by seanwlk** [comment]
None of the two. Error is always the same. Seems like no argument is being parsed.
Tried on both my personal PC and Office one, with version 4.70 it always give the output I sent you before.

**Comment by jay0lee** [comment]
OK, I see the issue. Going to push a 4.71 build with fix shortly.

**Comment by jay0lee** [comment]
I just pushed 4.71, can you try upgrading and see if that does the trick? Upgrade should be as simple as:

bash <(curl -s -S -L https://git.io/install-gam) -l

**Comment by seanwlk** [comment]
All works fine thanks for the fast fix and your work.

**Comment by jay0lee** [comment]
Glad it solved the problem. Closing this.
