### ISSUE TITLE
Unable to download and install on MacOS

### ISSUE THREAD

**Issue by msalonius** [jay0lee/GAM#892]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  run bash <(curl -s -S -L https://git.io/install-gam)

2.
3.

Expected outcome (what are you trying to do?):
to be able to install GAM
Actual outcome (what errors or bad behavior do you see instead?):

ERROR: Attribute: browser_download_url for macos.tar.xz version latest not found

**Comment by taers232c** [comment]
gam-4.71-macos-x86_64.tar.xz in repository should be named gam-4.71-macos.tar.xz

**Comment by jay0lee** [comment]
Fixed in gam-install.sh, we should be including -x86_64 in the filename we look for now. There have been rumors for ages about Apple switching Macs to their own ARM-based chips so we might as well be ready. Who knows, maybe they'll revive PowerPC chips instead :-)

**Comment by jay0lee** [comment]
btw you may need to wait for 20 minutes or so before the GAM install command starts pulling the updated version of the install script. Or you can try adding something like ?refresh to the end of the URL in the command to try and force the refresh.

**Comment by msalonius** [comment]
Works much thanks

-- 
Regards,
Mark Salonius | IT Operations Manager | Prodigy Labs | +1 416.908.2741 | Mark.Salonius@ProdigyLabs.net
