### ISSUE TITLE
Info User vs. Info Group | One is Index-able, one is not ?

### ISSUE THREAD

**Issue by avelis26** [jay0lee/GAM#90]
I'm using PowerShell to invoke GAM statements as a workaround for an issue we are having while migrating to Google Apps. My issue is when I need to capture an ID for a group or user (to stick it in a database later) my code works perfectly fine for groups but not users.

Example:
$GroupInfo = Invoke-Expression "GAM Info Group SomeGroup@MyDomain.com"
$GroupInfo[6]
Output would be "id: 99999999999999"

$UserInfo = Invoke-Expression "GAM Info User SomeUser@MyDomain.com"
$UserInfo[9]
Output would be "-1"
Expected output would be "Google Unique ID: 999999999999999999999"

I can't for the life of me figure out why this is happening. Both commands appear to return an array of strings and therefore I should be able to index said array for the data I need. It works for groups... but not users even though the returned data looks identical as far as format goes.

Any ideas oh master of all things GAM ? :)

p.s. I'm attempting a workaround to this issue for now where I use REGEX to totally break the output  down to just 0-9,a-z,A-Z and use a sub-string to pull out the exact number of chars I need for the ID. This method assumes the ID will always be proceeded by "Google Unique ID" and that the ID will always be 22 chars in length. I really don't like using such methods because they are fragile lol. And also it just bugs me that one returned output is index-able and the other isn't....

**Comment by jay0lee** [comment]
Sounds like a powershell issue, not GAM. You may want to check in a powershell forum for help.
