### ISSUE TITLE
error enabling admin.googleapis.com

### ISSUE THREAD

**Issue by secchic** [jay0lee/GAM#902]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. I type command gam create project
2. I enter my super admin email address
3. I click allow from my browser

Expected outcome (what are you trying to do?): I am trying to complete the initial install.

Actual outcome (what errors or bad behavior do you see instead?): 

![image](https://user-images.githubusercontent.com/49959932/56734640-69f17100-6731-11e9-9fb4-862a8d1b39f9.png)

API is enabled

Authentication successful.
Creating project "GAM Project"...
Checking project status...
Project still being created. Sleeping 1 seconds
Checking project status...
  Project: gam-project-4il-wnw-c5f, Enable 16 APIs

There was an error enabling admin.googleapis.com. Please resolve error as described below:

Please accept the following terms of service.

Press enter once resolved and we will try enabling the API again.

There was an error enabling admin.googleapis.com. Please resolve error as described below:

Please accept the following terms of service.

Press enter once resolved and we will try enabling the API again.

**Comment by secchic** [comment]
Also API access is already enabled.

**Comment by jay0lee** [comment]
Try, going to:

https://console.developers.google.com/apis/library/admin.googleapis.com?q=admin%20sdk

and manually enabling the Admin SDK API there, this should show you the ToS to accept.

**Comment by secchic** [comment]
Thank you that worked.
