### ISSUE TITLE
GAM Source missing dependencies for 4.82

### ISSUE THREAD

**Issue by kgmoore431** [jay0lee/GAM#909]
For versions of gam prior to 4.8x the source.zip file included the gam source code as well as the dependent modules (e.g. dns.resolver, google_auth_httplib2)  Could these dependencies either be re-included in the current source releases or a dependencies download also be made available?

**Comment by jay0lee** [comment]
You can install the latest version of all dependencies with:

    pip install -r requirements.txt

Where requirements.txt is located in GAM/src/

**Comment by kgmoore431** [comment]
I was hoping not to have to setup either virtualenv or add the modules to my system python.  It has been lovely for prior experiments etc to have the bundled download be self sufficient.

**Comment by jay0lee** [comment]
Then use the executable version?

**Comment by kgmoore431** [comment]
old man shakes fist at sky..... Fair point :-)
