### ISSUE TITLE
gam report users outputs excessive commas

### ISSUE THREAD

**Issue by carochester** [jay0lee/GAM#917]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Run: gam report users parameters "accounts:is_suspended,accounts:last_login_time,accounts:creation_time" > filename.csv
2. Open CSV, admire the number of commas and broken formatting 

This worked fine until I upgraded from 3.7x to 3.8x. I have run this report monthly for about a year with no issues until the upgrade. The report generated would be roughly 700KB, now it's around 45MB (again, the extra commas). 

Expected outcome (what are you trying to do?): Not so many commas. 

Actual outcome (what errors or bad behavior do you see instead?): Lots of extra commas 

(sorry, I'm not being facetious, but the commas are the only problem and this application is excellent)

**Comment by carochester** [comment]
On further testing, if I only run "gam report users parameters accounts:is_suspended"  I found that the column vs. result were reversed. The TRUE and FALSE are now a column header instead of the result. I don't think this would be intentional, but I could be wrong. But with all of those parameters combined, it turns the CSV into a mess.

**Comment by sparthe123** [comment]
I'm also seeing the same issue, running report gives result as shown in attached screenshot 

![Screenshot 2019-05-17 at 4 11 05 PM](https://user-images.githubusercontent.com/15688616/57922995-bfe3af80-78be-11e9-9889-492663a5e6b9.png)

**Comment by sparthe123** [comment]
Hi, 

Is this issue fixed ? i can see report still doing the same

**Comment by jay0lee** [comment]
should be fixed now in latest versions.
