### ISSUE TITLE
client_secrets.json

### ISSUE THREAD

**Issue by louismcdonald** [jay0lee/GAM#92]
I finally have gotten into GAFE, and came across this tool. When I go to the developers console and create a project, each project creation is flagged as Forbidden.

I saw a message early on that stated the developers console would move all projects to read-only in August. Not sure if this is why I am having problems creating a new project. 

Basically, trying to create the necessary json files. Not sure if there is a different path to getting there.

-- Louis
![forbidden](https://cloud.githubusercontent.com/assets/13633008/9050059/69ad80f8-3a17-11e5-8d5c-ab2c4b01e0da.png)

**Comment by jay0lee** [comment]
Closing as this is not a GAM issue.
