### ISSUE TITLE
error with Calendar API in latest versions 4.81 & 4.82

### ISSUE THREAD

**Issue by kjs72** [jay0lee/GAM#920]
trying to update freebusy for a calendar resource in latest versions 4.81 and 4.82

gam calendar xxxxxxxxxx@resource.calendar.google.com update freebusy domain

Returns the error:
ERROR: Authentication Token Error - ('invalid_grant: Invalid email or User ID', '{\n  "error": "invalid_grant",\n  "error_description": "Invalid email or User ID"\n}')

rolled back to 4.72 and all is fine

**Comment by jay0lee** [comment]
What OS are you using? Can you try testing with latest code and see if it works? (If you're using a compiled version of GAM, let me know the OS and I can share a binary installer with you.)

**Comment by CAC1226** [comment]
Thanks for this post
I'm using Win 10 Pro 64 with GAM 4.82 I was able to create the resource using GAM but running the same command I received the same error

ERROR: Authentication Token Error - ('invalid_grant: Invalid email or User ID', '{\n "error": "invalid_grant",\n "error_description": "Invalid email or User ID"\n}')

I reverted back to 4.72 and was able to update the calendar entry

**Comment by jay0lee** [comment]
Can you download this version and extract it overtop your existing install (it still shows version as 4.82 but has new patches)

https://drive.google.com/file/d/1fLoID8oIL9svR8UsuYef2wKZDGxCmRnD/view?usp=sharing

**Comment by CAC1226** [comment]
the new exe is working for me - thank you for the fast response.

**Comment by jay0lee** [comment]
thanks for confirming the fix. I'll try to get 4.83 out the door today.

**Comment by kjs72** [comment]
fixed for me also... thanks!
look forward to 4.83
