### ISSUE TITLE
No synchronization with the command group sync

### ISSUE THREAD

**Issue by mlazzje** [jay0lee/GAM#934]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Run syn group members: gam update group testgroup@domain.com sync member allmail ou "/TestOU"

Expected outcome: Add/remove members based on the users from a specific OU

Actual outcome: console output seems to good

```
Getting all Users in G Suite account that match query (orgUnitPath='/TestOU') (may take some time on a large account)...
Got 50 Users...
50 Users are directly in the OU.
Getting members of testgroup@domain.com (may take some time for large groups)...
Got 47 members...
Group: testgroup@domain.com, Will add 3 and remove 0 MEMBERs.
Using 3 processes...
```

But no members have been added. If I start again the command I still have the same output. I tried on different OUs, with different groups, removed/added some users in the group (nothing is removed or added), check groups audit in the admin console nothing happens.

I am using the last GAM version 4.85 installed on Linux with the command provided in the wiki.

Thank you,

**Comment by thanegill** [comment]
It looks like you're using gam batch. I ran into this same problem for syncing mailgroups when using `gam batch`. Does it work for you when run as a stand alone command?

**Comment by taers232c** [comment]
Max,

It's a bug in Gam; I've submitted a fix to Jay.
The command will work if you drop allmail; isn't that the default?

Ross
--
ross.scroggs@gmail.com

**Comment by mlazzje** [comment]
@taers232c, you are right, it's working without "allmail". Yes, it's the default setting, I can omit it.

Thank you.
