### ISSUE TITLE
G Suite Marketplace App?

### ISSUE THREAD

**Issue by Cancun101** [jay0lee/GAM#935]
Would developing a G Suite Marketplace app for GAM be useful?

IT/development novice here, please be nice :)

As I understand it, the G[G Suite marketplace](https://gsuite.google.com/marketplace) allows domain admins to have a one-click install for cloud platform projects on their domain. Wouldn't creating a GAM marketplace app allow domain admins to quickly and easily install and configure GAM's APIs and account authorization, etc. from the domain admin console, simplifying CLI client setup? Admins would have the ability to delegate GAM access to their team as a group, and could enable/disable APIs on a per-user basis, right?

This seems like a fairly simple and obvious improvement - is there some reason why this wouldn't be useful? Or would making this the standard domain-side setup (retaining the current oauth create workflow as the "advanced" setup) be detrimental somehow?

I think creating this sort of thing would be a good skill builder for me - is this a good project to pursue?

Cheers!
--Connor Gibson

**Comment by jay0lee** [comment]
Closing this as GAM is an installed app, not a web app which makes adding it to the G Suite Marketplace infeasible.
