### ISSUE TITLE
GAM 4.84 and 4.85 flagged as trojan/malware

### ISSUE THREAD

**Issue by York-tech** [jay0lee/GAM#936]
Confirming the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. - True

* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki - Also True

Potentially useful information:
OS: Windows Server 2016
Antivirus: Sophos
Detection type: Heuristic
Malware type: ML/PE-A
VirusTotal scan (per Sophos's instructions):  https://www.virustotal.com/#/file/f386a820771484ce2eb098e2c92dc6f55c7576e4d4ed0d954b354b287e3e6957/detection

I was upgrading GAM to 4.85 on a Windows Server 2016 machine from a much older version, and it completed successfully.  I did a test run to make sure all things were still working, but it kept getting hit with an access denied message followed by gam.exe getting deleted.  I attempted installing 4.84 as a comparison and got the same result.

Full steps to reproduce the issue:
1.  Have an affected AntiVirus 
2.  Run any command using gam.exe
3.  Get access denied message

Expected outcome (what are you trying to do?):
I was running a test c:\gam\gam.exe info domain to make sure the upgrade took correctly.

Actual outcome (what errors or bad behavior do you see instead?):
Received the following error in Powershell:
PS C:\Windows\system32> C:\gam\gam.exe info domain
Program 'gam.exe' failed to run: Access is deniedAt line:1 char:1
 C:\gam\gam.exe info domain

At line:1 char:1
 C:\gam\gam.exe info domain

CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
FullyQualifiedErrorId : NativeCommandFailed

Received the following error from a command shell:
C:\Windows\system32>c:\gam\gam.exe info domain
Access is denied.

There may not much that can or should be done with this error.  I may need to simply create an exception, but I thought you should be informed.

Thanks

**Comment by jay0lee** [comment]
closing this as there's little I can do about these issues.
