### ISSUE TITLE
CSV reading problem

### ISSUE THREAD

**Issue by karlosss** [jay0lee/GAM#94]
I encountered the following issue:

When reading a CSV, i keep getting the following error, which does not make sense to me, as long as the header "name" is obviously included. If any more pieces of information are required, just feel free to ask for them :)

Error: header "name" not found in CSV headers of "password,﻿name,surname,email", giving up.

**Comment by karlosss** [comment]
EDIT: the trick is to add a blank column as the first one of your CSV; it is not a proper solution, though

**Comment by jay0lee** [comment]
This sounds very much like an invalid CSV file format. Closing issue for now but feel free to re-open with an example CSV that demonstrates the issue.
