### ISSUE TITLE
GAM install doesn't install in ZSH (or other shells)

### ISSUE THREAD

**Issue by evilhamsterman** [jay0lee/GAM#940]
Full steps to reproduce the issue:
1. Install GAM as per wiki
2. Restart ZSH

Expected outcome (what are you trying to do?): GAM command will be available

Actual outcome (what errors or bad behavior do you see instead?): GAM command is not available

The appears to append `gam() { "/home/dmills/bin/gam/gam" "$@" ; }` to the .bashrc file to load the gam command. However zsh and other popular shells don't use .bashrc file. GAM should check what shell is running and append it in the appropriate file for at least common shell options.

**Comment by maximusapen** [comment]
Yes this is true, I'm having the same issue after installing macOS Catalina which uses zsh as the default shell

**Comment by ZdenekPO** [comment]
I have the same issue on macOS Catalina - any solution how to make the commands working ? 
thanks

**Comment by mick-t** [comment]
Use bash? The forum is probably a better place for this discussion.

**Comment by taers232c** [comment]
Start terminal
echo 'alias gam="~/bin/gam/gam"' >> .profile
source .profile
gam version

**Comment by ZdenekPO** [comment]
> Start terminal
> echo 'alias gam="~/bin/gam/gam"' >> .profile
> source .profile
> gam version

yes, it helps! thanks!

**Comment by evilhamsterman** [comment]
As far as I'm aware this is still an issue. More so with MacOS now defaulting to zsh instead of bash. Workarounds are nice, and I used one myself. But this should be solved by the package.

**Comment by valentinwong** [comment]
Thanks @taers232c! Totally helped :)

**Comment by eosrebel** [comment]
> As far as I'm aware this is still an issue. More so with MacOS now defaulting to zsh instead of bash. Workarounds are nice, and I used one myself. But this should be solved by the package.

So I have been doing the commands that @taers232c posted which would work until terminal was restarted, and then I would need to redo those steps. What I figured out that ~/.zshrc does not exist be default and doing those commands would only write them to either to the session or to a temp file that was purged when terminal restarted. Creating .zshrc using `touch ~/.zshrc` and then adding `alias gam="~/bin/gam/gam"` to it using nano or whatever you want solved this problem.

**Comment by evilhamsterman** [comment]
> > As far as I'm aware this is still an issue. More so with MacOS now defaulting to zsh instead of bash. Workarounds are nice, and I used one myself. But this should be solved by the package.
> 
> So I have been doing the commands that @taers232c posted which would work until terminal was restarted, and then I would need to redo those steps. What I figured out that ~/.zshrc does not exist by default and doing those commands would only write them to either to the session or to a temp file that was purged when terminal restarted. Creating .zshrc using `touch ~/.zshrc` and then adding `alias gam="~/bin/gam/gam"` to it using nano or whatever you want solved this problem.

I have a working .zshrc, I filed this bug because others probably have similar issues, and especially with MacOS switching to zsh it is probably going to come up a lot more.

**Comment by jnance86** [comment]
Gam install on zsh still not working after change https://github.com/jay0lee/GAM/pull/1164

**Comment by taers232c** [comment]
Jacob,

The change happened after 5.06 was released.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Jacob,

Are you installing GAM on lots of computers? Once you've set the GAM alias on a computer you're good to go.

Ross
--
ross.scroggs@gmail.com

**Comment by jnance86** [comment]
It worked now. Not sure what I did different to make it work. I had the alias set.

**Comment by syoung-quizlet** [comment]
Just installed GAM and had this issue when starting up Terminal...
```
Last login: Fri Sep 18 13:00:55 on ttys000
/Users/sean/.zshrc:104: defining function based on alias `gam'
/Users/sean/.zshrc:104: parse error near `()'
➜  ~ 
```

**Comment by syoung-quizlet** [comment]
Modified .zshrc to the below resolved it...
```
function gam() { "/Users/USERNAME/bin/gam/gam" "$@" ; }
```

**Comment by seanism** [comment]
Just forked the repo and submitted a fix.
https://github.com/jay0lee/GAM/pull/1245

**Comment by mattflemingrelyance** [comment]
This is still a problem out of the box. 😔
