### ISSUE TITLE
Some one maybe have a script for forwarding emails from users 

### ISSUE THREAD

**Issue by AMG-90** [jay0lee/GAM#955]
some how the help desk at my work struggling with doing the right command , i thought some might have a python script that just ask them like stupid bot:

User that forwarding : "answer"
User that forward to : "answer"

let me know if some one was thought about it already it will be a huge time saver

**Comment by ejochman** [comment]
If you're really doing this on a bulk basis, I'd highly recommend you use
the recipient address map, rather than trying to setup forwarding on each
individual account with GAM: https://support.google.com/a/answer/4524505

**Comment by jay0lee** [comment]
closing this, please move discussion to the group.
