### ISSUE TITLE
ERROR: 403: Not Authorized to access this resource/api - forbidden

### ISSUE THREAD

**Issue by jeffreyoelen** [jay0lee/GAM#963]
Hi, 

I am getting the following error "ERROR: 403: Not Authorized to access this resource/api - forbidden" when trying to move some Chrome Devices to an different OU with the following command:

gam csv jgz_cros.csv gam update cros ~Device ou ~OU_Nieuw

Installed the latest version of GAM. 

Outcome check serviceaccount command: 
Scope: https://mail.google.com/                                     PASS
 Scope: https://www.googleapis.com/auth/activity                     PASS
 Scope: https://www.googleapis.com/auth/apps.alerts                  PASS
 Scope: https://www.googleapis.com/auth/calendar                     PASS
 Scope: https://www.googleapis.com/auth/drive                        PASS
 Scope: https://www.googleapis.com/auth/gmail.settings.basic         PASS
 Scope: https://www.googleapis.com/auth/gmail.settings.sharing       PASS
 Scope: https://www.googleapis.com/auth/spreadsheets                 PASS

Hopefully someone can help me figure out how to solve this error. 

Kind regards, 
Jeffrey

**Comment by jay0lee** [comment]
What do the first few lines, including headers, of the CSV look like? Can
you confirm you are entering the OU just as you see it with:

gam print orgs

What is the output of:

gam oauth info

?

Jay

**Comment by jeffreyoelen** [comment]
Hi Jay0lee, 

Here the screenshot of the CSV file:
![Screen Shot 2019-07-03 at 13 53 34](https://user-images.githubusercontent.com/37935042/60589541-0c654a80-9d9a-11e9-8c27-5d70ca5dc373.png)

Yes i did enter that specific OU's

Output gam oauth info:

OAuth File: /Users/jeffreyoelen/bin/gam/oauth2.txt
Client ID: 662425554465-qvertuu9ple00jeja266bmqn98bcthm5.apps.googleusercontent.com
Scopes (27):
  https://www.googleapis.com/auth/admin.datatransfer
  https://www.googleapis.com/auth/admin.directory.customer
  https://www.googleapis.com/auth/admin.directory.device.chromeos
  https://www.googleapis.com/auth/admin.directory.device.mobile
  https://www.googleapis.com/auth/admin.directory.domain
  https://www.googleapis.com/auth/admin.directory.group
  https://www.googleapis.com/auth/admin.directory.orgunit
  https://www.googleapis.com/auth/admin.directory.resource.calendar
  https://www.googleapis.com/auth/admin.directory.rolemanagement
  https://www.googleapis.com/auth/admin.directory.user
  https://www.googleapis.com/auth/admin.directory.user.security
  https://www.googleapis.com/auth/admin.directory.userschema
  https://www.googleapis.com/auth/admin.reports.audit.readonly
  https://www.googleapis.com/auth/admin.reports.usage.readonly
  https://www.googleapis.com/auth/apps.groups.settings
  https://www.googleapis.com/auth/apps.licensing
  https://www.googleapis.com/auth/classroom.courses
  https://www.googleapis.com/auth/classroom.guardianlinks.students
  https://www.googleapis.com/auth/classroom.profile.emails
  https://www.googleapis.com/auth/classroom.profile.photos
  https://www.googleapis.com/auth/classroom.rosters
  https://www.googleapis.com/auth/cloudprint
  https://www.googleapis.com/auth/devstorage.read_only
  https://www.googleapis.com/auth/ediscovery
  https://www.googleapis.com/auth/siteverification
  https://www.googleapis.com/auth/userinfo.email
  openid
G Suite Admin: webrsupport@zuidzorg.nl
Expires: 2019-07-03T14:52:08.005699
audience: 662425554465-qvertuu9ple00jeja266bmqn98bcthm5.apps.googleusercontent.com
user_id: 110368666559586509002
verified_email: True
access_type: offline
ip-10-156-76-193:~ jeffreyoelen$

**Comment by jay0lee** [comment]
Looks like Device column is serial numbers which is not the same thing as device ID (it's confusing, I know). Try:

gam csv jgz_cros.csv gam update cros id:~~Device~~ ou ~OU_Nieuw

This should cause GAM to first lookup the serial number you are providing and convert it into a device ID which is needed for the move command.

Jay

**Comment by jeffreyoelen** [comment]
When i try your suggestion, i get the same error..
Why "Device" on your command line is crossed out?

moving 1 devices to /JGZ/Chrome Devices/Chromebook JGZ

ERROR: 403: Not Authorized to access this resource/api - forbidden

**Comment by taers232c** [comment]
Jeffrey,

The command should look like this:
gam csv jgz_cros.csv gam update cros query id:~~Device~~ ou ~OU_Nieuw

Ross
--
ross.scroggs@gmail.com

**Comment by jeffreyoelen** [comment]
This worked Ross, thank you guys!
