### ISSUE TITLE
Assistance reqd with configuring GAM for multiple projects

### ISSUE THREAD

**Issue by RohitGupta80** [jay0lee/GAM#972]
Hi Jay,

I am newbie and recently deployed GAM on my windows PC. As i have global admin rights on 2 different google tenants therefore I need to configure GAM to switch between the tenants to execute the commands. So far, i read 2 options:
Option 1: create different folders and install gam for each tenants
Option 2: create different Oauth in the same folder than multiple installs

Is their any step by step doc that can illustrate the steps to perform for Option 2 in a scenario where i already have installed GAM and is pointing to 1 tenant. thanks in advance # #

**Comment by jay0lee** [comment]
Glad to help but this likely belongs in the forum, not the bug tracker. Can you start a thread there:

https://groups.google.com/forum/#!forum/google-apps-manager
