### ISSUE TITLE
Bad Request error

### ISSUE THREAD

**Issue by ChicagoJay** [jay0lee/GAM#977]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. gam info domain (or any other valid command)
2.
3.

Expected outcome (what are you trying to do?):
I am expecting a non-error response.

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

I upgraded to a fresh version of Python (3.7.4) as well as the latest GAM today.  I had this working for several years.

When it failed, I renamed my client_secrets and outh2service files, and created a new project.  I followed the in-script directions, and everything appears to have worked.  However, I am still getting the same error.  I tried it in both an admin as well as non-admin cmd shell.

**Comment by aa2on** [comment]
did you ever find a resolution here? I'm having the same issue

**Comment by ChicagoJay** [comment]
> did you ever find a resolution here? I'm having the same issue

I uninstalled and reinstalled.

**Comment by ergosteur** [comment]
To anyone finding this - delete `oauth2.txt` in your gam directory (~/bin/gam) and rerun the `gam info domain` command.
