### ISSUE TITLE
Agree to Terms for users on creation

### ISSUE THREAD

**Issue by brandonusher** [jay0lee/GAM#98]
I notice there is no longer a parameter "agreedtoterms" but is there a new way to do this automatically for the emails I create?

I'm working on creating a bunch of emails for Apple ID's and need to have the terms agreed to before it allows me to set forwarding up. Is there a workaround for this? Below is the current code I am using

```powershell
gam create user "$username" firstname "$firstName" lastname "$int" password "$password" changepassword off agreedtoterms on
gam update user "$username" org "$org"
gam user "$username" forward on "$masterEmail" keep
```

**Comment by ARCMereel** [comment]
Hi.

I got the same problem for setting the signature directly after creating the user account.
Is there any known solution?

**Comment by racineunified** [comment]
Contact Google. They have ways behind the scenes for these settings.

**Comment by brandonusher** [comment]
Will I have to do that everyone I create users and want them mass agreed to?

**Comment by racineunified** [comment]
May be an all or nothing scenario. Or they may be able to set something up
for an Org unit. We had a separate domain just for students and we had that
"feature" turned off.  Give them a call and find out what they can do for
you.

**Comment by brandonusher** [comment]
Thanks @racineunified

**Comment by jay0lee** [comment]
Accept ToS is not supported by GAM.
