### ISSUE TITLE
Can't sync group to file: Errno 13

### ISSUE THREAD

**Issue by sestevens-1** [jay0lee/GAM#984]
Full steps to reproduce the issue:
1. Create text file containing email addresses (File is simply one email address per line)
2. gam update group [group_name] sync member file [file_name]

Expected outcome (what are you trying to do?):
Update a group by syncing it to a list of email addresses, to remove old members and add new ones

Actual outcome (what errors or bad behavior do you see instead?):

Getting members of group@domain.org (may take some time for large groups)...
Got 72 members...
Group: group@domain.org, Will add 6 and remove 9 MEMBERs.

ERROR: [Errno 13] Permission denied

I am able to run "gam update group [group-name] add member [email] and it works fine.  It's only when trying to sync to a file that I'm getting this error.  The file itself is world read and execute, so shouldn't be a problem there.

**Comment by taers232c** [comment]
Contact me via Google Hangouts and I'll see if I can help.

Ross

ross.scroggs@gmail.com

**Comment by sestevens-1** [comment]
Issue resolved by upgrading to gamadv. Suspect the issue on gam had to do with root-level permissions.
