### ISSUE TITLE
Group includeInGlobalAddressList

### ISSUE THREAD

**Issue by JonUrbanski** [jay0lee/GAM#993]
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  run gam update group <group> includeInGlobalAddressList false

Expected outcome (what are you trying to do?):
expecting command to update includeInGlobalAddressList to false

Actual outcome (what errors or bad behavior do you see instead?):
ERROR: value for includeInGlobalAddressList must be one of ,
-, true:, Group, is, included, in, the, Global, Address, List.,
-, false:, Group, is, not, included, in, the, Global, Address, List.. Got false.

I suspect error is on line 8916: (i'm attempting this on the windows version, but found this on the python source: )
  # Another ugly hack because Groups Settings API doesn't have proper enumerator values set in discovery file.
      if 'description' in params and params['description'].find('Possible values are: ') != -1:
        possible_values = params['description'][params['description'].find('Possible values are: ')+21:].split(' ')
        if value not in possible_values:
          systemErrorExit(2, 'value for %s must be one of %s. Got %s.' % (attrib, ', '.join(possible_values), value))
      gs_body[attrib] = value
      return

**Comment by taers232c** [comment]
This issue and others are all fixed in PR #990.

Ross

**Comment by JonUrbanski** [comment]
great work!
